#!/usr/bin/env python3
"""Append final-closure-only negative-path tests to a disposable probe copy."""
from pathlib import Path
import argparse

TEST = r'''
#[cfg(test)] mod final_closure_matrix {
use super::*;
fn fresh(name:&str)->Paths{let base=paths().unwrap().root;fs::create_dir_all(&base).unwrap();let root=base.join(format!("final-{name}-{}",now().unwrap()));let _=fs::remove_dir_all(&root);let mode=mode().unwrap();if mode==InputMode::Synthetic{fs::create_dir(&root).unwrap();}Paths{db:root.join(DB),root,mode}}
fn finish(p:&Paths){if p.root.is_dir(){let _=fs::remove_dir_all(&p.root);}else if p.root.exists(){let _=fs::remove_file(&p.root);}}
#[test] fn final_path_and_type_rejections_are_prewrite(){let p=fresh("path");let root_code=real_chain(Path::new("relative")).unwrap_err().code;assert!(root_code=="runtime_root_noncanonical"||root_code=="path_boundary_unavailable");if !p.root.exists(){fs::create_dir(&p.root).unwrap();}let sentinel=p.root.join("sentinel");fs::write(&sentinel,b"sentinel").unwrap();fs::remove_dir(&p.root).unwrap_err();assert_eq!(fs::read(&sentinel).unwrap(),b"sentinel");fs::remove_file(&sentinel).unwrap();fs::remove_dir(&p.root).unwrap();fs::write(&p.root,b"sentinel").unwrap();let code=db_present(&p).unwrap_err().code;assert!(code=="runtime_root_type_rejected"||code=="path_symlink_rejected");assert_eq!(fs::read(&p.root).unwrap(),b"sentinel");finish(&p);}
#[test] fn final_directory_link_chain_is_rejected_prewrite(){let p=fresh("link");if !p.root.exists(){fs::create_dir(&p.root).unwrap();}let link=p.root.parent().unwrap().join(format!("final-symlink-{}",now().unwrap()));std::os::unix::fs::symlink(&p.root,&link).unwrap();assert_eq!(real_chain(&link).unwrap_err().code,"path_symlink_rejected");assert!(!p.db.exists());fs::remove_file(&link).unwrap();finish(&p);}
#[test] fn final_dto_stale_and_unknown_ipc_are_closed(){let p=fresh("dto");let bad=CaptureRequest{text:"invalid".into(),key:"invalid".into()};let before=p.db.exists();let code=capture(&p,&bad).unwrap_err().code;assert!(code=="argument_schema_rejected"||code=="real_input_rejected");assert_eq!(before,p.db.exists());if mode().unwrap()==InputMode::Synthetic{let c=capture(&p,&CaptureRequest{text:SYN_SHORT.into(),key:SYN_SHORT_KEY.into()}).unwrap();assert_eq!(c.link_status,"unlinked_insufficient");assert!(next(&p,&ContextRequest{context_id:CONTEXT.into()}).unwrap().candidates.is_empty());}let s=status(&p);assert_eq!(s.ipc_allowlist,IPC);assert_eq!(s.unknown_ipc,"rejected");finish(&p);}
#[test] fn final_real_idempotency_and_limits_are_prewrite(){if mode().unwrap()!=InputMode::Real{return;}let p=fresh("real");let first=CaptureRequest{text:"甲".repeat(200),key:"p3-133-real-ui-final-a".into()};capture(&p,&first).unwrap();let before=fs::read(&p.db).unwrap();assert_eq!(capture(&p,&CaptureRequest{text:"乙".repeat(200),key:"p3-133-real-ui-final-a".into()}).unwrap_err().code,"idempotency_conflict");assert_eq!(before,fs::read(&p.db).unwrap());capture(&p,&CaptureRequest{text:"b".into(),key:"p3-133-real-ui-final-b".into()}).unwrap();capture(&p,&CaptureRequest{text:"c".into(),key:"p3-133-real-ui-final-c".into()}).unwrap();let full=fs::read(&p.db).unwrap();assert_eq!(capture(&p,&CaptureRequest{text:"d".into(),key:"p3-133-real-ui-final-d".into()}).unwrap_err().code,"input_limit_rejected");assert_eq!(full,fs::read(&p.db).unwrap());finish(&p);}
#[test] fn final_today_focus_is_stable_for_zero_one_multi_tie_and_reopen(){let p=fresh("today");assert!(today(&p).unwrap().todays_focus.is_none());if !p.root.exists(){fs::create_dir(&p.root).unwrap();}let prefix=if p.mode==InputMode::Real{"action:p3-133:"}else{"action:p3-131:"};let a=format!("{prefix}tie-a");let b=format!("{prefix}tie-b");let c=format!("{prefix}later");write(&p,|conn|{let t=now()?;for (id,time) in [(&a,t),(&b,t),(&c,t+1)]{conn.execute("INSERT INTO actions(id,candidate_id,action_text,confirmation_kind,action_state,created_at_ms) VALUES(?1,?2,'fixed synthetic action','accept','open',?3)",params![id,format!("candidate:{id}"),time]).map_err(sql)?;}Ok(())}).unwrap();let first=today(&p).unwrap();assert_eq!(first.todays_focus.as_deref(),Some(a.as_str()));assert_eq!(first.confirmed_actions.len(),3);let reopened=read(&p).unwrap();drop(reopened);let second=today(&p).unwrap();assert_eq!(second.todays_focus.as_deref(),Some(a.as_str()));assert_eq!(second.confirmed_actions.len(),3);finish(&p);}
}
'''

p=argparse.ArgumentParser();p.add_argument('--runtime',type=Path,required=True);a=p.parse_args();s=a.runtime.read_text();
if 'mod final_closure_matrix' in s: raise SystemExit('already appended')
a.runtime.write_text(s+TEST)
