# coding: utf-8
from pathlib import Path
r=Path(__file__).resolve().parents[1]/'candidate';p=r/'application/health_ui.ts';s=p.read_text().replace("import {HealthConversation,HealthFlow} from './health_conversation.ts';","import {ControlledConversation,ControlledFlow} from './controlled_conversation.ts';").replace('new HealthConversation','new ControlledConversation').replace('new HealthFlow','new ControlledFlow').replace('flow.send()','flow.prepare()')
start=s.index(" if(page==='Settings')");end=s.index(" if(page==='Me')",start)
s=s[:start]+''' if(page==='Settings')return `<div class="settings-shell"><nav class="settings-nav" aria-label="设置导航"><p>设置</p><button aria-current="page">模型设置</button></nav><div class="settings-content">${title('模型设置','选择这次对话使用的模型。')}<section class="service-card"><div><p class="eyebrow">当前服务</p><h2>DeepSeek</h2><p>${s?.provider?.credentialState==='stored'?'凭据已加密保存':'尚未配置凭据'} · 合成演练</p></div><span class="state-dot">${esc(s?.provider?.modelId||'未选择模型')}</span></section><section class="config-card"><h2>服务配置</h2><label>合成 API Key<input type="password" id="key" autocomplete="off" placeholder="仅输入虚构演练值"></label><div class="form-actions">${button('save-key','保存凭据')}${button('delete-key','删除本任务凭据')}</div><label>模型<input id="model" list="model-options" value="${esc(s?.provider?.modelId||'')}" placeholder="输入模型 ID"><datalist id="model-options">${(s?.provider?.models||[]).map((m:string)=>`<option value="${esc(m)}"></option>`).join('')}</datalist></label>${button('select-model','选择模型')}<p class="tiny">使用已有选项或输入模型 ID；选择本身不会联网测试。</p><details><summary>其他服务目录</summary><h3>云端服务</h3>${['OpenAI','Anthropic','Google Gemini','DeepSeek','Kimi','OpenRouter','其他 OpenAI-compatible 服务','自定义兼容接口'].map(n=>`<p>${n} · ${n==='DeepSeek'?'本任务受控服务':'目录保留，本任务不可发送'}</p>`).join('')}<h3>本地服务</h3>${['Ollama','LM Studio','OpenAI-compatible 本地接口','自定义本地服务'].map(n=>`<p>${n} · 目录保留，本任务不可发送</p>`).join('')}</details></section><p class="usage-help">当前为合成离线演练。每次确认仅验证发送流程；真实网络尚未启用。</p>${button('open-ai','返回对话')}</div></div>`;
'''+s[end:]
s=s.replace("${flow.snapshot?.modelId==='OfflineB'?'B':'A'}","${esc(flow.snapshot?.provider?.modelId||'未配置模型')}").replace('合成演练 · 离线测试 ${esc','合成演练 · ${esc')
s=s.replace('${chat()}<div id="chat-status">','${chat()}${disclosure()}<div id="chat-status">')
s=s.replace("flow.busy?'正在生成合成回答…'", "flow.phase==='preparing'?'正在本地筛选相关内容…':flow.busy?'正在进行合成发送…'")
s=s.replace("flow.phase==='cancelled'?'已取消，草稿保留。':flow.error?(flow.error.code==='offline_test_failure'?'这次合成生成失败，草稿已保留。':'这次操作未完成，草稿已保留。'):notice", "flow.phase==='cancelled'?flow.notice:flow.error?errorText(flow.error):notice")
s=s.replace("button('retry','重试')", "button('retry','重新准备披露')")
s=s.replace("if(a==='model')await flow.select(id);", "if(a==='confirm')await flow.confirm();if(a==='select-model')await flow.selectModel((document.getElementById('model') as HTMLInputElement).value);if(a==='save-key'){const key=document.getElementById('key') as HTMLInputElement;const value=key.value;key.value='';await flow.saveCredential(value);}if(a==='delete-key')await flow.deleteCredential();")
pos=s.index('const composer=')
s=s[:pos]+'''function errorText(e:any){const messages:any={credential_missing:'请先在模型设置中保存凭据并选择模型。',credential_invalid:'凭据格式不正确，请在设置中检查。',credential_authentication_failed:'本地凭据无法解密，请在设置中重新保存。',provider_authentication:'服务拒绝了凭据。草稿已保留，请检查设置。',provider_model:'服务不接受所选模型。请在设置中选择后重新准备。',provider_timeout:'请求超时，是否已发送无法确认。草稿保留；重试需要新的披露确认。',provider_network:'连接中断，是否已发送无法确认。草稿保留；重试需要新的披露确认。',dispatch_outcome_unknown:'结果尚未确认，不会自动重发。草稿已保留。',preview_stale:'内容或设置已变化，请重新准备披露。',context_stale:'来源或上下文已变化，请重新准备。',provider_unavailable:'服务暂不可用。草稿已保留，请手动重试。',context_budget_rejected:'相关内容过长，请收窄问题。',provider_response_rejected:'服务回答未通过本地检查，草稿已保留。'};return messages[e?.code]||'操作未完成，草稿已保留。';}
function disclosure(){const v=flow.preview;if(!v)return '';return `<section class="confirmation" aria-label="本次发送预览"><h3>发送前，请看一下</h3><p>接收方：DeepSeek · ${esc(v.modelId)}</p><small>合成演练，未联网 · 本次只包含下方问题与 ${v.items.length} 条依据</small><h3>你的问题</h3><p class="verbatim">${esc(v.question)}</p>${!v.items.some((i:any)=>i.identity==='来源观察'&&i.domain==='health')?'<p>本次没有健康来源观察，不会声称使用了健康依据。</p>':''}${v.items.map((i:any)=>`<article class="record"><small>${esc(i.citationId)} · ${esc(i.identity)}</small><p class="verbatim">${esc(i.text)}</p></article>`).join('')}<details data-keep="instructions"><summary>固定模型说明与完整请求</summary><p class="verbatim">${esc(v.instructions)}</p><small>${esc(v.recipient)}</small><pre class="source-original">${esc(v.exactBody)}</pre></details><div class="form-actions"><button class="button primary" data-action="confirm" ${flow.busy?'disabled':''}>确认演练发送</button>${button('cancel','取消')}</div></section>`;}
'''+s[pos:]
p.write_text(s)
p=Path(__file__).resolve().parent/'build_ui.mjs';s=p.read_text().replace("'health_ui'","'health_ui','controlled_conversation'");p.write_text(s)
