import {spawn} from 'node:child_process';import {createInterface} from 'node:readline';import assert from 'node:assert/strict';import {ControlledConversation,ControlledFlow} from '../candidate/ui/controlled_conversation.js';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let seq=0;const results=[];
function host(){const p=spawn('/private/tmp/lifeos-p3-152-health-conversation-v1/target/debug/synthetic-driver',[],{stdio:['pipe','pipe','inherit']});const pending=new Map();createInterface({input:p.stdout}).on('line',l=>{const v=JSON.parse(l),h=pending.get(v.id);pending.delete(v.id);v.ok?h.resolve(v.result):h.reject(v.error)});return {close:()=>p.kill(),invoke:(command,request)=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});p.stdin.write(JSON.stringify({id,command,request})+'\n')})};}
const draft=text=>({requestId:crypto.randomUUID(),turnId:crypto.randomUUID(),revision:1,text});
async function setup(a){await a.saveCredential('p152-only-fictional-test-secret',0);await a.selectModel('user-synthetic-model');}
async function test(name,fn){const h=host(),a=new ControlledConversation(h);try{await fn(a);results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:String(e.stack||JSON.stringify(e))});}finally{h.close()}}
await test('Preview is inert, exact personal data visible, explicit confirmation creates one answer',async a=>{await setup(a);const d=draft('我的睡眠记录是什么'),out=await a.prepare(d,()=>true);assert.equal(out.kind,'preview');assert.equal((await a.read()).turns.length,0);const body=JSON.parse(out.preview.exactBody),user=JSON.parse(body.messages[1].content);assert.deepEqual(user.items,out.preview.items);assert.equal(user.question,d.text);assert(out.preview.items.some(i=>i.text.includes('360')));await a.confirm(out.preview);await a.confirm(out.preview);const s=await a.read();assert.equal(s.turns.length,1);assert.equal(s.turns[0].text,d.text);assert.match(s.turns[0].answer,/合成演练/);});
await test('Local clarification and explicit state do not require configured network model',async a=>{let r=await a.prepare(draft('健康活动怎么安排'),()=>true);assert.equal(r.kind,'local');assert.equal((await a.read()).provider.credentialState,'absent');r=await a.prepare(draft('我有20分钟'),()=>true);assert.equal(r.kind,'local');assert.equal((await a.read()).states[0].value,20);await setup(a);r=await a.prepare(draft('请建议健康活动'),()=>true);assert.equal(r.kind,'preview');assert(r.preview.items.some(i=>i.text.includes('我有20分钟')));});
await test('Model change invalidates the previous preview without a send',async a=>{await setup(a);const r=await a.prepare(draft('我的睡眠记录'),()=>true);await a.selectModel('different-user-model');await assert.rejects(a.confirm(r.preview));assert.equal((await a.read()).turns.length,0);});
await test('Credential deletion blocks confirmation and retains conversation assets',async a=>{await setup(a);const r=await a.prepare(draft('我的步数记录'),()=>true);await a.deleteCredential(1);await assert.rejects(a.confirm(r.preview));const s=await a.read();assert.equal(s.turns.length,0);assert.equal(s.memories.length,2);});
await test('Failed response preserves draft; manual retry creates new preview and no duplicate turn',async a=>{await setup(a);const f=new ControlledFlow(a,()=>{});await f.start();f.edit('我的步数记录 [模拟失败一次]');await f.prepare();const first=f.preview.previewId;await f.confirm();assert.equal(f.phase,'failed');assert.match(f.draft.text,/模拟失败一次/);await f.prepare();assert.notEqual(f.preview.previewId,first);await Promise.all([f.confirm(),f.confirm()]);assert.equal(f.snapshot.turns.length,1);assert.equal(f.draft.text,'');f.dispose();});
await test('Cancel after dispatch is honest; late output cannot replace new question',async a=>{await setup(a);const f=new ControlledFlow(a,()=>{});await f.start();f.edit('我的步数记录');await f.prepare();const pending=f.confirm();await sleep(100);await f.cancel();f.edit('新的工作问题');await pending;assert.match(f.notice,/无法保证撤回/);assert.equal(f.draft.text,'新的工作问题');assert.equal((await a.read()).turns.length,0);f.dispose();});
await test('Editing preview invalidates it; restoration keeps the new draft',async a=>{await setup(a);const f=new ControlledFlow(a,()=>{});await f.start();f.edit('我的睡眠记录');await f.prepare();const old=f.preview;f.edit('新的健康问题');await sleep(300);assert.equal(f.preview,null);await assert.rejects(a.confirm(old));const g=new ControlledFlow(a,()=>{});await g.start();assert.equal(g.draft.text,'新的健康问题');f.dispose();g.dispose();});
await test('Unknown question uses no hidden history and models remain local choices',async a=>{await setup(a);const r=await a.prepare(draft('解释量子纠缠是什么'),()=>true);assert.equal(r.preview.items.length,0);const b=JSON.parse(r.preview.exactBody);assert.equal(b.messages.length,2);assert.equal((await a.read()).turns.length,0);await a.confirm(r.preview);assert.match((await a.read()).turns[0].answer,/没有披露健康依据/);});
console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));if(results.some(r=>!r.pass))process.exitCode=1;
