#![cfg_attr(not(debug_assertions),windows_subsystem="windows")]
mod repository{#[derive(Debug,serde::Serialize)]pub struct Error{pub code:String}impl Error{pub fn new(s:&str)->Self{Self{code:s.into()}}}impl From<rusqlite::Error> for Error{fn from(_:rusqlite::Error)->Self{Self::new("store_operation_failed")}}}
mod strict_json;
mod health_conversation_host;
use tauri::Manager;
use std::{sync::Mutex,io::Write,os::fd::FromRawFd};
struct State(Mutex<health_conversation_host::Store>);
async fn route(command:&'static str,body:tauri::ipc::InvokeBody,app:tauri::AppHandle)->Result<serde_json::Value,repository::Error>{let tauri::ipc::InvokeBody::Raw(bytes)=body else{return Err(repository::Error::new("raw_required"));};tauri::async_runtime::spawn_blocking(move||{let s=app.state::<State>();let store=s.0.lock().map_err(|_|repository::Error::new("store_busy"))?;store.dispatch(command,&bytes)}).await.map_err(|_|repository::Error::new("store_operation_failed"))?}
#[tauri::command]async fn capture_record(request:tauri::ipc::Request<'_>,app:tauri::AppHandle)->Result<serde_json::Value,repository::Error>{route("capture_record",request.body().clone(),app).await}
#[tauri::command]async fn get_context_recovery(request:tauri::ipc::Request<'_>,app:tauri::AppHandle)->Result<serde_json::Value,repository::Error>{route("get_context_recovery",request.body().clone(),app).await}
#[tauri::command]async fn resolve_request_context(request:tauri::ipc::Request<'_>,app:tauri::AppHandle)->Result<serde_json::Value,repository::Error>{route("resolve_request_context",request.body().clone(),app).await}
#[tauri::command]async fn decide_understanding_feedback(request:tauri::ipc::Request<'_>,app:tauri::AppHandle)->Result<serde_json::Value,repository::Error>{route("decide_understanding_feedback",request.body().clone(),app).await}
#[tauri::command]async fn save_ai_provider_settings(request:tauri::ipc::Request<'_>,app:tauri::AppHandle)->Result<serde_json::Value,repository::Error>{route("save_ai_provider_settings",request.body().clone(),app).await}
fn main(){std::panic::set_hook(Box::new(|_|{}));unsafe{libc::umask(0o077);let lim=libc::rlimit{rlim_cur:0,rlim_max:0};libc::setrlimit(libc::RLIMIT_CORE,&lim);}let out=unsafe{libc::fcntl(1,libc::F_DUPFD_CLOEXEC,3)};unsafe{let f=libc::open(c"/dev/null".as_ptr(),libc::O_RDWR);if f>=0{libc::dup2(f,0);libc::dup2(f,1);libc::dup2(f,2);if f>2{libc::close(f);}}}
 let store=match health_conversation_host::Store::open_fixed(){Ok(s)=>s,Err(e)=>{if out>=0{let mut f=unsafe{std::fs::File::from_raw_fd(out)};let _=writeln!(f,"{{\"status\":\"failed\",\"code\":\"{}\"}}",e.code);}return;}};
 let _=tauri::Builder::default().manage(State(Mutex::new(store))).invoke_handler(tauri::generate_handler![capture_record,get_context_recovery,resolve_request_context,decide_understanding_feedback,save_ai_provider_settings]).setup(move|app|{tauri::WebviewWindowBuilder::new(app,"main",tauri::WebviewUrl::App("index.html".into())).title("LifeOS P3-151 - Synthetic Conversation").inner_size(1280.0,949.0).min_inner_size(560.0,640.0).incognito(true).build()?;if out>=0{let mut f=unsafe{std::fs::File::from_raw_fd(out)};let _=writeln!(f,"{{\"status\":\"synthetic_conversation_started\"}}");}Ok(())}).run(tauri::generate_context!());}
