import assert from 'node:assert/strict';
import {test} from 'node:test';
import {Controller,content,detailContent,segments,chart} from '../candidate/ui/readonly.js';
const response=metric=>({metric,days:7,endDay:20003,latestDay:metric==='sleep'?20001:20003,importedAt:1730000000000,source:'Synthetic <Watch>',offset:480,groups:[],groupPage:0,points:[{day:20001,present:true,value:1},{day:20002,present:false,value:null},{day:20003,present:true,value:0}]});
async function ready(){const c=new Controller(async r=>response(r.payload.metric),()=>{});await c.initialize();return c;}
test('default is lightweight and has one detail entry',async()=>{const c=await ready();const h=content(c);assert.ok(h.includes('健康来源'));assert.equal((h.match(/id="data-toggle"/g)||[]).length,1);assert.ok(!h.includes('<svg'));assert.ok(!h.includes('id="metric"'));assert.ok(!h.includes('id="source"'));assert.ok(!h.includes('id="days"'));assert.ok(!h.includes('0 步'));});
test('freshness stays per metric and does not claim coverage',async()=>{const c=await ready();const h=content(c);assert.ok(h.includes('睡眠区间 2024-10-05'));assert.ok(h.includes('步数 2024-10-07'));assert.ok(h.includes('不代表连续或完整覆盖'));});
test('only one detail area and trend is secondary',async()=>{const c=await ready();c.detailsOpen=true;let h=content(c);assert.equal((h.match(/class="panel health-reader"/g)||[]).length,1);assert.ok(h.includes('id="metric"'));assert.ok(h.includes('查看历史趋势'));assert.ok(!h.includes('<svg'));c.trendOpen=true;h=content(c);assert.equal((h.match(/<svg/g)||[]).length,1);c.detailsOpen=false;assert.ok(!content(c).includes('<svg'));assert.ok(!content(c).includes('id="metric"'));});
test('no fake chat or AI state',async()=>{const h=content(await ready());assert.ok(h.includes('不提供对话或 AI 解读'));assert.ok(!h.includes('<textarea'));assert.ok(!h.includes('发送'));assert.ok(!h.includes('AI 已了解'));});
test('initial calls are serial and keep existing contract',async()=>{let active=0,max=0,seen=[];const c=new Controller(async r=>{active++;max=Math.max(max,active);seen.push(r);await Promise.resolve();active--;return response(r.payload.metric);},()=>{});await c.initialize();assert.equal(max,1);assert.deepEqual(seen.map(r=>r.payload.metric),['steps','sleep','exercise']);assert.ok(seen.every(r=>r.version===2&&r.operation==='health_view'&&r.payload.days===7));});
test('overview error never claims imported or exposes error body',async()=>{const c=new Controller(async()=>{throw Error('private');},()=>{});await c.initialize();const h=content(c);assert.ok(h.includes('role="alert"'));assert.ok(!h.includes('已找到成功'));assert.ok(!h.includes('private'));});
test('null and absence remain gaps while zero stays real',()=>{const ps=[{day:1,present:true,value:2},{day:2,present:true,value:null},{day:3,present:false,value:null},{day:4,present:true,value:0}];assert.deepEqual(segments(ps).map(s=>s.length),[1,1]);assert.ok(!chart({metric:'steps',points:ps}).includes('<polyline'));});
test('source escaping and empty states retained',async()=>{const c=await ready();c.detailsOpen=true;assert.ok(detailContent(c).includes('Synthetic &lt;Watch&gt;'));c.data.points=[];assert.ok(detailContent(c).includes('这个范围没有记录'));});
test('stale requests cannot replace the selected metric',async()=>{let pending=[];const c=new Controller(()=>new Promise(resolve=>pending.push(resolve)),()=>{});const a=c.load();const b=c.load({metric:'sleep'});pending[1](response('sleep'));await b;pending[0](response('steps'));await a;assert.equal(c.data.metric,'sleep');});
