import {test} from 'node:test';import assert from 'node:assert/strict';import {SourcesController,sourcesView} from '../candidate/ui/sources_view.js';
const good={connectorId:'directory',status:'active',grantGeneration:1,scanComplete:true,pending:0,discovered:2,parsed:2,files:[],links:[]};
test('health status failure leaves work source usable and isolated error',async()=>{const c=new SourcesController(async cmd=>{if(cmd==='get_source_status')return {connectors:[good]};throw {code:'store_busy',message:'PRIVATE_CANARY'}},()=>{});await c.start();assert.equal(c.error,'');assert(c.importState.error.includes('store_busy'));assert.equal(c.status.parsed,2);assert(!sourcesView(c).includes('PRIVATE_CANARY'));c.dispose()});
test('work status failure does not skip healthy import status',async()=>{let health=0;const c=new SourcesController(async cmd=>{if(cmd==='get_source_status')throw {code:'source_busy'};health++;return {status:'duplicate',inserted:0,duplicates:3}},()=>{});await c.start();assert.equal(health,1);assert.equal(c.importState.status.status,'duplicate');assert.equal(c.importState.error,'');assert(c.error.includes('source_busy'));c.dispose()});
test('failed apple action stays in health section after status refresh',async()=>{const c=new SourcesController(async(cmd,r)=>{if(cmd==='get_source_status')return {connectors:[good]};if(r.payload.action==='list')throw {code:'health_busy'};return {status:'idle'}},()=>{});await c.start();await c.action('apple-open');assert.equal(c.error,'');assert(c.importState.error.includes('health_busy'));c.dispose()});
test('late prior page status cannot overwrite a reopened source page',async()=>{let release;let first=true;const c=new SourcesController(async cmd=>{if(cmd==='get_source_status'&&first){first=false;return new Promise(r=>release=r)}return cmd==='get_source_status'?{connectors:[good]}:{status:'idle'}},()=>{});const old=c.start();c.dispose();await c.start();release({connectors:[{...good,parsed:999}]});await old;assert.equal(c.status.parsed,2);c.dispose()});

test('late source mutation completion cannot clear results or unlock a new action',async()=>{let complete;const c=new SourcesController(async(cmd,r)=>cmd==='get_source_status'?{connectors:[good]}:cmd==='control_source_job'?new Promise(r=>complete=r):{status:'idle'},()=>{});await c.start();const old=c.action('source-refresh');c.dispose();await c.start();c.rows=[{text:'new synthetic result'}];c.busy=true;complete({status:'active'});await old;assert.equal(c.rows[0].text,'new synthetic result');assert.equal(c.busy,true);c.dispose()});
test('paused and partial statuses expose independent recovery and honest counts',()=>{const c=new SourcesController(async()=>{},()=>{});c.status={...good,status:'paused',scanComplete:false,processed:3,discovered:4,pending:1,unparsed:1,failed:1,error:'source_changed',updateCounts:{added:1,changed:0,unchanged:2,missing:1}};c.importState.error='health_busy';const html=sourcesView(c);for(const text of ['继续处理','总量尚未确定','已处理 3','未变化 2','重新读取健康导入状态'])assert(html.includes(text));assert(!html.includes('100%'));c.dispose()});
