changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking changes
      labels:
        - breaking
    - title: Features
      labels:
        - type: feature
    - title: Fixes
      labels:
        - type: bug
    - title: Engineering and governance
      labels:
        - type: task
        - area: governance
        - area: engineering
    - title: Other changes
      labels:
        - "*"
