// UI owns interaction and drafts; the Host alone evaluates and persists outcomes.
export class ProactiveApplication {
 status:any=null; activeControl:any=null; ordinaryRequired=false; view:any={items:[]}; error=''; busy=false; policyBusy=false; responseDraft=''; responseRequest=''; handoffRequest=''; reply='';
 rangeOpen=false; credentialCheck:any={status:'idle'}; private checkGeneration=0;
 private generation=0; private polling=false; private acked=new Set<string>(); private acknowledgements=new Map<string,Promise<void>>();
 selected=new Set<string>(); selectedSources=new Set<string>(); private initialized=false; private submittedText='';
 constructor(private invoke:(c:string,r:any)=>Promise<any>,private changed:()=>void,private interaction?:any){}
 async call(command:string,operation:string,payload:any={}){
  const r=await this.invoke(command,{version:'proactive-v1',operation,payload});
  if(r?.version!=='proactive-v1'||r.operation!==operation||!r.result)throw new Error('proactive_protocol');return r.result;
 }
 private renderIdentity(){return JSON.stringify({credentialCheck:this.credentialCheck,view:this.view,policy:this.status?.policy,scope:this.status?.scope,controls:this.status?.controls,pauseReason:this.status?.pauseReason,budget:{analysis:this.status?.budget?.analysis,response:this.status?.budget?.response,shows:this.status?.budget?.shows},active:this.activeControl,busy:this.busy,reply:this.reply,error:this.error,draft:this.responseDraft,handoff:this.handoffRequest,ordinaryRequired:this.ordinaryRequired});}
 async refresh(){const before=this.renderIdentity();if(this.polling)return;this.polling=true;const g=this.generation;
  try{const [view,status]=await Promise.all([this.call('get_today','proactive_view'),this.call('get_context_recovery','proactive_status',{scopePage:this.status?.scope?.page||0})]);if(g!==this.generation)return;
   this.view=view;this.status=status;if(this.activeControl)this.activeControl=[...view.items,...(status.controls||[])].find((x:any)=>x.suggestion.id===this.activeControl.suggestion.id)||null;if(!this.initialized){this.selected=new Set(status.policy.subjectIds);this.selectedSources=new Set(status.policy.sourceIds);this.initialized=true;const pending=status.recentResponse;if(pending){this.ordinaryRequired=pending.outcome?.status==='ordinary_conversation_required';this.submittedText=pending.text;this.responseDraft=pending.status==='committed'&&pending.outcome?.status!=='ordinary_conversation_required'?'':pending.text;this.reply=pending.outcome?.reply||'';if(['reserved','response_queued'].includes(pending.status)){this.responseRequest=pending.requestId;this.busy=true;}if(pending.status==='awaiting_action_authorization')this.handoffRequest=pending.requestId;}}
   if(this.responseRequest){const r=await this.call('decide_understanding_feedback','proactive_response',{requestId:this.responseRequest});if(g!==this.generation)return;if(!['response_queued','reserved'].includes(r.status)){this.busy=false;this.reply=r.outcome?.reply||'';this.error=r.outcome?.errorCode||'';if(r.status==='awaiting_action_authorization'){this.handoffRequest=r.requestId;this.reply='这条回应涉及安排操作，将使用原对话的发送核对。';}this.ordinaryRequired=r.outcome?.status==='ordinary_conversation_required';if(this.ordinaryRequired)this.reply='这是另一个话题。可以在对话中继续，发送前会核对本次内容；这条建议保持原样。';if(r.status==='committed'&&r.outcome?.status!=='ordinary_conversation_required'&&!this.error&&this.responseDraft===this.submittedText)this.responseDraft='';this.responseRequest='';}}
   if(['awaiting_user','checking'].includes(this.credentialCheck.status)){const cg=this.checkGeneration;const check=await this.call('get_context_recovery','credential_check_status');if(cg===this.checkGeneration)this.credentialCheck=check;}
   if(before!==this.renderIdentity())this.changed();
  }catch{if(g===this.generation){this.error='主动帮助暂时无法恢复，原输入保留。';this.changed();}}finally{this.polling=false;}
 }
 async toggleEnabled(){if(this.status?.policy.enabled){await this.setEnabled(false);}else{this.rangeOpen=true;this.changed();}}
 async requestCredentialCheck(event:{isTrusted:boolean}){if(!event.isTrusted||!this.status?.pauseReason||['opening','awaiting_user','checking'].includes(this.credentialCheck.status))return;const cg=++this.checkGeneration;this.credentialCheck={status:'opening'};this.changed();try{const check=await this.call('save_ai_provider_settings','request_credential_check');if(cg===this.checkGeneration)this.credentialCheck=check;}catch(e:any){if(cg===this.checkGeneration)this.credentialCheck={status:'unavailable',errorCode:credentialEntryCode(e)};}this.changed();}
 async cancelCredentialCheck(){if(!['opening','awaiting_user','checking'].includes(this.credentialCheck.status))return;this.checkGeneration++;this.credentialCheck={status:'cancelled'};try{await this.call('save_ai_provider_settings','cancel_credential_check');}catch{}this.changed();}
 async continueOrdinary(flow:any){if(!this.ordinaryRequired||!this.responseDraft.trim())return;const text=this.responseDraft;flow.edit(text);this.activeControl=null;this.ordinaryRequired=false;await flow.prepare();this.changed();}
 async setEnabled(enabled:boolean){if(!this.status||this.policyBusy)return;await this.cancelCredentialCheck();this.policyBusy=true;this.error='';this.generation++;
  try{const p=this.status.policy;const payload={requestId:crypto.randomUUID(),expectedRevision:p.revision,enabled,subjectIds:enabled?[...this.selected]:p.subjectIds,sourceIds:enabled?[...this.selectedSources]:p.sourceIds,analysisPerDay:p.analysisPerDay,responsePerDay:p.responsePerDay,showsPerDay:p.showsPerDay,intervalMinutes:p.intervalMinutes,quietStart:p.quietStart,quietEnd:p.quietEnd};await this.call('save_ai_provider_settings','proactive_policy',payload);this.rangeOpen=false;}catch{this.error='主动帮助设置未保存，请核对选择范围。';}finally{this.policyBusy=false;if(!enabled){this.responseRequest='';this.busy=false;this.handoffRequest='';}await this.refresh();this.changed();}
 }
 async page(delta:number){if(!this.status)return;try{const status=await this.call('get_context_recovery','proactive_status',{scopePage:Math.max(0,this.status.scope.page+delta)});this.status=status;this.changed();}catch{this.error='范围列表未恢复。';this.changed();}}
 shown(id:string,revision:number){if(this.acked.has(id))return this.acknowledgements.get(id);this.acked.add(id);const task=(async()=>{try{const state=await this.call('resolve_request_context','proactive_event',{requestId:crypto.randomUUID(),suggestionId:id,revision});const item=this.view.items.find((x:any)=>x.suggestion.id===id);if(item)item.state=state;}catch{this.acked.delete(id);}})();this.acknowledgements.set(id,task);return task;}
 async respond(){const item=this.activeControl||this.view.items[0];if(!item||!this.responseDraft.trim()||this.busy)return;this.busy=true;this.ordinaryRequired=false;this.error='';this.reply='';this.submittedText=this.responseDraft;this.changed();
  try{await this.acknowledgements.get(item.suggestion.id);if(this.interaction&&this.status?.mode==='synthetic'){const r=await this.interaction.submitKeyboard(this.responseDraft,crypto.randomUUID(),{id:item.suggestion.id,revision:item.state.revision});this.responseRequest=r.proactiveRequestId;}else{const r=await this.call('resolve_request_context','prepare_proactive_response',{requestId:crypto.randomUUID(),suggestionId:item.suggestion.id,expectedRevision:item.state.revision,text:this.responseDraft});this.responseRequest=r.requestId;}}catch{this.busy=false;this.error='回应尚未处理，原输入保留，请恢复后重试。';}this.changed();
 }
}
export function proactiveSettings(p:ProactiveApplication,esc:(x:any)=>string){
 const s=p.status;if(!s)return '<section class="service-card proactive-settings"><h2>主动帮助</h2><p>正在读取设置…</p></section>';
 const enabled=!!s.policy.enabled,paused=enabled&&!!s.pauseReason,checking=['opening','awaiting_user','checking'].includes(p.credentialCheck.status),checked=p.credentialCheck.status==='finished'&&p.credentialCheck.diagnostic?.ok;
 const status=!enabled?'已关闭。':!paused?'已开启，只在值得时提醒。':checking?'等待你完成本次凭据检查。':checked?'本次检查成功，主动帮助仍暂停。':'已暂停，现有凭据暂不可用。';
 const sources=new Map<string,string[]>();for(const r of s.scope.items){if(r.requiresSourceOptIn){const labels=sources.get(r.sourceId)||[];labels.push(r.label);sources.set(r.sourceId,labels);}}
 const range=p.rangeOpen?`<div class="proactive-range"><fieldset><legend>关注哪些事项</legend>${s.scope.items.map((r:any)=>`<div class="proactive-scope"><label><input type="checkbox" data-proactive-scope="${esc(r.id)}" ${p.selected.has(r.id)?'checked':''}>${esc(r.label)}</label></div>`).join('')}</fieldset><fieldset><legend>允许使用的来源正文</legend><p class="quiet">这是来源层的独立许可，仅用于上方已选事项。未选中的事项不会因此加入关注范围。</p>${[...sources].map(([id,labels])=>`<div class="proactive-scope"><label><input type="checkbox" data-proactive-source="${esc(id)}" ${p.selectedSources.has(id)?'checked':''}>允许这些事项共用的来源正文：${esc(labels.join('、'))}</label></div>`).join('')||'<p>当前页没有需要单独许可的来源。</p>'}<p class="tiny">共保留 ${p.selectedSources.size} 个来源许可；新来源不会自动加入。</p></fieldset><div class="actions">${s.scope.page?'<button type="button" class="button secondary" data-action="proactive-prev">上一页</button>':''}${s.scope.hasMore?'<button type="button" class="button secondary" data-action="proactive-next">下一页</button>':''}</div><p>启用后，所选事项的必要内容与主动回应会发送给 DeepSeek；来源正文仅按上述许可使用。每天最多 12 次判断、20 次回应，费用按实际用量计算。随时关闭可停止新的主动请求。</p><div class="actions"><button type="button" class="button primary" data-action="proactive-enable" ${p.policyBusy?'disabled':''}>${enabled?'确认保存范围':'同意并启用'}</button><button type="button" class="button secondary" data-action="proactive-range">收起</button></div></div>`:'';
 const recovery=paused?`<div class="actions"><button type="button" class="button secondary" data-action="${checking?'proactive-credential-cancel':checked?'proactive-enable':'proactive-credential-check'}">${checking?'取消检查':checked?'恢复主动帮助':'处理凭据问题…'}</button></div>`:'';
 return `<section class="service-card proactive-settings"><div class="service-head"><h2>主动帮助</h2><button type="button" class="button secondary" role="switch" aria-label="主动帮助" aria-checked="${enabled}" data-action="proactive-toggle" ${p.policyBusy?'disabled':''}>${enabled?'关闭':'开启'}</button></div><p role="status">${status}</p><p>关注范围：已选 ${s.policy.subjectIds.length} 项 · <button type="button" class="button secondary" data-action="proactive-range">调整</button></p>${recovery}${range}<details data-keep="proactive-details"><summary>详情</summary><p>DeepSeek · deepseek-v4-pro · api.deepseek.com。仅一般工作与个人项目；健康、医疗、心理、财务、法律、密钥及配置不在此用途范围。</p><p>每次最多 8 个片段、8192 字节内容。今日判断 ${s.budget.analysis} 次，回应 ${s.budget.response} 次。用量按实际计费；关闭不会抹除历史、决定或计数。</p><p>${esc(credentialCheckText(p.credentialCheck))}</p>${Number.isInteger(p.credentialCheck.readAttempts)?`<p class="tiny">本进程手动检查 ${p.credentialCheck.readAttempts} 次；检查不发送模型请求。</p>`:''}${paused?'<p>凭据处理只进行一次只读检查，不发送模型请求。仅你在原生菜单选择“检查一次”后开始；系统密码只在系统窗口输入，不选择“始终允许”。检查成功不等于后台读取已恢复。</p>':''}<details><summary>已保存的提醒决定</summary>${(s.controls||[]).map((x:any)=>`<p>${esc(x.suggestion.candidate.proposal||x.suggestion.candidate.question)} · ${esc(({suppressed:'不再提示',snoozed:'已推迟',disputed:'待更正'} as any)[x.state.status])} <button type="button" class="button secondary" data-action="proactive-control" data-id="${esc(x.suggestion.id)}">讨论这件事</button></p>`).join('')||'<p>暂无。</p>'}</details></details>${p.error?`<p role="status">${esc(p.error)}</p>`:''}</section>`;
}
export function proactiveFocus(p:ProactiveApplication,esc:(x:any)=>string,discussion=false){const item=discussion?p.activeControl:p.view.items[0];if(!item)return '';const c=item.suggestion.candidate;return `<section class="focus-card proactive-focus" ${discussion?'':`data-proactive-shown="${esc(item.suggestion.id)}" data-revision="${item.state.revision}"`} aria-label="LifeOS noticed"><p class="eyebrow">LifeOS noticed</p><h2>${esc(c.proposal||c.question)}</h2><p>${esc(c.whyNow)}</p>${c.inferenceFlags.length?'<p class="quiet">这是基于现有资料的建议或推断。</p>':''}<details><summary>查看依据</summary>${item.suggestion.evidenceSnapshot.map((e:any)=>`<p>${esc(e.text)}</p>`).join('')}</details><label for="proactive-response">回应这条建议</label><textarea id="proactive-response" rows="2" maxlength="2000" placeholder="可以讨论、推迟，或纠正这条建议">${esc(p.responseDraft)}</textarea><button type="button" class="button secondary" data-action="proactive-respond" ${p.busy?'disabled':''}>${p.busy?'正在理解回应…':'回应'}</button><p role="status">${esc(p.reply||p.error)}</p>${p.ordinaryRequired?'<button type="button" class="button secondary" data-action="proactive-ordinary">在对话中继续</button>':''}${p.handoffRequest?'<button type="button" class="button secondary" data-action="proactive-action-handoff">核对安排操作</button>':''}</section>`;}

export function credentialCheckText(c:any){if(c.status==='finished'){if(c.diagnostic?.ok)return '上次只读检查成功。这只证明那次手动读取成功，不代表后台读取已稳定可用。';const d=c.diagnostic||{};return `本次检查未成功（阶段：${d.stage||'unknown'}${Number.isInteger(d.osStatus)?'，系统状态 '+d.osStatus:''}）。这是该次检查的结果，请勿反复重试。`;}if(c.status==='unavailable')return `检查入口未打开（${credentialEntryCode({code:c.errorCode})}），未读取凭据，未自动重试。`;return ({opening:'正在打开原生检查菜单…',awaiting_user:'请在原生菜单中选择“检查一次”。如系统出现密码提示，仅在系统窗口处理；不要选择“始终允许”。',checking:'正在检查现有凭据。取消或超时后不会采用迟到结果。',cancelled:'本次检查已取消。',timeout:'本次检查已超时，未自动重试。',binding_changed:'设置已变化，本次结果已丢弃。',unavailable:'检查入口暂不可用，未自动重试。'} as any)[c.status]||'';}

export function credentialEntryCode(e:any){const code=typeof e==='string'?e:e?.code;return ['credential_check_not_visible','credential_check_busy','credential_check_not_enabled','credential_check_configuration_binding','credential_check_native_unavailable','dto_rejected','raw_required','store_busy'].includes(code)?code:'credential_check_entry_unavailable';}
