import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const evidence = join(root, "evidence"); mkdirSync(evidence, { recursive: true });
const runAt = new Date().toISOString();
const run = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "tests/invariants.test.ts"], { cwd: root, encoding: "utf8" });
const log = `${run.stdout}${run.stderr}`; writeFileSync(join(evidence,"test_run.log"), log);
const pass = Number(log.match(/(?:#|ℹ)\s+pass\s+(\d+)/)?.[1] ?? 0);
const fail = Number(log.match(/(?:#|ℹ)\s+fail\s+(\d+)/)?.[1] ?? 1);
const failedTitles = [...new Set(log.split("\n").map(line => line.trim()).flatMap(line => {
  const match = line.match(/^(?:✖\s+|not ok\s+\d+\s+-\s+)(.+?)(?:\s+\([^)]+\))?$/);
  return match ? [match[1]] : [];
}))];
const severityFail = (severity) => failedTitles.filter(title => title.startsWith(severity)).length;
const p0Fail = severityFail("P0");
const p1Fail = severityFail("P1");
const p2Fail = severityFail("P2");
const p1MigrationPass = [...log.matchAll(/✔ P1-(?:3|5)[^\n]*/g)].length;
const conditionPatchPass = [...log.matchAll(/✔ P3-015[^\n]*/g)].length;
const generationStalingPass = [...log.matchAll(/✔ P1-4[^\n]*/g)].length;
const suggestionBindingPass = [...log.matchAll(/✔ P1-8[^\n]*/g)].length;
const restoreCandidatePass = [...log.matchAll(/✔ P1-6[^\n]*/g)].length;
const authorizationExpiryFeedbackRetractionPass = [...log.matchAll(/✔ P1-7[^\n]*/g)].length;
const p2CleanupPass = [...log.matchAll(/✔ P2-CLEAN-[^\n]*/g)].length;
const snapshotFiles = ["package.json","fixtures/synthetic_v1.json","src/types.ts","src/capability-policy.ts","src/content-identity.ts","src/store.ts","src/consumption-gate.ts","src/lifeos.ts","tests/invariants.test.ts","scripts/validate.mjs"];
const hashes = Object.fromEntries(snapshotFiles.map(f => [f, createHash("sha256").update(readFileSync(join(root,f))).digest("hex")]));
const snapshotId = createHash("sha256").update(JSON.stringify(hashes)).digest("hex");
const summary = { task:"LIFEOS-P3-022", migrated_engineering_asset:"LIFEOS-P3-009", run_at:runAt, command:"node scripts/validate.mjs", environment:{node:process.version,platform:process.platform,arch:process.arch,sqlite:"node:sqlite built-in"}, fixture:"lifeos-p3-009-synthetic-v1", snapshot_id:snapshotId, summary:{pass,fail,total_fail:fail,p0_fail:p0Fail,p1_fail:p1Fail,p2_fail:p2Fail,unclassified_fail:Math.max(0,fail-p0Fail-p1Fail-p2Fail),existing_regression_expected:34,existing_regression_pass:pass-p2CleanupPass,p1_migration_expected:4,p1_migration_pass:p1MigrationPass,p3_015_regression_expected:1,p3_015_regression_pass:conditionPatchPass,p1_4_expected:2,p1_4_pass:generationStalingPass,p1_8_expected:4,p1_8_pass:suggestionBindingPass,p1_6_expected:5,p1_6_pass:restoreCandidatePass,p1_7_expected:4,p1_7_pass:authorizationExpiryFeedbackRetractionPass,p2_cleanup_expected:3,p2_cleanup_pass:p2CleanupPass}, hashes };
writeFileSync(join(evidence,"test_results.json"), JSON.stringify(summary,null,2)+"\n");

writeFileSync(join(evidence,"invariant_migration_matrix.md"), `# H1-H9 / T-ARCH migration matrix\n\n| Invariant | Status | Executable coverage | Boundary / residual |\n|---|---|---|---|\n| H1 / T-SCOPE | Executable PASS | personal, local, single-device slice and capability closure | no UI/value validation |\n| H2 / T-ID | Executable PASS | immutable user original; stable suggestion ID binds Project plus sorted complete input/version/source/generation set; explicit feedback retraction preserves history while removing confirmation authority; confirmed important-link identity/source/version/evidence binding | external-reference adapter mapped only |\n| H3 / T-SAVE | Executable PASS (narrow) | SQLite transaction rollback; authority survives index failure; idempotent outbox shape | process-kill/fsync/durability remains unmigrated |\n| H4 / T-GATE | Executable PASS | read/search/recovery/suggest/feedback/export, read-only restore candidate evaluation and important-link writes recheck project, purpose, location, processor, version, generations, tombstone, evidence, authorization and optional expiry against an injected deterministic clock; restore candidates re-read current authority and reject package content/identity mismatch | real time service/IPC/external processor absent |\n| H5 / T-DEL | Executable PASS (active block) | delete/revoke/authorization expiry of any derivation input and independent artifact/source generation mismatch block feedback/export/suggest; explicit user feedback retraction is idempotent, retains the row, removes confirmed authority and never revives stale/invalid/unauthorized Derivations; old memory packages cannot revive blocked or stale Artifact/Derivation candidates | physical cleanup and formal restore/write-back protocol unmigrated |\n| H6 / T-IPC-OFF | Executable PASS (closed state) | Tauri, Vault and filesystem export throw | real Tauri matrix deliberately not run; R-0040 remains |\n| H7 / T-DATA | Executable PASS (synthetic) | fixture classification and secret/path/email pattern scan | no real-data gate |\n| H8 / T-OFF | Executable PASS | all eight excluded capability calls reject | no enablement path exists |\n| H9 / T-EXPORT | Executable PASS (memory) | Project closure, content identity, minimum authority projection and read-only restore candidates in controlled memory package | final UI, filesystem format and real backup/restore unmigrated |\n| T-ARCH | Executable PASS (minimum) | SQLite+FTS-first; authority/derivation inputs/important links/outbox/tombstone separation; consumer/write recheck | lease fencing, long rebuild nonblocking and SQLite-aware backup mapped but unmigrated |\n\nStatus is limited to this synthetic single-process skeleton and is not production or capability approval.\n`);

writeFileSync(join(evidence,"default_off_matrix.md"), `# Default-off capability matrix\n\n| Capability | Config | Runtime negative test | Enablement status |\n|---|---:|---|---|\n| Real Obsidian Vault | false | throws DisabledCapability | Not requested |\n| Real Tauri / IPC | false | throws DisabledCapability | Not requested; R-0040 remains Open / Conditional |\n| Filesystem export / path scope | false | throws DisabledCapability | Not requested |\n| Cloud / third-party model | false | throws DisabledCapability | Not requested |\n| Vector index | false | throws DisabledCapability | Not requested |\n| Sync / multi-device | false | throws DisabledCapability | Not requested |\n| L3 actions | false | throws DisabledCapability | Not requested |\n| External users | false | throws DisabledCapability | Not requested |\n\nAll rows are closed by immutable policy object plus executable negative tests. No UI, IPC or adapter bypass is present in this skeleton.\n`);

writeFileSync(join(evidence,"architecture_conformance.md"), `# T-ARCH conformance\n\n- Executable: Node/TypeScript modules use built-in SQLite and FTS5; immutable authority, normalized derivation inputs, important links/evidence, outbox/job, tombstone and authorization responsibilities are separate.\n- Executable: every implemented consumer and important-link write receives explicit context and fails closed on project, version, artifact/source generation, tombstone, purpose, location, processor, evidence, authorization mismatch or authorization expiry; expiry tests use an injected deterministic clock.\n- Executable: feedback IDs are insert-once; duplicate, conflicting and post-retraction writes fail closed without changing user text or status. Explicit user feedback retraction is idempotent, retains feedback history, removes confirmed/edited-confirmed Derivation authority and does not revive stale, invalid or unauthorized Derivations.\n- Executable: read-only restore candidate evaluation re-reads current authority and verifies package content hashes, identity and the complete derivation_input set without writing authority, FTS or outbox; derivation.evidence_version_id remains legacy compatibility/display metadata only.\n- Executable: suggestion IDs bind Project and the stable-sorted complete input set, including exact evidence version, Artifact, Source and both generations; revoke/delete or an independent current-generation mismatch of any input makes the old derivation stale and prevents ID reuse.\n- Executable: index failure does not roll back an already committed authoritative capture.\n- Closed: real Tauri/IPC, Vault, filesystem export, cloud/model, vector, sync/multi-device, L3 and external users.\n- Mapped, not executable here: process-kill durability, lease fencing race, long FTS rebuild nonblocking, SQLite-aware real backup/restore/write-back and model-provider replacement boundary.\n- No claim: production schema/API/module boundary/package strategy/export format/SLA freeze. R-0040 is unchanged.\n`);

const manifest = `# LIFEOS-P3-009 Evidence Manifest\n\n- Fixture: \`lifeos-p3-009-synthetic-v1\` (synthetic-disposable)\n- Runtime: Node \`${process.version}\`, built-in \`node:sqlite\`\n- Re-run: \`cd lifeos/engineering/LIFEOS-P3-009 && node scripts/validate.mjs\`\n- Run at: \`${runAt}\`\n- Content snapshot SHA-256: \`${snapshotId}\`\n- Result: **${pass} PASS / ${fail} FAIL; TOTAL FAIL = ${fail}; P0 FAIL = ${p0Fail}; P1 FAIL = ${p1Fail}; P2 FAIL = ${p2Fail}; existing 34-test regression = ${pass-p2CleanupPass}/34 PASS; P2 cleanup = ${p2CleanupPass}/3 PASS; P1-3/P1-5 migration = ${p1MigrationPass}/4 PASS; P3-015 regression = ${conditionPatchPass}/1 PASS; P1-4 generation staling = ${generationStalingPass}/2 PASS; P1-8 suggestion ID binding = ${suggestionBindingPass}/4 PASS; P1-6 restore candidates = ${restoreCandidatePass}/5 PASS; P1-7 authorization expiry / feedback retraction = ${authorizationExpiryFeedbackRetractionPass}/4 PASS**\n- Scope: synthetic, local, single-process TypeScript/SQLite skeleton; not real Tauri, Vault, filesystem export, cloud/model, vector, sync, L3, external user, production packaging or SLA.\n\n## Evidence files\n\n- \`test_results.json\`: machine-readable environment, result, snapshot and file hashes.\n- \`test_run.log\`: raw Node test output.\n- \`invariant_migration_matrix.md\`: H1-H9 / T-ARCH executable, mapped and unmigrated status.\n- \`default_off_matrix.md\`: config and runtime-negative closure matrix.\n- \`architecture_conformance.md\`: frozen-contract inheritance and remaining boundaries.\n\n## P3-022 cleanup semantics\n\n- Feedback IDs are insert-once: duplicate, conflicting and post-retraction writes fail closed without changing \`user_text\` or \`status\`.\n- \`fail\` and \`total_fail\` count all failures; \`p0_fail\`, \`p1_fail\` and \`p2_fail\` count only failed test titles beginning with the matching severity prefix. Any failure still exits nonzero.\n- \`derivation.evidence_version_id\` is retained only as a legacy compatibility/display pointer. \`derivation_input\` / exported \`inputs\` is the complete authoritative set for consumption, export inclusion and restore-candidate evaluation.\n\nThis manifest is engineering evidence, not PM Review, acceptance, freeze, capability enablement or stage advancement.\n`;
writeFileSync(join(evidence,"MANIFEST.md"), manifest);
if (run.status !== 0 || fail !== 0) process.exit(1);
