use super::*;
use crate::health_domain::{DAY, parse, observations, project};
fn batch()->Value {json!({"schema":"health-envelope-v1","batchId":"batch1","exportedAtMs":1788825600000i64,"windowStartMs":1788220800000i64,"windowEndMs":1788825600000i64,"timezoneOffsetMinutes":0,"source":{"id":"watch","name":"Synthetic Watch"},"samples":[{"sampleId":"s1","revision":1,"metric":"steps","startMs":1788739200000i64,"endMs":1788742800000i64,"value":3000,"unit":"count"}]})}
fn bytes(v:&Value)->Vec<u8>{serde_json::to_vec(v).unwrap()}
fn db()->Connection {let c=Connection::open_in_memory().unwrap();c.execute_batch("CREATE TABLE meta(id INTEGER PRIMARY KEY,revision INTEGER);INSERT INTO meta VALUES(1,0);CREATE TABLE records(id TEXT PRIMARY KEY,body TEXT);CREATE TABLE sources(id TEXT PRIMARY KEY,body TEXT);CREATE TABLE states(id TEXT PRIMARY KEY,body TEXT);").unwrap();c}
fn receive(c:&mut Connection,v:&Value)->R<Value>{ingest(&mut SqliteHealth(c),&bytes(v),1788825600100)}
fn snapshot(c:&Connection)->String {let mut out=vec![];for t in ["records","sources","states"]{let mut q=c.prepare(&format!("SELECT body FROM {t} ORDER BY id")).unwrap();out.extend(q.query_map([],|r|r.get::<_,String>(0)).unwrap().map(Result::unwrap));}out.join("\n")}
fn obs(v:&Value)->Vec<Observation>{observations(&parse(&bytes(v)).unwrap(),42)}
#[test] fn valid_receive_and_replay_are_atomic_idempotent(){let mut c=db();assert_eq!(receive(&mut c,&batch()).unwrap()["changed"],1);let before=snapshot(&c);assert_eq!(receive(&mut c,&batch()).unwrap()["state"],"duplicate");assert_eq!(before,snapshot(&c));}
#[test] fn invalid_fields_units_times_limits_leave_zero_writes(){let mut c=db();let mut cases=vec![];for (key,value) in [("unknown",json!(true)),("schema",json!("wrong")),("timezoneOffsetMinutes",json!(900)),("windowEndMs",json!(0))]{let mut v=batch();v[key]=value;cases.push(v);}for(key,value)in[("unit",json!("km")),("value",json!(-1)),("value",json!(0.5)),("endMs",json!(0)),("unknown",json!(0)),("revision",json!(0)),("metric",json!("pain"))]{let mut v=batch();v["samples"][0][key]=value;cases.push(v);}let mut v=batch();v["samples"]=json!(vec![v["samples"][0].clone();257]);cases.push(v);for v in cases{assert!(receive(&mut c,&v).is_err());assert_eq!(snapshot(&c),"");}assert!(ingest(&mut SqliteHealth(&mut c),&vec![b' ';domain::LIMIT+1],1).is_err());assert!(parse(b"{\"schema\":1,\"schema\":2}").is_err());assert!(parse(&[0xff]).is_err());}
#[test] fn conflicting_batch_or_sample_rolls_back_every_row(){let mut c=db();receive(&mut c,&batch()).unwrap();let before=snapshot(&c);let mut v=batch();v["samples"][0]["value"]=json!(4000);assert!(receive(&mut c,&v).is_err());v["batchId"]=json!("other");let mut first=v["samples"][0].clone();first["sampleId"]=json!("new");v["samples"].as_array_mut().unwrap().insert(0,first);assert_eq!(receive(&mut c,&v).unwrap_err().code,"health_version_conflict");assert_eq!(snapshot(&c),before);}
#[test] fn batch_internal_conflicts_and_duplicates_deterministic(){let mut c=db();let mut v=batch();let s=v["samples"][0].clone();v["samples"].as_array_mut().unwrap().push(s.clone());assert_eq!(receive(&mut c,&v).unwrap()["inserted"],1);let mut v=batch();v["samples"].as_array_mut().unwrap().push(s);v["samples"][1]["value"]=json!(1);assert_eq!(parse(&bytes(&v)).unwrap_err().code,"health_version_conflict");}
#[test] fn higher_revision_corrects_old_and_new_day_only(){let mut c=db();let mut v=batch();let mut unrelated=v["samples"][0].clone();unrelated["sampleId"]=json!("unrelated");unrelated["startMs"]=json!(1788566400000i64);unrelated["endMs"]=json!(1788570000000i64);v["samples"].as_array_mut().unwrap().push(unrelated);receive(&mut c,&v).unwrap();let before=rows(&c,"states","health_current_state").unwrap();let untouched=before.iter().find(|s|s["dayIndex"]==1788566400000i64/DAY).unwrap().clone();let mut fix=batch();fix["batchId"]=json!("fix");fix["samples"][0]["revision"]=json!(2);fix["samples"][0]["startMs"]=json!(1788652800000i64);fix["samples"][0]["endMs"]=json!(1788656400000i64);assert_eq!(receive(&mut c,&fix).unwrap()["changed"],2);let states=rows(&c,"states","health_current_state").unwrap();assert!(states.contains(&untouched));assert!(states.iter().any(|s|s["method"]=="no_current_sample"&&s["value"].is_null()));assert_eq!(rows(&c,"records","health_sample").unwrap().len(),3);}
#[test] fn lower_revision_late_and_empty_do_not_erase_current(){let mut c=db();let mut v=batch();v["samples"][0]["revision"]=json!(2);receive(&mut c,&v).unwrap();let before=rows(&c,"states","health_current_state").unwrap();v["batchId"]=json!("late");v["samples"][0]["revision"]=json!(1);v["samples"][0]["value"]=json!(5);assert_eq!(receive(&mut c,&v).unwrap()["changed"],0);v["batchId"]=json!("empty");v["samples"]=json!([]);receive(&mut c,&v).unwrap();assert_eq!(before,rows(&c,"states","health_current_state").unwrap());}
#[test] fn same_version_in_new_batch_does_not_refresh_observed_or_received_state(){let mut c=db();receive(&mut c,&batch()).unwrap();let before=rows(&c,"states","health_current_state").unwrap();let mut v=batch();v["batchId"]=json!("reexport");ingest(&mut SqliteHealth(&mut c),&bytes(&v),1788912000000).unwrap();assert_eq!(before,rows(&c,"states","health_current_state").unwrap());}
#[test] fn multi_source_count_never_max_or_sum(){let v=batch();let mut all=obs(&v);let mut other=all[0].clone();other.source.id="phone".into();other.sample.value=5000.0;all.push(other);let s=project(&all[0].keys().into_iter().next().unwrap(),&all);assert!(s["value"].is_null());assert_eq!(s["method"],"per_source_unmerged");assert_eq!(s["sources"].as_array().unwrap().len(),2);}
#[test] fn overlapping_count_same_source_is_uncertain(){let mut all=obs(&batch());let mut o=all[0].clone();o.sample.sample_id="s2".into();all.push(o);let s=project(&all[0].keys().into_iter().next().unwrap(),&all);assert!(s["value"].is_null());assert_eq!(s["method"],"overlap_uncertain");}
#[test] fn sleep_union_only_explicit_sleep_intervals(){let mut v=batch();v["samples"][0]["metric"]=json!("sleep");v["samples"][0]["unit"]=json!("milliseconds");v["samples"][0]["value"]=json!(3600000);let mut all=obs(&v);let mut other=all[0].clone();other.source.id="phone".into();all.push(other);assert_eq!(project(&all[0].keys().into_iter().next().unwrap(),&all)["value"],60.0);v["samples"][0]["metric"]=json!("inBed");assert!(parse(&bytes(&v)).is_err());}
#[test] fn cross_midnight_proration_explicit_and_offsets_separate(){let mut v=batch();v["samples"][0]["startMs"]=json!(1788737400000i64);v["samples"][0]["endMs"]=json!(1788741000000i64);let all=obs(&v);let keys=all[0].keys();assert_eq!(keys.len(),2);for k in &keys{let s=project(k,&all);assert_eq!(s["value"],1500.0);assert_eq!(s["estimated"],true);}let mut other=all[0].clone();other.offset=480;let mut both=all.clone();both.push(other);assert_eq!(project(keys.first().unwrap(),&both)["sources"].as_array().unwrap().len(),1);}
#[test] fn missing_metric_is_absent_not_zero(){let mut c=db();receive(&mut c,&batch()).unwrap();let s=rows(&c,"states","health_current_state").unwrap();assert_eq!(s.len(),1);assert_eq!(s[0]["metric"],"steps");}
#[test] fn exercise_rejects_impossible_duration(){let mut v=batch();v["samples"][0]["metric"]=json!("exercise");v["samples"][0]["unit"]=json!("minutes");v["samples"][0]["value"]=json!(61);assert!(parse(&bytes(&v)).is_err());v["samples"][0]["value"]=json!(30);assert!(parse(&bytes(&v)).is_ok());}
#[test] fn transaction_failure_rolls_back_and_retry_succeeds(){let mut c=db();c.execute_batch("CREATE TRIGGER fail_state BEFORE INSERT ON states BEGIN SELECT RAISE(ABORT,'simulated interruption'); END;").unwrap();assert!(receive(&mut c,&batch()).is_err());assert_eq!(snapshot(&c),"");c.execute_batch("DROP TRIGGER fail_state;").unwrap();assert!(receive(&mut c,&batch()).is_ok());}
#[test] fn multi_revision_batch_order_does_not_change_projection(){let mut a=batch();let mut next=a["samples"][0].clone();next["revision"]=json!(2);next["value"]=json!(4000);a["samples"].as_array_mut().unwrap().push(next);let mut b=a.clone();b["samples"].as_array_mut().unwrap().reverse();let mut c=db();let mut d=db();receive(&mut c,&a).unwrap();receive(&mut d,&b).unwrap();assert_eq!(rows(&c,"states","health_current_state").unwrap(),rows(&d,"states","health_current_state").unwrap());}
#[test] fn restart_and_public_legacy_prepare_keep_health_out(){
 let fixture=format!("health-restart-{}",std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos());
 let mut c=repository::open(&fixture).unwrap();crate::source_store::init(&c).unwrap();receive(&mut c,&batch()).unwrap();let before=rows(&c,"states","health_current_state").unwrap();drop(c);
 let mut c=repository::open(&fixture).unwrap();assert_eq!(before,rows(&c,"states","health_current_state").unwrap());let mut bad=batch();bad["samples"][0]["value"]=json!(-1);assert!(receive(&mut c,&bad).is_err());assert_eq!(before,rows(&c,"states","health_current_state").unwrap());drop(c);
 crate::conversation_store::dispatch("get_context_recovery",repository::Request{version:3,operation:"open_conversation".into(),payload:json!({"requestId":"health-open","conversationId":"source-chat"})},&fixture).unwrap();
 let call=|ipc:&str,op:&str,payload:Value|repository::dispatch(ipc,repository::Request{version:2,operation:op.into(),payload},&fixture);
 let snap=call("get_today","snapshot",json!({})).unwrap();let raw=snap["records"].as_array().unwrap().iter().find(|r|r["kind"]=="health_sample").unwrap();
 let packet=json!({"id":"health-denied-packet","purpose":"health","budget":256,"usedBudget":8,"topK":3,"inputRefs":[{"id":raw["id"],"version":1,"authorizationGeneration":1}],"included":[{"id":raw["id"],"text":"synthetic health","layer":"L3","domain":"Health"}],"excluded":[],"states":[],"feedback":[],"createdAt":1788825600000i64});
 let error=call("assemble_global_ai_context","local_prepare",json!({"requestId":"health-denied","expectedGeneration":snap["revision"],"packet":packet})).unwrap_err();assert_eq!(error.code,"context_stale");
 let after=call("get_today","snapshot",json!({})).unwrap();assert_eq!(after["packets"],json!([]));
}
#[test] fn inbox_adapter_rejects_links_oversize_and_partial_files(){
 use std::os::unix::fs::symlink;
 let name=format!("health-files-{}",std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos());
 let d=crate::artifact_io::Dir::root().unwrap().child("fixtures",false).unwrap().new_child(&name).unwrap();let path=std::path::Path::new(crate::runtime_root::ROOT).join("fixtures").join(name);
 let mut valid=d.create("valid.json").unwrap();valid.write_all(&bytes(&batch())).unwrap();assert!(parse(&read_file(&d,"valid.json").unwrap()).is_ok());
 symlink("valid.json",path.join("link.json")).unwrap();assert!(read_file(&d,"link.json").is_err());std::fs::hard_link(path.join("valid.json"),path.join("hard.json")).unwrap();assert!(read_file(&d,"hard.json").is_err());
 let mut big=d.create("big.json").unwrap();big.write_all(&vec![b' ';domain::LIMIT+1]).unwrap();assert!(read_file(&d,"big.json").is_err());
 let mut partial=d.create("partial.json").unwrap();partial.write_all(b"{\"schema\":").unwrap();assert!(parse(&read_file(&d,"partial.json").unwrap()).is_err());
 assert_eq!(std::fs::read(path.join("valid.json")).unwrap(),bytes(&batch()));
}
