use super::*;use std::sync::{Arc,Mutex};use crate::model_port::ModelPort;
fn store()->Store{super::super::controlled_tests::store()}
fn preview(s:&Store,raw:&str)->Value{let t=crate::conversation_store::uid("turn");let d=json!({"requestId":format!("draft:{t}"),"turnId":t,"revision":1,"text":raw});s.dispatch("capture_record",json!({"version":4,"operation":"draft_turn","payload":d}).to_string().as_bytes()).unwrap();s.dispatch("resolve_request_context",json!({"version":7,"operation":"prepare_operation_turn","payload":{"requestId":format!("prepare:{t}"),"turnId":t,"expectedDraftRevision":1}}).to_string().as_bytes()).unwrap()}
fn cp(v:&Value)->Value{json!({"requestId":v["requestId"],"previewId":v["previewId"],"expectedPreviewRevision":v["revision"]})}
fn span(v:&Value)->Value{json!([{"messageRef":"current","start":0,"end":v["question"].as_str().unwrap().chars().count()}])}
fn create(v:&Value)->Value{json!({"operation":"create","content":v["question"],"evidenceSpans":span(v),"sourceRefs":[]})}
fn update(v:&Value,op:&str)->Value{let a=&v["disclosure"]["allowed_targets"][0];let mut c=json!({"operation":op,"targetRef":a["ref"],"expectedVersion":a["version"],"evidenceSpans":span(v)});if op=="adjust"{c["content"]=json!("后天下午去健身房");c["sourceRefs"]=json!([]);}c}
struct Spy{calls:usize,reply:String,body:String}
impl Spy{fn new(c:Value)->Self{Self{calls:0,reply:json!({"schemaVersion":1,"answerText":"模型说已经完成（不得冒充回执）","candidate":c}).to_string(),body:String::new()}}}
impl ModelPort for Spy{fn generate(&mut self,b:&str,_:&[u8])->R<ModelResponse>{self.calls+=1;self.body=b.into();Ok(ModelResponse{text:self.reply.clone(),usage:None})}}
fn send(s:&Arc<Mutex<Store>>,v:&Value,p:&mut dyn ModelPort)->Value{crate::host_gateway::dispatch_with_port(s,"send_source_ai_request",json!({"version":7,"operation":"confirm_operation_turn","payload":cp(v)}).to_string().as_bytes(),p).unwrap()}
fn actions(s:&Arc<Mutex<Store>>)->Vec<Value>{Store::actions(&s.lock().unwrap().c).unwrap()}
#[test]fn v7_public_create_adjust_complete_identity_replay_and_disclosure(){let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"明天下午去健身房");assert!(!v.to_string().contains("p152-secret-leak-canary"));assert!(serde_json::to_vec(&v["disclosure"]).unwrap().len()<=4096);let mut p=Spy::new(create(&v));let r=send(&s,&v,&mut p);assert_eq!(r["businessChanged"],true);assert!(r["reply"].as_str().unwrap().starts_with("本地记录：已记下"));assert!(!r["reply"].as_str().unwrap().contains("模型说"));assert_eq!(p.body,v["exactBody"].as_str().unwrap());assert_eq!(send(&s,&v,&mut p),r);assert_eq!(p.calls,1);let aid=r["action"]["id"].clone();
 let v=preview(&s.lock().unwrap(),"挪到后天吧");let r=send(&s,&v,&mut Spy::new(update(&v,"adjust")));assert_eq!(r["action"]["id"],aid);assert_eq!(r["action"]["version"],2);
 let v=preview(&s.lock().unwrap(),"做完啦");let r=send(&s,&v,&mut Spy::new(update(&v,"complete")));assert_eq!(r["action"]["id"],aid);assert_eq!(r["action"]["status"],"completed");assert_eq!(actions(&s).len(),1);
}
#[test]fn v7_public_cancellation_uses_existing_identity(){let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"明天下午去健身房");send(&s,&v,&mut Spy::new(create(&v)));let v=preview(&s.lock().unwrap(),"先不去健身房了");let r=send(&s,&v,&mut Spy::new(update(&v,"cancel")));assert_eq!(r["action"]["status"],"cancelled");assert_eq!(actions(&s)[0]["version"],2);}
#[test]fn v7_two_possible_targets_do_not_follow_single_history_shortcut(){let s=Arc::new(Mutex::new(store()));for q in ["明天下午去健身房","周六去游泳馆"]{let v=preview(&s.lock().unwrap(),q);send(&s,&v,&mut Spy::new(create(&v)));}let v=preview(&s.lock().unwrap(),"那个先不去了");assert_eq!(v["disclosure"]["allowed_targets"].as_array().unwrap().len(),2);let r=send(&s,&v,&mut Spy::new(update(&v,"cancel")));assert_eq!(r["businessChanged"],false);assert!(actions(&s).iter().all(|a|a["status"]=="planned"));}
#[test]fn v7_topic_switch_breaks_implicit_target(){let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"明天下午去健身房");send(&s,&v,&mut Spy::new(create(&v)));let v=preview(&s.lock().unwrap(),"换个话题聊电影");send(&s,&v,&mut Spy::new(json!({"operation":"none"})));let v=preview(&s.lock().unwrap(),"那个做完了");assert!(v["disclosure"]["allowed_targets"].as_array().unwrap().is_empty());let c=json!({"operation":"complete","targetRef":"T1","expectedVersion":1,"evidenceSpans":span(&v)});assert_eq!(send(&s,&v,&mut Spy::new(c))["businessChanged"],false);assert_eq!(actions(&s)[0]["status"],"planned");}
#[test]fn v7_conditional_quote_and_vague_pause_cannot_be_model_authority(){for raw in ["我明天要是下雨就不出门","他说他明天下午去健身房","我不打算买材料","先缓缓"]{let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),raw);let r=send(&s,&v,&mut Spy::new(create(&v)));assert_eq!(r["operation"],"clarify");assert_eq!(r["businessChanged"],false);assert!(actions(&s).is_empty());}}
#[test]fn v7_empty_nonjson_duplicate_fields_null_extra_permission_are_rejected(){for reply in ["".into(),"not-json".into(),"{\"schemaVersion\":1,\"schemaVersion\":1,\"answerText\":\"\",\"candidate\":{\"operation\":\"none\"}}".into(),json!({"schemaVersion":1,"answerText":"","candidate":null}).to_string(),json!({"schemaVersion":1,"answerText":"","candidate":{"operation":"none","authorization":true}}).to_string()]{let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"明天下午去健身房");let mut p=Spy::new(create(&v));p.reply=reply;assert_eq!(send(&s,&v,&mut p)["state"],"failed");assert_eq!(send(&s,&v,&mut p)["state"],"failed");assert_eq!(p.calls,1);assert!(actions(&s).is_empty());assert_eq!(s.lock().unwrap().snapshot().unwrap()["pendingDraft"]["text"],"明天下午去健身房");}}
#[test]fn v7_source_text_and_old_message_cannot_supply_current_evidence(){let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"请解释我的睡眠记录");let mut c=create(&v);c["evidenceSpans"]=json!([{"messageRef":"S1","start":0,"end":2}]);assert_eq!(send(&s,&v,&mut Spy::new(c))["state"],"failed");assert!(actions(&s).is_empty());}
#[test]fn v7_cancel_before_confirm_has_zero_calls(){let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"明天下午去健身房");s.lock().unwrap().operation_cancel(decode(json!({"previewId":v["previewId"],"expectedPreviewRevision":1})).unwrap()).unwrap();let mut p=Spy::new(create(&v));assert!(crate::host_gateway::dispatch_with_port(&s,"send_source_ai_request",json!({"version":7,"operation":"confirm_operation_turn","payload":cp(&v)}).to_string().as_bytes(),&mut p).is_err());assert_eq!(p.calls,0);}
#[test]fn v7_forged_confirm_fields_or_request_cannot_send(){let s=store();let v=preview(&s,"明天下午去健身房");for k in ["body","modelId","authorization","targetRefs"]{let mut p=cp(&v);p[k]=json!("forged");assert!(s.operation_consume(p).is_err());}let mut p=cp(&v);p["requestId"]=json!("foreign");assert!(s.operation_consume(p).is_err());}
#[test]fn v7_late_deadline_or_authorization_change_never_executes(){for mutation in 0..2{let s=store();let v=preview(&s,"明天下午去健身房");let OperationStart::Send(plan)=s.operation_consume(cp(&v)).unwrap()else{panic!()};if mutation==0{let mut p=get(&s.c,"packets",v["previewId"].as_str().unwrap()).unwrap().unwrap();p["deadline"]=json!(now()-1);put(&s.c,"packets",v["previewId"].as_str().unwrap(),&p).unwrap();}else{let mut a=get(&s.c,"sources","conversation").unwrap().unwrap();a["generation"]=json!(2);put(&s.c,"sources","conversation",&a).unwrap();}let r=s.operation_finish(&plan,Ok(ModelResponse{text:Spy::new(create(&v)).reply,usage:None})).unwrap();assert_eq!(r["state"],"failed");assert!(Store::actions(&s.c).unwrap().is_empty());}}
#[test]fn v7_transaction_fault_rolls_back_action_feedback_and_receipt(){let s=store();let v=preview(&s,"明天下午去健身房");s.c.execute_batch("CREATE TRIGGER operation_fault BEFORE INSERT ON feedback BEGIN SELECT RAISE(ABORT,'synthetic'); END").unwrap();let s=Arc::new(Mutex::new(s));let mut p=Spy::new(create(&v));assert_eq!(send(&s,&v,&mut p)["state"],"failed");assert!(actions(&s).is_empty());assert_eq!(send(&s,&v,&mut p)["state"],"failed");assert_eq!(p.calls,1);assert!(s.lock().unwrap().snapshot().unwrap()["pendingDraft"].is_object());}
#[test]fn v7_lost_return_and_restart_read_same_receipt_no_resend(){let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"明天下午去健身房");let path=s.lock().unwrap().c.path().unwrap().to_string();let mut p=Spy::new(create(&v));let first=send(&s,&v,&mut p);drop(s);let s=Arc::new(Mutex::new(Store::open(Path::new(&path)).unwrap()));let bytes=json!({"version":7,"operation":"operation_turn_status","payload":{"requestId":v["requestId"]}}).to_string();let r=s.lock().unwrap().dispatch("get_context_recovery",bytes.as_bytes()).unwrap();assert_eq!(first,r);assert_eq!(send(&s,&v,&mut p),first);assert_eq!(p.calls,1);assert_eq!(actions(&s).len(),1);}
#[test]fn v7_restart_inflight_never_resends_or_reinterprets(){let s=store();let v=preview(&s,"明天下午去健身房");assert!(matches!(s.operation_consume(cp(&v)).unwrap(),OperationStart::Send(_)));let path=s.c.path().unwrap().to_string();drop(s);let s=Arc::new(Mutex::new(Store::open(Path::new(&path)).unwrap()));let mut p=Spy::new(create(&v));assert_eq!(send(&s,&v,&mut p)["state"],"outcome_unknown");assert_eq!(p.calls,0);assert!(actions(&s).is_empty());}
#[test]fn v7_unicode_scalar_offsets_and_oversize_budget(){let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"明天看🌼花展");assert_eq!(send(&s,&v,&mut Spy::new(create(&v)))["businessChanged"],true);let v=preview(&s.lock().unwrap(),"明天看🌼花展");let mut c=create(&v);c["evidenceSpans"][0]["end"]=json!(999);assert_eq!(send(&s,&v,&mut Spy::new(c))["state"],"failed");}
#[test]fn v7_explicit_short_state_and_existing_source_context_are_retained(){let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"我有20分钟工作时间");assert_eq!(send(&s,&v,&mut Spy::new(json!({"operation":"none"})))["businessChanged"],false);let snap=s.lock().unwrap().snapshot().unwrap();assert!(snap["states"].as_array().unwrap().iter().any(|x|x["value"]==20.0));let v=preview(&s.lock().unwrap(),"给我工作建议");assert!(v["items"].as_array().unwrap().iter().any(|i|i["text"]=="我有20分钟工作时间"));assert!(actions(&s).is_empty());}
#[test]fn v7_response_truncation_and_timeout_are_consumed_without_business_change(){struct Fault{calls:usize,truncated:bool}impl ModelPort for Fault{fn generate(&mut self,_:&str,_:&[u8])->R<ModelResponse>{self.calls+=1;if self.truncated{crate::provider_transport::decode_chat_response(br#"{"choices":[{"finish_reason":"length","message":{"content":"{}"}}]}"#)}else{Err(error("provider_timeout"))}}}for truncated in [false,true]{let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"明天下午去健身房");let mut f=Fault{calls:0,truncated};assert_eq!(send(&s,&v,&mut f)["state"],"failed");assert_eq!(send(&s,&v,&mut f)["state"],"failed");assert_eq!(f.calls,1);assert!(actions(&s).is_empty());}}
#[test]fn v7_target_version_race_cannot_overwrite_new_action(){let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"明天下午去健身房");send(&s,&v,&mut Spy::new(create(&v)));let v=preview(&s.lock().unwrap(),"先不去健身房了");let s=s.lock().unwrap();let OperationStart::Send(plan)=s.operation_consume(cp(&v)).unwrap()else{panic!()};let mut a=Store::actions(&s.c).unwrap()[0].clone();a["version"]=json!(2);a["confirmedContent"]=json!("新的并发安排");put(&s.c,"records","race-event",&json!({"id":"race-event","kind":"action_event","previousVersion":1,"operation":"adjust","rawRef":"synthetic-race","at":now(),"action":a})).unwrap();let r=s.operation_finish(&plan,Ok(ModelResponse{text:Spy::new(update(&v,"cancel")).reply,usage:None})).unwrap();assert_eq!(r["state"],"failed");assert_eq!(Store::actions(&s.c).unwrap()[0]["status"],"planned");assert_eq!(Store::actions(&s.c).unwrap()[0]["version"],2);}
#[test]fn v7_budget_cannot_be_reset_by_new_preview_or_restart(){let s=store();put(&s.c,"sources","operation-budget-offline",&json!({"used":100000})).unwrap();let v=preview(&s,"明天下午去健身房");assert!(s.operation_consume(cp(&v)).is_err());let path=s.c.path().unwrap().to_string();drop(s);let s=Store::open(Path::new(&path)).unwrap();let mut s=s;s.connect_source().unwrap();let v=preview(&s,"明天去看合成画展");assert!(s.operation_consume(cp(&v)).is_err());assert_eq!(get(&s.c,"sources","operation-budget-offline").unwrap().unwrap()["used"],100000);}
#[test]fn v7_cancel_after_dispatch_discards_late_candidate(){let s=store();let v=preview(&s,"明天下午去健身房");let OperationStart::Send(plan)=s.operation_consume(cp(&v)).unwrap()else{panic!()};let cancel=s.operation_cancel(decode(json!({"previewId":v["previewId"],"expectedPreviewRevision":1})).unwrap()).unwrap();assert_eq!(cancel["state"],"cancel_requested_after_dispatch");let r=s.operation_finish(&plan,Ok(ModelResponse{text:Spy::new(create(&v)).reply,usage:None})).unwrap();assert_eq!(r["businessChanged"],false);assert!(Store::actions(&s.c).unwrap().is_empty());}

#[test]fn v7_B_partition_and_C_budget_boundaries_do_not_share_an_unlimited_mode(){
 for (mode,phase,used,dev,unseen,ok) in [("online-synthetic","development",23,23,0,true),("online-synthetic","development",24,24,0,false),("online-synthetic","unseen",39,24,15,true),("online-synthetic","unseen",40,24,16,false),("online-synthetic","development",0,0,0,true),("real","offline",7,0,0,true),("real","offline",8,0,0,false),("unknown","offline",0,0,0,false)]{assert_eq!(check_budget(&json!({"used":used,"development":dev,"unseen":unseen}),mode,phase).is_ok(),ok);}
 assert!(check_budget(&json!({"used":0}),"online-synthetic","unseen").is_err());
}

#[test]fn v7_elapsed_time_preserves_topic_but_not_send_authorization(){
 let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"明天下午去健身房");send(&s,&v,&mut Spy::new(create(&v)));
 {let h=s.lock().unwrap();let mut topic=get(&h.c,"sources","operation-topic").unwrap().unwrap();topic["expiresAt"]=json!(now()-1);put(&h.c,"sources","operation-topic",&topic).unwrap();}
 let v=preview(&s.lock().unwrap(),"算了，不去了");assert_eq!(v["disclosure"]["allowed_targets"].as_array().unwrap().len(),1);assert_eq!(v["disclosure"]["conversation_context"].as_array().unwrap().len(),1);
 {let h=s.lock().unwrap();let mut p=get(&h.c,"packets",v["previewId"].as_str().unwrap()).unwrap().unwrap();p["expiresAt"]=json!(now()-1);let id=p["id"].as_str().unwrap().to_string();put(&h.c,"packets",&id,&p).unwrap();}
 let c=json!({"operation":"cancel","targetRef":"T1","expectedVersion":1,"evidenceSpans":span(&v)});let mut model=Spy::new(c);let result=crate::host_gateway::dispatch_with_port(&s,"send_source_ai_request",json!({"version":7,"operation":"confirm_operation_turn","payload":cp(&v)}).to_string().as_bytes(),&mut model);assert_eq!(result.unwrap_err().code,"preview_stale");assert_eq!(model.calls,0);assert_eq!(actions(&s)[0]["status"],"planned");
}

#[test]fn v7_terminal_action_does_not_keep_automatic_topic_alive(){let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"明天下午去健身房");send(&s,&v,&mut Spy::new(create(&v)));let v=preview(&s.lock().unwrap(),"算了，不去了");send(&s,&v,&mut Spy::new(update(&v,"cancel")));let v=preview(&s.lock().unwrap(),"今晚把书桌整理一下");assert!(v["disclosure"]["allowed_targets"].as_array().unwrap().is_empty());assert!(v["disclosure"]["conversation_context"].as_array().unwrap().is_empty());assert_eq!(actions(&s)[0]["status"],"cancelled");}

#[test]fn v7_terminal_targets_are_not_retrieved_by_lexical_similarity(){let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"明天下午去健身房");send(&s,&v,&mut Spy::new(create(&v)));let v=preview(&s.lock().unwrap(),"算了，不去了");send(&s,&v,&mut Spy::new(update(&v,"cancel")));for raw in ["明天下午去图书馆","健身房那件事"]{let v=preview(&s.lock().unwrap(),raw);assert!(v["disclosure"]["allowed_targets"].as_array().unwrap().is_empty());}assert_eq!(actions(&s)[0]["status"],"cancelled");}

#[test]fn v7_safe_transport_error_classes_are_preserved_without_resend(){struct Fault(&'static str);impl ModelPort for Fault{fn generate(&mut self,_:&str,_:&[u8])->R<ModelResponse>{Err(error(self.0))}}for code in ["provider_protocol","provider_authentication","provider_model","provider_response_truncated","provider_response_empty","provider_rate_limited","dispatch_outcome_unknown","response_too_large","provider_network","provider_timeout","provider_unavailable"]{let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"明天下午去健身房");let r=send(&s,&v,&mut Fault(code));assert_eq!(r["errorCode"],code);assert_eq!(r["businessChanged"],false);assert!(actions(&s).is_empty());assert_eq!(send(&s,&v,&mut Fault("SHOULD_NOT_RUN")),r);}}
#[test]fn v7_untrusted_transport_error_text_is_not_persisted(){struct Fault;impl ModelPort for Fault{fn generate(&mut self,_:&str,_:&[u8])->R<ModelResponse>{Err(error("SECRET_ERROR_CANARY"))}}let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"明天下午去健身房");let r=send(&s,&v,&mut Fault);assert_eq!(r["errorCode"],"provider_failure_unclassified");assert!(!r.to_string().contains("SECRET_ERROR_CANARY"));}

#[test]fn v7_empty_target_clarification_is_valid_and_persisted(){let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"那个改到周末吧");assert!(v["disclosure"]["allowed_targets"].as_array().unwrap().is_empty());let c=json!({"operation":"clarify","question":"你指的是哪一件安排？","targetRefs":[],"intent":"adjust"});let r=send(&s,&v,&mut Spy::new(c));assert_eq!(r["state"],"succeeded");assert_eq!(r["operation"],"clarify");assert_eq!(r["businessChanged"],false);assert!(actions(&s).is_empty());let h=s.lock().unwrap();assert_eq!(get(&h.c,"packets",&format!("operation-status:{}",v["requestId"].as_str().unwrap())).unwrap().unwrap(),r);let snap=h.dispatch("get_context_recovery",json!({"version":7,"operation":"action_snapshot","payload":{"offset":0}}).to_string().as_bytes()).unwrap();assert!(snap.to_string().contains("你指的是哪一件安排"));}
#[test]fn v7_clarification_diagnostics_keep_strict_fields_refs_and_spans(){let s=store();let v=preview(&s,"那个改到周末吧");let base=json!({"schemaVersion":1,"answerText":"","candidate":{"operation":"clarify","question":"哪件安排？","targetRefs":[],"intent":"adjust"}});let mut r=base.clone();r["candidate"]["evidenceSpans"]=json!([]);assert_eq!(validate_response(&v,r).unwrap_err().code,"operation_candidate_fields");let mut r=base.clone();r["candidate"]["targetRefs"]=json!(["invented"]);let mut internal=v.clone();internal["targetMap"]=json!({});assert_eq!(validate_response(&internal,r).unwrap_err().code,"operation_target_refs_invalid");}

#[test]fn v7_chinese_prompt_and_variable_clarification_text_are_preserved(){for question in ["你指的是哪一件安排？","请说明需要调整的事项。"]{let s=Arc::new(Mutex::new(store()));let v=preview(&s.lock().unwrap(),"那个改到周末吧");let body=v["exactBody"].as_str().unwrap();assert!(body.contains("Simplified Chinese for Chinese input"));assert!(body.contains("你指的是哪一件安排"));assert!(!body.contains("Which arrangement do you mean"));let r=send(&s,&v,&mut Spy::new(json!({"operation":"clarify","question":question,"targetRefs":[],"intent":"adjust"})));assert_eq!(r["reply"],format!("本轮未更改安排。\n{question}"));assert_eq!(r["businessChanged"],false);}}

#[test]fn d0667_waited_credential_rechecks_expiry_revoke_profile_enabled_and_target(){
 for mode in ["expiry","credential_revoke","profile_revision","disabled","authorization","target"]{
  let shared=Arc::new(Mutex::new(store()));let first=preview(&shared.lock().unwrap(),"明天下午去健身房");send(&shared,&first,&mut Spy::new(create(&first)));let s=shared.lock().unwrap();let v=preview(&s,"挪到后天吧");
  if mode=="expiry"{let mut saved=get(&s.c,"packets",v["previewId"].as_str().unwrap()).unwrap().unwrap();saved["expiresAt"]=json!(now()+200);let id=saved["id"].as_str().unwrap().to_string();put(&s.c,"packets",&id,&saved).unwrap();}
  let mut loads=0;let result=s.operation_consume_with_loader(cp(&v),||{loads+=1;let key=crate::provider_store::credential(&s.fixture())?;
   match mode{
    "expiry"=>std::thread::sleep(std::time::Duration::from_millis(250)),
    "credential_revoke"|"profile_revision"=>{let path=PathBuf::from(ROOT).join("synthetic").join(format!("{}-provider.sqlite",s.fixture()));let c=Connection::open(path).unwrap();if mode=="credential_revoke"{c.execute("UPDATE provider_profile SET envelope_json=NULL,credential_revision=credential_revision+1",[]).unwrap();}else{c.execute("UPDATE provider_profile SET revision=revision+1",[]).unwrap();}},
    "disabled"=>{let mut x=get(&s.c,"sources","_provider_lifecycle")?.unwrap();x["enabled"]=json!(false);put(&s.c,"sources","_provider_lifecycle",&x)?;},
    "authorization"=>{let mut x=get(&s.c,"sources","conversation")?.unwrap();x["generation"]=json!(999);x["authorized"]=json!(false);put(&s.c,"sources","conversation",&x)?;},
    "target"=>{let mut a=Store::actions(&s.c)?[0].clone();a["version"]=json!(2);put(&s.c,"records","waiting-race",&json!({"id":"waiting-race","kind":"action_event","previousVersion":1,"operation":"adjust","rawRef":"synthetic-only","at":now(),"action":a}))?;},_=>unreachable!()};Ok(key)});
  assert!(result.is_err(),"{mode}");assert_eq!(loads,1);assert_eq!(get(&s.c,"sources","operation-budget-offline").unwrap().unwrap()["used"],1);assert_eq!(s.c.query_row("SELECT count(*) FROM requests WHERE id=?",[v["requestId"].as_str().unwrap()],|r|r.get::<_,i64>(0)).unwrap(),0);assert_eq!(Store::actions(&s.c).unwrap()[0]["version"],1);
 }
}
#[test]fn d0667_unchanged_credential_wait_allows_one_plan(){let s=store();let v=preview(&s,"明天下午去健身房");let mut loads=0;let start=s.operation_consume_with_loader(cp(&v),||{loads+=1;crate::provider_store::credential(&s.fixture())}).unwrap();let OperationStart::Send(plan)=start else{panic!()};assert_eq!(loads,1);assert!(s.operation_preflight(&plan).unwrap().is_none());assert_eq!(get(&s.c,"sources","operation-budget-offline").unwrap().unwrap()["used"],1);}
#[test]fn d0667_last_transport_boundary_rejects_new_authorization_race(){let s=store();let v=preview(&s,"明天下午去健身房");let OperationStart::Send(plan)=s.operation_consume(cp(&v)).unwrap()else{panic!()};let mut x=get(&s.c,"sources","conversation").unwrap().unwrap();x["generation"]=json!(999);put(&s.c,"sources","conversation",&x).unwrap();let result=s.operation_preflight(&plan).unwrap().unwrap();assert_eq!(result["state"],"failed");assert_eq!(result["businessChanged"],false);assert!(Store::actions(&s.c).unwrap().is_empty());assert_eq!(get(&s.c,"sources","operation-budget-offline").unwrap().unwrap()["used"],1);}

#[test]fn d0667_pretransport_cancel_preserves_original_receipt(){let s=store();let v=preview(&s,"明天下午去健身房");let OperationStart::Send(plan)=s.operation_consume(cp(&v)).unwrap()else{panic!()};let cancelled=s.operation_cancel(decode(json!({"previewId":v["previewId"],"expectedPreviewRevision":1})).unwrap()).unwrap();assert_eq!(s.operation_preflight(&plan).unwrap().unwrap(),cancelled);assert_eq!(s.operation_preflight(&plan).unwrap().unwrap(),cancelled);assert!(Store::actions(&s.c).unwrap().is_empty());}
