import {test} from 'node:test';
import assert from 'node:assert/strict';
import {resolve} from '../ui/core.js';
import {healthView,healthSettings} from '../ui/health_view.js';
import {ConversationFlow} from '../ui/conversation_flow.js';
const snap={revision:1,now:Date.now(),records:[{id:'health:s1',kind:'health_sample',status:'observed',modelEligible:false,sourceId:'health',version:1,text:'PRIVATE HEALTH',domain:'Health'}],sources:[{id:'health',authorized:false}],states:[{id:'health-state',kind:'health_current_state',status:'observed',modelEligible:false,rawId:'health:s1',dayIndex:20600,offsetMinutes:480,metric:'steps',unit:'count',value:null,method:'per_source_unmerged',sources:[{name:'Watch',value:3000},{name:'Phone',value:5000}],refs:[],observedAt:1,receivedAt:Date.now()}],memories:[],questions:[],packets:[],derivations:[],feedback:[],drafts:[]};
test('health excluded by actual resolver for every purpose, even active/status spoof',()=>{for(const purpose of ['person','work','health'])for(const spoof of [false,true]){const s=structuredClone(snap);if(spoof){s.records[0].status='active';s.sources[0].authorized=true;}const p=resolve(s,purpose);assert.equal(p.included.length,0);assert.equal(p.states.length,0);assert(!JSON.stringify(p).includes('PRIVATE HEALTH'));}});
test('health view shows unmerged sources, observation freshness, and no fabricated zero',()=>{const html=healthView(snap);for(const text of ['暂无法可靠合并','Watch','3000','Phone','5000','观察已超过24小时','收到','未授权 AI 读取'])assert(html.includes(text),text);assert(healthView({}).includes('缺失不记为零'));assert(healthSettings({sources:[]}).includes('尚未连接 iPhone'));});
const defer=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject}};
function setup(overrides={}){const calls=[];let n=0;const api={open:async()=>({pendingDraft:{text:'OLD RECOVERY'}}),call:async(...a)=>calls.push(a),ask:async()=>{},preview:async(t,removed=[])=>{calls.push(['preview',t,removed]);return{previewId:'p'+(++n),state:removed.length?'no_match':'ready',revision:1,confirmationToken:'token',expiresAt:Date.now()+60000,items:removed.length?[]:[{source:{segmentId:'segment1'}}]}},cancel:async p=>calls.push(['cancel',p.previewId]),send:async()=>calls.push(['send']),...overrides};const f=new ConversationFlow(api,()=>{},async()=>{});return{f,calls};}
test('failed startup retry cannot overwrite typing between attempts',async()=>{let attempts=0;const {f}=setup({open:async()=>{if(!attempts++)throw{code:'database_unavailable'};return{pendingDraft:{text:'STALE'}}}});await f.start();f.edit('USER EDIT');await f.start();assert.equal(f.draft.text,'USER EDIT');f.dispose();});
test('remove uses stored turn identity even public preview has no turnId, cancels before rebuilding',async()=>{const {f,calls}=setup();await f.start();f.edit('q');await f.prepare();const turn=calls.find(c=>c[0]==='preview')[1];await f.remove('segment1');assert.equal(calls.at(-1)[1],turn);assert.deepEqual(calls.at(-1)[2],['segment1']);assert.equal(calls.at(-2)[0],'cancel');assert.equal(f.preview.state,'no_match');await f.confirm();assert(!calls.some(c=>c[0]==='send'));f.dispose();});
test('remove failure never leaves old send confirmation',async()=>{const {f}=setup({cancel:async()=>{throw{code:'database_unavailable'}}});await f.start();f.edit('q');await f.prepare();await f.remove('segment1');assert.equal(f.preview,null);assert.equal(f.error.code,'database_unavailable');f.dispose();});
test('edit during removal cannot resurrect returned confirmation',async()=>{const wait=defer();let n=0;const {f}=setup({preview:async()=>{if(n++)return wait.promise;return{previewId:'old',state:'ready',expiresAt:Date.now()+60000,items:[{source:{segmentId:'segment1'}}]}}});await f.start();f.edit('q');await f.prepare();const pending=f.remove('segment1');await Promise.resolve();f.edit('new draft');wait.resolve({previewId:'late',state:'ready'});await pending;assert.equal(f.preview,null);assert.equal(f.draft.text,'new draft');f.dispose();});
test('observation display uses envelope offset, receipt labels device time',()=>{const s=structuredClone(snap);s.states[0].observedAt=0;s.states[0].offsetMinutes=-300;const html=healthView(s);assert(html.includes('1969-12-31 19:00:00'));assert(html.includes('UTC-5'));assert(html.includes('收到（本机时间）'));});
