use super::*;use std::sync::{Arc,Mutex,atomic::{AtomicUsize,Ordering}};use crate::model_port::{ModelPort,ModelResponse};
static NEXT:AtomicUsize=AtomicUsize::new(0);
fn store()->Store{let mut s=Store::open(&PathBuf::from(ROOT).join(format!("synthetic/controlled-{}-{}.sqlite",std::process::id(),NEXT.fetch_add(1,Ordering::SeqCst)))).unwrap();s.connect_source().unwrap();s.controlled("save_ai_provider_settings","save_credential",json!({"requestId":"key","expectedCredentialRevision":0,"apiKey":"p152-secret-leak-canary"})).unwrap();s.controlled("save_ai_provider_settings","select_model",json!({"requestId":"model","modelId":"user-chosen-synthetic"})).unwrap();s}
fn preview(s:&Store,t:&str,q:&str)->Value{let draft=json!({"requestId":format!("d-{t}"),"turnId":t,"revision":1,"text":q});s.draft(decode(draft.clone()).unwrap(),draft).unwrap();let p=json!({"requestId":format!("p-{t}"),"turnId":t,"expectedDraftRevision":1});let packet=s.prepare(decode(p.clone()).unwrap(),p).unwrap();let refs=packet["snapshot"]["records"].as_array().unwrap().iter().map(|r|json!({"id":r["id"],"version":r["version"],"authorizationGeneration":1})).collect::<Vec<_>>();s.controlled("resolve_request_context","prepare_disclosure",json!({"requestId":format!("v-{t}"),"turnId":t,"packetId":packet["id"],"modelId":"user-chosen-synthetic","inputRefs":refs})).unwrap()}
fn confirmation(v:&Value)->Value{json!({"requestId":format!("send-{}",v["turnId"].as_str().unwrap()),"previewId":v["previewId"],"expectedPreviewRevision":1,"confirmationToken":v["confirmationToken"]})}
fn send(s:&Arc<Mutex<Store>>,v:&Value,port:&mut dyn ModelPort)->R<Value>{crate::host_gateway::dispatch_with_port(s,"send_source_ai_request",json!({"version":5,"operation":"confirm_send","payload":confirmation(v)}).to_string().as_bytes(),port)}
struct Spy{calls:usize,body:String,reply:String}
impl Spy{fn new()->Self{Self{calls:0,body:String::new(),reply:"synthetic reply".into()}}}
impl ModelPort for Spy{fn generate(&mut self,b:&str,_:&[u8])->R<ModelResponse>{self.calls+=1;self.body=b.into();Ok(ModelResponse{text:self.reply.clone(),usage:None})}}
#[test]fn exact_preview_body_is_only_body_sent_and_duplicate_consumes_once(){let s=store();let v=preview(&s,"one","我的睡眠记录");let body:Value=serde_json::from_str(v["exactBody"].as_str().unwrap()).unwrap();assert_eq!(body["model"],v["modelId"]);assert_eq!(body["messages"].as_array().unwrap().len(),2);let user:Value=serde_json::from_str(body["messages"][1]["content"].as_str().unwrap()).unwrap();assert_eq!(user["items"],v["items"]);assert_eq!(user["question"],v["question"]);assert!(!v.to_string().contains("p152-secret-leak-canary"));let s=Arc::new(Mutex::new(s));let mut spy=Spy::new();assert_eq!(send(&s,&v,&mut spy).unwrap()["state"],"succeeded");assert_eq!(spy.body,v["exactBody"].as_str().unwrap());assert_eq!(send(&s,&v,&mut spy).unwrap()["state"],"succeeded");assert_eq!(spy.calls,1);}
#[test]fn stale_model_draft_source_or_credential_never_reaches_adapter(){for mutation in 0..4 {let s=store();let v=preview(&s,"one","我的睡眠记录");match mutation{0=>{s.controlled("save_ai_provider_settings","select_model",json!({"requestId":"change","modelId":"different-model"})).unwrap();},1=>{let p=json!({"requestId":"edit","turnId":"one","revision":2,"text":"我的步数记录"});s.draft(decode(p.clone()).unwrap(),p).unwrap();},2=>{let mut src=get(&s.c,"sources","health-demo").unwrap().unwrap();src["authorized"]=json!(false);put(&s.c,"sources","health-demo",&src).unwrap();},_=>{s.controlled("save_ai_provider_settings","delete_credential",json!({"requestId":"delete","expectedCredentialRevision":1})).unwrap();}}let s=Arc::new(Mutex::new(s));let mut spy=Spy::new();assert!(send(&s,&v,&mut spy).is_err());assert_eq!(spy.calls,0);}}
#[test]fn readonly_health_source_bytes_unchanged_and_changes_invalidate_preview(){let s=store();let path=crate::health_source::path(&s.fixture()).unwrap();let before=std::fs::read(&path).unwrap();let v=preview(&s,"one","我的睡眠记录");assert_eq!(std::fs::read(&path).unwrap(),before);let c=Connection::open(&path).unwrap();c.execute("UPDATE states SET body=json_set(body,'$.value',123) WHERE id='sleep'",[]).unwrap();drop(c);let mut spy=Spy::new();assert!(send(&Arc::new(Mutex::new(s)),&v,&mut spy).is_err());assert_eq!(spy.calls,0);}
#[test]fn cancelled_preview_and_forged_body_are_rejected(){let s=store();let v=preview(&s,"one","睡眠记录");s.controlled("resolve_request_context","cancel_preview",json!({"requestId":"cancel","previewId":v["previewId"]})).unwrap();let mut spy=Spy::new();let s=Arc::new(Mutex::new(s));assert!(send(&s,&v,&mut spy).is_err());let mut p=confirmation(&v);p["exactBody"]=json!("forged secret body");assert!(s.lock().unwrap().consume(p).is_err());assert_eq!(spy.calls,0);}
#[test]fn remote_key_echo_is_never_persisted_or_returned(){let s=store();let v=preview(&s,"one","睡眠记录");let path=s.c.path().unwrap().to_string();let s=Arc::new(Mutex::new(s));let mut spy=Spy::new();spy.reply="p152-secret-leak-canary".into();let result=send(&s,&v,&mut spy).unwrap();assert_eq!(result["errorCode"],"provider_response_rejected");assert!(!result.to_string().contains(&spy.reply));let bytes=std::fs::read(path).unwrap();assert!(!bytes.windows(spy.reply.len()).any(|w|w==spy.reply.as_bytes()));}
#[test]fn restart_inflight_stays_unknown_and_never_resends(){let s=store();let v=preview(&s,"one","睡眠记录");assert!(matches!(s.consume(confirmation(&v)).unwrap(),Start::Send(_)));let path=s.c.path().unwrap().to_string();drop(s);let s=Store::open(Path::new(&path)).unwrap();let mut spy=Spy::new();let r=send(&Arc::new(Mutex::new(s)),&v,&mut spy).unwrap();assert_eq!(r["state"],"outcome_unknown");assert_eq!(spy.calls,0);}
#[test]fn cancel_after_handoff_does_not_claim_remote_retraction(){let s=store();let v=preview(&s,"one","睡眠记录");let Start::Send(plan)=s.consume(confirmation(&v)).unwrap() else{panic!()};let r=s.controlled("resolve_request_context","cancel_preview",json!({"requestId":"cancel","previewId":v["previewId"]})).unwrap();assert_eq!(r["state"],"cancel_requested_after_dispatch");let r=s.finish(&plan,Ok(ModelResponse{text:"late response".into(),usage:None})).unwrap();assert_eq!(r["state"],"cancelled_after_dispatch");assert!(get(&s.c,"derivations","answer:one").unwrap().is_none());}
#[test]fn future_or_wrong_metric_has_no_fabricated_health_projection(){let s=store();let v=preview(&s,"one","今天的睡眠记录");assert!(v["items"].as_array().unwrap().iter().all(|i|i["identity"]!="来源观察"));let v=preview(&s,"two","我的步数记录");assert!(v["items"].as_array().unwrap().iter().filter(|i|i["identity"]=="来源观察").all(|i|i["text"].as_str().unwrap().contains("步数")));}
#[test]fn expired_preview_or_client_supplied_body_cannot_be_confirmed(){let s=store();let v=preview(&s,"one","睡眠记录");let mut p=confirmation(&v);p["exactBody"]=json!("forged");assert!(s.consume(p).is_err());let key=v["previewId"].as_str().unwrap();let mut old=get(&s.c,"packets",key).unwrap().unwrap();old["expiresAt"]=json!(now()-1);put(&s.c,"packets",key,&old).unwrap();assert!(s.consume(confirmation(&v)).is_err());}
#[test]fn second_preview_replaces_confirmation_slot(){let s=store();let first=preview(&s,"one","睡眠记录");let second=s.controlled("resolve_request_context","prepare_disclosure",json!({"requestId":"fresh-preview","turnId":"one","packetId":"packet:one","modelId":"user-chosen-synthetic","inputRefs":first["inputRefs"]})).unwrap();assert_ne!(first["previewId"],second["previewId"]);assert!(s.consume(confirmation(&first)).is_err());assert!(matches!(s.consume(confirmation(&second)).unwrap(),Start::Send(_)));}
#[test]fn concurrent_duplicate_while_transport_owns_body_does_not_send_twice(){struct Waiting{started:std::sync::mpsc::Sender<()>,release:std::sync::mpsc::Receiver<()>}impl ModelPort for Waiting{fn generate(&mut self,_:&str,_:&[u8])->R<ModelResponse>{self.started.send(()).unwrap();self.release.recv().unwrap();Ok(ModelResponse{text:"synthetic delayed".into(),usage:None})}}
 let s=store();let v=preview(&s,"one","睡眠记录");let s=Arc::new(Mutex::new(s));let (started,ready)=std::sync::mpsc::channel();let(release,wait)=std::sync::mpsc::channel();let copy=s.clone();let preview=v.clone();let handle=std::thread::spawn(move||send(&copy,&preview,&mut Waiting{started,release:wait}));ready.recv().unwrap();let mut spy=Spy::new();assert_eq!(send(&s,&v,&mut spy).unwrap()["state"],"dispatching");assert_eq!(spy.calls,0);release.send(()).unwrap();assert_eq!(handle.join().unwrap().unwrap()["state"],"succeeded");}
#[test]fn second_store_instance_and_source_sidecar_fail_closed(){let s=store();assert!(Store::open(Path::new(s.c.path().unwrap())).is_err());let path=crate::health_source::path(&s.fixture()).unwrap();std::fs::OpenOptions::new().create_new(true).write(true).mode(0o600).open(PathBuf::from(format!("{}-journal",path.display()))).unwrap();assert!(crate::health_source::read(&s.fixture(),"睡眠记录").is_err());}

#[test]fn forged_confirmation_token_never_dispatches(){let s=store();let v=preview(&s,"token","睡眠记录");let mut forged=confirmation(&v);forged["confirmationToken"]=json!("forged-token");assert!(s.consume(forged).is_err());}
#[test]fn old_projection_invalidated_even_after_large_unrelated_history(){let s=store();preview(&s,"prior","睡眠记录");for i in 0..150{put(&s.c,"records",&format!("history-{i}"),&json!({"id":format!("history-{i}"),"kind":"health_conversation_expression","domain":"work","sourceId":"conversation","text":"synthetic history","status":"active","version":1})).unwrap();}s.refresh_source("今天的睡眠记录").unwrap();assert_eq!(get(&s.c,"records","health-source-sleep").unwrap().unwrap()["status"],"unavailable");}
#[test]fn unknown_estimated_and_multi_source_are_preserved_without_source_writes(){let s=store();let path=crate::health_source::path(&s.fixture()).unwrap();let c=Connection::open(&path).unwrap();c.execute("UPDATE states SET body=json_set(body,'$.value',NULL) WHERE id='sleep'",[]).unwrap();drop(c);let before=std::fs::read(&path).unwrap();let rows=crate::health_source::read(&s.fixture(),"睡眠记录").unwrap();assert!(rows[0]["value"].is_null());assert!(rows[0]["text"].as_str().unwrap().contains("未知，不当作零"));assert!(rows[0]["text"].as_str().unwrap().contains("不合并为总量"));let exercise=crate::health_source::read(&s.fixture(),"运动").unwrap();assert!(exercise.iter().any(|r|r["estimated"]==true&&r["text"].as_str().unwrap().contains("估算")));assert_eq!(std::fs::read(path).unwrap(),before);}
