import {test} from 'node:test';
import assert from 'node:assert/strict';
import {ControlledFlow} from '../candidate/ui/controlled_conversation.js';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
const snapshot={revision:1,pendingDraft:null,turns:[{turnId:'prior-synthetic-turn',answer:'synthetic prior answer'}]};
function setup(overrides={}){let sends=0,prepares=0;const app={read:async()=>snapshot,draft:async()=>{},cancel:async()=>{},cancelPreview:async()=>({}),prepare:async()=>{prepares++;return {kind:'preview',preview:{previewId:'synthetic-preview'}}},confirm:async()=>{sends++;return {state:'succeeded'}},...overrides};const flow=new ControlledFlow(app,()=>{});return {flow,app,counts:()=>({sends,prepares})}}
test('successful restoration clears earlier restore error',async()=>{const {flow:f,app}=setup({read:async()=>{throw {code:'store_busy'}}});await f.start();app.read=async()=>snapshot;await f.start();assert.equal(f.phase,'idle');assert.equal(f.error,null);f.dispose()});
test('queued draft failure cannot survive successful prepare',async()=>{const {flow:f}=setup({draft:async()=>{throw {code:'store_busy'}}});await f.start();f.edit('synthetic new input');f.persist();await f.prepare();assert.equal(f.phase,'awaiting-confirmation');assert.equal(f.error,null);f.dispose()});
test('late old draft failure cannot attach to new draft',async()=>{const wait=deferred();const {flow:f}=setup({draft:()=>wait.promise});await f.start();f.edit('synthetic old');f.persist();await Promise.resolve();f.edit('synthetic new');wait.reject({code:'store_busy'});await f.queue;assert.equal(f.error,null);assert.equal(f.draft.text,'synthetic new');f.dispose()});
test('saved result refresh failure retries only read and never prepares or sends again',async()=>{const {flow:f,app,counts}=setup();await f.start();f.edit('synthetic send');await f.prepare();app.read=async()=>{throw {code:'store_busy',stage:'conversation_snapshot'}};await f.confirm();assert.equal(f.phase,'refresh-failed');assert.equal(f.preview,null);app.read=async()=>({...snapshot,revision:2});await f.restore();assert.equal(f.error,null);assert.equal(f.phase,'idle');assert.deepEqual(counts(),{sends:1,prepares:1});f.dispose()});
test('new prepare failure belongs to new turn and revision, prior answer is unchanged',async()=>{const {flow:f}=setup({prepare:async()=>{throw {code:'source_unavailable',stage:'prepare_turn'}}});await f.start();f.edit('synthetic next question');const d={...f.draft};await f.prepare();assert.equal(f.error.turnId,d.turnId);assert.equal(f.error.draftRevision,d.revision);assert.deepEqual(f.snapshot.turns,snapshot.turns);f.dispose()});
test('late completed cancel cannot erase newly edited draft',async()=>{const wait=deferred();const {flow:f}=setup({cancelPreview:()=>wait.promise});await f.start();f.edit('synthetic first');await f.prepare();const p=f.cancel();f.edit('synthetic later');wait.resolve({alreadyCompleted:true});await p;assert.equal(f.draft.text,'synthetic later');assert.notEqual(f.notice,'回答已完成。');f.dispose()});
test('superseded snapshot rejection is ignored',async()=>{const wait=deferred();const {flow:f,app}=setup();await f.start();app.read=()=>wait.promise;const old=f.reload();app.read=async()=>({...snapshot,revision:3});await f.reload();wait.reject({code:'store_busy'});await assert.doesNotReject(old);assert.equal(f.snapshot.revision,3);f.dispose()});

test('actual status renderer offers read-only recovery after saved result',async()=>{
 const {readFileSync}=await import('node:fs');const vm=await import('node:vm');const ui=readFileSync(new URL('../candidate/ui/health_ui.js',import.meta.url),'utf8');
 const snippet=ui.slice(ui.indexOf('const status ='),ui.indexOf('if (aiOpen)',ui.indexOf('const status =')));
 assert(snippet.length>0);const html=vm.runInNewContext(snippet+';html;', {flow:{phase:'refresh-failed',busy:false,error:{code:'store_busy'},draft:{}},errorText:()=> 'store_busy',esc:String,notice:'',button:(action,label)=>`<button data-action="${action}">${label}</button>`});
 assert(html.includes('data-action="restore"'));assert(!html.includes('data-action="retry"'));assert(ui.includes("if (a === 'restore') await flow.restore()"));
});
