// P142 presentation hierarchy, with P152's existing DeepSeek-only backend capabilities.
export const settingView={section:'模型设置',mode:'cloud',pendingModel:'',drafts:{cloud:{provider:'DeepSeek',model:''},local:{provider:'Ollama',model:''}}};
const catalogs:any={cloud:['OpenAI','Anthropic','Google Gemini','DeepSeek','Kimi','OpenRouter','其他 OpenAI-compatible 服务','自定义兼容接口'],local:['Ollama','LM Studio','OpenAI-compatible 本地接口','自定义本地服务']};
const ids:any={OpenAI:'openai',Anthropic:'anthropic','Google Gemini':'google_gemini',DeepSeek:'deepseek',Kimi:'kimi',OpenRouter:'openrouter','其他 OpenAI-compatible 服务':'cloud_openai_compatible','自定义兼容接口':'cloud_custom',Ollama:'ollama','LM Studio':'lm_studio','OpenAI-compatible 本地接口':'local_openai_compatible','自定义本地服务':'local_custom'};
let seen=-1;let seenTest:string|undefined;let preferences:any=null;
export function proposedSettings(s:any){const v=settingView,d=v.drafts[v.mode as 'cloud'|'local'],id=ids[d.provider];return {version:1,primary:{mode:v.mode,providerId:id,modelLabel:d.model||(id==='deepseek'?s?.provider?.modelId||'':''),endpointUrl:v.mode==='cloud'?(id==='deepseek'?'https://api.deepseek.com':'offline://catalog/cloud/'+id):null,localRuntime:v.mode==='local'?'synthetic-local-runtime-v1':null},routingPolicy:preferences?.routingPolicy||{preferLocal:true,allowCloudSupplement:false,allowAutomaticFailover:false,preferFastResponse:false},fallback:preferences?.fallback||{configured:false,providerId:null},advanced:preferences?.advanced||{expanded:false,capabilityOverrides:{text:'auto',vision:'auto',speech_input:'auto',speech_output:'auto',tool_use:'auto',long_context:'auto'},temperature:70,maxOutputTokens:2048,timeoutSeconds:60,contextWindow:32}}}
export function updatePolicy(key:string,value:boolean,s:any){preferences=proposedSettings(s);preferences.routingPolicy[key]=value}
export function catalogCapability(provider:string,mode:string,index:number){if(mode==='cloud'){if([0,4,5,6,7].includes(index))return true;if(index===1)return ['openai','google_gemini','openrouter'].includes(provider);return ['openai','google_gemini'].includes(provider)}return [0,5,6].includes(index)||(index===1&&['ollama','lm_studio'].includes(provider))}
export function settingsView(s:any,esc:(s:any)=>string,button:(a:string,l:string,i?:string)=>string,sourceContent='',actions={busy:false,notice:''}){
 if(s?.catalog&&s.catalog.revision!==seen){seen=s.catalog.revision;if(s.catalog.settings){preferences=s.catalog.settings;const p=preferences.primary;settingView.mode=p.mode;settingView.drafts[p.mode as 'cloud'|'local']={provider:Object.keys(ids).find(n=>ids[n]===p.providerId)||'DeepSeek',model:p.modelLabel};}}
 if(seenTest!==s?.provider?.testReceiptId){seenTest=s?.provider?.testReceiptId;settingView.pendingModel=s?.provider?.modelId||'';}
 const v=settingView,d=v.drafts[v.mode as 'cloud'|'local'],ready=!!s?.catalog?.settings||s?.provider?.credentialState==='stored',deep=v.mode==='cloud'&&d.provider==='DeepSeek';
 const nav=`<nav class="settings-nav" aria-label="设置导航"><p>设置</p>${['通用','模型设置','数据与隐私','备份与导出','关于'].map(n=>`<button data-action="settings-section" data-id="${n}" ${v.section===n?'aria-current="page"':''}>${n}${['模型设置','数据与隐私'].includes(n)?'':'<span>暂未开放</span>'}</button>`).join('')}</nav>`;
 if(v.section==='数据与隐私')return `<div class="settings-shell">${nav}<div class="settings-content"><header><h1>数据与隐私</h1></header>${sourceContent}</div></div>`;
 if(v.section!=='模型设置')return `<div class="settings-shell">${nav}<div class="settings-content"><header><h1>${v.section}</h1><p class="quiet">这个设置分类暂未开放。</p></header></div></div>`;
 return `<div class="settings-shell">${nav}<div class="settings-content"><header class="page-head"><div><h1>模型设置</h1><p class="subhead">选择一个主服务，让 LifeOS 按你的选择提供帮助。</p></div></header>
 <section class="service-card ${ready?'':'empty'}"><div class="service-head"><div><p class="eyebrow">主 AI 服务</p><h2>${ready?esc(s?.catalog?.settings?(Object.keys(ids).find(n=>ids[n]===s.catalog.settings.primary.providerId)||'主服务'):'DeepSeek'):'还没有配置服务'}</h2><p>${ready?esc(s?.provider?.modelId||'请在下方选择测试返回的模型'):'从添加一个主服务开始。'}</p></div><span class="state-dot">${s?.provider?.enabled?'已启用':s?.provider?.connectionState==='succeeded'?'测试成功 · 未启用':ready?'待测试':'未配置'}</span></div></section>
 <div class="settings-grid"><div class="main-stack"><section class="config-card" id="service-form"><div class="section-heading"><div><p class="eyebrow">服务配置</p><h2>${ready?'更换或调整服务':'添加主服务'}</h2></div><span class="microcopy">选择不会自动联网</span></div>
 <div class="mode-control" role="group" aria-label="服务处理位置"><button data-action="settings-mode" data-id="cloud" aria-pressed="${v.mode==='cloud'}"><strong>云端服务</strong><small>可替换的云端模型</small></button><button data-action="settings-mode" data-id="local" aria-pressed="${v.mode==='local'}"><strong>本地服务</strong><small>设备上的模型</small></button></div>
 <div class="form-grid"><label>模型提供方<select id="provider-choice">${catalogs[v.mode].map((n:string)=>`<option ${n===d.provider?'selected':''}>${n}</option>`).join('')}</select></label><label>已测试的模型<select id="tested-model" ${deep&&s?.provider?.connectionState==='succeeded'&&!actions.busy?'':'disabled'}><option value="">请选择测试返回的模型</option>${(deep?s?.provider?.models||[]:[]).map((m:string)=>`<option value="${esc(m)}" ${settingView.pendingModel===m?'selected':''}>${esc(m)}</option>`).join('')}</select><small>模型列表仅来自你手动成功完成的测试。</small></label>
 ${v.mode==='cloud'?`<label class="wide">服务端点<input readonly value="${deep?'https://api.deepseek.com':'尚未接入'}"><small>${deep?'每次发送前显示本次内容，由你确认。':'目录已保留，此服务当前尚未接入。'}</small></label><label class="wide credential">${s?.mode==='real'?'API Key':'合成 API Key'}<div><input id="key" type="password" autocomplete="off" ${deep?'':'disabled'} placeholder="${deep?(s?.mode==='real'?'在这里输入 API Key':'仅输入虚构演练值'):'此服务暂不可配置'}"><button class="button secondary" data-action="save-key" ${deep&&!actions.busy?'':'disabled'}>保存凭据</button></div><small>加密保存在本地。${deep?(s?.provider?.credentialState==='stored'?`API Key 已保存 ${esc(credentialMask(s.provider.maskedTail))}`:'API Key 未保存或不可用。'):''}</small></label>`:`<label class="wide">本地 Runtime<input readonly value="${esc(d.provider)} · 尚未接入"><small>不会探测设备或自动启动本地服务。</small></label>`}</div>
 <div class="form-actions"><button class="button primary" data-action="save-catalog" ${actions.busy?'disabled':''}>保存配置</button><button class="button secondary" data-action="test-models" ${deep&&s?.provider?.credentialState==='stored'&&!actions.busy?'':'disabled'}>测试并读取模型</button><button class="button secondary" data-action="select-tested-model" ${deep&&s?.provider?.connectionState==='succeeded'&&settingView.pendingModel&&!actions.busy?'':'disabled'}>确认选择模型</button><button class="button secondary" data-action="enable-model" ${deep&&s?.provider?.modelId&&!s?.provider?.enabled&&!actions.busy?'':'disabled'}>显式启用所选模型</button><button class="button secondary" data-action="disable-model" ${deep&&s?.provider?.enabled&&!actions.busy?'':'disabled'}>停用模型</button>${deep?button('delete-key','移除凭据'):''}</div><p class="notice" role="status">${esc(actions.notice)}</p><p class="tiny">${deep?'保存不会自动测试、选择或启用。测试仅请求 DeepSeek 模型列表，不携带个人内容；发送问题仍须逐次确认。':'可保存本地配置；该服务的实际发送尚未接入。'}</p></section>
 <section class="routing-card"><div class="section-heading"><div><p class="eyebrow">运行策略</p><h2>按需要匹配能力</h2></div></div><div class="policy-list">${['优先使用本地','允许云端补齐','服务失败时自动切换','优先响应更快'].map((n,i)=>`<label><input type="checkbox" data-policy="${['preferLocal','allowCloudSupplement','allowAutomaticFailover','preferFastResponse'][i]}" ${proposedSettings(s).routingPolicy[['preferLocal','allowCloudSupplement','allowAutomaticFailover','preferFastResponse'][i]]?'checked':''}><span><strong>${n}</strong><small>仅保存偏好，本轮不执行自动路由</small></span></label>`).join('')}</div><div class="fallback"><div><strong>备用服务（可选）</strong><p>尚未配置，不会自动切换。</p></div></div></section>
 <details class="advanced" data-keep="settings-advanced"><summary><span><b>高级设置</b><small>能力覆盖与请求参数</small></span><i>⌄</i></summary><div class="advanced-body"><div class="overrides">${['文字','视觉','语音输入','语音输出','工具调用','长文本'].map(n=>`<label>${n}<select disabled><option>自动（暂不可调整）</option></select></label>`).join('')}</div><div class="advanced-values"><span>温度 <b>${proposedSettings(s).advanced.temperature/100}</b></span><span>最大输出偏好 <b>${proposedSettings(s).advanced.maxOutputTokens}</b></span><span>超时偏好 <b>${proposedSettings(s).advanced.timeoutSeconds} 秒</b></span><span>上下文偏好 <b>${proposedSettings(s).advanced.contextWindow}k</b></span></div><p>偏好保留在本地；本轮实际发送仍固定为最大输出1024、超时60秒，不自动扩大预算或补齐服务。</p></div></details>
 <details class="storage-help" data-keep="storage"><summary>隐私与本地存储</summary><p>${s?.mode==='real'?'API Key加密保存在本地，解密密钥由系统钥匙串保护；对话保存在本机未加密业务库。':'合成预览只使用虚构资料，不访问网络或系统钥匙串。'}</p></details>
 </div><aside><section class="capability-card"><div class="section-heading"><div><p class="eyebrow">能力状态</p><h2>LifeOS 自动匹配</h2></div></div><div class="capability-list">${['文字推理','视觉理解','语音输入','语音输出','工具调用','长文本','结构化输出','嵌入'].map((n,i)=>`<div><span class="cap-icon">–</span><strong>${n}</strong><small>${i===0&&s?.provider?.enabled?'已启用 · 发送结果待验证':catalogCapability(s?.catalog?.settings?.primary?.providerId||ids[d.provider],s?.catalog?.settings?.primary?.mode||v.mode,i)?'目录声明支持 · 运行待接入':'目录未声明支持'}</small></div>`).join('')}</div></section></aside></div></div></div>`;
}

export function credentialMask(tail:any){return typeof tail==='string'&&/^[\x21-\x7e]{4}$/.test(tail)?'••••'+tail:'••••';}
