import {test} from 'node:test';import assert from 'node:assert/strict';
import {spawn,spawnSync} from 'node:child_process';import {createInterface} from 'node:readline';import {once} from 'node:events';
import {actionCandidate,validateCandidate,transition} from '../candidate/ui/action_domain.js';
import {ActionApplication,IpcActionRepository,OfflineActionModel} from '../candidate/ui/action_application.js';
import {ControlledConversation,ControlledFlow} from '../candidate/ui/controlled_conversation.js';
import {actionFocus} from '../candidate/ui/action_view.js';
const root='/private/tmp/lifeos-p3-157-real-actions-v1/closure-1',draft=text=>({requestId:crypto.randomUUID(),turnId:crypto.randomUUID(),revision:1,text});
function host(fixture='p157-actions-'+crypto.randomUUID()) {const p=spawn(root+'/target/debug/synthetic-driver',['--synthetic-fixture',fixture],{stdio:['pipe','pipe','pipe']});const pending=new Map();let seq=0,err='';p.stderr.on('data',b=>err+=b);p.on('exit',()=>{for(const {reject} of pending.values())reject(Error('host exited '+err));pending.clear()});createInterface({input:p.stdout}).on('line',line=>{const v=JSON.parse(line),r=pending.get(v.id);pending.delete(v.id);v.ok?r.resolve(v.result):r.reject(v.error)});const h={fixture,async close(){p.stdin.end();await once(p,'exit')},invoke(command,request){return new Promise((resolve,reject)=>{pending.set(++seq,{resolve,reject});p.stdin.write(JSON.stringify({id:seq,command,request})+'\n')})}};return h;}
const call=(h,o,p={})=>h.invoke(o==='action_snapshot'?'get_context_recovery':'resolve_request_context',{version:6,operation:o,payload:p});
async function prepare(h,raw){const d=draft(raw);await h.invoke('capture_record',{version:4,operation:'draft_turn',payload:d});const p=await call(h,'prepare_action_turn',{requestId:'p:'+d.turnId,turnId:d.turnId,expectedDraftRevision:1});return {d,p,c:actionCandidate(p)}}
const payload=({d,p,c})=>({requestId:'c:'+d.turnId,turnId:d.turnId,packetId:p.id,expectedDraftRevision:1,candidate:c,modelId:'OfflineA'});
async function submit(h,raw){const x=await prepare(h,raw);assert(x.c,raw);validateCandidate(x.p,x.c);return call(h,'commit_action_turn',payload(x));}
const read=h=>call(h,'action_snapshot',{offset:0});
function sql(fixture,code){const p=spawnSync('python3',['-c',`import sqlite3,json\nc=sqlite3.connect(${JSON.stringify(root+'/synthetic/'+fixture+'.sqlite')})\n${code}\nc.commit()`],{encoding:'utf8'});assert.equal(p.status,0,p.stderr);return p.stdout.trim();}
async function run(fn){const h=host();try{await fn(h)}finally{await h.close()}}
for(const text of ['他说“报告结论做完了”。','假如报告结论做完了就好了。','报告结论还没做完。','我不打算明天整理报告结论。','今天聊天挺有意思。','','我今天心情很好。','我明天可以做什么？','不要把报告标记为完成','如果我明天做这个呢？'])test('no action for '+JSON.stringify(text),()=>{assert.equal(actionCandidate({raw:text,actions:[],suggestions:[],expiresAt:Date.now()+1000}),undefined)});
test('natural conversation create adjust complete and immutable history',()=>run(async h=>{const a=new ControlledConversation(h);assert.equal((await a.prepare(draft('我明天先整理报告结论。'),()=>true)).kind,'local');let s=await read(h);const id=s.actions[0].id;assert.equal(s.actions[0].status,'planned');await submit(h,'把整理报告结论改成明天下午整理报告结论。');await submit(h,'报告结论做完了。');s=await read(h);assert.equal(s.actions[0].id,id);assert.equal(s.actions[0].version,3);assert.equal(s.actions[0].status,'completed');assert.equal(s.focus,null);assert.equal(s.turns.length,3);const audit=JSON.parse(sql(h.fixture,`print(json.dumps([c.execute("select count(*) from records where json_extract(body,'$.kind')='action_event'").fetchone()[0],c.execute("select count(*) from feedback where json_extract(body,'$.kind')='action_feedback'").fetchone()[0],c.execute("select count(*) from memories").fetchone()[0]]))`));assert.deepEqual(audit,[3,3,2]);assert.equal((await a.read()).turns.length,3)}));
test('same submission replay and different payload reject',()=>run(async h=>{const x=await prepare(h,'我明天先写报告。'),p=payload(x);const a=await call(h,'commit_action_turn',p);assert.deepEqual(await call(h,'commit_action_turn',p),a);await assert.rejects(call(h,'commit_action_turn',{...p,modelId:'OfflineB'}),e=>e.code==='idempotency_conflict');assert.equal((await read(h)).actions.length,1)}));
test('multiple targets clarify, plain natural target response resolves once',()=>run(async h=>{await submit(h,'我明天先整理报告结论。');await submit(h,'我明天先修复测试。');await submit(h,'做完了。');assert((await read(h)).actions.every(a=>a.status==='planned'));await submit(h,'报告结论');const s=await read(h);assert.equal(s.actions.find(a=>a.confirmedContent.includes('报告')).status,'completed');assert.equal(s.actions.find(a=>a.confirmedContent.includes('测试')).status,'planned')}));
test('single current target cancellation and terminal refusal',()=>run(async h=>{await submit(h,'我明天先写报告。');await submit(h,'先不做了。');const x=await prepare(h,'这个完成了。');await assert.rejects(call(h,'commit_action_turn',payload(x)),e=>e.code==='action_terminal');assert.equal((await read(h)).actions[0].status,'cancelled')}));
test('stale expected version rejects late commit',()=>run(async h=>{await submit(h,'我明天先写报告。');const old=await prepare(h,'报告完成了。');await submit(h,'把报告改成明天下午写报告。');await assert.rejects(call(h,'commit_action_turn',payload(old)),e=>e.code==='action_version_conflict')}));
test('forged model intent and target rejected by real Host',()=>run(async h=>{let x=await prepare(h,'今天聊天挺有意思。');x.c={operation:'create',content:'伪造安排',sourceRefs:[],rawSpan:{start:0,end:x.d.text.length}};await assert.rejects(call(h,'commit_action_turn',payload(x)),e=>e.code==='action_candidate_rejected');await submit(h,'我明天先写报告。');x=await prepare(h,'报告完成了。');x.c.targetId='forged';await assert.rejects(call(h,'commit_action_turn',payload(x)),e=>e.code==='action_candidate_rejected');assert.equal((await read(h)).actions.length,1)}));
test('fault transaction rolls back all action assets and retains draft',()=>run(async h=>{const x=await prepare(h,'我明天先写报告。');sql(h.fixture,`c.execute("CREATE TRIGGER action_fault BEFORE INSERT ON feedback BEGIN SELECT RAISE(ABORT,'synthetic-fault'); END")`);await assert.rejects(call(h,'commit_action_turn',payload(x)));assert.equal((await read(h)).actions.length,0);const a=new ControlledConversation(h);assert.equal((await a.read()).pendingDraft.text,x.d.text);sql(h.fixture,'c.execute("DROP TRIGGER action_fault")');await call(h,'commit_action_turn',payload(x));assert.equal((await read(h)).actions.length,1)}));
test('restart restores identity feedback and status, reads have no writes',async()=>{let h=host();const f=h.fixture;try{await submit(h,'我明天先写报告。');await submit(h,'报告先不做了。');const before=await read(h);await h.close();h=host(f);assert.deepEqual(await read(h),before);const rev=sql(f,'print(c.execute("select total_changes()").fetchone()[0])');await read(h);assert.equal(sql(f,'print(c.execute("select revision from meta").fetchone()[0])'),String(before.revision));assert.equal(rev,'0')}finally{await h.close()}});
test('source expiry/revoke/correction preserves action and removes valid-basis claim',()=>run(async h=>{await submit(h,'我明天先写报告。');sql(h.fixture,`row=c.execute("select id,body from records where json_extract(body,'$.kind')='action_event'").fetchone();v=json.loads(row[1]);v['action']['sourceRefs']=[{'id':'work-report','version':1,'authorizationGeneration':1}];c.execute('update records set body=? where id=?',(json.dumps(v),row[0]))`);assert.equal((await read(h)).actions[0].basisStatus,'valid');for(const change of ["v['validUntil']=1","v['version']=2","v['status']='unavailable'"]){sql(h.fixture,`row=c.execute("select body from records where id='work-report'").fetchone();v=json.loads(row[0]);v.pop('validUntil',None);v['version']=1;v['status']='active';${change};c.execute("update records set body=? where id='work-report'",(json.dumps(v),))`);const a=(await read(h)).actions[0];assert.equal(a.basisStatus,'needs_user_judgment');assert.equal(a.status,'planned');assert.match(actionFocus(a),/需要你判断/);}sql(h.fixture,`v=json.loads(c.execute("select body from records where id='work-report'").fetchone()[0]);v.pop('validUntil',None);v['version']=1;v['status']='active';c.execute("update records set body=? where id='work-report'",(json.dumps(v),));v=json.loads(c.execute("select body from sources where id='work-demo'").fetchone()[0]);v['authorized']=False;v['generation']=2;c.execute("update sources set body=? where id='work-demo'",(json.dumps(v),))`);assert.equal((await read(h)).actions[0].basisStatus,'needs_user_judgment');await submit(h,'报告先不做了。');assert.equal((await read(h)).actions[0].status,'cancelled')}));
test('conversation authorization denies writes before action append',()=>run(async h=>{const x=await prepare(h,'我明天先写报告。');sql(h.fixture,`v=json.loads(c.execute("select body from sources where id='conversation'").fetchone()[0]);v['authorized']=False;c.execute("update sources set body=? where id='conversation'",(json.dumps(v),))`);await assert.rejects(call(h,'commit_action_turn',payload(x)),e=>e.code==='source_not_authorized');assert.equal(sql(h.fixture,`print(c.execute("select count(*) from records where json_extract(body,'$.kind')='action_event'").fetchone()[0])`),'0')}));
test('Application rejects fabricated model output before repository commit',async()=>{let commits=0;const app=new ActionApplication({prepare:async()=>({raw:'我明天先整理合成材料。',actions:[],suggestions:[],expiresAt:Date.now()+1000}),commit:async()=>commits++},{id:'OfflineB',parse:async()=>({operation:'create',content:'伪造',rawSpan:{start:0,end:9},sourceRefs:[]})});await assert.rejects(app.submit({turnId:'test',revision:1},()=>true));assert.equal(commits,0)});
test('read recovery after lost commit response never resends model or write',()=>run(async h=>{let lost=true,commits=0;const wrapped={invoke:async(c,r)=>{const result=await h.invoke(c,r);if(r.operation==='commit_action_turn'){commits++;if(lost){lost=false;throw {code:'store_busy'}}}return result}};const f=new ControlledFlow(new ControlledConversation(wrapped),()=>{});await f.start();f.edit('我明天先写报告。');await f.prepare();assert.equal(f.phase,'refresh-failed');await f.restore();assert.equal(f.draft.text,'');assert.equal(f.phase,'idle');assert.equal(commits,1);assert.equal(f.snapshot.actions.length,1);f.dispose()}));
test('OfflineA and OfflineB operate same repository identity',()=>run(async h=>{const repo=new IpcActionRepository((c,o,p)=>h.invoke(c,{version:6,operation:o,payload:p}));const a=new ActionApplication(repo);let d=draft('我明天先写报告。');await h.invoke('capture_record',{version:4,operation:'draft_turn',payload:d});await a.submit(d,()=>true);const id=(await a.read()).actions[0].id;a.model=new OfflineActionModel('OfflineB');d=draft('报告完成了。');await h.invoke('capture_record',{version:4,operation:'draft_turn',payload:d});await a.submit(d,()=>true);assert.equal((await a.read()).actions[0].id,id)}));
test('Today single Focus escapes content and never adds action buttons',()=>{const html=actionFocus({id:'x',confirmedContent:'<script>unsafe</script>',status:'planned',version:2,updatedAt:Date.now(),basisStatus:'valid',sourceRefs:[]});assert(!html.includes('<script>'));assert(!html.includes('<button'));assert.equal(actionFocus({status:'completed'}),'')});
test('actual model suggestion stays candidate until explicit pronoun acceptance',()=>run(async h=>{const a=new ControlledConversation(h);await a.saveCredential('p157-synthetic-fiction-only',0);await a.testModels();await a.selectModel('user-synthetic-model');await a.setEnabled(true);await a.prepare(draft('我有20分钟工作时间'),()=>true);const v=await a.prepare(draft('给我一个工作建议'),()=>true);assert.equal(v.kind,'preview');await a.confirm(v.preview);assert.equal((await read(h)).actions.length,0);await a.prepare(draft('那我明天先做这个'),()=>true);const s=await read(h);assert.equal(s.actions.length,1);assert.match(s.actions[0].confirmedContent,/整理报告结论/);assert(s.actions[0].sourceRefs.length>0)}));
test('multiple targets beyond first page cannot imply one',()=>run(async h=>{for(let i=0;i<23;i++)await submit(h,'我明天先整理报告'+i+'。');const s=await read(h);assert.equal(s.actions.length,20);assert.equal(s.total,23);await submit(h,'做完了。');assert.equal((await read(h)).total,23);assert.equal((await read(h)).actions.filter(a=>a.status==='completed').length,0)}));
test('expired packet and cancelled draft reject commits',()=>run(async h=>{let x=await prepare(h,'我明天先写报告。');sql(h.fixture,`v=json.loads(c.execute('select body from packets where id=?',(${JSON.stringify(x.p.id)},)).fetchone()[0]);v['expiresAt']=1;c.execute('update packets set body=? where id=?',(json.dumps(v),${JSON.stringify(x.p.id)}))`);await assert.rejects(call(h,'commit_action_turn',payload(x)),e=>e.code==='action_context_stale');x=await prepare(h,'我明天先修复测试。');await h.invoke('resolve_request_context',{version:4,operation:'cancel_turn',payload:{requestId:'cancel:'+x.d.turnId,turnId:x.d.turnId}});await assert.rejects(call(h,'commit_action_turn',payload(x)),e=>e.code==='draft_revision_conflict')}));
test('snapshot is read-only and incompatible v6 fields fail closed',()=>run(async h=>{await assert.rejects(h.invoke('get_today',{version:6,operation:'action_snapshot',payload:{offset:0}}));await assert.rejects(call(h,'action_snapshot',{offset:0,unknown:true}));await assert.rejects(call(h,'action_snapshot',{offset:null}));const before=await read(h);for(let i=0;i<3;i++)assert.deepEqual(await read(h),before)}));
for(const raw of ['我明天整理报告吗','我今天写报告很累','我今天散步了','我明天可能整理报告','我明天整理报告，只是举例'])test('uncertain/historical expression does not create: '+raw,()=>assert.equal(actionCandidate({raw,actions:[],suggestions:[]}),undefined));
test('completed history does not obscure the only current planned target',()=>run(async h=>{await submit(h,'我明天先写报告。');await submit(h,'报告完成了。');await submit(h,'我明天先修复测试。');await submit(h,'做完了。');const s=await read(h);assert(s.actions.every(a=>a.status==='completed'));assert(s.actions.every(a=>a.historyRefs.length===2))}));
test('stale model derivation cannot be accepted via pronoun',()=>run(async h=>{const a=new ControlledConversation(h);await a.saveCredential('p157-synthetic-fiction-only',0);await a.testModels();await a.selectModel('user-synthetic-model');await a.setEnabled(true);await a.prepare(draft('我有20分钟工作时间'),()=>true);const v=await a.prepare(draft('给我一个工作建议'),()=>true);await a.confirm(v.preview);const x=await prepare(h,'那我明天先做这个');assert.equal(x.c.operation,'create');sql(h.fixture,`for row in c.execute("select id,body from derivations where json_extract(body,'$.kind')='health_conversation_answer'").fetchall():\n v=json.loads(row[1]);v['status']='stale';c.execute('update derivations set body=? where id=?',(json.dumps(v),row[0]))`);await assert.rejects(call(h,'commit_action_turn',payload(x)),e=>e.code==='action_basis_stale');const fresh=await prepare(h,'那我明天先做这个');assert.equal(fresh.c.operation,'clarify');assert.equal((await read(h)).actions.length,0)}));
test('Host refuses changing confirmed content inside an otherwise valid parsed create',()=>run(async h=>{const x=await prepare(h,'我明天先写报告。');x.c.content='模型擅自改写的内容';await assert.rejects(call(h,'commit_action_turn',payload(x)),e=>e.code==='action_candidate_rejected');assert.equal((await read(h)).actions.length,0)}));
test('closure generalized creation and exact withdrawal persist across restart',async()=>{let h=host();const fixture=h.fixture;try{await submit(h,'我明天先买不锈钢合成材料。');await submit(h,'先不买不锈钢合成材料了。');const before=await read(h);assert.equal(before.actions[0].status,'cancelled');assert.equal(before.actions[0].version,2);await h.close();h=host(fixture);assert.deepEqual(await read(h),before)}finally{await h.close()}});
test('closure no target or multiple normalized targets cannot silently cancel',()=>run(async h=>{let x=await prepare(h,'先不买合成材料了。');assert.equal(x.c,undefined);await submit(h,'我明天先买合成材料。');await submit(h,'我今天要买合成材料。');x=await prepare(h,'先不买合成材料了。');assert.equal(x.c.operation,'clarify');await call(h,'commit_action_turn',payload(x));assert((await read(h)).actions.every(a=>a.status==='planned'));await submit(h,'我明天先买合成材料那个');assert.equal((await read(h)).actions.filter(a=>a.status==='cancelled').length,1)}));
test('closure Host rejects arbitrary negativity and unsupported fallback forgery',()=>run(async h=>{await submit(h,'我明天先买合成材料。');for(const raw of ['我不打算买合成材料。','帮我把这件事安排一下。','我明天可能先买合成材料。']){const x=await prepare(h,raw);x.c={operation:'cancel',rawSpan:{start:0,end:raw.length},sourceRefs:[],targetId:(await read(h)).actions[0].id,expectedVersion:1};await assert.rejects(call(h,'commit_action_turn',payload(x)),e=>e.code==='action_candidate_rejected')}assert.equal((await read(h)).actions[0].status,'planned')}));
