import {test} from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {createInterface} from 'node:readline';import {once} from 'node:events';import {writeFileSync} from 'node:fs';
import {ControlledConversation,ControlledFlow} from '../candidate/ui/controlled_conversation.js';
const root='/private/tmp/lifeos-p3-159-unified-proactive-v1/offline';
function host(fixture='p158-v8-'+crypto.randomUUID()){const p=spawn('/private/tmp/lifeos-p3-159-unified-proactive-v1/build/offline/debug/synthetic-driver',['--synthetic-fixture',fixture],{stdio:['pipe','pipe','pipe']});let next=0;const pending=new Map();createInterface({input:p.stdout}).on('line',line=>{const v=JSON.parse(line),x=pending.get(v.id);pending.delete(v.id);v.ok?x.resolve(v.result):x.reject(v.error)});p.on('exit',()=>{for(const x of pending.values())x.reject(Error('host exited'));pending.clear()});return {fixture,invoke(command,request){return new Promise((resolve,reject)=>{pending.set(++next,{resolve,reject});p.stdin.write(JSON.stringify({id:next,command,request})+'\n')})},async close(){p.stdin.end();await once(p,'exit')}};}
const samples=['明天去合成健身房','改到后天吧','取消合成健身房安排','如果合成预报下雨，就安排室内阅读','查一下公开合成笔记'];
const spans=q=>[{messageRef:'current',start:0,end:Array.from(q).length}];
const response=candidate=>({schemaVersion:8,answerText:'公开合成回答',candidate});
const action=(q,op,extra)=>({operation:op,evidenceSpans:spans(q),...extra});
const conditional=action(samples[3],'conditional_action',{content:'按公开合成条件安排室内阅读',condition:{join:'all',atoms:[{factRef:'__fact0__',operator:'eq',expected:{type:'boolean',value:true}}]},intent:{kind:'apply_if_true',evidenceSpans:spans(samples[3])},consequence:action(samples[3],'create',{content:'室内阅读',sourceRefs:[]})});
writeFileSync(root+'/coordination-responses.json',JSON.stringify({
 ['公开合成失败恢复']:{first:{schemaVersion:8,answerText:'',candidate:{operation:'forged'}}},
 [samples[0]]:{first:response(action(samples[0],'create',{content:'明天去合成健身房',sourceRefs:[]}))},
 [samples[1]]:{first:response(action(samples[1],'adjust',{targetRef:'__target0__',expectedVersion:1,content:'后天去合成健身房',sourceRefs:[]}))},
 [samples[2]]:{first:response(action(samples[2],'cancel',{targetRef:'__target0__',expectedVersion:2}))},
 [samples[3]]:{first:response({operation:'query_need',capabilityId:'fixture.forecast.lookup.v1',capabilityVersion:1,targetRef:'__forecast__',arguments:{start:0,end:3600000,fields:['rainExpected']},neededFacts:['rainExpected']}),second:response(conditional)},
 [samples[4]]:{first:response({operation:'query_need',capabilityId:'fixture.note.lookup.v1',capabilityVersion:1,targetRef:'__note__',arguments:{query:'评审',limit:2},neededFacts:['matches']}),second:response({operation:'none'})}
}),{mode:0o600});
async function ready(app){await app.saveCredential('p158-offline-fictional-key',0);await app.testModels();await app.selectModel('user-synthetic-model');await app.setEnabled(true);}
test('production v8 IPC Flow preserves action identity and independent restart',async()=>{let h=host(),f;try{let app=new ControlledConversation(h);await ready(app);f=new ControlledFlow(app,()=>{});await f.start();let id;for(let i=0;i<3;i++){f.edit(samples[i]);await f.prepare();assert.equal(f.phase,'awaiting-confirmation',JSON.stringify(f.error));assert.equal(f.preview.version,8);await f.confirm();assert.equal(f.phase,'idle',JSON.stringify(f.error));const a=f.snapshot.actions[0];id??=a.id;assert.equal(a.id,id);assert.equal(a.version,i+1);}const before=f.snapshot.actions;f.dispose();const fixture=h.fixture;await h.close();h=host(fixture);f=new ControlledFlow(new ControlledConversation(h),()=>{});await f.start();assert.deepEqual(f.snapshot.actions,before);}finally{f?.dispose();await h.close()}});
test('public fixture query is automatic but second model waits for explicit confirm',async()=>{const h=host();let f;try{const app=new ControlledConversation(h);await ready(app);f=new ControlledFlow(app,()=>{});await f.start();f.edit(samples[3]);await f.prepare();await f.confirm();assert.equal(f.phase,'awaiting-confirmation',JSON.stringify(f.error));assert.equal(f.preview.phase,'second');assert.equal(f.snapshot.actions.length,0);assert.equal(f.draft.text,samples[3]);assert.equal(f.preview.disclosure.queryResults.length,1);await f.confirm();assert.equal(f.phase,'idle',JSON.stringify(f.error));assert.equal(f.snapshot.actions.length,1);assert.match(f.snapshot.turns.at(-1).answer,/条件依据已保存/);assert.equal(f.draft.text,'');}finally{f?.dispose();await h.close()}});
test('note adapter answers through same v8 flow without local Action',async()=>{const h=host();let f;try{const app=new ControlledConversation(h);await ready(app);f=new ControlledFlow(app,()=>{});await f.start();f.edit(samples[4]);await f.prepare();await f.confirm();assert.equal(f.preview.phase,'second');assert.match(f.notice,/请核对/);await f.confirm();assert.equal(f.phase,'idle',JSON.stringify(f.error));assert.equal(f.snapshot.actions.length,0);assert.match(f.snapshot.turns.at(-1).answer,/本轮未更改安排/);assert.equal(f.notice,'');assert.equal(f.preview,null);}finally{f?.dispose();await h.close()}});
for(const secondPhase of [false,true])test(`restart resumes ${secondPhase?'second':'first'} preview without replaying consumed query or model`,async()=>{let h=host(),f;try{let app=new ControlledConversation(h);await ready(app);f=new ControlledFlow(app,()=>{});await f.start();f.edit(secondPhase?samples[3]:samples[0]);await f.prepare();if(secondPhase)await f.confirm();const old=f.preview;const before=await app.operationStatus(old.requestId);f.dispose();const fixture=h.fixture;await h.close();h=host(fixture);app=new ControlledConversation(h);f=new ControlledFlow(app,()=>{});await f.start();assert.equal(f.draft.turnId,before.turnId);await f.prepare();assert.equal(f.phase,'awaiting-confirmation',JSON.stringify(f.error));assert.equal(f.preview.phase,secondPhase?'second':'first');assert.notEqual(f.preview.previewId,old.previewId);const resumed=await app.operationStatus(old.requestId);assert.equal(resumed.modelCalls,before.modelCalls);assert.equal(resumed.queryCalls,before.queryCalls);assert.ok(resumed.activityBudget.usedMs>=before.activityBudget.usedMs);if(secondPhase)assert.deepEqual(f.preview.disclosure.queryResults,old.disclosure.queryResults);await f.confirm();assert.equal(f.phase,'idle',JSON.stringify(f.error));assert.equal(f.snapshot.actions.length,1);}finally{f?.dispose();await h.close()}});
test('clearing a saved draft twice does not restore stale text after restart',async()=>{let h=host();try{const app=new ControlledConversation(h);await ready(app);const turnId=crypto.randomUUID();for(let i=0;i<2;i++){await app.draft({requestId:crypto.randomUUID(),turnId,revision:i+1,text:'公开合成待清空草稿'+i});assert.equal((await app.read()).pendingDraft.text,'公开合成待清空草稿'+i);await app.draft({requestId:crypto.randomUUID(),turnId,revision:i+2,text:''});assert.equal((await app.read()).pendingDraft,null);}const fixture=h.fixture;await h.close();h=host(fixture);assert.equal((await new ControlledConversation(h).read()).pendingDraft,null);}finally{await h.close()}});
test('late legacy cancellation cannot change a committed v8 draft',async()=>{const h=host();try{const app=new ControlledConversation(h);await ready(app);const d={requestId:crypto.randomUUID(),turnId:crypto.randomUUID(),revision:1,text:samples[0]};const {preview}=await app.prepare(d,()=>true);const committed=await app.confirm(preview);assert.equal(committed.state,'succeeded');const cancel=await app.cancel(d.turnId);assert.equal(cancel.status,'completed');const restored=await app.operationStatus(preview.requestId);assert.equal(restored.state,'committed');assert.deepEqual(restored.receipt,committed.receipt);assert.equal((await app.read()).actions.length,1);}finally{await h.close()}});

test('D0674 failed draft restarts as explicit new preview while historical failure and counts remain',async()=>{let h=host(),f;try{let app=new ControlledConversation(h);await ready(app);f=new ControlledFlow(app,()=>{});await f.start();f.edit('公开合成失败恢复');await f.prepare();const old=f.preview;await f.confirm();assert.equal(f.phase,'failed');const failed=await app.operationStatus(old.requestId);assert.equal(failed.modelCalls,1);assert.equal(f.draft.text,'公开合成失败恢复');f.dispose();const fixture=h.fixture;await h.close();h=host(fixture);app=new ControlledConversation(h);f=new ControlledFlow(app,()=>{});await f.start();assert.equal(f.draft.text,'公开合成失败恢复');await f.prepare();assert.equal(f.phase,'awaiting-confirmation',JSON.stringify(f.error));assert.notEqual(f.preview.requestId,old.requestId);assert.equal((await app.operationStatus(f.preview.requestId)).modelCalls,0);assert.deepEqual(await app.operationStatus(old.requestId),failed);assert.equal(f.snapshot.actions.length,0);}finally{f?.dispose();await h.close()}});
