import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {InteractionApplication} from '../candidate/ui/interaction_application.js';
import {ProactiveApplication} from '../candidate/ui/proactive_application.js';
const wrap=(r,result)=>({version:'interaction-v1',operation:r.operation,result});
test('PM canonical specification is inherited byte for byte',()=>{const bytes=readFileSync(new URL('../candidate/application/interaction_contract.ts',import.meta.url));assert.equal(createHash('sha256').update(bytes).digest('hex'),'8234e7eb9523f5b8ea7114f50ef24acece5cbadfce8b98d92cdcc6b14b2bbafc');});
test('keyboard uses Host canonical id while preserving legacy correlation',async()=>{let allocation,submitted;const port=new InteractionApplication(async(c,r)=>{if(r.operation==='allocate_user_turn'){allocation=r.payload;return wrap(r,{turnId:'host-canonical',conversationRef:{id:'source-chat',revision:1},allocatedAt:1800000000000})}if(r.operation==='submit_user_turn'){submitted=r.payload;return wrap(r,{receipt:{turnId:r.payload.turnId,status:'pending_authorization',code:'confirmation'}})}return wrap(r,{proactiveRequestId:null})});await port.submitKeyboard('当前用户原文','legacy-uuid');assert.equal(allocation.correlationId,'legacy-uuid');assert.equal(submitted.turnId,'host-canonical');assert.equal(submitted.text,'当前用户原文');assert.equal(submitted.origin.kind,'keyboard');});
test('active proactive response shares the port without falling back to a second send',async()=>{let calls=0,fallback=0;const p=new ProactiveApplication(async()=>{fallback++;throw Error('must use common port')},()=>{}, {async submitKeyboard(text,correlation,ref){calls++;assert.equal(text,'先讨论一下');assert.deepEqual(ref,{id:'suggestion',revision:2});return {proactiveRequestId:'host-response'}}});p.status={mode:'synthetic'};p.view={items:[{suggestion:{id:'suggestion'},state:{revision:2}}]};p.responseDraft='先讨论一下';await p.respond();assert.equal(calls,1);assert.equal(fallback,0);assert.equal(p.responseRequest,'host-response');});
test('Host-final output is delivered once and never requests speech without permission',async()=>{let delivered=0,spoken=0;const turn={schemaVersion:'interaction-v1',turnRef:{id:'assistant',revision:1},conversationRef:{id:'source-chat',revision:1},origin:'conversation',content:{kind:'response',text:'宿主终局文字'},finalizedAt:'2026-09-12T10:00:00Z'};const port=new InteractionApplication(async(c,r)=>wrap(r,{turns:[turn],speechRequests:[]}));port.onAssistantTurn(()=>delivered++);port.onSpeechOutputRequest(()=>spoken++);await port.refreshOutputs();await port.refreshOutputs();assert.equal(delivered,1);assert.equal(spoken,0);});
test('an interruption is reported only to Host and cannot submit another business turn',async()=>{const operations=[];const port=new InteractionApplication(async(c,r)=>{operations.push([c,r.operation]);throw {code:'speech_request_not_authorized'}});await assert.rejects(port.reportSpeechInterrupted({schemaVersion:'interaction-v1',eventId:'stop',sessionId:'s',sessionGeneration:1,speechRequestId:'r',assistantTurnRef:{id:'a',revision:1},reason:'user_stop',occurredAt:'2026-09-12T10:00:00Z'}));assert.deepEqual(operations,[['decide_understanding_feedback','speech_interrupted']]);});

test('shared wire fixtures traverse the TypeScript port without shape or identity rewriting',async()=>{const fixtures=JSON.parse(readFileSync(new URL('./interaction_v1_fixtures.json',import.meta.url)));const submitted=[];const delivered=[];const port=new InteractionApplication(async(c,r)=>{if(r.operation==='submit_user_turn'){submitted.push(r.payload);return wrap(r,{receipt:fixtures.receipts[0]});}return wrap(r,{turns:fixtures.assistants.map((a,i)=>({...a,turnRef:{id:'assistant-'+i,revision:1}})),speechRequests:[]})});for(const turn of fixtures.users){assert.deepEqual(await port.submitUserTurn(turn),fixtures.receipts[0]);}assert.deepEqual(submitted,fixtures.users);port.onAssistantTurn(a=>delivered.push(a));await port.refreshOutputs();assert.deepEqual(delivered.map(a=>a.content),fixtures.assistants.map(a=>a.content));});
