import {test} from 'node:test';import assert from 'node:assert/strict';
import {V7ControlledConversation as ControlledConversation,ControlledFlow} from '../candidate/ui/controlled_conversation.js';
import {OperationApplication} from '../candidate/ui/action_application.js';
import {validateOperationReceipt} from '../candidate/ui/action_domain.js';
const v={version:7,previewId:'preview',requestId:'request',operationId:'operation',revision:1};
const r={...v,state:'succeeded',operation:'create',businessChanged:true,action:{id:'action',version:1},reply:'本地记录：已记下：合成事项。'};
test('historical v7 conversation entry only drafts and prepares v7, no local parser or v5 fallback',async()=>{const ops=[];const app=new ControlledConversation({invoke:async(c,p)=>{ops.push([c,p]);if(p.operation==='draft_turn')return {};if(p.operation==='prepare_operation_turn')return v;throw Error('unexpected '+p.operation)}});const out=await app.prepare({requestId:'draft',turnId:'turn',revision:1,text:'明天下午去健身房'},()=>true);assert.equal(out.kind,'preview');assert.deepEqual(ops.map(x=>[x[1].version,x[1].operation]),[[4,'draft_turn'],[7,'prepare_operation_turn']]);});
test('lost confirmation response recovers read only without another model invocation',async()=>{let sends=0,reads=0;const app=new OperationApplication({confirm:async()=>{sends++;throw Error('lost')},status:async()=>{reads++;return r}});assert.deepEqual(await app.confirm(v),r);assert.equal(sends,1);assert.equal(reads,1)});
test('forged request and false success cannot clear input',()=>{for(const delta of [{requestId:'forged'},{operationId:'forged'},{businessChanged:false},{reply:'模型已完成'},{action:{id:'a',version:0.5}}])assert.throws(()=>validateOperationReceipt(v,{...r,...delta}));});
test('none receipt cannot impersonate committed action',()=>{assert.throws(()=>validateOperationReceipt(v,{...r,operation:'none'}));assert.equal(validateOperationReceipt(v,{...v,state:'succeeded',operation:'none',businessChanged:false,reply:'本轮未更改安排。'}).businessChanged,false)});
test('Flow clears draft only after request bound commit then reads stored state',async()=>{let reads=0;const app={read:async()=>{reads++;return {revision:reads,turns:[]}},draft:async()=>{},prepare:async()=>({kind:'preview',preview:v}),confirm:async()=>r,cancel:async()=>{},cancelPreview:async()=>({})};const f=new ControlledFlow(app,()=>{});await f.start();f.edit('明天下午去健身房');await f.prepare();assert.equal(f.draft.text,'明天下午去健身房');assert.equal(f.phase,'awaiting-confirmation');await f.confirm();assert.equal(f.draft.text,'');assert.equal(f.phase,'idle');assert.equal(reads,2);f.dispose();});
test('Flow failed result keeps draft and unknown status never means success',async()=>{const app={read:async()=>({revision:0,turns:[]}),draft:async()=>{},prepare:async()=>({kind:'preview',preview:v}),confirm:async()=>({...v,state:'failed',businessChanged:false,errorCode:'operation_response_rejected'})};const f=new ControlledFlow(app,()=>{});await f.start();f.edit('合成原文');await f.prepare();await f.confirm();assert.equal(f.draft.text,'合成原文');assert.equal(f.phase,'failed');f.dispose();});

test('clarification UI state uses persisted variable reply without translation replacement',async()=>{for(const reply of ['本轮未更改安排。\n你指的是哪一件安排？','本轮未更改安排。\n请说明需要调整的事项。']){let committed=false;const receipt={...v,state:'succeeded',operation:'clarify',businessChanged:false,reply};const turn={turnId:'stored',text:'那个改到周末吧',answer:reply};const app={read:async()=>({revision:committed?1:0,turns:committed?[turn]:[]}),draft:async()=>{},prepare:async()=>({kind:'preview',preview:v}),confirm:async()=>{committed=true;return validateOperationReceipt(v,receipt)}};const flow=new ControlledFlow(app,()=>{});await flow.start();flow.edit('那个改到周末吧');await flow.prepare();await flow.confirm();assert.equal(flow.snapshot.turns[0].answer,reply);flow.dispose();}});
