import test from 'node:test';
import assert from 'node:assert/strict';
import {ProactiveApplication,proactiveFocus,proactiveSettings,credentialEntryCode,credentialCheckText} from '../candidate/ui/proactive_application.js';
const status={policy:{enabled:true,revision:1,generation:1,subjectIds:['a'],sourceIds:[],analysisPerDay:12,responsePerDay:20,showsPerDay:3,intervalMinutes:30,quietStart:22,quietEnd:8},scope:{items:[],page:0,hasMore:false},budget:{analysis:0,response:0}};
const wrap=(r,result)=>({version:'proactive-v1',operation:r.operation,result});
test('closing purpose is available during in-flight response and preserves input',async()=>{let saved;const app=new ProactiveApplication(async(c,r)=>{if(r.operation==='proactive_policy'){saved=r.payload;return wrap(r,{})}return wrap(r,r.operation==='proactive_status'?status:{items:[]})},()=>{});app.status=status;app.busy=true;app.responseDraft='原始回应';app.responseRequest='pending';await app.setEnabled(false);assert.equal(saved.enabled,false);assert.equal(app.responseDraft,'原始回应');assert.equal(app.responseRequest,'');});
test('a late old refresh cannot restore enabled UI after generation changes',async()=>{let release;const gate=new Promise(r=>release=r);const app=new ProactiveApplication(async(c,r)=>{await gate;return wrap(r,r.operation==='proactive_status'?status:{items:[{bad:true}]})},()=>{});const read=app.refresh();app.generation++;release();await read;assert.equal(app.status,null);assert.deepEqual(app.view.items,[]);});
test('projection acknowledgements update revision before response preparation',async()=>{let release;const gate=new Promise(r=>release=r);let prepared;const app=new ProactiveApplication(async(c,r)=>{if(r.operation==='proactive_event'){await gate;return wrap(r,{revision:2})}prepared=r.payload;return wrap(r,{requestId:'request'})},()=>{});app.view={items:[{suggestion:{id:'s'},state:{revision:1}}]};app.responseDraft='稍后讨论';const ack=app.shown('s',1);const response=app.respond();assert.equal(prepared,undefined);release();await ack;await response;assert.equal(prepared.expectedRevision,2);});
test('source/model text is escaped and never interpreted as markup',()=>{const app={view:{items:[{suggestion:{id:'s',candidate:{proposal:'<script>bad</script>',whyNow:'<a href="x">x</a>',inferenceFlags:[]},evidenceSnapshot:[{text:'<img onerror=bad>'}]},state:{revision:1}}]},responseDraft:'',reply:'',error:'',busy:false};const esc=s=>String(s??'').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');const html=proactiveFocus(app,esc);assert(!html.includes('<script>'));assert(!html.includes('<img onerror'));assert(html.includes('&lt;script&gt;'));});
test('reload restores persisted pending response without resubmitting it',async()=>{let sends=0;const app=new ProactiveApplication(async(c,r)=>{if(r.operation==='prepare_proactive_response')sends++;if(r.operation==='proactive_response')return wrap(r,{status:'reserved'});return wrap(r,r.operation==='proactive_status'?{...status,recentResponse:{requestId:'r',status:'reserved',text:'保留我这句话'}}:{items:[]})},()=>{});await app.refresh();assert.equal(app.responseDraft,'保留我这句话');assert.equal(app.responseRequest,'r');assert.equal(sends,0);});

test('unchanged polling preserves the mounted page and unsaved selections',async()=>{let renders=0;let tick=0;const app=new ProactiveApplication(async(c,r)=>wrap(r,r.operation==='proactive_status'?{...status,budget:{...status.budget,highWater:++tick}}:{items:[]}),()=>renders++);await app.refresh();app.selected.add('unsaved-selection');for(let n=0;n<4;n++)await app.refresh();assert.equal(renders,1);assert(app.selected.has('unsaved-selection'));});

test('completed response does not erase a newer typed follow-up',async()=>{const app=new ProactiveApplication(async(c,r)=>wrap(r,r.operation==='proactive_status'?status:r.operation==='proactive_response'?{status:'committed',outcome:{reply:'已讨论'}}:{items:[]}),()=>{});app.initialized=true;app.status=status;app.responseRequest='prior';app.submittedText='先讨论一下';app.responseDraft='新的问题还没发';await app.refresh();assert.equal(app.responseDraft,'新的问题还没发');});

test('unrelated response keeps original draft during completion and restart',async()=>{const outcome={status:'ordinary_conversation_required'};const invoke=async(c,r)=>wrap(r,r.operation==='proactive_status'?{...status,recentResponse:{requestId:'topic',status:'committed',text:'另一个项目的问题',outcome}}:r.operation==='proactive_response'?{status:'committed',outcome}:{items:[]});const app=new ProactiveApplication(invoke,()=>{});app.initialized=true;app.status=status;app.responseRequest='topic';app.submittedText=app.responseDraft='另一个项目的问题';await app.refresh();assert.equal(app.responseDraft,'另一个项目的问题');const reopened=new ProactiveApplication(invoke,()=>{});await reopened.refresh();assert.equal(reopened.responseDraft,'另一个项目的问题');});

test('topic switch uses existing ordinary preview without auto-confirming or changing suggestion',async()=>{let calls=[];const app=new ProactiveApplication(async()=>{throw Error('no proactive request expected')},()=>{});app.ordinaryRequired=true;app.responseDraft='另一个项目的问题';app.activeControl={suggestion:{id:'old'}};await app.continueOrdinary({edit:t=>calls.push(['edit',t]),prepare:async()=>calls.push(['prepare']),confirm:async()=>{throw Error('automatic send forbidden')}});assert.deepEqual(calls,[['edit','另一个项目的问题'],['prepare']]);assert.equal(app.responseDraft,'另一个项目的问题');assert.equal(app.activeControl,null);assert.equal(app.ordinaryRequired,false);});


test('credential recovery never starts from polling or a forged click',async()=>{const calls=[];const app=new ProactiveApplication(async(c,r)=>{calls.push(r.operation);return wrap(r,r.operation==='proactive_status'?{...status,pauseReason:'credential_unavailable'}:{items:[]})},()=>{});await app.refresh();await app.requestCredentialCheck({isTrusted:false});await app.refresh();assert(!calls.includes('request_credential_check'));});
test('credential recovery opens only native menu and cannot issue start, save or POST',async()=>{const calls=[];const app=new ProactiveApplication(async(c,r)=>{calls.push([c,r.operation,r.payload]);return wrap(r,{status:'awaiting_user'})},()=>{});app.status={...status,pauseReason:'credential_unavailable'};await app.requestCredentialCheck({isTrusted:true});assert.deepEqual(calls,[['save_ai_provider_settings','request_credential_check',{}]]);await app.requestCredentialCheck({isTrusted:true});assert.equal(calls.length,1);assert.equal(app.credentialCheck.status,'awaiting_user');});
test('credential check cancelled during menu open cannot restore late state',async()=>{let release;const gate=new Promise(r=>release=r);const app=new ProactiveApplication(async(c,r)=>{if(r.operation==='request_credential_check')await gate;return wrap(r,{status:'awaiting_user'})},()=>{});app.status={...status,pauseReason:'credential_unavailable'};const pending=app.requestCredentialCheck({isTrusted:true});await app.cancelCredentialCheck();release();await pending;assert.equal(app.credentialCheck.status,'cancelled');});

test('compact settings keeps scope and technical details out of default region',()=>{const app=new ProactiveApplication(async()=>{},()=>{});app.status={...status,pauseReason:'credential_unavailable',controls:[]};app.selected.add('a');const html=proactiveSettings(app,String);const primary=html.split('<details')[0];assert(!primary.includes('<fieldset'));assert(!primary.includes('api.deepseek.com'));assert(!primary.includes('8192'));assert(primary.includes('role="switch"'));assert.equal((primary.match(/data-action="proactive-credential-check"/g)||[]).length,1);assert(!primary.includes('data-action="proactive-enable"'));app.rangeOpen=true;assert(proactiveSettings(app,String).includes('确认保存范围'));});
test('first enable opens disclosure without grant write; one-click disable preserves selected sources',async()=>{let writes=0;const app=new ProactiveApplication(async(c,r)=>{if(r.operation==='proactive_policy')writes++;return wrap(r,r.operation==='proactive_status'?{...status,policy:{...status.policy,enabled:false}}:{items:[]})},()=>{});app.status={...status,policy:{...status.policy,enabled:false}};app.initialized=true;app.selectedSources.add('shared-source');await app.toggleEnabled();assert.equal(writes,0);assert.equal(app.rangeOpen,true);assert(proactiveSettings(app,String).includes('同意并启用'));app.status=status;await app.toggleEnabled();assert.equal(writes,1);assert(app.selectedSources.has('shared-source'));});
test('credential entry errors retain only safe fixed code',async()=>{const app=new ProactiveApplication(async()=>{throw {code:'credential_check_configuration_binding',detail:'SECRET'}},()=>{});app.status={...status,pauseReason:'credential_unavailable'};await app.requestCredentialCheck({isTrusted:true});assert.equal(app.credentialCheck.errorCode,'credential_check_configuration_binding');assert(!JSON.stringify(app.credentialCheck).includes('SECRET'));assert.equal(credentialEntryCode({code:'secret-path'}),'credential_check_entry_unavailable');});

test('turning off while scope is being edited retains the last saved permission set',async()=>{let saved;const app=new ProactiveApplication(async(c,r)=>{if(r.operation==='proactive_policy')saved=r.payload;return wrap(r,r.operation==='proactive_status'?status:{items:[]})},()=>{});app.status=status;app.initialized=true;app.selected.add('unsaved-new-item');app.selectedSources.add('unsaved-source');await app.toggleEnabled();assert.deepEqual(saved.subjectIds,status.policy.subjectIds);assert.deepEqual(saved.sourceIds,status.policy.sourceIds);assert.equal(saved.enabled,false);});

test('historical credential success does not contradict current Host policy after resume or disable',()=>{const check={status:'finished',diagnostic:{ok:true},readAttempts:1};const text=credentialCheckText(check);assert(!text.includes('仍暂停'));assert(text.includes('手动读取成功'));const app=new ProactiveApplication(async()=>{},()=>{});app.credentialCheck=check;for(const [enabled,pause] of [[true,null],[true,'credential_unavailable'],[false,null]]){app.status={...status,policy:{...status.policy,enabled},pauseReason:pause};const html=proactiveSettings(app,String);const main=html.split('<details')[0];assert.equal(main.includes('data-action="proactive-enable"'),enabled&&!!pause);assert.equal(main.includes('仍暂停'),enabled&&!!pause);assert.equal(main.includes('已关闭'),!enabled);}});
