import {spawn} from 'node:child_process';import {createInterface} from 'node:readline';import assert from 'node:assert/strict';
import {HealthConversation,HealthFlow} from '../candidate/ui/health_conversation.js';
import {chooseContext} from '../candidate/ui/health_context.js';
let seq=0;const results=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function host(){const p=spawn('/private/tmp/lifeos-p3-151-health-conversation-v1/target/debug/synthetic-driver',[],{stdio:['pipe','pipe','inherit']});const pending=new Map();createInterface({input:p.stdout}).on('line',l=>{const v=JSON.parse(l),h=pending.get(v.id);pending.delete(v.id);v.ok?h.resolve(v.result):h.reject(v.error)});return {close:()=>p.kill(),invoke:(command,request)=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});p.stdin.write(JSON.stringify({id,command,request})+'\n')})};}
function draft(text){return {requestId:crypto.randomUUID(),turnId:crypto.randomUUID(),revision:1,text}}
async function test(name,fn){const h=host(),a=new HealthConversation(h);try{await fn(a,h);results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:String(e.stack||JSON.stringify(e))});}finally{h.close()}}
await test('natural health -> clarification -> explicit state -> changed suggestion -> correction',async a=>{await a.answer(draft('根据我的健康记录，怎么安排活动？'),()=>true);let s=await a.read();assert.equal(s.questions[0].field,'available_time');assert.equal(s.states.length,0);await a.answer(draft('我有20分钟'),()=>true);s=await a.read();assert.equal(s.states[0].value,20);assert.equal(s.questions[0].status,'answered');await a.answer(draft('请建议散步活动'),()=>true);s=await a.read();assert.match(s.turns.at(-1).answer,/20 分钟/);await a.answer(draft('纠正，我只有5分钟'),()=>true);s=await a.read();assert.equal(s.states[0].value,5);assert(s.turns.some(t=>t.text==='我有20分钟'));assert(s.turns.some(t=>t.status==='stale'));await a.answer(draft('怎么安排健康活动'),()=>true);s=await a.read();assert.match(s.turns.at(-1).answer,/5 分钟/);assert.equal(s.memories.length,2);});
await test('Work excludes Health; unknown and ambiguous questions honest',async a=>{for(const q of ['工作报告怎么开始？','请解释量子纠缠是什么','健康和工作一起怎么安排？'])await a.answer(draft(q),()=>true);const s=await a.read();assert(s.turns[0].refs.every(r=>r.domain==='work'));assert.equal(s.turns[1].refs.length,0);assert.match(s.turns[1].answer,/不具备开放域推理/);assert.equal(s.turns[2].refs.length,0);assert.match(s.turns[2].answer,/工作安排，还是健康/);});
await test('ignored or deferred clarification causes no state and no repeated prompt',async a=>{await a.answer(draft('健康活动怎么安排'),()=>true);let s=await a.read();await a.decision(s.questions[0].id,'ignore');await a.answer(draft('再建议健康活动'),()=>true);s=await a.read();assert.equal(s.states.length,0);assert(!s.turns.at(-1).clarificationId);await a.answer(draft('工作报告怎么安排'),()=>true);s=await a.read();await a.decision(s.questions.find(q=>q.domain==='work').id,'defer');await a.answer(draft('再建议工作报告计划'),()=>true);s=await a.read();assert.equal(s.states.length,0);assert(!s.turns.at(-1).clarificationId);});
await test('Adapter switch retains memory and conversation',async a=>{await a.answer(draft('我的睡眠记录是什么'),()=>true);const before=await a.read();await a.select('OfflineB');await a.answer(draft('我的步数记录是什么'),()=>true);const after=await a.read();assert.equal(after.turns.length,2);assert.deepEqual(after.memories,before.memories);assert.match(after.turns.at(-1).answer,/离线测试 B/);assert.match(after.turns.at(-1).answer,/6200/);});
await test('Flow failure keeps draft; retry and double submit commit once',async a=>{const f=new HealthFlow(a,()=>{});await f.start();f.edit('我的睡眠记录 [模拟失败]');await f.send();assert.equal(f.phase,'failed');assert.match(f.draft.text,/模拟失败/);await Promise.all([f.send(),f.send()]);assert.equal(f.snapshot.turns.length,1);assert.equal(f.draft.text,'');f.dispose();});
await test('Flow cancel and late Adapter output cannot overwrite new question',async a=>{await a.select('OfflineB');const f=new HealthFlow(a,()=>{});await f.start();f.edit('我的睡眠记录');const run=f.send();await sleep(100);await f.cancel();f.edit('新的工作报告问题');await run;assert.equal(f.draft.text,'新的工作报告问题');assert.equal((await a.read()).turns.length,0);f.dispose();});
await test('Editing in flight retains new draft; restart restores pending draft',async a=>{await a.select('OfflineB');const f=new HealthFlow(a,()=>{});await f.start();f.edit('我的步数记录');const run=f.send();await sleep(100);f.edit('工作报告的新草稿');await run;await sleep(260);assert.equal((await a.read()).turns.length,0);const g=new HealthFlow(a,()=>{});await g.start();assert.equal(g.draft.text,'工作报告的新草稿');f.dispose();g.dispose();});
await test('Second Host validation rejects before Adapter invocation',async(a,h)=>{let prepares=0,generated=0;const guarded=new HealthConversation({invoke:async(c,r)=>{if(r.operation==='prepare_turn'&&++prepares===2)throw {code:'context_stale'};return h.invoke(c,r)}});guarded.models.OfflineA.generate=async()=>{generated++;throw Error('must not call')};await assert.rejects(guarded.answer(draft('我的睡眠记录'),()=>true));assert.equal(generated,0);});
await test('Request context budget is bounded and excludes unauthorized projections',async a=>{const d=draft('我的睡眠和步数、运动记录');await a.draft(d);const p=await a.call('resolve_request_context','prepare_turn',{requestId:crypto.randomUUID(),turnId:d.turnId,expectedDraftRevision:1});const c=chooseContext(p);assert(c.usedBytes<=4096);assert(c.included.filter(r=>r.layer==='L3').length<=3);assert(c.included.filter(r=>r.layer!=='L3').length<=2);assert(c.inputRefs.every(r=>!['denied-health','expired-health'].includes(r.id)));});
await test('Overlapping Chinese words retrieve report inside a natural sentence',async a=>{await a.answer(draft('请建议工作报告计划'),()=>true);const s=await a.read();assert(s.turns.at(-1).refs.some(r=>r.id==='work-report'));assert(s.turns.at(-1).refs.every(r=>r.domain==='work'));});
console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));if(results.some(r=>!r.pass))process.exitCode=1;
