import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';import {createInterface} from 'node:readline';
import {ControlledConversation} from '../candidate/ui/controlled_conversation.js';
const results=[],sleep=ms=>new Promise(r=>setTimeout(r,ms));
function host(){const p=spawn('/private/tmp/lifeos-p3-156-next-action-v1/target/debug/synthetic-driver',[],{stdio:['pipe','pipe','inherit']});let seq=0;const pending=new Map();createInterface({input:p.stdout}).on('line',l=>{const v=JSON.parse(l),h=pending.get(v.id);pending.delete(v.id);clearTimeout(h.timer);v.ok?h.resolve(v.result):h.reject(v.error)});p.on('exit',()=>{for(const h of pending.values()){clearTimeout(h.timer);h.reject(Error('driver exited'));}});const invoke=(command,request)=>new Promise((resolve,reject)=>{const id=++seq,timer=setTimeout(()=>{reject(Error('IPC deadline'));p.kill()},20000);pending.set(id,{resolve,reject,timer});p.stdin.write(JSON.stringify({id,command,request})+'\n')});return {invoke,call:(c,p)=>invoke(c,{version:1,payload:p}),close:()=>p.kill()};}
const draft=()=>({requestId:crypto.randomUUID(),turnId:crypto.randomUUID(),revision:1,text:'我的项目星舟资料包含什么内容'});
async function poll(fn,predicate){for(let i=0;i<150;i++){const v=await fn();if(predicate(v))return v;await sleep(100)}throw Error('completion deadline');}
async function status(h){return (await h.call('get_source_status',{})).connectors.find(c=>c.connectorId==='directory');}
async function connect(h){await h.call('connect_source_directory',{requestId:crypto.randomUUID()});return poll(()=>status(h),s=>s?.scanComplete&&s.pending===0);}
async function control(h,action){const s=await status(h);return h.call('control_source_job',{requestId:crypto.randomUUID(),connectorId:s.connectorId,expectedGeneration:s.grantGeneration,action});}
async function test(name,fn){const h=host();try{await fn(h);results.push({name,pass:true})}catch(e){results.push({name,pass:false,error:e.stack||JSON.stringify(e)})}finally{h.close()}}
async function prepared(h){await connect(h);const a=new ControlledConversation(h);await a.saveCredential('combined-fictional-only',0);await a.testModels();await a.selectModel('user-synthetic-model');await a.setEnabled(true);const r=await a.prepare(draft(),()=>true);assert.equal(r.kind,'preview');assert(r.preview.items.some(i=>i.text.includes('星舟')));return {a,preview:r.preview};}
async function imported(h,file){await h.call('import_apple_health_file',{action:'start',file});return poll(()=>h.call('import_apple_health_file',{action:'status'}),s=>s.status!=='running');}
const health=h=>h.invoke('get_today',{version:2,operation:'health_view',payload:{metric:'steps',days:7,endDay:Math.floor(Date.parse('2026-09-08T00:00:00Z')/86400000)}});
await test('connection parsing statuses, search and original evidence',async h=>{const s=await connect(h);assert.equal(s.discovered,8);assert(s.files.some(f=>f.status==='restricted'));assert(s.files.some(f=>f.status==='unparsed'));const r=await h.call('get_source_evidence',{mode:'search',connectorId:'directory',expectedGeneration:s.grantGeneration,query:'星舟'});assert(r.results.length>0);for(const row of r.results){assert(!/config.json|unknown.bin/.test(row.sourceRef));const d=await h.call('get_source_evidence',{mode:'detail',connectorId:row.sourceId,sourceRef:row.sourceRef,expectedVersion:row.version});assert(d.segments.some(v=>v.text.includes('星舟')));}});
await test('pause resume cancel refresh disconnect and reconnect generations',async h=>{const first=await connect(h);assert.equal((await control(h,'pause')).status,'paused');assert.equal((await control(h,'resume')).status,'active');assert.equal((await control(h,'cancel')).status,'cancelled');assert.equal((await control(h,'refresh')).status,'active');await poll(()=>status(h),s=>s.scanComplete&&s.pending===0);assert.equal((await control(h,'disconnect')).status,'disconnected');const next=await connect(h);assert(next.grantGeneration>first.grantGeneration);});
await test('original detail pagination and stale cursor rejection',async h=>{const s=await connect(h),file=s.files.find(f=>f.title==='pagination.txt');assert(file);const p={mode:'detail',connectorId:'directory',sourceRef:file.sourceRef,expectedVersion:file.version};const first=await h.call('get_source_evidence',p);assert.equal(first.segments.length,50);assert(first.nextCursor);const second=await h.call('get_source_evidence',{...p,cursor:first.nextCursor});assert(second.segments.length>0);assert.notEqual(first.segments[0].locator,second.segments[0].locator);assert.equal(first.segments.map(v=>v.text).join('')+second.segments.map(v=>v.text).join(''),'pagination fixture '+('abcdefghijklmnop '.repeat(4000)));await control(h,'refresh');await assert.rejects(h.call('get_source_evidence',{...p,cursor:first.nextCursor}));});
await test('source preview is inert and confirmation has bound typed references',async h=>{const {a,preview}=await prepared(h);assert.equal((await a.read()).turns.length,0);await a.confirm(preview);const turn=(await a.read()).turns[0];assert(turn.refs.some(r=>r.engineRef?.store&&r.engineRef?.contentHash));assert(turn.refs.filter(r=>r.engineRef).length<=3);});
for(const action of ['refresh','disconnect','pause','cancel'])await test(action+' invalidates previous source confirmation',async h=>{const {a,preview}=await prepared(h);await control(h,action);await assert.rejects(a.confirm(preview));assert.equal((await a.read()).turns.length,0);});
await test('offline target grant and revocation',async h=>{let s=await connect(h);const link=s.links.find(l=>l.target==='../external/approved.txt');assert(link);const act=decision=>h.call('authorize_source_target',{requestId:crypto.randomUUID(),connectorId:'directory',expectedGeneration:s.grantGeneration,linkId:link.linkId,decision});await act('grant');s=await poll(()=>status(h),s=>s.links.some(l=>l.linkId===link.linkId&&l.status!=='fetch_pending'));assert.equal(s.links.find(l=>l.linkId===link.linkId).status,'fetched');await act('revoke');assert.equal((await status(h)).links.find(l=>l.linkId===link.linkId).status,'revoked');});
await test('XML ZIP duplicate and failure preserve Reader observations',async h=>{const a=await imported(h,'health-demo.xml');assert.equal(a.status,'completed');const before=await health(h);assert(before.points.some(p=>p.value===4321));const b=await imported(h,'health-demo.xml');assert.equal(b.status,'duplicate');assert.equal(b.inserted,0);const z=await imported(h,'health-demo.zip');assert.equal(z.status,'completed');assert.equal(z.inserted,0);assert.equal((await imported(h,'broken.xml')).status,'failed');assert.deepEqual((await health(h)).points,before.points);});
await test('source and import reject injected paths and incorrect schemas',async h=>{for(const [c,p] of [['connect_source_directory',{requestId:crypto.randomUUID(),path:'/not-authorized'}],['get_source_status',{path:'/not-authorized'}],['import_apple_health_file',{action:'start',file:'../outside.xml'}],['import_apple_health_file',{action:'status',extra:true}],['get_source_evidence',{mode:'search',connectorId:'directory',expectedGeneration:1,query:'x',extra:true}]])await assert.rejects(h.call(c,p));assert.equal((await h.call('get_source_status',{})).connectors.length,0);});
console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));if(results.some(r=>!r.pass))process.exitCode=1;
