use super::*;
use std::sync::atomic::{AtomicUsize,Ordering};
static N:AtomicUsize=AtomicUsize::new(0);
fn store()->Store{Store::open(&PathBuf::from(ROOT).join(format!("synthetic/test-{}-{}.sqlite",std::process::id(),N.fetch_add(1,Ordering::SeqCst)))).unwrap()}
fn call(s:&Store,op:&str,p:Value)->R<Value>{let cmd=match op{"draft_turn"=>"capture_record","conversation_snapshot"=>"get_context_recovery","clarification_decision"=>"decide_understanding_feedback","select_offline_adapter"=>"save_ai_provider_settings",_=>"resolve_request_context"};s.dispatch(cmd,json!({"version":4,"operation":op,"payload":p}).to_string().as_bytes())}
fn prepare(s:&Store,t:&str,q:&str)->Value{call(s,"draft_turn",json!({"requestId":format!("d:{t}"),"turnId":t,"revision":1,"text":q})).unwrap();call(s,"prepare_turn",json!({"requestId":format!("p:{t}"),"turnId":t,"expectedDraftRevision":1})).unwrap()}
fn rf(p:&Value,r:&Value)->Value{let src=p["snapshot"]["sources"].as_array().unwrap().iter().find(|s|s["id"]==r["sourceId"]).unwrap();json!({"id":r["id"],"version":r["version"],"authorizationGeneration":src["generation"]})}
fn payload(p:&Value)->Value{let refs=p["snapshot"]["records"].as_array().unwrap().iter().filter(|r|r["kind"]=="source_projection").take(3).map(|r|rf(p,r)).collect::<Vec<_>>();json!({"requestId":format!("c:{}",p["turnId"].as_str().unwrap()),"turnId":p["turnId"],"packetId":p["id"],"modelId":p["modelId"],"text":"合成演练 · 离线测试 A\n仅为测试回答。","inputRefs":refs})}
#[test]fn raw_duplicate_unknown_null_and_mode_rejected(){let s=store();for raw in [r#"{"version":4,"version":4,"operation":"conversation_snapshot","payload":{}}"#,r#"{"version":4,"operation":"draft_turn","payload":{"requestId":"x","turnId":"x","revision":1,"text":"x","authorized":true}}"#,r#"{"version":4,"operation":"conversation_snapshot","payload":null}"#]{assert!(s.dispatch("capture_record",raw.as_bytes()).is_err());}assert!(s.dispatch("get_context_recovery",&vec![b' ';16385]).is_err());assert!(s.dispatch("send_source_ai_request",b"{}").is_err());}
#[test]fn drafts_preserve_text_cas_and_idempotency(){let s=store();let p=json!({"requestId":"d","turnId":"t","revision":1,"text":" 原样保留 "});let a=call(&s,"draft_turn",p.clone()).unwrap();assert_eq!(a,call(&s,"draft_turn",p.clone()).unwrap());let mut bad=p.clone();bad["text"]=json!("other");assert_eq!(call(&s,"draft_turn",bad.clone()).unwrap_err().code,"idempotency_conflict");bad["requestId"]=json!("new");assert_eq!(call(&s,"draft_turn",bad).unwrap_err().code,"draft_revision_conflict");assert_eq!(call(&s,"conversation_snapshot",json!({})).unwrap()["pendingDraft"]["text"]," 原样保留 ");}
#[test]fn scoped_authorized_current_candidates(){let s=store();let work=prepare(&s,"work","帮我安排工作报告");assert!(work["snapshot"]["records"].as_array().unwrap().iter().all(|r|r["domain"]=="work"));let both=prepare(&s,"both","工作和健康怎么安排");assert!(both["snapshot"]["records"].as_array().unwrap().is_empty());let health=prepare(&s,"health","最近的睡眠记录如何");let rows=health["snapshot"]["records"].as_array().unwrap();assert!(!rows.iter().any(|r|r["id"]=="expired-health"||r["id"]=="denied-health"));assert!(rows.iter().any(|r|r["id"]=="sleep-unknown"&&r["value"].is_null()));let mut source=get(&s.c,"sources","health-demo").unwrap().unwrap();source["authorized"]=json!(false);put(&s.c,"sources","health-demo",&source).unwrap();let denied=prepare(&s,"denied","我的睡眠怎么样");assert!(denied["snapshot"]["records"].as_array().unwrap().is_empty());assert!(!call(&s,"conversation_snapshot",json!({})).unwrap()["memories"].as_array().unwrap().iter().any(|m|m["domain"]=="health"));}
#[test]fn duplicate_forged_generation_and_cross_domain_refs_rejected(){let s=store();let p=prepare(&s,"t","我的睡眠记录");let good=payload(&p);let mut bad=good.clone();bad["inputRefs"].as_array_mut().unwrap().push(good["inputRefs"][0].clone());assert_eq!(call(&s,"commit_turn",bad).unwrap_err().code,"reference_rejected");let mut bad=good.clone();bad["inputRefs"][0]["authorizationGeneration"]=json!(999);assert!(call(&s,"commit_turn",bad).is_err());let mut bad=good;bad["inputRefs"][0]["id"]=json!("work-report");assert!(call(&s,"commit_turn",bad).is_err());assert_eq!(s.c.query_row("SELECT count(*) FROM derivations",[],|r|r.get::<_,i64>(0)).unwrap(),0);}
#[test]fn preflight_and_commit_revalidate_authorization(){let s=store();let p=prepare(&s,"t","睡眠记录");let mut grant=get(&s.c,"sources","health-demo").unwrap().unwrap();grant["generation"]=json!(2);put(&s.c,"sources","health-demo",&grant).unwrap();assert_eq!(call(&s,"prepare_turn",json!({"requestId":"p2","turnId":"t","expectedDraftRevision":1})).unwrap_err().code,"context_stale");assert!(call(&s,"commit_turn",payload(&p)).is_err());}
#[test]fn draft_revision_and_adapter_baseline_revalidated(){let s=store();let p=prepare(&s,"t","安排工作");call(&s,"select_offline_adapter",json!({"requestId":"m","modelId":"OfflineB"})).unwrap();assert!(call(&s,"commit_turn",payload(&p)).is_err());let p=prepare(&s,"t2","安排工作");call(&s,"draft_turn",json!({"requestId":"edit","turnId":"t2","revision":2,"text":"新的问题"})).unwrap();assert!(call(&s,"commit_turn",payload(&p)).is_err());}
#[test]fn commit_atomic_once_and_same_turn_replay(){let s=store();let p=prepare(&s,"t","工作报告");let d=payload(&p);call(&s,"commit_turn",d.clone()).unwrap();call(&s,"commit_turn",d.clone()).unwrap();let mut replay=d.clone();replay["requestId"]=json!("second");call(&s,"commit_turn",replay).unwrap();assert_eq!(s.c.query_row("SELECT count(*) FROM derivations",[],|r|r.get::<_,i64>(0)).unwrap(),1);assert!(call(&s,"conversation_snapshot",json!({})).unwrap()["pendingDraft"].is_null());let mut bad=d;bad["requestId"]=json!("third");bad["text"]=json!("合成演练 · 其他");assert_eq!(call(&s,"commit_turn",bad).unwrap_err().code,"turn_conflict");}
#[test]fn cancel_before_and_after_commit_is_honest(){let s=store();let p=prepare(&s,"t","安排工作");call(&s,"cancel_turn",json!({"requestId":"cancel","turnId":"t"})).unwrap();assert!(call(&s,"commit_turn",payload(&p)).is_err());let p=prepare(&s,"u","工作报告");call(&s,"commit_turn",payload(&p)).unwrap();assert_eq!(call(&s,"cancel_turn",json!({"requestId":"cancel2","turnId":"u"})).unwrap()["status"],"completed");call(&s,"cancel_turn",json!({"requestId":"early","turnId":"v"})).unwrap();call(&s,"draft_turn",json!({"requestId":"d:v","turnId":"v","revision":1,"text":"安排工作"})).unwrap();assert!(call(&s,"prepare_turn",json!({"requestId":"p:v","turnId":"v","expectedDraftRevision":1})).is_err());}
#[test]fn clarification_ignore_defer_do_not_write_state(){for decision in ["ignore","defer"]{let s=store();let p=prepare(&s,"ask","怎么安排运动");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});call(&s,"commit_turn",d).unwrap();call(&s,"clarification_decision",json!({"requestId":"decision","questionId":Store::question_id("health","available_time","ask"),"decision":decision})).unwrap();assert!(active_states(&s.c,now()).unwrap().is_empty());let p=prepare(&s,"again","怎么安排运动");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});if decision=="defer"{assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"clarification_suppressed");}else{call(&s,"commit_turn",d).unwrap();assert_eq!(list(&s.c,"questions",10).unwrap().len(),2);}assert_eq!(list(&s.c,"memories",10).unwrap().len(),2);}}
#[test]fn reply_and_correction_preserve_history_and_invalidate_dependents(){let s=store();let p=prepare(&s,"ask","怎么安排运动");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});call(&s,"commit_turn",d).unwrap();let p=prepare(&s,"reply","我有20分钟");let mut d=payload(&p);d["state"]=json!({"key":"available_time","value":20,"domain":"health"});d["answerTo"]=json!(Store::question_id("health","available_time","ask"));call(&s,"commit_turn",d).unwrap();let p=prepare(&s,"use","今天怎么运动");let mut d=payload(&p);let raw=p["snapshot"]["records"].as_array().unwrap().iter().find(|r|r["id"]=="raw:reply").unwrap();d["inputRefs"].as_array_mut().unwrap().push(rf(&p,raw));call(&s,"commit_turn",d).unwrap();let p=prepare(&s,"fix","纠正，我只有5分钟");let mut d=payload(&p);d["state"]=json!({"key":"available_time","value":5,"domain":"health"});d["corrects"]=json!("state:reply");call(&s,"commit_turn",d).unwrap();assert_eq!(get(&s.c,"records","raw:reply").unwrap().unwrap()["text"],"我有20分钟");assert_eq!(get(&s.c,"states","state:reply").unwrap().unwrap()["status"],"superseded");assert_eq!(get(&s.c,"derivations","answer:use").unwrap().unwrap()["status"],"stale");assert_eq!(active_states(&s.c,now()).unwrap()[0]["value"],5.0);assert_eq!(list(&s.c,"memories",10).unwrap().len(),2);}
#[test]fn arbitrary_state_and_question_binding_rejected(){let s=store();let p=prepare(&s,"t","我有20分钟运动");let mut d=payload(&p);d["state"]=json!({"key":"available_time","value":200,"domain":"health"});assert_eq!(call(&s,"commit_turn",d.clone()).unwrap_err().code,"state_claim_rejected");d["state"]["value"]=json!(20);d["answerTo"]=json!("unrelated");assert!(call(&s,"commit_turn",d).is_err());}
#[test]fn self_report_does_not_replace_sensor_projection(){let s=store();let before=get(&s.c,"records","sleep-1").unwrap();let p=prepare(&s,"self","我睡了5小时");let mut d=payload(&p);d["state"]=json!({"key":"sleep_hours","value":5,"domain":"health"});call(&s,"commit_turn",d).unwrap();assert_eq!(get(&s.c,"records","sleep-1").unwrap(),before);assert_eq!(get(&s.c,"states","state:self").unwrap().unwrap()["identity"],"user_self_report");}
#[test]fn context_and_snapshot_budgets_are_enforced(){let s=store();let mut row=get(&s.c,"records","work-report").unwrap().unwrap();row["text"]=json!("x".repeat(4500));put(&s.c,"records","work-report",&row).unwrap();let p=prepare(&s,"big","工作报告");let d=payload(&p);assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"context_budget_rejected");row["text"]=json!("工作报告");put(&s.c,"records","work-report",&row).unwrap();for i in 0..35{let p=prepare(&s,&format!("t{i}"),"工作报告");call(&s,"commit_turn",payload(&p)).unwrap();}let snap=call(&s,"conversation_snapshot",json!({})).unwrap();assert!(snap["hasMore"].as_bool().unwrap());assert!(serde_json::to_vec(&snap).unwrap().len()<=32768);let count=snap["turns"].as_array().unwrap().iter().map(|t|1+t["refs"].as_array().unwrap().len()).sum::<usize>()+snap["states"].as_array().unwrap().len()+snap["memories"].as_array().unwrap().len()+snap["questions"].as_array().unwrap().len()+usize::from(!snap["pendingDraft"].is_null());assert!(count<=40);}
#[test]fn restart_and_adapter_switch_keep_assets(){let s=store();let p=prepare(&s,"t","工作报告");call(&s,"commit_turn",payload(&p)).unwrap();call(&s,"select_offline_adapter",json!({"requestId":"m","modelId":"OfflineB"})).unwrap();let path=s.c.path().unwrap().to_string();drop(s);let r=Store::open(Path::new(&path)).unwrap();let v=call(&r,"conversation_snapshot",json!({})).unwrap();assert_eq!(v["turns"].as_array().unwrap().len(),1);assert_eq!(v["modelId"],"OfflineB");assert_eq!(v["memories"].as_array().unwrap().len(),2);}
#[test]fn fixed_scope_only(){assert!(Store::open(Path::new("relative.sqlite")).is_err());}
#[test]fn historical_answer_hidden_when_any_health_input_becomes_unavailable(){let s=store();let p=prepare(&s,"t","睡眠记录");let d=payload(&p);call(&s,"commit_turn",d.clone()).unwrap();let key=d["inputRefs"][0]["id"].as_str().unwrap();let mut row=get(&s.c,"records",key).unwrap().unwrap();row["status"]=json!("revoked");put(&s.c,"records",key,&row).unwrap();let snap=call(&s,"conversation_snapshot",json!({})).unwrap();assert_eq!(snap["turns"][0]["status"],"unavailable");assert_ne!(snap["turns"][0]["answer"],d["text"]);assert!(!snap["turns"][0]["refs"].as_array().unwrap().iter().any(|r|r["id"]==key));}

#[test]fn p153_known_authorized_source_prevents_unnecessary_time_question(){
 let s=store();let mut row=get(&s.c,"records","work-report").unwrap().unwrap();row["text"]=json!("工作安排：我有20分钟");put(&s.c,"records","work-report",&row).unwrap();
 let p=prepare(&s,"known","请建议工作安排");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"clarification_rejected");assert!(list(&s.c,"states",10).unwrap().is_empty());
}
#[test]fn p153_no_value_gap_cannot_be_injected_by_client(){
 let s=store();for (t,q) in [("fact","我的睡眠记录是什么"),("general","解释量子纠缠是什么")]{let p=prepare(&s,t,q);let mut d=payload(&p);d["clarification"]=json!({"field":if t=="fact"{"available_time"}else{"domain"}});assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"clarification_rejected");}
}
#[test]fn p153_silence_is_readonly_and_correction_ends_old_validity_selectively(){
 let s=store();let p=prepare(&s,"unrelated","工作报告");call(&s,"commit_turn",payload(&p)).unwrap();let unrelated=get(&s.c,"derivations","answer:unrelated").unwrap();
 let p=prepare(&s,"first","我有20分钟运动");let mut d=payload(&p);d["state"]=json!({"key":"available_time","value":20,"domain":"health"});call(&s,"commit_turn",d).unwrap();let raw=get(&s.c,"records","raw:first").unwrap();let old=get(&s.c,"states","state:first").unwrap().unwrap();
 let p=prepare(&s,"correction","纠正，改为5分钟");let mut d=payload(&p);d["state"]=json!({"key":"available_time","value":5,"domain":"health"});d["corrects"]=json!("state:first");call(&s,"commit_turn",d).unwrap();let previous=get(&s.c,"states","state:first").unwrap().unwrap();let current=get(&s.c,"states","state:correction").unwrap().unwrap();
 assert_eq!(previous["validUntil"],current["observedAt"]);assert_eq!(previous["observedAt"],old["observedAt"]);assert_eq!(get(&s.c,"records","raw:first").unwrap(),raw);assert_eq!(get(&s.c,"derivations","answer:first").unwrap().unwrap()["status"],"stale");assert_eq!(get(&s.c,"derivations","answer:unrelated").unwrap(),unrelated);assert_eq!(get(&s.c,"records","raw:correction").unwrap().unwrap()["corrects"],"state:first");
 let before=fs::read(s.c.path().unwrap()).unwrap();let _=call(&s,"conversation_snapshot",json!({})).unwrap();assert_eq!(fs::read(s.c.path().unwrap()).unwrap(),before);
}
#[test]fn p153_correction_without_domain_cannot_guess_between_two_active_domains(){let s=store();for (t,q,domain) in [("h","我有20分钟运动","health"),("w","我有30分钟工作","work")]{let p=prepare(&s,t,q);let mut d=payload(&p);d["state"]=json!({"key":"available_time","value":if t=="h"{20}else{30},"domain":domain});call(&s,"commit_turn",d).unwrap();}let p=prepare(&s,"ambiguous-correction","纠正，改为5分钟");assert_eq!(p["domain"],"ambiguous");let mut d=payload(&p);d["state"]=json!({"key":"available_time","value":5,"domain":"health"});d["corrects"]=json!("state:h");assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"state_claim_rejected");assert_eq!(active_states(&s.c,now()).unwrap().len(),2);}

fn p153_ask(s:&Store,turn:&str)->String{let p=prepare(s,turn,"怎么安排运动");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});call(s,"commit_turn",d).unwrap();Store::question_id("health","available_time",turn)}
fn p153_decision(s:&Store,rid:&str,qid:&str,decision:&str)->R<Value>{call(s,"clarification_decision",json!({"requestId":rid,"questionId":qid,"decision":decision}))}
#[test]fn p153_reject_persists_beyond_history_window_and_reopen_is_explicit(){
 let s=store();let qid=p153_ask(&s,"refuse");let before_states=list(&s.c,"states",10).unwrap();let before_memories=list(&s.c,"memories",10).unwrap();
 assert_eq!(p153_decision(&s,"reject",&qid,"reject").unwrap()["status"],"rejected");p153_decision(&s,"reject",&qid,"reject").unwrap();assert_eq!(list(&s.c,"feedback",100).unwrap().len(),1);
 for i in 0..20{let id=format!("history-{i}");put(&s.c,"questions",&id,&json!({"id":id,"field":"available_time","domain":"work","status":"ignored","basisTurn":id,"createdAt":now()})).unwrap();}
 let p=prepare(&s,"still-no","请建议健康活动");assert!(p["questions"].as_array().unwrap().iter().any(|q|q["id"]==qid&&q["status"]=="rejected"));let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"clarification_suppressed");
 assert_eq!(list(&s.c,"states",10).unwrap(),before_states);assert_eq!(list(&s.c,"memories",10).unwrap(),before_memories);assert_eq!(p153_decision(&s,"reopen",&qid,"reopen").unwrap()["status"],"pending");p153_decision(&s,"reopen",&qid,"reopen").unwrap();assert_eq!(list(&s.c,"feedback",100).unwrap().len(),2);
 let p=prepare(&s,"voluntary-answer","20分钟");let mut d=payload(&p);d["answerTo"]=json!(qid);d["state"]=json!({"key":"available_time","domain":"health","value":20});call(&s,"commit_turn",d).unwrap();assert_eq!(active_states(&s.c,now()).unwrap()[0]["value"],20.0);
}
#[test]fn p153_defer_retries_only_after_recorded_time_with_new_instance(){
 let s=store();let qid=p153_ask(&s,"defer-old");p153_decision(&s,"defer",&qid,"defer").unwrap();let mut q=get(&s.c,"questions",&qid).unwrap().unwrap();assert!(q["resumeAt"].as_i64().unwrap()>now());let p=prepare(&s,"too-early","怎么安排运动");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"clarification_suppressed");
 q["resumeAt"]=json!(now()-1);put(&s.c,"questions",&qid,&q).unwrap();let next=p153_ask(&s,"defer-new");assert_ne!(qid,next);assert_eq!(get(&s.c,"questions",&qid).unwrap().unwrap(),q);assert_eq!(p153_decision(&s,"old-action",&qid,"reject").unwrap_err().code,"clarification_stale");
}
#[test]fn p153_legacy_id_compatibility_and_no_implicit_reopen(){
 let s=store();let qid="q:health:available_time";put(&s.c,"questions",qid,&json!({"id":qid,"domain":"health","field":"available_time","status":"pending","basisTurn":"legacy","createdAt":now()})).unwrap();
 assert_eq!(p153_decision(&s,"legacy-reject",qid,"reject").unwrap()["status"],"rejected");let p=prepare(&s,"ordinary","健康活动怎么安排");call(&s,"commit_turn",payload(&p)).unwrap();assert_eq!(get(&s.c,"questions",qid).unwrap().unwrap()["status"],"rejected");assert_eq!(p153_decision(&s,"legacy-open",qid,"reopen").unwrap()["status"],"pending");
}
#[test]fn p153_answer_history_remains_resolved_but_new_gap_can_be_asked(){
 let s=store();let qid=p153_ask(&s,"resolved");let mut q=get(&s.c,"questions",&qid).unwrap().unwrap();q["status"]=json!("answered");q["answeredAt"]=json!(now()-172800000);put(&s.c,"questions",&qid,&q).unwrap();
 let before=fs::read(s.c.path().unwrap()).unwrap();assert_eq!(call(&s,"conversation_snapshot",json!({})).unwrap()["questions"][0]["status"],"answered");assert_eq!(before,fs::read(s.c.path().unwrap()).unwrap());
 let p=prepare(&s,"resolved-again","怎么安排运动");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});call(&s,"commit_turn",d).unwrap();assert_eq!(get(&s.c,"questions",&qid).unwrap().unwrap(),q);
}
#[test]fn p153_reject_during_prepared_turn_and_revoke_prevent_late_question(){
 let s=store();let qid=p153_ask(&s,"race-question");let p=prepare(&s,"race","怎么安排运动");p153_decision(&s,"race-reject",&qid,"reject").unwrap();let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"clarification_suppressed");
 let mut auth=get(&s.c,"sources","health-demo").unwrap().unwrap();auth["authorized"]=json!(false);put(&s.c,"sources","health-demo",&auth).unwrap();assert!(p153_decision(&s,"revoked-open",&qid,"reopen").is_err());assert!(call(&s,"conversation_snapshot",json!({})).unwrap()["questions"].as_array().unwrap().is_empty());assert!(active_states(&s.c,now()).unwrap().is_empty());
}

#[test]fn p153_voluntary_answer_can_resolve_deferred_question_before_retry_time(){let s=store();let qid=p153_ask(&s,"later-answer");p153_decision(&s,"later",&qid,"defer").unwrap();let p=prepare(&s,"voluntary","20分钟");assert_eq!(p["domain"],"health");let mut d=payload(&p);d["state"]=json!({"key":"available_time","value":20,"domain":"health"});d["answerTo"]=json!(qid);call(&s,"commit_turn",d).unwrap();assert_eq!(active_states(&s.c,now()).unwrap()[0]["value"],20.0);}

#[test]fn p153_negative_and_fractional_time_cannot_be_silently_truncated(){let s=store();for (t,q,value) in [("negative","我有-5分钟运动",5),("fraction","我有2.5分钟运动",5),("overflow","我有1020分钟运动",20)]{let p=prepare(&s,t,q);let mut d=payload(&p);d["state"]=json!({"key":"available_time","value":value,"domain":"health"});assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"state_claim_rejected");}assert!(active_states(&s.c,now()).unwrap().is_empty());}

pub(super) struct C1Clock;
impl Drop for C1Clock{fn drop(&mut self){TEST_NOW.with(|c|c.set(None));}}
pub(super) fn c1_clock()->C1Clock{let at=now();TEST_NOW.with(|c|c.set(Some(at)));C1Clock}
pub(super) fn c1_advance(ms:i64){TEST_NOW.with(|c|c.set(Some(c.get().unwrap()+ms)));}
fn c1_answered(s:&Store)->String{
 for mut r in list(&s.c,"records",100).unwrap(){if r["kind"]=="source_projection"&&r["sourceId"]=="health-demo"{r["validUntil"]=json!(now()+259200000);put(&s.c,"records",r["id"].as_str().unwrap(),&r).unwrap();}}
 let qid=p153_ask(s,"c1-ask");let p=prepare(s,"c1-reply","我有20分钟");let mut d=payload(&p);d["answerTo"]=json!(qid);d["state"]=json!({"key":"available_time","value":20,"domain":"health"});call(s,"commit_turn",d).unwrap();qid
}
#[test]fn c1_expired_answer_allows_new_gap_without_overwriting_history(){
 let _clock=c1_clock();let s=store();let qid=c1_answered(&s);let old=get(&s.c,"questions",&qid).unwrap();c1_advance(86400001);assert!(active_states(&s.c,now()).unwrap().is_empty());
 let p=prepare(&s,"c1-today","今天健康活动怎么安排");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});call(&s,"commit_turn",d).unwrap();assert_eq!(get(&s.c,"questions",&qid).unwrap(),old);assert_eq!(list(&s.c,"questions",10).unwrap().len(),2);
}
#[test]fn c1_state_expiring_during_pending_packet_is_rejected(){
 let _clock=c1_clock();let s=store();c1_answered(&s);c1_advance(86399000);let p=prepare(&s,"c1-late","健康活动怎么安排");let mut d=payload(&p);let raw=p["snapshot"]["records"].as_array().unwrap().iter().find(|r|r["id"]=="raw:c1-reply").unwrap();d["inputRefs"].as_array_mut().unwrap().push(rf(&p,raw));c1_advance(2000);assert!(active_states(&s.c,now()).unwrap().is_empty());assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"context_stale");assert!(get(&s.c,"derivations","answer:c1-late").unwrap().is_none());
}
#[test]fn c1_valid_replacement_state_suppresses_repeat(){let _clock=c1_clock();let s=store();let qid=c1_answered(&s);c1_advance(86400001);let p=prepare(&s,"c1-new-state","我有30分钟运动");let mut d=payload(&p);d["state"]=json!({"key":"available_time","value":30,"domain":"health"});call(&s,"commit_turn",d).unwrap();let p=prepare(&s,"c1-no-need","今天健康活动怎么安排");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"clarification_rejected");assert_eq!(get(&s.c,"questions",&qid).unwrap().unwrap()["status"],"answered");}
fn c1_time_source(s:&Store){put(&s.c,"sources","c1-time-source",&json!({"id":"c1-time-source","authorized":true,"generation":1})).unwrap();put(&s.c,"records","c1-time-row",&json!({"id":"c1-time-row","sourceId":"c1-time-source","domain":"health","kind":"source_projection","status":"active","version":1,"text":"健康活动安排：我有30分钟","observedAt":now(),"validUntil":now()+86400000})).unwrap();}
#[test]fn c1_source_replacement_validity_and_authorization_matrix(){for case in ["valid","expired","revoked","tombstone"]{let _clock=c1_clock();let s=store();c1_answered(&s);c1_advance(86400001);c1_time_source(&s);let mut row=get(&s.c,"records","c1-time-row").unwrap().unwrap();let mut grant=get(&s.c,"sources","c1-time-source").unwrap().unwrap();match case{"expired"=>row["validUntil"]=json!(now()-1),"revoked"=>grant["authorized"]=json!(false),"tombstone"=>row["status"]=json!("revoked"),_=>{}}put(&s.c,"records","c1-time-row",&row).unwrap();put(&s.c,"sources","c1-time-source",&grant).unwrap();let p=prepare(&s,"c1-replacement","今天健康活动怎么安排");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});if case=="valid"{assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"clarification_rejected");}else{assert!(!p["snapshot"]["records"].as_array().unwrap().iter().any(|r|r["id"]=="c1-time-row"));call(&s,"commit_turn",d).unwrap();}}}
#[test]fn c1_source_changes_after_prepare_fail_closed(){for case in ["expiry","generation","version","revoke"]{let _clock=c1_clock();let s=store();c1_time_source(&s);if case=="expiry"{let mut r=get(&s.c,"records","c1-time-row").unwrap().unwrap();r["validUntil"]=json!(now()+1000);put(&s.c,"records","c1-time-row",&r).unwrap();}let p=prepare(&s,"c1-stale-source","健康活动怎么安排");let mut row=get(&s.c,"records","c1-time-row").unwrap().unwrap();let mut grant=get(&s.c,"sources","c1-time-source").unwrap().unwrap();match case{"expiry"=>c1_advance(2000),"generation"=>grant["generation"]=json!(2),"version"=>row["version"]=json!(2),_=>grant["authorized"]=json!(false)}put(&s.c,"records","c1-time-row",&row).unwrap();put(&s.c,"sources","c1-time-source",&grant).unwrap();assert_eq!(call(&s,"commit_turn",payload(&p)).unwrap_err().code,"context_stale");}}
#[test]fn c1_reject_outlives_time_without_timer_or_state_write(){let _clock=c1_clock();let s=store();let mut r=get(&s.c,"records","exercise-1").unwrap().unwrap();r["validUntil"]=json!(now()+604800000);put(&s.c,"records","exercise-1",&r).unwrap();let qid=p153_ask(&s,"c1-reject");p153_decision(&s,"c1-reject-action",&qid,"reject").unwrap();c1_advance(259200000);let before=fs::read(s.c.path().unwrap()).unwrap();let snap=call(&s,"conversation_snapshot",json!({})).unwrap();assert_eq!(snap["questions"][0]["status"],"rejected");assert_eq!(before,fs::read(s.c.path().unwrap()).unwrap());let p=prepare(&s,"c1-refused-again","今天健康活动怎么安排");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"clarification_suppressed");}
#[test]fn c1_expiry_alone_does_not_rewrite_answered_history(){let _clock=c1_clock();let s=store();let qid=c1_answered(&s);let old=get(&s.c,"questions",&qid).unwrap();c1_advance(86400001);let before=fs::read(s.c.path().unwrap()).unwrap();let snap=call(&s,"conversation_snapshot",json!({})).unwrap();assert!(snap["states"].as_array().unwrap().is_empty());assert_eq!(get(&s.c,"questions",&qid).unwrap(),old);assert_eq!(before,fs::read(s.c.path().unwrap()).unwrap());}
#[test]fn c1_state_revoke_or_tombstone_enables_gap_without_resurrection(){for case in ["grant","raw"]{let _clock=c1_clock();let s=store();let qid=c1_answered(&s);if case=="grant"{let mut v=get(&s.c,"sources","conversation").unwrap().unwrap();v["authorized"]=json!(false);v["generation"]=json!(2);put(&s.c,"sources","conversation",&v).unwrap();}else{let mut v=get(&s.c,"records","raw:c1-reply").unwrap().unwrap();v["status"]=json!("revoked");put(&s.c,"records","raw:c1-reply",&v).unwrap();}assert!(active_states(&s.c,now()).unwrap().is_empty());let p=prepare(&s,"c1-missing-state","健康活动怎么安排");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});call(&s,"commit_turn",d).unwrap();assert_eq!(get(&s.c,"questions",&qid).unwrap().unwrap()["status"],"answered");assert!(active_states(&s.c,now()).unwrap().is_empty());}}
