use super::*;
use std::{fs,os::unix::fs::{PermissionsExt,symlink},sync::atomic::{AtomicUsize,Ordering}};
static N:AtomicUsize=AtomicUsize::new(0);
fn fixture()->std::path::PathBuf{
 let p=std::path::PathBuf::from(format!("/private/tmp/lifeos-p3-154-real-continuity-v1/synthetic/health-view-test-{}-{}",std::process::id(),N.fetch_add(1,Ordering::SeqCst)));fs::create_dir(&p).unwrap();fs::set_permissions(&p,fs::Permissions::from_mode(0o700)).unwrap();let p=p.join("health-import.sqlite");let c=Connection::open(&p).unwrap();c.execute_batch("CREATE TABLE states(id TEXT PRIMARY KEY,body TEXT);CREATE TABLE records(id TEXT PRIMARY KEY,body TEXT);CREATE TABLE sources(id TEXT PRIMARY KEY,body TEXT);").unwrap();for metric in ["sleep","steps","exercise"]{for day in 20000..20100{if day==20098{continue;}let body=json!({"protocol":"apple-file-v1","kind":"health_current_state","metric":metric,"dayIndex":day,"offsetMinutes":480,"sources":[{"name":"Synthetic Watch"}],"value":if day==20097{None}else{Some((day-20000)as f64)},"estimated":metric=="sleep","observedAt":day*86400000i64,"receivedAt":20101i64*86400000,"method":"subset"});c.execute("INSERT INTO states VALUES(?1,?2)",params![format!("{metric}-{day}"),body.to_string()]).unwrap();}}drop(c);fs::set_permissions(&p,fs::Permissions::from_mode(0o600)).unwrap();p
}
fn q(metric:&str,days:i64)->Query{Query{metric:metric.into(),days,end_day:None,source:None,offset:None,group_page:0}}
#[test]fn windows_and_gaps(){let p=fixture();let r=Reader::open(&p).unwrap();for m in ["sleep","steps","exercise"]{for days in [7,30,90]{let v=r.query(q(m,days)).unwrap();assert_eq!(v["points"].as_array().unwrap().len(),days as usize);assert_eq!(v["latestDay"],20099);assert_eq!(v["points"][days as usize-2]["present"],false);assert!(v["points"][days as usize-3]["value"].is_null());}}}
#[test]fn unknown_group_and_empty_range(){let p=fixture();let r=Reader::open(&p).unwrap();let mut a=q("steps",7);a.source=Some("' OR 1=1 --".into());a.offset=Some(480);assert!(r.query(a).unwrap()["points"].as_array().unwrap().is_empty());let mut a=q("steps",30);a.end_day=Some(21000);assert!(r.query(a).unwrap()["points"].as_array().unwrap().iter().all(|v|v["present"]==false));}
#[test]fn strict_requests(){let p=fixture();let r=Reader::open(&p).unwrap();for s in [r#"{"version":1,"operation":"snapshot","payload":{}}"#,r#"{"version":2,"version":2,"operation":"health_view","payload":{"metric":"steps","days":7}}"#,r#"{"version":2,"operation":"health_view","payload":{"metric":"steps","days":7,"sql":"DELETE"}}"#]{assert!(r.dispatch(tauri::ipc::InvokeBody::Raw(s.as_bytes().to_vec())).is_err());}for (m,d) in [("heart",7),("steps",8)]{assert!(r.query(q(m,d)).is_err());}let mut a=q("steps",7);a.offset=Some(480);assert!(r.query(a).is_err());}
#[test]fn readonly_lifecycle(){let p=fixture();let before=fs::read(&p).unwrap();for _ in 0..2{let r=Reader::open(&p).unwrap();assert!(r.c.execute_batch("CREATE TABLE forbidden(x)").is_err());assert!(r.c.execute_batch("DELETE FROM states").is_err());r.query(q("steps",90)).unwrap();}assert_eq!(before,fs::read(&p).unwrap());for ext in ["-wal","-shm","-journal"]{assert!(!std::path::PathBuf::from(format!("{}{ext}",p.display())).exists());}}
#[test]fn sidecar_and_symlink_rejected(){let p=fixture();fs::write(format!("{}-wal",p.display()),b"synthetic").unwrap();assert!(Reader::open(&p).is_err());let p=fixture();let link=p.with_file_name("link.sqlite");symlink(&p,&link).unwrap();assert!(Reader::open(&link).is_err());}
#[test]fn changed_database_rejected(){let p=fixture();let r=Reader::open(&p).unwrap();let c=Connection::open(&p).unwrap();c.execute("DELETE FROM states WHERE id='steps-20099'",[]).unwrap();drop(c);assert!(r.query(q("steps",7)).is_err());}
#[test]fn permissions_rejected(){let p=fixture();fs::set_permissions(&p,fs::Permissions::from_mode(0o644)).unwrap();assert!(Reader::open(&p).is_err());}
#[test]fn stable_group_pagination(){let p=fixture();let c=Connection::open(&p).unwrap();for i in 0..70{let b=json!({"protocol":"apple-file-v1","kind":"health_current_state","metric":"steps","dayIndex":20000,"offsetMinutes":0,"sources":[{"name":format!("Group{i:03}")}],"value":1});c.execute("INSERT INTO states VALUES(?1,?2)",params![format!("group{i}"),b.to_string()]).unwrap();}drop(c);let r=Reader::open(&p).unwrap();let mut seen=std::collections::HashSet::new();for page in 0..3{let mut a=q("steps",7);a.group_page=page;let v=r.query(a).unwrap();for g in v["groups"].as_array().unwrap(){assert!(seen.insert(g["source"].as_str().unwrap().to_owned()));}}assert_eq!(seen.len(),71);}
#[test]fn large_fixture_bounded(){let owned=fixture();let p=owned.as_path();let before=fs::read(p).unwrap();let started=Instant::now();let r=Reader::open(p).unwrap();for m in ["steps","sleep","exercise"]{for days in [7,30,90]{let v=r.query(q(m,days)).unwrap();assert_eq!(v["points"].as_array().unwrap().len(),days as usize);assert!(v["groups"].as_array().unwrap().len()<=32);assert!(serde_json::to_vec(&v).unwrap().len()<131072);}}assert!(started.elapsed()<Duration::from_secs(3));drop(r);assert_eq!(before,fs::read(p).unwrap());}
#[test]fn busy_fails_bounded(){let p=fixture();let r=Reader::open(&p).unwrap();let writer=Connection::open(&p).unwrap();writer.execute_batch("BEGIN EXCLUSIVE").unwrap();let started=Instant::now();assert!(r.query(q("steps",7)).is_err());assert!(started.elapsed()<Duration::from_secs(1));writer.execute_batch("ROLLBACK").unwrap();}
#[test]fn offset_group_isolation(){let p=fixture();let r=Reader::open(&p).unwrap();let mut a=q("steps",7);a.source=Some("Synthetic Watch".into());a.offset=Some(0);assert!(r.query(a).unwrap()["points"].as_array().unwrap().is_empty());}
#[test]fn sqlite_progress_deadline(){let p=fixture();let r=Reader::open(&p).unwrap();let t=Instant::now();r.c.progress_handler(1000,Some(move||t.elapsed()>Duration::from_millis(20)));let result=r.c.query_row("WITH RECURSIVE n(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM n WHERE x<100000000) SELECT sum(x) FROM n",[],|r|r.get::<_,i64>(0));assert!(result.is_err());assert!(t.elapsed()<Duration::from_secs(1));}
#[test]fn duplicate_projection_fails_closed(){let p=fixture();let c=Connection::open(&p).unwrap();c.execute("INSERT INTO states SELECT 'duplicate',body FROM states WHERE id='steps-20099'",[]).unwrap();drop(c);assert!(Reader::open(&p).is_err());}
#[test]fn wal_header_and_hardlink_fail_closed(){use std::io::{Seek,SeekFrom,Write};let p=fixture();let mut f=fs::OpenOptions::new().write(true).open(&p).unwrap();f.seek(SeekFrom::Start(18)).unwrap();f.write_all(&[2,2]).unwrap();drop(f);assert!(Reader::open(&p).is_err());let p=fixture();fs::hard_link(&p,p.with_file_name("extra-link.sqlite")).unwrap();assert!(Reader::open(&p).is_err());}
#[test]fn dto_bounds_and_no_json_fallback(){let p=fixture();let r=Reader::open(&p).unwrap();assert!(r.dispatch(tauri::ipc::InvokeBody::Json(json!({}))).is_err());assert!(r.dispatch(tauri::ipc::InvokeBody::Raw(vec![b' ';4097])).is_err());for end in [-1,47482]{let mut a=q("steps",7);a.end_day=Some(end);assert!(r.query(a).is_err());}let mut a=q("steps",7);a.group_page=1001;assert!(r.query(a).is_err());let mut a=q("steps",7);a.source=Some("X".repeat(641));a.offset=Some(480);assert!(r.query(a).is_err());}
