use super::*;
use std::sync::{Arc,Mutex,atomic::{AtomicUsize,Ordering}};
static NEXT:AtomicUsize=AtomicUsize::new(0);
fn store()->Store{Store::open(&PathBuf::from(ROOT).join(format!("synthetic/view-{}-{}.sqlite",std::process::id(),NEXT.fetch_add(1,Ordering::SeqCst)))).unwrap()}
fn request()->Vec<u8>{json!({"version":2,"operation":"health_view","payload":{"metric":"sleep","days":7}}).to_string().into_bytes()}
struct NoModel;impl crate::model_port::ModelPort for NoModel{fn generate(&mut self,_:&str,_:&[u8])->R<crate::model_port::ModelResponse>{panic!("auxiliary view must not call ModelPort")}}
#[test]fn auxiliary_does_not_write_or_use_model(){let mut s=store();s.connect_source().unwrap();let db=PathBuf::from(s.c.path().unwrap());let health=crate::health_source::path(&s.fixture()).unwrap();let before=fs::read(&db).unwrap();let source_before=fs::read(&health).unwrap();let s=Arc::new(Mutex::new(s));let v=crate::host_gateway::dispatch_with_port(&s,"get_today",&request(),&mut NoModel).unwrap();assert_eq!(v["metric"],"sleep");assert_eq!(fs::read(db).unwrap(),before);assert_eq!(fs::read(health).unwrap(),source_before);}
#[test]fn existing_health_authorization_required_including_synthetic(){let mut s=store();s.connect_source().unwrap();let mut source=get(&s.c,"sources","health-demo").unwrap().unwrap();source["authorized"]=json!(false);put(&s.c,"sources","health-demo",&source).unwrap();assert_eq!(s.health_view(&request()).unwrap_err().code,"source_not_authorized");source["authorized"]=json!(true);put(&s.c,"sources","health-demo",&source).unwrap();assert!(s.health_view(&request()).is_ok());s.source_connected=false;assert_eq!(s.health_view(&request()).unwrap_err().code,"source_not_authorized");}
#[test]fn invalid_request_rejected_before_missing_source_open(){let mut s=store();s.source_connected=true;let invalid=json!({"version":2,"operation":"health_view","payload":{"metric":"heart","days":7}}).to_string();assert_eq!(s.health_view(invalid.as_bytes()).unwrap_err().code,"readonly_request_rejected");assert!(s.health_view(&request()).is_err());}

#[test]fn imported_observation_spoof_does_not_expand_model_eligibility(){let s=store();let at=now();for kind in ["health_sample","health_batch","health_current_state"]{for eligible in [false,true]{let r=json!({"id":"raw-observation","kind":kind,"status":"active","domain":"work","modelEligible":eligible,"sourceId":"conversation"});assert!(!allowed(&s.c,&r,at).unwrap());}}let mut projection=json!({"kind":"source_projection","status":"active","domain":"health","sourceId":"health-demo"});assert!(allowed(&s.c,&projection,at).unwrap());projection["modelEligible"]=json!(false);assert!(!allowed(&s.c,&projection,at).unwrap());}
