import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {actionCandidate} from '../../candidate/ui/action_domain.js';
import {ControlledConversation} from '../../candidate/ui/controlled_conversation.js';
const action={id:'synthetic-arrangement',version:1,confirmedContent:'我明天先买合成材料',status:'planned',createdAt:1,updatedAt:1,confirmationRawRef:'synthetic-original',sourceRefs:[],basisStatus:'valid'};
const cases=[['unsupported-create','我明天先买合成材料。',[],null],['unsupported-cancel','先不买合成材料了。',[action],null],['supported-create','我明天先整理合成材料。',[],'create'],['canonical-cancel','合成材料先不做了。',[action],'cancel'],['negative-new-intent','我不打算买合成材料。',[],null],['quoted','他说“先不买合成材料了”。',[action],null],['ambiguous-target','做完了。',[action,{...action,id:'synthetic-second',confirmedContent:'我明天先整理合成报告'}],'clarify']];
const results=[];
for(const [name,raw,actions,expected] of cases){const p={id:'synthetic-packet',raw,actions,suggestions:[],revision:1,expiresAt:Date.now()+100000};const candidate=actionCandidate(p);assert.equal(candidate?.operation??null,expected);const calls=[];let actionEvents=0;const repo={invoke:async(command,r)=>{calls.push(r.operation);if(r.operation==='draft_turn')return {};if(r.operation==='prepare_action_turn')return p;if(r.operation==='commit_action_turn'){if(r.payload.candidate.operation!=='clarify')actionEvents++;return {status:'committed'}}if(r.operation==='prepare_turn')return {id:'synthetic-legacy',domain:'ambiguous',question:raw,now:Date.now(),questions:[],snapshot:{}};if(r.operation==='read_local')return {credentialState:'stored',modelId:'synthetic-model',enabled:true};if(r.operation==='prepare_disclosure')return {previewId:'synthetic-preview'};throw Error('Unexpected operation '+r.operation)}};
 const app=new ControlledConversation(repo);const out=await app.prepare({requestId:'synthetic-request',turnId:'synthetic-turn',revision:1,text:raw},()=>true);results.push({name,syntheticRaw:raw,candidateOperation:candidate?.operation??null,applicationResult:out.kind,actionEvents,ordinaryDisclosurePath:calls.includes('prepare_disclosure'),calls});}
assert(results[0].ordinaryDisclosurePath&&results[0].actionEvents===0);assert(results[1].ordinaryDisclosurePath&&results[1].actionEvents===0);assert(results[2].actionEvents===1&&!results[2].ordinaryDisclosurePath);
const out={status:'confirmed_defect_reproduction_not_product_pass',cases:results,caseCount:results.length,realDataAccess:false,networkCalls:0,realAppAccess:false,note:'Immutable delivered JS plus synthetic Repository doubles; no database or provider process was opened.'};writeFileSync(new URL('../evidence/reproduction.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({reproduced:2,cases:results.length,networkCalls:0,realAppAccess:false}));
