import {test,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
import {DatabaseSync} from 'node:sqlite';
import {writeFileSync,symlinkSync,readFileSync} from 'node:fs';
import {Application,resolve,nextQuestion,makeModel,boundary,validRows,FixtureSource} from '../ui/core.js';
const root='/private/tmp/lifeos-p3-147-obsidian-source-v1';
const bin=root+'/initial-build-cache/debug/lifeos-p3-147';
let counter=0;const run=Date.now().toString(36);const active=[];
function repo(name='test'){
 const fixture=`test-${run}-${name}-${++counter}`;let child,queue;
 const start=()=>{queue=[];child=spawn(bin,['--repository-stdio',fixture],{env:{...process.env,TMPDIR:root+'/tmp',LIFEOS_P3_147_PROFILE:'synthetic'},stdio:['pipe','pipe','pipe']});child.stderr.on('data',d=>process.stderr.write(d));createInterface({input:child.stdout}).on('line',s=>{const cb=queue.shift();if(!cb)throw new Error('unexpected response');const v=JSON.parse(s);v.error?cb.reject(new Error(v.error.code)):cb.resolve(v.ok)});};start();
 const r={fixture,closed:false,invoke(ipc,request){return new Promise((resolve,reject)=>{queue.push({resolve,reject});child.stdin.write(JSON.stringify({ipc,request})+'\n')})},async restart(){child.stdin.end();await new Promise(ok=>child.on('exit',ok));start()},async close(){if(this.closed)return;this.closed=true;child.stdin.end();if(child.exitCode===null)await new Promise(ok=>child.on('exit',ok))}};active.push(r);return r;
}
afterEach(async()=>{for(const r of active)await r.close()});
const call=(r,ipc,operation,payload={})=>r.invoke(ipc,{version:2,operation,payload});
function markdown(version=1,content='合成项目：整理项目计划。'){return {sourceId:'obsidian-demo',externalId:'note',sourceType:'synthetic_markdown',mimeType:'text/markdown',version,content}}
const healthy=(version=1,hours=6)=>({sourceId:'health-demo',externalId:'sleep',sourceType:'synthetic_health',mimeType:'application/json',version,content:JSON.stringify({sleepHours:hours,start:Date.now()-8*3600000,end:Date.now()-1000,unit:'hours'})});
const stable=s=>JSON.stringify({...s,now:0});
async function setup(name){const r=repo(name),a=new Application(r);await a.snapshot();return [r,a]}
test('original bytes, persisted draft, once-only save and lost acknowledgement retry',async()=>{const [r,a]=await setup('save');const text='  合成：准备项目计划。  ';await a.draft(text,'draft-1','daily','turn-1',1);const now=Date.now();const opts={requestId:'request-1',conversationId:'daily',turnId:'turn-1',draftId:'draft-1',now};const first=await a.save(text,opts);await r.restart();const second=await a.save(text,opts);assert.deepEqual(first,second);const s=await a.snapshot();assert.equal(s.records.length,1);assert.equal(s.records[0].text,text);assert.equal(s.records[0].contentHash.length,64);assert.equal(s.drafts[0].status,'committed');await assert.rejects(a.save('改了内容',opts),/idempotency_conflict/);await r.close()});
test('same text with distinct intentional turns is not deduplicated',async()=>{const [r,a]=await setup('repeat');await a.save('合成重复表达');await a.save('合成重复表达');assert.equal((await a.snapshot()).records.length,2);await r.close()});
test('transaction failure before receipt leaves original/state/audit unchanged and draft recoverable',async()=>{const [r,a]=await setup('fail');await a.draft('合成计划','draft-fail','daily','turn-fail',1);const before=await a.snapshot();const db=new DatabaseSync(root+'/'+r.fixture+'.sqlite');db.exec("CREATE TRIGGER fail_receipt BEFORE INSERT ON requests BEGIN SELECT RAISE(ABORT,'test failure'); END;");await assert.rejects(a.save('合成计划',{requestId:'failed',conversationId:'daily',turnId:'turn-fail',draftId:'draft-fail'}),/database_unavailable/);assert.equal(stable(await a.snapshot()),stable(before));db.exec('DROP TRIGGER fail_receipt');db.close();await r.restart();assert.equal((await a.snapshot()).drafts[0].text,'合成计划');await r.close()});
test('invalid input rejects before mutation and arbitrary roots/profile cannot be selected',async()=>{const [r,a]=await setup('deny');const before=await a.snapshot();await assert.rejects(a.save('   '),/text_rejected/);await assert.rejects(call(r,'capture_record','save',{requestId:'bad',root:'/not-a-root'}),/unknown_field/);await assert.rejects(call(r,'unapproved','execute'),/unavailable/);await assert.rejects(call(r,'resolve_request_context','confirm_send'),/offline_contract_rejected/);await assert.rejects(call(r,'save_ai_provider_credential','save'),/offline_capability_denied/);await assert.rejects(call(r,'test_ai_provider_connection','test'),/offline_capability_denied/);assert.equal(stable(await a.snapshot()),stable(before));await r.close()});
test('one valuable clarification, irrelevant or already available evidence produces no question',async()=>{const [r,a]=await setup('question');assert.equal(await a.question(),null);await a.save('合成：整理项目计划。');const q=await a.question();assert.equal(q.missingField,'available_time');assert.equal((await a.snapshot()).questions.length,1);await a.question();assert.equal((await a.snapshot()).questions.length,1);await a.save('今天时间 10 分钟',{intent:'answer',questionId:q.id});assert.equal(await a.question(),null);const p=await a.prepare();const o=await a.generate(p);assert.match(o.body.text,/10 分钟/);assert.equal((await a.snapshot()).memories.length,0);await r.restart();assert.equal(await a.question(),null);await r.close()});
for(const decision of ['ignore','refuse','defer'])test('persistent question decision '+decision,async()=>{const [r,a]=await setup(decision);await a.save('合成：项目计划');const q=await a.question();await a.decide(q,decision,decision==='defer'?Date.now()+3600000:undefined);await r.restart();assert.equal(await a.question(),null);assert.equal((await a.snapshot()).records.length,1);await r.close()});
test('silence makes no state or implicit confirmation; deferred time can reopen same gap',async()=>{const [r,a]=await setup('silence');await a.save('合成计划');const q=await a.question();const before=await a.snapshot();await r.restart();assert.equal(stable(await a.snapshot()),stable(before));await a.decide(q,'defer',Date.now()+80);await new Promise(ok=>setTimeout(ok,110));const again=await a.question();assert.equal(again.id,q.id);assert.equal(again.status,'pending');assert.equal(again.generation,3);await r.close()});
test('memory confirmation is single explicit intent, inference/source is not confirmation',async()=>{const [r,a]=await setup('memory');await a.save('我希望每次只做一件事',{intent:'remember'});await a.importSource(markdown());await a.generate(await a.prepare());const s=await a.snapshot();assert.equal(s.memories.length,1);assert.equal(s.memories[0].confirmed,true);assert.equal(s.derivations[0].confirmed,false);await assert.rejects(a.save('第二条长期偏好',{intent:'remember'}),/durable_memory_limit_rejected/);await r.close()});
test('correction is atomic, preserves provenance and invalidates only dependent projections',async()=>{const [r,a]=await setup('correct');await a.save('今天时间 10 分钟');await a.importSource(healthy());let s=await a.snapshot();const health=s.states.find(v=>v.domain==='health');const work=s.records.find(v=>v.domain==='work');const oldpacket=await a.prepare();await a.generate(oldpacket);const db=new DatabaseSync(root+'/'+r.fixture+'.sqlite');db.exec("CREATE TRIGGER fail_correct BEFORE INSERT ON requests WHEN NEW.operation='correct' BEGIN SELECT RAISE(ABORT,'test failure'); END;");const before=await a.snapshot();await assert.rejects(a.correct(work,'今天时间 20 分钟'),/database_unavailable/);assert.equal(stable(await a.snapshot()),stable(before));db.exec('DROP TRIGGER fail_correct');db.close();await a.correct(work,'今天时间 20 分钟');s=await a.snapshot();assert.equal(s.records.find(v=>v.id===work.id).status,'corrected');assert.equal(s.records.find(v=>v.supersedes===work.id).text,'今天时间 20 分钟');assert.deepEqual(s.states.find(v=>v.id===health.id),health);assert.equal(s.derivations[0].status,'stale');await assert.rejects(a.generate(oldpacket),/context_stale/);const o=await a.generate(await a.prepare());assert.match(o.body.text,/20 分钟/);await r.close()});
test('source version deduplication, identity isolation, version conflict and rollback',async()=>{const [r,a]=await setup('source');const item=markdown();await a.importSource(item);await a.importSource(item);assert.equal((await a.snapshot()).records.length,1);await assert.rejects(a.importSource(markdown(1,'不同内容')),/source_version_conflict/);await a.importSource(markdown(2,'合成项目第二版本'));assert.equal(validRows(await a.snapshot()).length,1);await assert.rejects(a.importSource(markdown(1)),/source_version_stale/);await a.importSource(healthy());const s=await a.snapshot();assert.equal(s.records.length,3);assert.equal(new Set(s.records.map(v=>v.id)).size,3);assert.equal(s.memories.length,0);await r.close()});
test('revocation excludes all historical packets and model switching never revives source',async()=>{const [r,a]=await setup('revoke');await a.importSource(markdown());await a.importSource(healthy());const packet=await a.prepare();await a.generate(packet);let s=await a.snapshot();await a.revoke(s.sources.find(v=>v.id==='health-demo'));await assert.rejects(a.generate(packet,'OfflineB'),/context_stale/);await r.restart();s=await a.snapshot();const fresh=await a.prepare();assert(fresh.included.every(v=>v.domain!=='health'));await a.generate(fresh,'OfflineB');assert.equal((await a.snapshot()).sources.find(v=>v.id==='health-demo').authorized,false);await assert.rejects(a.importSource(healthy(2)),/authorization_rejected/);await r.close()});
test('required layers budget is prewrite atomic, exact boundary and optional pruning',async()=>{const [r,a]=await setup('budget');await a.save('长'.repeat(180));const before=await a.snapshot();await assert.rejects(a.prepare('person',{budget:32}),/context_budget_rejected/);assert.equal(stable(await a.snapshot()),stable(before));const cost=8+Math.ceil(180/4);const exact=await a.prepare('person',{budget:cost});assert.equal(exact.usedBudget,cost);await assert.rejects(a.prepare('person',{budget:cost-1}),/context_budget_rejected/);await r.close()});
test('expired evidence and request-local removal do not become current facts',async()=>{const [r,a]=await setup('expiry');await a.save('今天时间 10 分钟');const s=await a.snapshot();const p=resolve(s,'person',{now:Date.now()+2*86400000});assert.equal(p.inputRefs.length,0);const removed=resolve(s,'person',{removedRefs:[s.records[0].id]});assert.equal(removed.inputRefs.length,0);assert.equal(s.records[0].status,'active');await r.close()});
test('two actual offline adapters across process restarts preserve all authority and feedback',async()=>{const [r,a]=await setup('adapters');await a.save('今天时间 15 分钟');const output=await a.generate(await a.prepare(),'OfflineA');await a.feedback(output.id,'reject');let s=await a.snapshot();const authority=JSON.stringify([s.records,s.states,s.memories,s.feedback,s.sources]);await r.restart();const b=await a.generate(await a.prepare(),'OfflineB');assert.match(b.body.text,/纠正/);s=await a.snapshot();assert.equal(JSON.stringify([s.records,s.states,s.memories,s.feedback,s.sources]),authority);await r.restart();await a.generate(await a.prepare(),'OfflineA');s=await a.snapshot();assert.equal(JSON.stringify([s.records,s.states,s.memories,s.feedback,s.sources]),authority);assert.equal(boundary.network.calls,0);assert.equal(boundary.credential.calls,0);await r.close()});
test('health parser rejects missing/invalid units, field inflation, future times and unsupported sync',async()=>{const [r,a]=await setup('health');const before=await a.snapshot();for(const content of ['{}','not json',JSON.stringify({sleepHours:26,start:1,end:2,unit:'hours'}),JSON.stringify({sleepHours:6,start:1,end:2,unit:'minutes'}),JSON.stringify({sleepHours:6,start:1,end:2,unit:'hours',pain:false})])await assert.rejects(a.importSource({...healthy(),content}),/health_payload_rejected/);assert.equal(stable(await a.snapshot()),stable(before));const source=new FixtureSource([markdown()]);assert.deepEqual(source.discover(),['note']);assert.throws(()=>source.sync(),/unsupported/);await r.close()});
test('database symlink is rejected before opening and sentinel stays unchanged',async()=>{const fixture=`test-${run}-link`;const sentinel=root+'/fixtures/sentinel-'+run;writeFileSync(sentinel,'sentinel');symlinkSync(sentinel,root+'/'+fixture+'.sqlite');const p=spawn(bin,['--repository-stdio',fixture],{stdio:['pipe','pipe','pipe']});const answer=new Promise(ok=>p.stdout.once('data',d=>ok(JSON.parse(d))));p.stdin.end(JSON.stringify({ipc:'get_today',request:{version:2,operation:'snapshot',payload:{}}})+'\n');assert.equal((await answer).error.code,'database_path_rejected');assert.equal(readFileSync(sentinel,'utf8'),'sentinel')});
test('authorized Markdown answers a relevant gap without asking again',async()=>{const [r,a]=await setup('source-answer');await a.importSource(markdown(1,'今天时间 12 分钟'));assert.equal(await a.question(),null);const o=await a.generate(await a.prepare());assert.match(o.body.text,/12 分钟/);await r.close()});
test('a fresh state makes superseded facts and their model packets unavailable',async()=>{const [r,a]=await setup('new-state');await a.save('今天时间 10 分钟');const old=await a.prepare();await a.generate(old);await a.save('今天时间 20 分钟');await assert.rejects(a.generate(old),/context_stale/);const fresh=await a.prepare();assert(fresh.included.every(v=>!v.text.includes('10 分钟')));await r.close()});
test('renderer cannot forge packet content or state projection while retaining valid refs',async()=>{const [r,a]=await setup('tamper');await a.save('今天时间 10 分钟');let s=await a.snapshot();const packet=resolve(s,'person');packet.included[0].text='伪造事实';await assert.rejects(call(r,'assemble_global_ai_context','local_prepare',{requestId:'tamper-1',expectedGeneration:s.revision,packet}),/packet_rejected/);assert.equal((await a.snapshot()).packets.length,0);await r.close()});
test('correction commits its draft and restart does not resurrect that pending edit',async()=>{const [r,a]=await setup('correct-draft');await a.save('今天时间 10 分钟');let s=await a.snapshot();await a.draft('今天时间 18 分钟','edit-draft','daily','edit-turn',1,'edit-request',Date.now());await a.correct(s.records[0],'今天时间 18 分钟',Date.now(),'edit-draft');await r.restart();assert.equal((await a.snapshot()).drafts.find(v=>v.id==='edit-draft').status,'committed');await r.close()});
test('production secret code stays byte-exact but unlinked; original catalog and 20 IPC plus approved five stay visible',()=>{const base=new URL('../',import.meta.url);const main=readFileSync(new URL('src/main.rs',base),'utf8');const repoCode=readFileSync(new URL('src/repository.rs',base),'utf8');assert(!/mod (secure_credentials|deepseek);/.test(main));assert(!/Keychain|TcpStream|reqwest|load_api_key/.test(repoCode));const handlers=main.slice(main.indexOf('generate_handler![')).split(']')[0];assert.equal(handlers.split(',').map(s=>s.trim()).filter(Boolean).length,25);for(const name of ['connect_source_directory','control_source_job','get_source_status','authorize_source_target','get_source_evidence'])assert(handlers.includes(name));for(const f of ['secure_credentials.rs','deepseek.rs'])assert.equal(readFileSync(new URL('src/'+f,base),'utf8'),readFileSync(new URL('../../baseline/src/'+f,import.meta.url),'utf8'));const ui=readFileSync(new URL('application/ui.ts',base),'utf8');for(const label of ['OpenAI','Anthropic','Google Gemini','DeepSeek','Kimi','OpenRouter','其他 OpenAI-compatible 服务','自定义兼容接口','Ollama','LM Studio','OpenAI-compatible 本地接口','自定义本地服务','Today','Me','Contexts','Memory','Settings','Global AI'])assert(ui.includes(label),label);assert(!/fetch\(|XMLHttpRequest|WebSocket/.test(ui));});
test('PM counterexample: nonexistent or unrelated feedback does not affect a pure packet or output',async()=>{const [r,a]=await setup('fb-pure');await a.save('今天时间 15 分钟');const s=await a.snapshot();const baseline=resolve(s,'work');const polluted=structuredClone(s);polluted.feedback=[{targetId:'unrelated-old-output',decision:'reject'}];const p=resolve(polluted,'work');assert.deepEqual(p.feedback,[]);assert.equal(makeModel('OfflineA').generate(p).text,makeModel('OfflineA').generate(baseline).text);await r.close()});
test('feedback requires entire current target basis, removed or domain-excluded refs leave unrelated result unchanged across restart',async()=>{const [r,a]=await setup('fb-basis');await a.save('今天时间 15 分钟');await a.importSource(healthy());const target=await a.generate(await a.prepare());await a.feedback(target.id,'reject');let p=await a.prepare();assert.equal(p.feedback.length,1);assert.match((await a.generate(p)).body.text,/纠正/);for(let i=0;i<2;i++){const s=await a.snapshot();const clean={...s,feedback:[]};p=await a.prepare('work');assert.deepEqual(p.feedback,[]);assert.equal((await a.generate(p)).body.text,makeModel('OfflineA').generate(resolve(clean,'work')).text);const health=s.records.find(v=>v.domain==='health');const removed=await a.prepare('person',{removedRefs:[health.id]});assert.deepEqual(removed.feedback,[]);await r.restart()}await r.close()});
test('forged feedback packets are rejected by repository before packet audit or receipt writes',async()=>{const [r,a]=await setup('fb-forge');await a.save('今天时间 10 分钟');const target=await a.generate(await a.prepare());await a.feedback(target.id,'reject');const s=await a.snapshot();for(const feedback of [[{targetId:'nonexistent',decision:'reject'}],[{targetId:target.id,decision:'correct'}],[],[{targetId:target.id,decision:'reject',extra:true}]]){const packet=resolve(s,'person');packet.feedback=feedback;await assert.rejects(call(r,'assemble_global_ai_context','local_prepare',{requestId:crypto.randomUUID(),expectedGeneration:s.revision,packet}),/feedback_scope_rejected/);assert.equal(stable(await a.snapshot()),stable(s))}await r.restart();assert.equal((await a.prepare()).feedback.length,1);await r.close()});
test('revoked, expired and replaced target basis cannot carry feedback into fresh or stale packets',async()=>{for(const mode of ['revoke','expire','replace']){const [r,a]=await setup('fb-'+mode);await a.save('今天时间 10 分钟');await a.importSource(healthy());const target=await a.generate(await a.prepare());await a.feedback(target.id,'correct');const old=await a.prepare();assert.equal(old.feedback.length,1);let s=await a.snapshot();if(mode==='revoke')await a.revoke(s.sources.find(v=>v.id==='health-demo'));if(mode==='replace')await a.correct(s.records.find(v=>v.domain==='work'),'今天时间 12 分钟');if(mode==='expire'){const db=new DatabaseSync(root+'/'+r.fixture+'.sqlite');db.prepare("UPDATE records SET body=json_set(body,'$.validUntil',?) WHERE id=?").run(BigInt(Date.now()-1),s.records.find(v=>v.domain==='health').id);db.close()}await assert.rejects(a.generate(old),/context_stale/);await r.restart();s=await a.snapshot();const fresh=await a.prepare();assert.deepEqual(fresh.feedback,[]);assert.equal((await a.generate(fresh)).body.text,makeModel('OfflineA').generate(resolve({...s,feedback:[]},'person')).text);await r.close()}});
test('type-changing or unparseable corrections reject atomically and keep draft original state and unrelated output after restart',async()=>{const [r,a]=await setup('correct-type');await a.save('今天时间 10 分钟');await a.save('睡眠 7 小时');const s=await a.snapshot();const work=s.records.find(v=>v.domain==='work'),health=s.records.find(v=>v.domain==='health');const oldpacket=await a.prepare();const originalOutput=await a.generate(oldpacket);for(const [record,text] of [[work,'睡眠 6 小时'],[work,'暂时不知道'],[health,'今天时间 6 分钟'],[health,'还不确定']]){const draftId=crypto.randomUUID();await a.draft(text,draftId,'daily',crypto.randomUUID(),1);const before=await a.snapshot();await assert.rejects(a.correct(record,text,Date.now(),draftId),/correction_type_rejected/);assert.equal(stable(await a.snapshot()),stable(before));await r.restart();assert.equal(stable(await a.snapshot()),stable(before));assert.equal((await a.generate(oldpacket)).body.text,originalOutput.body.text)}await r.close()});
test('correction repository derives type and value from text and rejects forged missing null or out-of-range values',async()=>{const [r,a]=await setup('correct-forge');await a.save('今天时间 10 分钟');const record=(await a.snapshot()).records[0];for(const [text,stateValue] of [['睡眠 6 小时',6],['无法解析',null],['今天时间 20 分钟',null],['今天时间 20 分钟',999],['今天时间 0 分钟',0]]){const before=await a.snapshot();await assert.rejects(call(r,'update_current_state','correct',{requestId:crypto.randomUUID(),id:record.id,expectedGeneration:1,observedAt:Date.now(),validUntil:Date.now()+86400000,text,stateValue}),/correction_type_rejected|state_value_rejected/);assert.equal(stable(await a.snapshot()),stable(before))}await r.close()});
test('same-type work and sleep corrections succeed, preserve unrelated projection, rollback on receipt failure and persist',async()=>{const [r,a]=await setup('correct-same');await a.save('今天时间 10 分钟');await a.save('睡眠 6 小时');let s=await a.snapshot();const health=s.records.find(v=>v.domain==='health'),workState=s.states.find(v=>v.domain==='work');const db=new DatabaseSync(root+'/'+r.fixture+'.sqlite');db.exec("CREATE TRIGGER closure_correct_fail BEFORE INSERT ON requests WHEN NEW.operation='correct' BEGIN SELECT RAISE(ABORT,'closure test'); END;");const before=await a.snapshot();await assert.rejects(a.correct(health,'睡眠 7.5 小时'),/database_unavailable/);assert.equal(stable(await a.snapshot()),stable(before));db.exec('DROP TRIGGER closure_correct_fail');db.close();await a.correct(health,'睡眠 7.5 小时');await r.restart();s=await a.snapshot();assert.deepEqual(s.states.find(v=>v.id===workState.id),workState);const sleep=s.states.find(v=>v.status==='active'&&v.domain==='health');assert.equal(sleep.stateKey,'sleep_hours');assert.equal(sleep.value,7.5);assert.equal(s.records.find(v=>v.id===health.id).status,'corrected');await r.close()});

test('approved source query feeds only bounded valid context, keeps configuration out, and disconnect survives replay and restart',async()=>{
 const [r,a]=await setup('source-context');
 await a.sourceCall('connect_source_directory',{requestId:'connect'});
 const until=Date.now()+30000;let source;
 while(Date.now()<until){source=(await a.sourceCall('get_source_status')).connectors[0];if(source.error)throw Error(source.error);if(source.scanComplete&&!source.pending)break;await new Promise(ok=>setTimeout(ok,50));}
 assert(source.scanComplete&&!source.pending);
 await a.save('今天时间 10 分钟');
 const packet=await a.prepareSources('项目计划');
 assert(packet.inputRefs.length<=8);assert(packet.included.some(r=>r.id.startsWith('seg:')));assert(packet.usedBudget<=packet.budget);assert(!JSON.stringify(packet).includes('CONFIG_CANARY'));
 const result=await a.generate(packet);assert(result.inputRefs.length>0);
 await a.sourceCall('control_source_job',{requestId:'disconnect',connectorId:'directory',expectedGeneration:source.grantGeneration,action:'disconnect'});
 await assert.rejects(a.generate(packet),/context_stale/);await r.restart();await assert.rejects(a.generate(packet),/context_stale/);
 const fresh=await a.prepareSources('项目计划');assert(!fresh.inputRefs.some(r=>r.id.startsWith('seg:')));assert((await a.snapshot()).records.every(r=>!r.sourceFile));await r.close();
});
