import {test} from 'node:test';
import assert from 'node:assert/strict';
import {ConversationFlow} from '../ui/conversation_flow.js';
import {SourceConversation} from '../ui/source_conversation.js';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
function setup(overrides={}){const calls=[],states=[];let packet;
const repo={open:async()=>{calls.push('open');return{}},ask:async d=>calls.push(['ask',d]),preview:async(t,x=[])=>{calls.push(['preview',t,x]);return packet={previewId:crypto.randomUUID(),turnId:t,revision:1,state:'ready',confirmationToken:'token',expiresAt:Date.now()+100000}},cancel:async p=>calls.push(['cancel',p.previewId]),send:async p=>{calls.push(['send',p]);return{state:'succeeded'}},call:async(c,o,p)=>{calls.push([c,o,p]);return packet},...overrides};
let flow;flow=new ConversationFlow(repo,()=>states.push(flow.phase),async()=>calls.push('reload'));return{flow,calls,states,repo}}
test('U01 startup once; recovery never replaces typing during deferred open',async()=>{const d=deferred();const x=setup({open:()=>d.promise});const a=x.flow.start(),b=x.flow.start();assert.equal(a,b);x.flow.edit('new typing');d.resolve({pendingDraft:{text:'old'}});await a;assert.equal(x.flow.draft.text,'new typing');assert.equal(x.flow.opened,true);await x.flow.start();assert.equal(x.calls.filter(c=>c==='reload').length,1);x.flow.dispose()});
test('U01 failure retains draft and only explicit retry opens',async()=>{let n=0;const x=setup({open:async()=>{if(!n++)throw{code:'database_unavailable'};return{}}});x.flow.edit('retain');await x.flow.start();assert.equal(x.flow.phase,'open-failed');assert.equal(n,1);assert.equal(x.flow.draft.text,'retain');await x.flow.start();assert.equal(n,2);assert.equal(x.flow.opened,true);x.flow.dispose()});
test('U02 local prepare does not send; exactly one explicit confirmation sends',async()=>{const x=setup();await x.flow.start();x.flow.edit('question');await x.flow.prepare();assert.equal(x.calls.filter(c=>c[0]==='send').length,0);assert(x.states.includes('preparing'));await Promise.all([x.flow.confirm(),x.flow.confirm()]);assert.equal(x.calls.filter(c=>c[0]==='send').length,1);assert.equal(x.flow.preview,null);x.flow.dispose()});
test('U03 editing while preparing discards returned confirmation and preserves new draft',async()=>{const d=deferred();const x=setup({ask:()=>d.promise});await x.flow.start();x.flow.edit('first');const old=x.flow.draft.draftId;const p=x.flow.prepare();x.flow.edit('second');d.resolve();await p;assert.notEqual(x.flow.draft.draftId,old);assert.equal(x.flow.draft.text,'second');assert.equal(x.flow.preview,null);await x.flow.confirm();assert.equal(x.calls.filter(c=>c[0]==='send').length,0);x.flow.dispose()});
test('U03 removed source gets new packet; edit and cancel revoke UI confirmation',async()=>{const x=setup();await x.flow.start();x.flow.edit('q');await x.flow.prepare();const old=x.flow.preview.previewId;await x.flow.prepareTurn('turn',['s1']);assert.notEqual(x.flow.preview.previewId,old);assert.deepEqual(x.calls.filter(c=>c[0]==='preview').at(-1)[2],['s1']);x.flow.edit('changed');assert.equal(x.flow.preview,null);await x.flow.confirm();assert.equal(x.calls.filter(c=>c[0]==='send').length,0);x.flow.dispose()});
test('U03 current backend stale/revoked packet refuses send',async()=>{const x=setup({call:async()=>({state:'stale',revision:2})});await x.flow.start();x.flow.edit('q');await x.flow.prepare();await x.flow.confirm();assert.equal(x.calls.filter(c=>c[0]==='send').length,0);assert.equal(x.flow.error.code,'preview_stale');x.flow.dispose()});
test('U03 expiry removes button without automatic retry',async()=>{const x=setup({preview:async()=>({state:'ready',previewId:'p',expiresAt:Date.now()+5})});await x.flow.start();x.flow.edit('q');await x.flow.prepare();await new Promise(r=>setTimeout(r,20));assert.equal(x.flow.preview,null);assert.equal(x.flow.error.code,'preview_expired');assert.equal(x.calls.filter(c=>c[0]==='send').length,0);x.flow.dispose()});
test('U02/U04 unknown result is visible and never resent or requiring feedback',async()=>{const x=setup({send:async()=>({state:'unknown',errorCode:'dispatch_outcome_unknown'})});await x.flow.start();x.flow.edit('q');await x.flow.prepare();await x.flow.confirm();assert.equal(x.flow.error.code,'dispatch_outcome_unknown');assert.equal(x.flow.preview,null);assert.equal(x.flow.busy,false);assert(!x.calls.some(c=>c[0]==='decide_understanding_feedback'));x.flow.dispose()});
test('U06 startup repository requests only existing conversation recovery, no credential/model/scan calls',async()=>{const calls=[];const repo=new SourceConversation({invoke:async(c,r)=>{calls.push([c,r]);return{turns:[]}}});const flow=new ConversationFlow(repo,()=>{},async()=>{await repo.read('source-chat');await repo.settings()});await flow.start();assert.deepEqual(calls.map(c=>c[1].operation),['open_conversation','read_conversation','read_settings']);assert.equal(calls[0][1].payload.conversationId,'source-chat');flow.dispose()});
