import {test} from 'node:test';import assert from 'node:assert/strict';
import {VoiceConsumer} from '../candidate/application/voice/consumer.ts';
import {voiceSettings,voiceStatus} from '../candidate/application/voice/settings.ts';
// CONTRACT FAKE ONLY. It is not the P3-159 production bridge or model understanding.
function fixture(){const events=[],ls={};let s={state:'capturing',sessionId:'s1',generation:1,policyRevision:1};const host={status:()=>s,canSubmit:()=>true,speak:async r=>{events.push(['speak',r])},stopPlayback:()=>events.push(['stop']),onFinal:f=>(ls.final=f,()=>delete ls.final),onInterrupted:f=>(ls.interrupted=f,()=>delete ls.interrupted),receipt:r=>events.push(['receipt',r]),failure:c=>events.push(['error',c])};const port={submitUserTurn:async t=>(events.push(['submit',t]),{turnId:t.turnId,status:'accepted',recordRef:{id:'r',revision:1}}),onAssistantTurn:()=>()=>{},onSpeechOutputRequest:f=>(ls.output=f,()=>delete ls.output),reportSpeechInterrupted:async e=>events.push(['interrupt',e])};return {events,host,port,ls,setStatus:x=>s=x};}
const turn={schemaVersion:'interaction-v1',turnId:'host-turn',conversationRef:{id:'c1',revision:1},text:'这个周末再说',origin:{kind:'voice',sessionId:'s1',segmentId:'seg1',asrRequestId:'asr1',language:'zh'},finalizedAt:'2026-09-12T00:00:00Z'};
const request={schemaVersion:'interaction-v1',requestId:'speech1',sessionId:'s1',sessionGeneration:1,assistantTurnRef:{id:'a1',revision:1},projectionRef:{id:'p1',revision:1},policyRevision:1,voice:'mimo_default',language:'zh-CN'};
test('final exact once; changed id and changed text cannot reuse segment',async()=>{const f=fixture(),c=new VoiceConsumer(f.port,f.host);await c.final(turn);await c.final(turn);await c.final({...turn,turnId:'new'});await c.final({...turn,text:'other'});assert.equal(f.events.filter(x=>x[0]==='submit').length,1);assert.equal(f.events.filter(x=>x[1]==='voice_segment_conflict').length,2);c.dispose();});
test('late conversation/session and revoked purpose denied',async()=>{const f=fixture(),c=new VoiceConsumer(f.port,f.host);await c.final({...turn,origin:{...turn.origin,sessionId:'old'}});f.host.canSubmit=()=>false;await c.final(turn);assert(!f.events.some(x=>x[0]==='submit'));});
test('unknown submit not retried after transport failure',async()=>{const f=fixture();let n=0;f.port.submitUserTurn=async()=>{n++;throw Error('synthetic failure');};const c=new VoiceConsumer(f.port,f.host);await c.final(turn);await c.final(turn);assert.equal(n,1);assert.equal(f.events.find(x=>x[0]==='receipt')[1].status,'unknown');});
test('interruption reports audio only; no business turn or semantic keyword matching',async()=>{const f=fixture(),c=new VoiceConsumer(f.port,f.host);await c.interrupted({schemaVersion:'interaction-v1',eventId:'i1',sessionId:'s1',sessionGeneration:1,speechRequestId:'speech1',assistantTurnRef:{id:'a1',revision:1},reason:'user_speech',occurredAt:'2026-09-12T00:00:00Z'});assert.deepEqual(f.events.map(x=>x[0]),['stop','interrupt']);});
test('output deduplicated; generation and unwoken output silent',async()=>{const f=fixture(),c=new VoiceConsumer(f.port,f.host);await c.output(request);await c.output(request);await c.output({...request,requestId:'stale',sessionGeneration:0});f.setStatus({state:'wake_listening',sessionId:null,generation:2,policyRevision:1});await c.output({...request,requestId:'late'});assert.equal(f.events.filter(x=>x[0]==='speak').length,1);c.dispose();assert.deepEqual(Object.keys(f.ls),[]);});
test('no AssistantTurn auto-speaking or partial submission subscription',()=>{const f=fixture(),c=new VoiceConsumer(f.port,f.host);assert.deepEqual(Object.keys(f.ls).sort(),['final','interrupted','output']);c.dispose();});
test('settings truthful, escaped, unavailable default and no key copy',()=>{const html=voiceSettings({enabled:false,asr:false,tts:false,sessionTurn:false,wakeWord:'<script>',keyConfigured:false,usageLabel:'0 次',available:false},{state:'disabled'});assert(!html.includes('<script>'));assert.equal((html.match(/type="checkbox"/g)||[]).length,4);assert.equal((html.match(/ disabled/g)||[]).length,4);assert(!html.includes('type="password"'));assert(!html.includes('checked'));assert(voiceStatus({state:'speaking'}).includes('停止朗读'));});
