import {test} from 'node:test';import assert from 'node:assert/strict';
import {settingsView,settingView,credentialMask} from '../candidate/ui/settings_view.js';
import {ControlledFlow} from '../candidate/ui/controlled_conversation.js';
import {SettingsActions,settingsError} from '../candidate/ui/settings_actions.js';
const cfg={primary:{mode:'cloud',providerId:'deepseek',modelLabel:''}};
function fixture(){let revision=0;const calls=[],state={revision:0,catalog:{revision:0,settings:null},provider:{profileRevision:1,credentialRevision:0,credentialState:'absent',connectionState:'not_tested',models:[],enabled:false}};const app={read:async()=>structuredClone({...state,revision}),saveCatalog:async c=>{calls.push('save');state.catalog={revision:1,settings:c};revision++;},saveCredential:async()=>{calls.push('credential');state.provider.credentialRevision++;state.provider.credentialState='stored';revision++;},testModels:async()=>{calls.push('test');state.provider.connectionState='succeeded';state.provider.models=['synthetic-model'];state.provider.testReceiptId='receipt-'+(++revision);return {state:'succeeded'};},selectModel:async m=>{calls.push('select');state.provider.modelId=m;revision++;return {state:'saved'};},setEnabled:async e=>{calls.push('enable');state.provider.enabled=e;revision++;}};const flow=new ControlledFlow(app,()=>{}),actions=new SettingsActions(flow,()=>{});return {calls,state,app,flow,actions};}
test('saving configuration and key does not test select or enable',async()=>{const f=fixture();await f.flow.start();const input={value:'fictional-key'};await f.actions.save('catalog',input,cfg);assert.deepEqual(f.calls,['save','credential']);assert.equal(input.value,'');assert.equal(f.state.provider.enabled,false);});
test('explicit four steps are possible without implicit transitions',async()=>{const f=fixture();await f.flow.start();await f.actions.save('credential',{value:'fictional-key'},null);await f.actions.lifecycle('test');assert.equal(f.state.provider.modelId,undefined);assert.equal(f.state.provider.enabled,false);await f.actions.lifecycle('select','synthetic-model');assert.equal(f.state.provider.enabled,false);await f.actions.lifecycle('enable');assert.equal(f.state.provider.enabled,true);assert.deepEqual(f.calls,['credential','test','select','enable']);});
test('failed key save preserves input and hides raw failure body',async()=>{const f=fixture();await f.flow.start();const input={value:'fictional-private-key'};f.app.saveCredential=async()=>{throw {code:'credential_unavailable',message:input.value}};await f.actions.save('credential',input,null);assert.equal(input.value,'fictional-private-key');assert.match(f.actions.notice,/credential_unavailable/);assert.ok(!f.actions.notice.includes(input.value));});
test('pending action ignores second click and retains newer input',async()=>{const f=fixture();await f.flow.start();let finish;f.app.saveCredential=()=>new Promise(r=>finish=r);const input={value:'fictional-key'},p=f.actions.save('credential',input,null);assert.equal(f.actions.busy,true);await f.actions.lifecycle('test');input.value='new-fictional-input';finish();await p;assert.equal(input.value,'new-fictional-input');assert.deepEqual(f.calls,[]);});
test('fixed mask never follows length or displays malformed tail',()=>{assert.equal(credentialMask('9876'),'••••9876');assert.equal(credentialMask('full-secret'),'••••');assert.equal(credentialMask(null),'••••');assert.equal(credentialMask(''),'••••');});
test('model dropdown starts unselected and enable unavailable after successful test',()=>{settingView.section='模型设置';settingView.mode='cloud';settingView.drafts.cloud={provider:'DeepSeek',model:''};const s={provider:{credentialState:'stored',maskedTail:'9876',connectionState:'succeeded',models:['synthetic-a','synthetic-b'],testReceiptId:'ui-new-receipt',enabled:false},catalog:{revision:0,settings:null}};let html=settingsView(s,String,()=> '');assert.ok(html.includes('••••9876'));assert.ok(!html.includes('输入模型 ID'));assert.ok(!html.includes('<datalist'));assert.equal(settingView.pendingModel,'');assert.match(html,/data-action="enable-model" disabled/);assert.match(html,/data-action="select-tested-model" disabled/);assert.ok(html.includes('测试并读取模型'));});
test('Local mode has no key input or cloud model options',()=>{settingView.mode='local';settingView.drafts.local={provider:'Ollama',model:''};const html=settingsView({catalog:{revision:0,settings:null},provider:{models:[],enabled:false}},String,()=> '');assert.ok(!html.includes('id="key"'));assert.ok(html.includes('Ollama'));assert.ok(!html.includes('<option >DeepSeek</option>'));});
test('unknown errors use a fixed message and timeout is not credential TTL',()=>{assert.ok(!settingsError({code:'private-secret',message:'private-secret'}).includes('private-secret'));assert.match(settingsError({code:'provider_timeout'}),/API Key 不会因此过期/);});
