use super::*;
use std::sync::atomic::{AtomicUsize,Ordering};
static N:AtomicUsize=AtomicUsize::new(0);
fn store()->Store{Store::open(&PathBuf::from(ROOT).join(format!("synthetic/test-{}-{}.sqlite",std::process::id(),N.fetch_add(1,Ordering::SeqCst)))).unwrap()}
fn call(s:&Store,op:&str,p:Value)->R<Value>{let cmd=match op{"draft_turn"=>"capture_record","conversation_snapshot"=>"get_context_recovery","clarification_decision"=>"decide_understanding_feedback","select_offline_adapter"=>"save_ai_provider_settings",_=>"resolve_request_context"};s.dispatch(cmd,json!({"version":4,"operation":op,"payload":p}).to_string().as_bytes())}
fn prepare(s:&Store,t:&str,q:&str)->Value{call(s,"draft_turn",json!({"requestId":format!("d:{t}"),"turnId":t,"revision":1,"text":q})).unwrap();call(s,"prepare_turn",json!({"requestId":format!("p:{t}"),"turnId":t,"expectedDraftRevision":1})).unwrap()}
fn rf(p:&Value,r:&Value)->Value{let src=p["snapshot"]["sources"].as_array().unwrap().iter().find(|s|s["id"]==r["sourceId"]).unwrap();json!({"id":r["id"],"version":r["version"],"authorizationGeneration":src["generation"]})}
fn payload(p:&Value)->Value{let refs=p["snapshot"]["records"].as_array().unwrap().iter().filter(|r|r["kind"]=="source_projection").take(3).map(|r|rf(p,r)).collect::<Vec<_>>();json!({"requestId":format!("c:{}",p["turnId"].as_str().unwrap()),"turnId":p["turnId"],"packetId":p["id"],"modelId":p["modelId"],"text":"合成演练 · 离线测试 A\n仅为测试回答。","inputRefs":refs})}
#[test]fn raw_duplicate_unknown_null_and_mode_rejected(){let s=store();for raw in [r#"{"version":4,"version":4,"operation":"conversation_snapshot","payload":{}}"#,r#"{"version":4,"operation":"draft_turn","payload":{"requestId":"x","turnId":"x","revision":1,"text":"x","authorized":true}}"#,r#"{"version":4,"operation":"conversation_snapshot","payload":null}"#]{assert!(s.dispatch("capture_record",raw.as_bytes()).is_err());}assert!(s.dispatch("get_context_recovery",&vec![b' ';16385]).is_err());assert!(s.dispatch("send_source_ai_request",b"{}").is_err());}
#[test]fn drafts_preserve_text_cas_and_idempotency(){let s=store();let p=json!({"requestId":"d","turnId":"t","revision":1,"text":" 原样保留 "});let a=call(&s,"draft_turn",p.clone()).unwrap();assert_eq!(a,call(&s,"draft_turn",p.clone()).unwrap());let mut bad=p.clone();bad["text"]=json!("other");assert_eq!(call(&s,"draft_turn",bad.clone()).unwrap_err().code,"idempotency_conflict");bad["requestId"]=json!("new");assert_eq!(call(&s,"draft_turn",bad).unwrap_err().code,"draft_revision_conflict");assert_eq!(call(&s,"conversation_snapshot",json!({})).unwrap()["pendingDraft"]["text"]," 原样保留 ");}
#[test]fn scoped_authorized_current_candidates(){let s=store();let work=prepare(&s,"work","帮我安排工作报告");assert!(work["snapshot"]["records"].as_array().unwrap().iter().all(|r|r["domain"]=="work"));let both=prepare(&s,"both","工作和健康怎么安排");assert!(both["snapshot"]["records"].as_array().unwrap().is_empty());let health=prepare(&s,"health","最近的睡眠记录如何");let rows=health["snapshot"]["records"].as_array().unwrap();assert!(!rows.iter().any(|r|r["id"]=="expired-health"||r["id"]=="denied-health"));assert!(rows.iter().any(|r|r["id"]=="sleep-unknown"&&r["value"].is_null()));let mut source=get(&s.c,"sources","health-demo").unwrap().unwrap();source["authorized"]=json!(false);put(&s.c,"sources","health-demo",&source).unwrap();let denied=prepare(&s,"denied","我的睡眠怎么样");assert!(denied["snapshot"]["records"].as_array().unwrap().is_empty());assert!(!call(&s,"conversation_snapshot",json!({})).unwrap()["memories"].as_array().unwrap().iter().any(|m|m["domain"]=="health"));}
#[test]fn duplicate_forged_generation_and_cross_domain_refs_rejected(){let s=store();let p=prepare(&s,"t","我的睡眠记录");let good=payload(&p);let mut bad=good.clone();bad["inputRefs"].as_array_mut().unwrap().push(good["inputRefs"][0].clone());assert_eq!(call(&s,"commit_turn",bad).unwrap_err().code,"reference_rejected");let mut bad=good.clone();bad["inputRefs"][0]["authorizationGeneration"]=json!(999);assert!(call(&s,"commit_turn",bad).is_err());let mut bad=good;bad["inputRefs"][0]["id"]=json!("work-report");assert!(call(&s,"commit_turn",bad).is_err());assert_eq!(s.c.query_row("SELECT count(*) FROM derivations",[],|r|r.get::<_,i64>(0)).unwrap(),0);}
#[test]fn preflight_and_commit_revalidate_authorization(){let s=store();let p=prepare(&s,"t","睡眠记录");let mut grant=get(&s.c,"sources","health-demo").unwrap().unwrap();grant["generation"]=json!(2);put(&s.c,"sources","health-demo",&grant).unwrap();assert_eq!(call(&s,"prepare_turn",json!({"requestId":"p2","turnId":"t","expectedDraftRevision":1})).unwrap_err().code,"context_stale");assert!(call(&s,"commit_turn",payload(&p)).is_err());}
#[test]fn draft_revision_and_adapter_baseline_revalidated(){let s=store();let p=prepare(&s,"t","安排工作");call(&s,"select_offline_adapter",json!({"requestId":"m","modelId":"OfflineB"})).unwrap();assert!(call(&s,"commit_turn",payload(&p)).is_err());let p=prepare(&s,"t2","安排工作");call(&s,"draft_turn",json!({"requestId":"edit","turnId":"t2","revision":2,"text":"新的问题"})).unwrap();assert!(call(&s,"commit_turn",payload(&p)).is_err());}
#[test]fn commit_atomic_once_and_same_turn_replay(){let s=store();let p=prepare(&s,"t","工作报告");let d=payload(&p);call(&s,"commit_turn",d.clone()).unwrap();call(&s,"commit_turn",d.clone()).unwrap();let mut replay=d.clone();replay["requestId"]=json!("second");call(&s,"commit_turn",replay).unwrap();assert_eq!(s.c.query_row("SELECT count(*) FROM derivations",[],|r|r.get::<_,i64>(0)).unwrap(),1);assert!(call(&s,"conversation_snapshot",json!({})).unwrap()["pendingDraft"].is_null());let mut bad=d;bad["requestId"]=json!("third");bad["text"]=json!("合成演练 · 其他");assert_eq!(call(&s,"commit_turn",bad).unwrap_err().code,"turn_conflict");}
#[test]fn cancel_before_and_after_commit_is_honest(){let s=store();let p=prepare(&s,"t","安排工作");call(&s,"cancel_turn",json!({"requestId":"cancel","turnId":"t"})).unwrap();assert!(call(&s,"commit_turn",payload(&p)).is_err());let p=prepare(&s,"u","工作报告");call(&s,"commit_turn",payload(&p)).unwrap();assert_eq!(call(&s,"cancel_turn",json!({"requestId":"cancel2","turnId":"u"})).unwrap()["status"],"completed");call(&s,"cancel_turn",json!({"requestId":"early","turnId":"v"})).unwrap();call(&s,"draft_turn",json!({"requestId":"d:v","turnId":"v","revision":1,"text":"安排工作"})).unwrap();assert!(call(&s,"prepare_turn",json!({"requestId":"p:v","turnId":"v","expectedDraftRevision":1})).is_err());}
#[test]fn clarification_ignore_defer_do_not_write_state(){for decision in ["ignore","defer"]{let s=store();let p=prepare(&s,"ask","怎么安排运动");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});call(&s,"commit_turn",d).unwrap();call(&s,"clarification_decision",json!({"requestId":"decision","questionId":"q:health:available_time","decision":decision})).unwrap();assert!(active_states(&s.c,now()).unwrap().is_empty());let p=prepare(&s,"again","怎么安排运动");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"clarification_suppressed");assert_eq!(list(&s.c,"memories",10).unwrap().len(),2);}}
#[test]fn reply_and_correction_preserve_history_and_invalidate_dependents(){let s=store();let p=prepare(&s,"ask","怎么安排运动");let mut d=payload(&p);d["clarification"]=json!({"field":"available_time"});call(&s,"commit_turn",d).unwrap();let p=prepare(&s,"reply","我有20分钟");let mut d=payload(&p);d["state"]=json!({"key":"available_time","value":20,"domain":"health"});d["answerTo"]=json!("q:health:available_time");call(&s,"commit_turn",d).unwrap();let p=prepare(&s,"use","今天怎么运动");let mut d=payload(&p);let raw=p["snapshot"]["records"].as_array().unwrap().iter().find(|r|r["id"]=="raw:reply").unwrap();d["inputRefs"].as_array_mut().unwrap().push(rf(&p,raw));call(&s,"commit_turn",d).unwrap();let p=prepare(&s,"fix","纠正，我只有5分钟");let mut d=payload(&p);d["state"]=json!({"key":"available_time","value":5,"domain":"health"});d["corrects"]=json!("state:reply");call(&s,"commit_turn",d).unwrap();assert_eq!(get(&s.c,"records","raw:reply").unwrap().unwrap()["text"],"我有20分钟");assert_eq!(get(&s.c,"states","state:reply").unwrap().unwrap()["status"],"superseded");assert_eq!(get(&s.c,"derivations","answer:use").unwrap().unwrap()["status"],"stale");assert_eq!(active_states(&s.c,now()).unwrap()[0]["value"],5.0);assert_eq!(list(&s.c,"memories",10).unwrap().len(),2);}
#[test]fn arbitrary_state_and_question_binding_rejected(){let s=store();let p=prepare(&s,"t","我有20分钟运动");let mut d=payload(&p);d["state"]=json!({"key":"available_time","value":200,"domain":"health"});assert_eq!(call(&s,"commit_turn",d.clone()).unwrap_err().code,"state_claim_rejected");d["state"]["value"]=json!(20);d["answerTo"]=json!("unrelated");assert!(call(&s,"commit_turn",d).is_err());}
#[test]fn self_report_does_not_replace_sensor_projection(){let s=store();let before=get(&s.c,"records","sleep-1").unwrap();let p=prepare(&s,"self","我睡了5小时");let mut d=payload(&p);d["state"]=json!({"key":"sleep_hours","value":5,"domain":"health"});call(&s,"commit_turn",d).unwrap();assert_eq!(get(&s.c,"records","sleep-1").unwrap(),before);assert_eq!(get(&s.c,"states","state:self").unwrap().unwrap()["identity"],"user_self_report");}
#[test]fn context_and_snapshot_budgets_are_enforced(){let s=store();let mut row=get(&s.c,"records","work-report").unwrap().unwrap();row["text"]=json!("x".repeat(4500));put(&s.c,"records","work-report",&row).unwrap();let p=prepare(&s,"big","工作报告");let d=payload(&p);assert_eq!(call(&s,"commit_turn",d).unwrap_err().code,"context_budget_rejected");row["text"]=json!("工作报告");put(&s.c,"records","work-report",&row).unwrap();for i in 0..35{let p=prepare(&s,&format!("t{i}"),"工作报告");call(&s,"commit_turn",payload(&p)).unwrap();}let snap=call(&s,"conversation_snapshot",json!({})).unwrap();assert!(snap["hasMore"].as_bool().unwrap());assert!(serde_json::to_vec(&snap).unwrap().len()<=32768);let count=snap["turns"].as_array().unwrap().iter().map(|t|1+t["refs"].as_array().unwrap().len()).sum::<usize>()+snap["states"].as_array().unwrap().len()+snap["memories"].as_array().unwrap().len()+snap["questions"].as_array().unwrap().len()+usize::from(!snap["pendingDraft"].is_null());assert!(count<=40);}
#[test]fn restart_and_adapter_switch_keep_assets(){let s=store();let p=prepare(&s,"t","工作报告");call(&s,"commit_turn",payload(&p)).unwrap();call(&s,"select_offline_adapter",json!({"requestId":"m","modelId":"OfflineB"})).unwrap();let path=s.c.path().unwrap().to_string();drop(s);let r=Store::open(Path::new(&path)).unwrap();let v=call(&r,"conversation_snapshot",json!({})).unwrap();assert_eq!(v["turns"].as_array().unwrap().len(),1);assert_eq!(v["modelId"],"OfflineB");assert_eq!(v["memories"].as_array().unwrap().len(),2);}
#[test]fn fixed_scope_only(){assert!(Store::open(Path::new("relative.sqlite")).is_err());}
#[test]fn historical_answer_hidden_when_any_health_input_becomes_unavailable(){let s=store();let p=prepare(&s,"t","睡眠记录");let d=payload(&p);call(&s,"commit_turn",d.clone()).unwrap();let key=d["inputRefs"][0]["id"].as_str().unwrap();let mut row=get(&s.c,"records",key).unwrap().unwrap();row["status"]=json!("revoked");put(&s.c,"records",key,&row).unwrap();let snap=call(&s,"conversation_snapshot",json!({})).unwrap();assert_eq!(snap["turns"][0]["status"],"unavailable");assert_ne!(snap["turns"][0]["answer"],d["text"]);assert!(!snap["turns"][0]["refs"].as_array().unwrap().iter().any(|r|r["id"]==key));}
