//! D0670 inherited purpose pools plus D0675 B cross-purpose actual POST ceiling.
use super::*;
impl Store{
 pub(super) fn v8_existing_online_budget(&self,c:&Connection,t:&Value,field:&str,phase:&str,wall:i64)->R<()>{
  let (turns,models)=match phase{"development"=>(8,16),"unseen"=>(4,8),_=>return Err(error("operation_batch_not_ready"))};
  let cap=match field{"turns"|"queries"=>turns,"models"=>models,_=>return Err(error("operation_rejected"))};
  let key=format!("coord8:budget:{phase}");let mut b=get(c,"sources",&key)?.ok_or_else(||error("operation_budget_history_unknown"))?;
  for (k,max) in [("turns",turns),("queries",turns),("models",models)]{if b[k].as_u64().is_none_or(|v|v>max){return Err(error("store_contract_rejected"))}}
  if field!="turns"&&t["budgetPhase"]!=phase{return Err(error("operation_rejected"))}
  let used=b[field].as_u64().unwrap();if used>=cap{return Err(error(match field{"models"=>"model_limit","queries"=>"query_limit",_=>"turn_limit"}))}
  // Caller holds the existing Store transaction. Both ledgers roll back together.
  if field=="models"{Self::proactive_online_budget_purpose(c,wall,None)?;}
  b[field]=json!(used+1);put(c,"sources",&key,&b)
 }
}
#[cfg(test)]mod tests{
 use super::*;
 #[test]fn online_old_budget_unknown_is_not_new_allowance(){let s=super::super::super::controlled_tests::store();let t=json!({"budgetPhase":"development"});assert!(s.v8_existing_online_budget(&s.c,&t,"models","development",now()).is_err());assert!(get(&s.c,"sources","coord8:budget:development").unwrap().is_none());}
 #[test]fn online_old_and_proactive_pools_share_outer_count_without_transfer(){let s=super::super::super::controlled_tests::store();let wall=now();put(&s.c,"sources","coord8:budget:development",&json!({"turns":4,"queries":2,"models":6})).unwrap();let t=json!({"budgetPhase":"development"});for n in 0..47{s.tx(&format!("proactive-{n}"),"budget",&json!({}),|c|{Store::proactive_online_budget_purpose(c,wall,Some("development"))?;Ok(json!({}))}).unwrap();}s.tx("ordinary-last","budget",&json!({}),|c|{s.v8_existing_online_budget(c,&t,"models","development",wall)?;Ok(json!({}))}).unwrap();let b=get(&s.c,"sources","proactive:budget:B").unwrap().unwrap();assert_eq!(b["developmentReserved"],47);assert_eq!(b["ordinaryReserved"],1);assert_eq!(b["dayReserved"],48);assert_eq!(get(&s.c,"sources","coord8:budget:development").unwrap().unwrap()["models"],7);assert!(s.tx("ordinary-over","budget",&json!({}),|c|{s.v8_existing_online_budget(c,&t,"models","development",wall)?;Ok(json!({}))}).is_err());assert_eq!(get(&s.c,"sources","coord8:budget:development").unwrap().unwrap()["models"],7);assert!(s.v8_existing_online_budget(&s.c,&t,"models","unseen",wall).is_err());}
 #[test]fn online_local_turn_does_not_count_as_model_post(){let s=super::super::super::controlled_tests::store();put(&s.c,"sources","coord8:budget:development",&json!({"turns":4,"queries":2,"models":6})).unwrap();s.tx("turn-local","budget",&json!({}),|c|{s.v8_existing_online_budget(c,&json!({"budgetPhase":"development"}),"turns","development",now())?;Ok(json!({}))}).unwrap();assert!(get(&s.c,"sources","proactive:budget:B").unwrap().is_none());assert_eq!(get(&s.c,"sources","coord8:budget:development").unwrap().unwrap()["models"],6);}
 #[test]fn online_outer_last_daily_allowance_is_shared_under_concurrency(){let s=super::super::super::controlled_tests::store();let wall=now();put(&s.c,"sources","coord8:budget:development",&json!({"turns":4,"queries":2,"models":6})).unwrap();for _ in 0..47{Store::proactive_online_budget_purpose(&s.c,wall,Some("development")).unwrap();}let store=std::sync::Arc::new(std::sync::Mutex::new(s));let barrier=std::sync::Arc::new(std::sync::Barrier::new(2));let mut handles=vec![];for ordinary in [false,true]{let store=store.clone();let barrier=barrier.clone();handles.push(std::thread::spawn(move||{barrier.wait();let s=store.lock().unwrap();s.tx(&format!("outer-last-{ordinary}"),"budget",&json!({}),|c|{if ordinary{s.v8_existing_online_budget(c,&json!({"budgetPhase":"development"}),"models","development",wall)?}else{Store::proactive_online_budget_purpose(c,wall,Some("development"))?}Ok(json!({}))}).is_ok()}));}assert_eq!(handles.into_iter().filter_map(|h|h.join().ok()).filter(|v|*v).count(),1);let s=store.lock().unwrap();let b=get(&s.c,"sources","proactive:budget:B").unwrap().unwrap();assert_eq!(b["dayReserved"],48);assert_eq!(b["developmentReserved"].as_u64().unwrap()+b["ordinaryReserved"].as_u64().unwrap(),48);}
 #[test]fn online_outer_total_ceiling_includes_old_purpose_and_rolls_back(){let s=super::super::super::controlled_tests::store();let wall=now();put(&s.c,"sources","coord8:budget:development",&json!({"turns":4,"queries":2,"models":6})).unwrap();put(&s.c,"sources","proactive:budget:B",&json!({"kind":"proactive_online_budget","developmentReserved":96,"unseenReserved":40,"ordinaryReserved":7,"dayReserved":0,"nextReset":wall+10000,"highWater":wall})).unwrap();let t=json!({"budgetPhase":"development"});s.c.execute_batch("CREATE TEMP TRIGGER old_budget_fault BEFORE INSERT ON sources WHEN NEW.id='coord8:budget:development' BEGIN SELECT RAISE(ABORT,'A fault'); END;").unwrap();assert!(s.tx("outer-rollback","budget",&json!({}),|c|{s.v8_existing_online_budget(c,&t,"models","development",wall)?;Ok(json!({}))}).is_err());assert_eq!(get(&s.c,"sources","proactive:budget:B").unwrap().unwrap()["ordinaryReserved"],7);s.c.execute_batch("DROP TRIGGER old_budget_fault").unwrap();s.tx("outer-rollback","budget",&json!({}),|c|{s.v8_existing_online_budget(c,&t,"models","development",wall)?;Ok(json!({}))}).unwrap();assert!(Store::proactive_online_budget_purpose(&s.c,wall,Some("unseen")).is_err());assert_eq!(get(&s.c,"sources","proactive:budget:B").unwrap().unwrap()["ordinaryReserved"],8);}

}
