//! D0675 same local conversation/Action purpose. No real query capability.
use super::*;
#[cfg(test)]thread_local!{pub(super) static CONTRACT_MODE:std::cell::Cell<bool>=const{std::cell::Cell::new(false)};}
pub(super) fn active()->bool{#[cfg(test)]{if CONTRACT_MODE.with(|c|c.get()){return true}}crate::runtime_root::is_real()}
pub(super) fn validate(t:&Value,with_query:bool)->R<()>{if !active(){return Ok(())}if with_query||t["runtimeMode"]!="real"||t["budgetPhase"]!="existing-real"||t["fixtureGrant"]!=Value::Null||t["capabilityTargets"]!=json!({})||t["disclosure"]["capabilities"]!=json!([])||t["disclosure"]["queryResults"]!=json!([])||t.get("queryResult").is_some()||t.get("queryDescriptor").is_some()||t["queryCalls"]!=0||t["modelCalls"].as_u64().is_none_or(|n|n>1)||t["state"].as_str().is_none_or(|s|s.contains("second")||s.contains("query")){return Err(error("capability_unavailable"))}if t.get("sendPreview").is_some()&&t["sendPreview"]["phase"]!="first"{return Err(error("capability_unavailable"))}Ok(())}

#[cfg(test)]mod tests{
 use super::*;
 struct Mode;impl Mode{fn new()->Self{CONTRACT_MODE.with(|c|c.set(true));Self}}impl Drop for Mode{fn drop(&mut self){CONTRACT_MODE.with(|c|c.set(false));}}
 fn store()->Store{let s=super::super::super::controlled_tests::store();put(&s.c,"sources","operation-budget-C",&json!({"used":0,"development":0,"unseen":0})).unwrap();s}
 fn prepare(s:&Store,text:&str)->Value{let tid=uid("real-local-test");s.coordination_dispatch("capture_record","save_coordination_draft",json!({"requestId":uid("draft"),"turnId":tid,"expectedDraftRevision":0,"text":text})).unwrap();s.coordination_dispatch("resolve_request_context","prepare_coordination_turn",json!({"requestId":uid("prepare"),"turnId":tid,"expectedDraftRevision":1})).unwrap()["result"]["preview"].clone()}
 fn confirm(p:&Value)->Value{json!({"requestId":format!("confirm:{}",p["id"].as_str().unwrap()),"sendPreviewId":p["id"],"expectedRevision":p["revision"]})}
 #[test]fn real_local_existing_budget_missing_and_corrupt_never_default_to_zero(){let s=super::super::super::controlled_tests::store();assert!(super::super::super::operations::existing_c_budget(&s.c).is_err());for bad in [json!({}),json!({"used":9,"development":0,"unseen":0}),json!({"used":null,"development":0,"unseen":0})]{put(&s.c,"sources","operation-budget-C",&bad).unwrap();assert!(super::super::super::operations::reserve_existing_c_budget(&s.c).is_err());assert_eq!(get(&s.c,"sources","operation-budget-C").unwrap(),Some(bad));}}
 #[test]fn real_local_without_queries_supports_answer_and_action_with_shared_budget(){let _mode=Mode::new();let s=store();for (text,candidate) in [("请讨论报告",json!({"operation":"none"})),("请把整理报告记为安排",json!({"operation":"create","content":"整理报告","evidenceSpans":[{"messageRef":"current","start":0,"end":10}],"sourceRefs":[]}))]{let p=prepare(&s,text);let body:Value=serde_json::from_str(p["exactBody"].as_str().unwrap()).unwrap();assert!(body.get("max_tokens").is_none());assert_eq!(p["disclosure"]["capabilities"],json!([]));let V8Start::Send(plan)=s.v8_consume_with_loader(confirm(&p),||Ok(Zeroizing::new(b"A-fictional".to_vec()))).unwrap() else{panic!()};let out=s.v8_finish(&plan,Ok(ModelResponse{text:json!({"schemaVersion":8,"answerText":if candidate["operation"]=="none"{"讨论结果"}else{""},"candidate":candidate}).to_string(),usage:None})).unwrap();assert_eq!(out["state"],"committed");}assert_eq!(Store::actions(&s.c).unwrap().len(),1);assert_eq!(get(&s.c,"sources","operation-budget-C").unwrap().unwrap()["used"],2);assert!(get(&s.c,"sources","coord8:budget:offline").unwrap().is_none());}
 #[test]fn real_local_failed_send_reopen_never_refunds_or_sends_twice(){let _mode=Mode::new();let s=store();let p=prepare(&s,"讨论合成报告");let payload=confirm(&p);let V8Start::Send(plan)=s.v8_consume_with_loader(payload.clone(),||Ok(Zeroizing::new(b"A-fictional".to_vec()))).unwrap() else{panic!()};s.v8_finish(&plan,Err(error("provider_timeout"))).unwrap();let path=PathBuf::from(s.c.path().unwrap());drop(s);let s=Store::open(&path).unwrap();assert_eq!(get(&s.c,"sources","operation-budget-C").unwrap().unwrap()["used"],1);assert!(matches!(s.v8_consume_with_loader(payload,||panic!("must not reload key or POST")),Ok(V8Start::Replay(_))));}
 #[test]fn real_local_second_query_mode_and_fixture_state_spoof_rejected(){let _mode=Mode::new();let s=store();let p=prepare(&s,"讨论合成报告");let t=s.v8_get(p["turnRequestId"].as_str().unwrap()).unwrap();assert!(validate(&t,false).is_ok());assert!(validate(&t,true).is_err());for (field,value) in [("runtimeMode",json!("synthetic")),("budgetPhase",json!("offline")),("state",json!("second_ready")),("queryCalls",json!(1)),("fixtureGrant",json!({"read":true})),("queryResult",json!({"status":"success"}))]{let mut changed=t.clone();changed[field]=value;assert!(validate(&changed,false).is_err(),"{field}");}assert!(s.coordination_dispatch("resolve_request_context","prepare_coordination_second_send",json!({})).is_err());assert!(s.coordination_dispatch("resolve_request_context","confirm_coordination_query",json!({})).is_err());}
 #[test]fn real_local_shared_v7_primitive_and_v8_budget_compete_for_last_allowance(){let _mode=Mode::new();let s=store();let p=prepare(&s,"讨论报告");let t=s.v8_get(p["turnRequestId"].as_str().unwrap()).unwrap();put(&s.c,"sources","operation-budget-C",&json!({"used":7,"development":0,"unseen":0})).unwrap();let s=std::sync::Arc::new(std::sync::Mutex::new(s));let barrier=std::sync::Arc::new(std::sync::Barrier::new(2));let mut handles=vec![];for label in ["v7","v8"]{let s=s.clone();let barrier=barrier.clone();let t=t.clone();handles.push(std::thread::spawn(move||{let _mode=Mode::new();barrier.wait();let s=s.lock().unwrap();s.tx(&format!("last-{label}"),"existing-c-reservation",&json!({}),|c|{if label=="v7"{super::super::super::operations::reserve_existing_c_budget(c)?;}else{s.v8_budget(c,&t,"models")?;}Ok(json!({"reserved":true}))}).is_ok()}));}assert_eq!(handles.into_iter().filter_map(|h|h.join().ok()).filter(|v|*v).count(),1);assert_eq!(get(&s.lock().unwrap().c,"sources","operation-budget-C").unwrap().unwrap()["used"],8);}
 #[test]fn real_local_old_synthetic_receipt_cannot_replay_resume_or_project(){let _mode=Mode::new();let s=store();let p=prepare(&s,"讨论合成报告");let payload=confirm(&p);let V8Start::Send(plan)=s.v8_consume_with_loader(payload.clone(),||Ok(Zeroizing::new(b"A-fictional".to_vec()))).unwrap()else{panic!()};s.v8_finish(&plan,Err(error("provider_timeout"))).unwrap();let tid=p["turnRequestId"].as_str().unwrap();let mut t=s.v8_get(tid).unwrap();t["runtimeMode"]=json!("synthetic");put(&s.c,"packets",&turn_key(tid),&t).unwrap();assert!(s.v8_consume_with_loader(payload,||panic!("must reject before credential")).is_err());assert!(s.coordination_dispatch("get_context_recovery","coordination_turn_status",json!({"turnRequestId":tid})).is_err());assert!(s.coordination_dispatch("get_context_recovery","coordination_snapshot",json!({"offset":0,"limit":20})).is_err());assert!(s.coordination_dispatch("resolve_request_context","resume_coordination_turn",json!({"requestId":uid("resume"),"turnRequestId":tid,"expectedTurnRevision":t["revision"]})).is_err());}

}
