//! v6 synthetic Action Repository Adapter. Domain decisions are checked again at the storage boundary.
use super::*;
use std::collections::BTreeMap;
#[derive(Deserialize)]#[serde(rename_all="camelCase",deny_unknown_fields)]struct ActionCommit{request_id:String,turn_id:String,packet_id:String,expected_draft_revision:u64,candidate:Value,model_id:String}
#[derive(Deserialize)]#[serde(deny_unknown_fields)]struct Page{offset:usize}
fn rows(c:&Connection,t:&str,kind:&str)->R<Vec<Value>>{let mut st=c.prepare(&format!("SELECT body FROM {t} WHERE json_extract(body,'$.kind')=?1 ORDER BY rowid"))?;let strings=st.query_map([kind],|r|r.get::<_,String>(0))?.collect::<Result<Vec<_>,_>>()?;strings.into_iter().map(|s|serde_json::from_str(&s).map_err(|_|error("store_contract_rejected"))).collect()}
fn insert(c:&Connection,t:&str,key:&str,v:&Value)->R<()>{c.execute(&format!("INSERT INTO {t}(id,body) VALUES(?1,?2)"),params![key,v.to_string()])?;Ok(())}
fn clean(s:&str)->&str{s.trim().trim_end_matches(['。','！','!']).trim()}
fn forbidden(s:&str)->bool{s.contains(['“','”','"','「','」','『','』','\n','？','?'])||["如果","假如","假设","他说","她说","引用","是否","吗","可能","也许","举例","比如","例如","希望","据说","考虑","正在","已经","很累","还没","没做","不是","不打算","不想","不要"].iter().any(|w|s.contains(w))||(s.contains('不')&&!s.ends_with("先不做了"))}
fn clear_arrangement(s:&str)->bool{let mut s=s.strip_prefix("那我").or_else(||s.strip_prefix('我')).unwrap_or(s);for words in [&["明天","今天","接下来","打算"][..],&["下午","上午","晚上"][..],&["先","要"][..]]{for w in words{if let Some(t)=s.strip_prefix(w){s=t;break}}}["整理","完善","修复","核对","写","阅读","散步","走路","跑步","联系","完成","处理","复习","练习","做","开会","发送","发邮件"].iter().any(|v|s.starts_with(v))}
fn matched<'a>(s:&str,actions:&'a [Value])->Vec<&'a Value>{let s=clean(s);let s=s.strip_prefix('把').or_else(||s.strip_prefix('我')).unwrap_or(s);if s.is_empty()||["这个","那个","这件事"].contains(&s){return vec![]}actions.iter().filter(|a|{let content=a["confirmedContent"].as_str().unwrap_or("");content.contains(s)||s.contains(content)}).collect()}
fn legacy_candidate(p:&Value)->Option<Value>{let raw=p["raw"].as_str()?;let s=clean(raw);if s.is_empty()||forbidden(s){return None}let actions=p["actions"].as_array()?;let mut v=json!({"rawSpan":{"start":0,"end":raw.encode_utf16().count()},"sourceRefs":[]});
 let active:Vec<_>=actions.iter().filter(|a|a["status"]=="planned").collect();let current=if active.is_empty(){actions.iter().collect::<Vec<_>>()}else{active};let pending=&p["pending"];if !pending.is_null()&&["complete","cancel","adjust"].contains(&pending["intendedOperation"].as_str().unwrap_or("")){let targets:Vec<_>=actions.iter().filter(|a|pending["targetIds"].as_array().is_some_and(|ids|ids.contains(&a["id"]))).cloned().collect();let found=matched(s.strip_suffix("那个").unwrap_or(s),&targets);if found.len()==1{let a=found[0];v["operation"]=pending["intendedOperation"].clone();v["targetId"]=a["id"].clone();v["expectedVersion"]=pending["versions"][a["id"].as_str()?].clone();if let Some(content)=pending.get("content"){v["content"]=content.clone();}v["questionId"]=pending["id"].clone();return Some(v)}}
 let(mut op,mut target,mut content)=("","",String::new());for(suffix,operation)in[("做完了","complete"),("完成了","complete"),("先不做了","cancel"),("取消了","cancel")]{if let Some(t)=s.strip_suffix(suffix){op=operation;target=t;break}}
 if op.is_empty(){if let Some(t)=s.strip_prefix('把'){if let Some((a,b))=t.split_once("改成"){op="adjust";target=a;content=b.split("改成").next().unwrap().into();}else if let Some((a,b))=t.split_once("改到"){op="adjust";target=a;content=format!("{a}，{}",b.split("改到").next().unwrap());}}}
 if !op.is_empty(){let found=if target.is_empty()||["这个","那个","这件事"].contains(&target){if current.len()==1{vec![current[0]]}else{vec![]}}else{matched(target,actions)};if found.len()==1{v["operation"]=json!(op);v["targetId"]=found[0]["id"].clone();v["expectedVersion"]=found[0]["version"].clone();if op=="adjust"{v["content"]=json!(content);}return Some(v)}v["operation"]=json!("clarify");v["intendedOperation"]=json!(op);v["targetIds"]=json!(actions.iter().map(|a|a["id"].clone()).collect::<Vec<_>>());if !content.is_empty(){v["content"]=json!(content);}v["question"]=json!("你指的是哪件安排？请说出它的内容。");return Some(v)}
 if ["好了","这个"].contains(&s){v["operation"]=json!("clarify");v["intendedOperation"]=json!("unknown");v["targetIds"]=json!(actions.iter().map(|a|a["id"].clone()).collect::<Vec<_>>());v["question"]=json!("你指哪件事，想怎样调整它？");return Some(v)}
 if ["我明天","我今天","我接下来","我打算","那我明天","那我今天"].iter().any(|w|s.starts_with(w))&&!s.contains("可以")&&!s.contains("想聊"){
  if s.contains("这个")||s.contains("那个"){let suggestions=p["suggestions"].as_array()?;if suggestions.len()!=1{v["operation"]=json!("clarify");v["intendedOperation"]=json!("create");v["targetIds"]=json!([]);v["question"]=json!("你想记下哪件安排？请直接说出内容。");return Some(v)}let suggestion=&suggestions[0];v["operation"]=json!("create");v["content"]=json!(s.replacen("这个",suggestion["content"].as_str()?,1).replacen("那个",suggestion["content"].as_str()?,1));v["sourceRefs"]=suggestion["sourceRefs"].clone();return Some(v)}
  if s.encode_utf16().count()>4&&!s.ends_with('了')&&(!(s.starts_with("我今天")||s.starts_with("那我今天"))||s.contains('先')||s.contains('要'))&&clear_arrangement(s){v["operation"]=json!("create");v["content"]=json!(s);return Some(v)}
 }None
}
fn frame_body(s:&str)->Option<&str>{
 let text=s.strip_prefix("那").unwrap_or(s);if let Some(t)=text.strip_prefix('我'){for time in ["明天","今天","接下来"]{if let Some(mut b)=t.strip_prefix(time){for part in ["上午","下午","晚上"]{if let Some(v)=b.strip_prefix(part){b=v;break}}if let Some(b)=b.strip_prefix('先').or_else(||b.strip_prefix('要')){if !b.is_empty(){return Some(b)}}}}}
 s.strip_prefix("我打算").filter(|b|!b.is_empty())
}
fn subject(s:&str)->String{let s=clean(s);if let Some(b)=frame_body(s){return b.into()}let mut s=s.strip_prefix("那我").or_else(||s.strip_prefix('我')).unwrap_or(s);for t in ["明天","今天","接下来"]{if let Some(b)=s.strip_prefix(t){s=b;for part in ["上午","下午","晚上"]{if let Some(b)=s.strip_prefix(part){s=b;break}}break}}s.strip_prefix('先').or_else(||s.strip_prefix('要')).unwrap_or(s).into()}
fn candidate(p:&Value)->Option<Value>{
 let raw=p["raw"].as_str()?;let s=clean(raw);if s.is_empty()||s.contains(['“','”','"','「','」','『','』','?','？'])||["如果","假如","假设","他说","她说","引用","举例","比如","例如","是否","好吗","吗","怎么办","要不要"].iter().any(|w|s.contains(w)){return None}
 if s.contains(['，',',','；',';','\n'])||["可能","也许","考虑","还没决定","不确定","但是","但还"].iter().any(|w|s.contains(w)){return None}
 let withdrawal=s.strip_prefix('我').unwrap_or(s).strip_prefix("先不").and_then(|s|s.strip_suffix('了')).filter(|s|!s.is_empty());
 if withdrawal==Some("做"){return legacy_candidate(p)}
 let mut v=json!({"rawSpan":{"start":0,"end":raw.encode_utf16().count()},"sourceRefs":[]});
 if let Some(target)=withdrawal{let found:Vec<_>=p["actions"].as_array()?.iter().filter(|a|a["status"]=="planned"&&subject(a["confirmedContent"].as_str().unwrap_or(""))==target).collect();if found.len()==1{v["operation"]=json!("cancel");v["targetId"]=found[0]["id"].clone();v["expectedVersion"]=found[0]["version"].clone();return Some(v)}if found.len()>1{v["operation"]=json!("clarify");v["intendedOperation"]=json!("cancel");v["targetIds"]=json!(found.iter().map(|a|a["id"].clone()).collect::<Vec<_>>());v["question"]=json!("你指的是哪件已记下的安排？请说出包含时间的完整内容。");return Some(v)}return None}
 if let Some(body)=frame_body(s){if body.trim().is_empty()||body.starts_with(['不','没','未','别'])||body.ends_with('了')||["可以","想聊","正在","已经","很累"].iter().any(|w|body.contains(w)){return None}if s.contains("这个")||s.contains("那个"){return legacy_candidate(p)}v["operation"]=json!("create");v["content"]=json!(s);return Some(v)}
 legacy_candidate(p)
}
impl Store{
 fn action_refs_valid(c:&Connection,refs:&Value)->R<bool>{let a=refs.as_array().ok_or_else(||error("action_candidate_rejected"))?;for rf in a{let Some(r)=get(c,"records",rf["id"].as_str().unwrap_or(""))?else{return Ok(false)};if !allowed(c,&r,now())?||r["version"]!=rf["version"]||get(c,"sources",r["sourceId"].as_str().unwrap_or(""))?.is_none_or(|s|s["generation"]!=rf["authorizationGeneration"]){return Ok(false)}}Ok(true)}
 fn actions(c:&Connection)->R<Vec<Value>>{let mut map=BTreeMap::<String,Value>::new();for event in rows(c,"records","action_event")?{let a=&event["action"];let key=a["id"].as_str().ok_or_else(||error("store_contract_rejected"))?.to_string();let previous=map.get(&key).and_then(|a|a["version"].as_u64()).unwrap_or(0);if a["version"].as_u64()!=Some(previous+1)||event["previousVersion"].as_u64()!=Some(previous){return Err(error("store_contract_rejected"))}let mut a=a.clone();let mut history=map.get(&key).and_then(|old|old["historyRefs"].as_array()).cloned().unwrap_or_default();history.push(json!({"eventId":event["id"],"version":a["version"],"rawRef":event["rawRef"],"operation":event["operation"]}));a["historyRefs"]=json!(history);map.insert(key,a);}let mut out:Vec<_>=map.into_values().collect();for a in &mut out{a["basisStatus"]=json!(if Self::action_refs_valid(c,&a["sourceRefs"])?{"valid"}else{"needs_user_judgment"});}out.sort_by_key(|a|std::cmp::Reverse(a["updatedAt"].as_i64().unwrap_or(0)));Ok(out)}
 fn pending_action(c:&Connection)->R<Value>{Ok(rows(c,"questions","action_clarification")?.into_iter().last().filter(|q|q["status"]=="pending"&&q["expiresAt"].as_i64().unwrap_or(0)>now()).unwrap_or(Value::Null))}
 pub(super) fn action_dispatch(&self,command:&str,op:&str,p:Value)->R<Value>{crate::runtime_root::verify()?;Self::validate_existing_schema(&self.c)?;match(command,op){("resolve_request_context","prepare_action_turn")=>self.action_prepare(decode(p.clone())?,p),("resolve_request_context","commit_action_turn")=>self.action_commit(decode(p.clone())?,p),("get_context_recovery","action_snapshot")=>self.action_snapshot(decode(p)?),_=>Err(error("operation_rejected"))}}
 fn action_prepare(&self,d:Prepare,p:Value)->R<Value>{self.tx(&d.request_id,"prepare_action_turn",&p,|c|{let draft=get(c,"drafts",&format!("draft:{}",d.turn_id))?.ok_or_else(||error("draft_missing"))?;if draft["status"]!="pending"||draft["revision"]!=d.expected_draft_revision{return Err(error("draft_revision_conflict"))}if !enabled(c,"conversation")?{return Err(error("source_not_authorized"))}let actions=Self::actions(c)?;if actions.len()>128{return Err(error("action_context_limit"))}let mut suggestions=vec![];if let Some(answer)=rows(c,"derivations","health_conversation_answer")?.last(){if answer["status"]=="candidate"&&answer["createdAt"].as_i64().is_some_and(|at|now()-at<300000)&&Self::action_refs_valid(c,&answer["inputRefs"])?{for line in answer["text"].as_str().unwrap_or("").lines(){if let Some(s)=line.strip_prefix("建议："){let s=clean(s);if !s.is_empty()&&s.chars().count()<=200&&!forbidden(s){suggestions.push(json!({"content":s,"sourceRefs":answer["inputRefs"],"answerId":answer["id"]}));}}}}}
 let key=format!("action-packet:{}:{}",d.turn_id,d.expected_draft_revision);let revision:i64=c.query_row("SELECT revision FROM meta WHERE id=1",[],|r|r.get(0))?;let v=json!({"id":key,"kind":"action_packet","turnId":d.turn_id,"draftRevision":d.expected_draft_revision,"raw":draft["text"],"expiresAt":now()+300000,"actions":actions,"suggestions":suggestions,"pending":Self::pending_action(c)?,"revision":revision+1});if serde_json::to_vec(&v).unwrap().len()>32768{return Err(error("action_context_limit"))}insert(c,"packets",&key,&v)?;Ok(v)})}
 fn action_commit(&self,d:ActionCommit,p:Value)->R<Value>{self.tx(&d.request_id,"commit_action_turn",&p,|c|{
  if !["OfflineA","OfflineB"].contains(&d.model_id.as_str()){return Err(error("adapter_rejected"))}if !enabled(c,"conversation")?{return Err(error("source_not_authorized"))}
  let packet=get(c,"packets",&d.packet_id)?.ok_or_else(||error("action_context_stale"))?;let draft=get(c,"drafts",&format!("draft:{}",d.turn_id))?.ok_or_else(||error("draft_missing"))?;
  if packet["kind"]!="action_packet"||packet["turnId"]!=d.turn_id||packet["draftRevision"]!=d.expected_draft_revision||packet["expiresAt"].as_i64().unwrap_or(0)<=now(){return Err(error("action_context_stale"))}
  if draft["status"]!="pending"||draft["revision"]!=d.expected_draft_revision||draft["text"]!=packet["raw"]{return Err(error("draft_revision_conflict"))}
  let expected=candidate(&packet).ok_or_else(||error("action_candidate_rejected"))?;if expected!=d.candidate{return Err(error("action_candidate_rejected"))}let v=&d.candidate;let op=v["operation"].as_str().unwrap_or("");let current=Self::actions(c)?;
  if json!(current)!=packet["actions"]{return Err(error("action_version_conflict"))}
  if let Some(q)=v.get("questionId"){let pending=Self::pending_action(c)?;if pending.is_null()||pending["id"]!=*q||pending!=packet["pending"]{return Err(error("action_context_stale"))}}
  if !Self::action_refs_valid(c,&v["sourceRefs"])?{return Err(error("action_basis_stale"))}if op=="create"&&!packet["suggestions"].as_array().unwrap().is_empty()&&(packet["raw"].as_str().unwrap().contains("这个")||packet["raw"].as_str().unwrap().contains("那个")){for suggestion in packet["suggestions"].as_array().unwrap(){let a=get(c,"derivations",suggestion["answerId"].as_str().unwrap())?.ok_or_else(||error("action_basis_stale"))?;if a["status"]!="candidate"{return Err(error("action_basis_stale"))}}}
  let at=now();let raw_id=format!("action-raw:{}",d.turn_id);let raw=json!({"id":raw_id,"kind":"action_expression","schemaVersion":6,"text":draft["text"],"sourceId":"conversation","version":1,"status":"active","observedAt":at,"turnId":d.turn_id});
  let mut action=Value::Null;let reply;
  if op=="clarify"{let key=format!("action-question:{}",d.turn_id);let mut q=v.clone();q["id"]=json!(key);q["kind"]=json!("action_clarification");q["rawRef"]=json!(raw_id);q["status"]=json!("pending");q["expiresAt"]=json!(at+300000);q["versions"]=json!(current.iter().map(|a|(a["id"].as_str().unwrap().to_string(),a["version"].clone())).collect::<BTreeMap<_,_>>());insert(c,"questions",&key,&q)?;reply=format!("本地澄清：{}",v["question"].as_str().unwrap_or("请说明具体安排。"));}
  else {let old=current.iter().find(|a|a["id"]==v["targetId"]);if op!="create"{let a=old.ok_or_else(||error("action_candidate_rejected"))?;if a["version"]!=v["expectedVersion"]{return Err(error("action_version_conflict"))}if a["status"]!="planned"{return Err(error("action_terminal"))}if !["adjust","complete","cancel"].contains(&op){return Err(error("action_candidate_rejected"))}}
   let content=if op=="create"||op=="adjust"{v["content"].as_str().ok_or_else(||error("action_candidate_rejected"))?}else{old.unwrap()["confirmedContent"].as_str().unwrap()};text(content,4096)?;
   if op=="adjust"&&!Self::action_refs_valid(c,&old.unwrap()["sourceRefs"])?{return Err(error("action_basis_stale"))}
   let key=old.map(|a|a["id"].as_str().unwrap().to_string()).unwrap_or_else(||format!("action:{}",d.turn_id));let previous=old.and_then(|a|a["version"].as_u64()).unwrap_or(0);action=json!({"id":key,"version":previous+1,"confirmedContent":content,"status":match op{"complete"=>"completed","cancel"=>"cancelled",_=>"planned"},"createdAt":old.map(|a|a["createdAt"].clone()).unwrap_or(json!(at)),"updatedAt":at,"confirmationRawRef":raw_id,"sourceRefs":old.map(|a|a["sourceRefs"].clone()).unwrap_or(v["sourceRefs"].clone())});
   let event_id=format!("action-event:{}",d.turn_id);insert(c,"records",&event_id,&json!({"id":event_id,"schemaVersion":6,"kind":"action_event","previousVersion":previous,"operation":op,"rawRef":raw_id,"at":at,"action":action}))?;
   let f=format!("action-feedback:{}",d.turn_id);insert(c,"feedback",&f,&json!({"kind":"action_feedback","eventId":event_id,"rawRef":raw_id,"actionId":key,"operation":op,"at":at}))?;
   if let Some(qid)=v["questionId"].as_str(){let mut q=get(c,"questions",qid)?.unwrap();q["status"]=json!("answered");put(c,"questions",qid,&q)?;}
   reply=format!("本地记录：{}{}。",match op{"complete"=>"已完成：","cancel"=>"已取消：","adjust"=>"已调整为：",_=>"已记下："},content);
  }
  insert(c,"records",&raw_id,&raw)?;let answer_id=format!("action-answer:{}",d.turn_id);insert(c,"derivations",&answer_id,&json!({"id":answer_id,"kind":"action_answer","turnId":d.turn_id,"rawRef":raw_id,"text":reply,"createdAt":at,"modelId":d.model_id}))?;
  let mut draft=draft;draft["status"]=json!("committed");put(c,"drafts",&format!("draft:{}",d.turn_id),&draft)?;c.execute("INSERT INTO audit(event,ref,at) VALUES('action_turn_committed',?1,?2)",params![d.turn_id,at])?;
  Ok(json!({"status":"committed","action":action,"reply":reply}))
 })}
 fn action_snapshot(&self,p:Page)->R<Value>{let c=&self.c;if p.offset>100000{return Err(error("dto_rejected"))}if !enabled(c,"conversation")?{return Err(error("source_not_authorized"))}let actions=Self::actions(c)?;let total=actions.len();let focus=actions.iter().find(|a|a["status"]=="planned").cloned();let mut turns=vec![];for answer in rows(c,"derivations","action_answer")?.into_iter().rev().take(30){let raw=get(c,"records",answer["rawRef"].as_str().unwrap())?.ok_or_else(||error("store_contract_rejected"))?;turns.push(json!({"turnId":answer["turnId"],"text":raw["text"],"answer":answer["text"],"modelId":answer["modelId"],"status":"local","refs":[],"createdAt":answer["createdAt"]}));}turns.reverse();let revision:i64=c.query_row("SELECT revision FROM meta WHERE id=1",[],|r|r.get(0))?;let mut v=json!({"revision":revision,"actions":actions.into_iter().skip(p.offset).take(20).collect::<Vec<_>>(),"total":total,"hasMore":p.offset+20<total,"focus":focus,"turns":turns});while serde_json::to_vec(&v).unwrap().len()>32768{if !v["turns"].as_array().unwrap().is_empty(){v["turns"].as_array_mut().unwrap().remove(0);}else if v["actions"].as_array().unwrap().len()>1{v["actions"].as_array_mut().unwrap().pop();v["hasMore"]=json!(true);}else{return Err(error("response_budget_rejected"))}}Ok(v)}
}
