import {test} from 'node:test';import assert from 'node:assert/strict';
import {AppleImportController,appleImportView} from '../ui/apple_import.js';
import {healthView,appleHistory} from '../ui/health_view.js';import {resolve} from '../ui/core.js';
function fixture(handler){const calls=[];let refresh=0;const c=new AppleImportController(async(name,raw)=>{assert.equal(name,'import_apple_health_file');assert(raw instanceof Uint8Array);const r=JSON.parse(new TextDecoder().decode(raw));assert.equal(r.version,1);calls.push(r.payload);return handler(r.payload);},()=>{},async()=>{refresh++});return {c,calls,get refresh(){return refresh}}}
const complete={status:'completed',file:'demo.xml',inserted:3,duplicates:1,unsupported:2,failed:0,attachments:1,importedAt:1,unsupportedTypes:{Other:2}};
test('one file selection starts the sole raw IPC and status completes refresh',async()=>{const x=fixture(p=>p.action==='list'?{files:['demo.xml']}:p.action==='start'?{status:'running',file:p.file}:complete);await x.c.open();await x.c.choose('demo.xml');await x.c.poll();assert.deepEqual(x.calls,[{action:'list'},{action:'start',file:'demo.xml'},{action:'status'}]);assert.equal(x.refresh,1);assert.equal(x.c.state.picker,null);});
test('failed import remains visible and retry uses same file',async()=>{let tries=0;const x=fixture(p=>p.action==='start'?(++tries===1?Promise.reject({code:'health_file_changed'}):{status:'running',file:p.file}):complete);await x.c.choose('demo.xml');assert(appleImportView(x.c.state).includes('已有数据保留'));await x.c.choose(x.c.state.status.file);await x.c.poll();assert.equal(tries,2);assert.equal(x.c.state.status.status,'completed');});
test('starting or running cannot start another import',async()=>{let release;const wait=new Promise(r=>release=r);const x=fixture(()=>wait);const p=x.c.choose('first.xml');await x.c.choose('second.xml');await x.c.poll();assert.equal(x.calls.length,1);release({status:'running',file:'first.xml'});await p;await x.c.choose('third.xml');assert.equal(x.calls.length,1);});
test('duplicate restores original import time without claiming new samples',async()=>{const x=fixture(()=>({...complete,status:'duplicate',inserted:0,originalImport:true}));await x.c.restore();const html=appleImportView(x.c.state);for(const t of ['未重复写入','保留原导入时间','重复内容','非自动同步','不支持','失败 0'])assert(html.includes(t));});
test('HTML escaping applies to filename and unsupported types',()=>{const h=appleImportView({status:{...complete,file:'<img>',unsupportedTypes:{'<script>':1}},picker:['"<svg>']});assert(!h.includes('<script>'));assert(!h.includes('<img>'));assert(h.includes('&lt;svg&gt;'));});
test('unknown failed counts are not fabricated totals',()=>{const h=appleImportView({status:{status:'failed',code:'health_document_corrupt',file:'a.zip'}});assert(h.includes('文件失败 1'));assert(h.includes('无法确认的记录数量不作推测'));assert(!h.includes('undefined'));});
const snapshot={records:[{id:'batch',kind:'health_batch',protocol:'apple-file-v1',file:'demo.xml',status:'observed',modelEligible:false,inserted:1,duplicates:0,unsupported:1,receivedAt:1}],states:[{id:'state',kind:'health_current_state',protocol:'apple-file-v1',status:'observed',modelEligible:false,dayIndex:20000,metric:'steps',unit:'count',value:null,offsetMinutes:480,observedAt:1,receivedAt:2,sources:[{name:'Synthetic',value:null}],refs:[]}],sources:[],memories:[],feedback:[],derivations:[]};
test('Apple observation labels do not imply completeness, identity or revision',()=>{const h=healthView(snapshot,true);for(const t of ['查询覆盖未知','非完整日总量','未区分同名设备','暂无法可靠合并','内容去重不是样本修订证明','最新256条'])assert(h.includes(t),t);assert(!h.includes('undefined'));assert(appleHistory(snapshot).includes('demo.xml'));});
test('actual frontend resolver excludes Apple batches and states under all purposes',()=>{for(const purpose of ['person','health','work']){const r=resolve(snapshot,purpose);assert.equal(r.included.length,0);assert.equal(r.states.length,0);assert(!JSON.stringify(r).includes('demo.xml'));}});
