import assert from 'node:assert/strict';
import {test} from 'node:test';
import {SettingsActions,settingsError} from '../candidate/ui/settings_actions.js';
import {ControlledFlow} from '../candidate/ui/controlled_conversation.js';
import {settingsView} from '../candidate/ui/settings_view.js';
const cfg={primary:{mode:'cloud',providerId:'deepseek',modelLabel:'fictional-model'}};
function fixture(){
 const state={revision:0,catalog:{revision:0,settings:null},provider:{credentialState:'absent',credentialRevision:0}};
 const calls=[];
 const app={read:async()=>structuredClone(state),saveCatalog:async(c,r)=>{calls.push('catalog');assert.equal(r,state.catalog.revision);if(!c.primary.modelLabel)throw {code:'catalog_rejected'};state.catalog={revision:r+1,settings:c};state.revision++;},saveCredential:async(k,r)=>{calls.push('credential');if(r!==state.provider.credentialRevision)throw {code:'credential_revision_conflict'};if(k.length<8)throw {code:'credential_invalid'};state.provider.credentialRevision++;state.provider.credentialState='stored';state.revision++;},selectModel:async m=>{calls.push('model');state.provider.modelId=m;state.revision++;}};
 const flow=new ControlledFlow(app,()=>{});const actions=new SettingsActions(flow,()=>{});
 return {state,calls,app,flow,actions,input:{value:'fictional-only-secret'}};
}
test('primary save persists catalog and credential, clears only acknowledged input',async()=>{const f=fixture();await f.flow.start();await f.actions.save('catalog',f.input,cfg);assert.deepEqual(f.calls,['catalog','credential','model']);assert.equal(f.input.value,'');assert.equal(f.flow.snapshot.provider.credentialRevision,1);assert.match(f.actions.notice,/配置和 API Key 已保存/);});
test('standalone credential save works without catalog or model',async()=>{const f=fixture();await f.flow.start();await f.actions.save('credential',f.input,null);assert.deepEqual(f.calls,['credential']);assert.equal(f.state.catalog.settings,null);assert.equal(f.input.value,'');});
test('blank model rejects primary save and retains unsaved key',async()=>{const f=fixture();await f.flow.start();await f.actions.save('catalog',f.input,{primary:{...cfg.primary,modelLabel:''}});assert.deepEqual(f.calls,['catalog']);assert.equal(f.input.value,'fictional-only-secret');assert.match(f.actions.notice,/catalog_rejected/);});
test('catalog success with credential failure is honest and preserves input',async()=>{const f=fixture();await f.flow.start();f.app.saveCredential=async()=>{throw {code:'credential_unavailable',message:f.input.value}};await f.actions.save('catalog',f.input,cfg);assert.match(f.actions.notice,/配置已保存，后续保存未完成/);assert.match(f.actions.notice,/credential_unavailable/);assert.equal(f.input.value,'fictional-only-secret');assert.ok(!f.actions.notice.includes(f.input.value));});
test('post-save model failure reloads credential CAS without resaving secret',async()=>{const f=fixture();f.state.catalog.settings=cfg;await f.flow.start();f.app.selectModel=async()=>{throw {code:'model_rejected'}};await f.actions.save('credential',f.input,null);assert.equal(f.input.value,'');assert.match(f.actions.notice,/API Key 已保存，后续配置未完成/);assert.equal(f.flow.snapshot.provider.credentialRevision,1);assert.deepEqual(f.calls,['credential']);});
test('CAS failure refreshes metadata, keeps input and never automatically retries',async()=>{const f=fixture();await f.flow.start();f.state.provider.credentialRevision=3;f.state.revision=3;await f.actions.save('credential',f.input,null);assert.deepEqual(f.calls,['credential']);assert.equal(f.flow.snapshot.provider.credentialRevision,3);assert.equal(f.input.value,'fictional-only-secret');assert.match(f.actions.notice,/credential_revision_conflict/);await f.actions.save('credential',f.input,null);assert.equal(f.state.provider.credentialRevision,4);});
test('double click performs one mutation; user replacement draft survives acknowledgment',async()=>{const f=fixture();await f.flow.start();let finish;const save=f.app.saveCredential;f.app.saveCredential=async(...args)=>{await new Promise(r=>finish=r);return save(...args);};const pending=f.actions.save('credential',f.input,null);await f.actions.save('credential',f.input,null);f.input.value='new-fictional-draft';finish();await pending;assert.deepEqual(f.calls,['credential']);assert.equal(f.input.value,'new-fictional-draft');});
test('only allowlisted error codes appear; private messages and unknown codes are discarded',()=>{for(const code of ['credential_unavailable','runtime_target_rejected','database_path_rejected','credential_revision_conflict'])assert.ok(settingsError({code,message:'secret-canary'}).includes(code));assert.equal(settingsError({code:'secret-canary',message:'secret-canary'}),settingsError(null));assert.ok(!settingsError({code:'credential_unavailable',message:'secret-canary'}).includes('secret-canary'));});
test('catalog saved alone does not claim an existing credential',()=>{const f=fixture();f.state.catalog={revision:987,settings:cfg};let h=settingsView(f.state,String,()=>'', '',{busy:true,notice:'credential_unavailable'});assert.ok(h.includes('API Key 未保存或不可用'));assert.ok(!h.includes('API Key 已保存'));assert.match(h,/data-action="save-catalog" disabled/);assert.ok(h.includes('credential_unavailable'));});
