use super::*;
impl Store {
    pub(super) fn v8_commit(&self, t: &Value, response: Value, stage: &HostStage) -> R<Value> {
        let oid = t["operationId"].as_str().unwrap();
        let rid = format!("coord8:commit:{oid}");
        let payload = json!({"schemaVersion":8,"operationId":oid,"turnRequestId":t["turnRequestId"],"turnRevision":t["revision"],"candidate":response["candidate"],"basisVersions":t["queryResult"]["facts"].as_array().unwrap_or(&vec![]).iter().map(|f|json!({"ref":f["ref"],"version":f["sourceVersion"],"authorizationGeneration":t["fixtureGrant"]["generation"]})).collect::<Vec<_>>()});
        self.tx(&rid,"coord8_commit",&payload,|c|{let live=self.v8_get(t["turnRequestId"].as_str().unwrap())?;if live["revision"]!=t["revision"]||!["first_inflight","second_inflight"].contains(&live["state"].as_str().unwrap_or("")){return Err(error("revision_conflict"))}self.v8_check(t,t.get("queryResult").is_some())?;if get(c,"packets",&format!("coord8:committed:{}",t["turnId"].as_str().unwrap()))?.is_some(){return Err(error("idempotency_conflict"))}let mut cand=response["candidate"].clone();let mut op=cand["operation"].as_str().unwrap().to_string();let raw=t["question"].as_str().unwrap();
 // A current quoted statement cannot delegate execution to a source or third party.
 if !["none","clarify"].contains(&op.as_str())&&(raw.contains(['“','”','"','「','」'])||has(raw,&["他说","她说","引用","请解释","请说明"])) {cand=json!({"operation":"clarify","question":"这段内容是引用，还是你现在希望落实的安排？","targetRefs":[],"intent":"unknown"});op="clarify".into();}
 // Explicit current-user non-execution constraints override a model's apply claim.
 // This is a rejection guard, never a local sentence-to-action parser.
 let record_constraint=has(raw,&["只记录","仅记录","只记下","仅记下","不要执行","不执行安排","不要落实","先别执行","暂不执行","不要创建","不要修改","不要调整","不要取消","不要完成"]);
 let requests_action=["create","adjust","complete","cancel"].contains(&op.as_str())||(op=="conditional_action"&&cand["intent"]["kind"]=="apply_if_true");
 if record_constraint&&requests_action {cand=json!({"operation":"clarify","question":"你当前要求仅记录或暂不执行；本次候选与此不一致，安排未更改。","targetRefs":[],"intent":"unknown"});op="clarify".into();}
 let at=now();let raw_ref=format!("coord8:raw:{}",t["turnId"].as_str().unwrap());let mut action_cand=if ["create","adjust","complete","cancel"].contains(&op.as_str()){Some(cand.clone())}else{None};let mut condition=None;let mut truth="unknown";let mut reason="condition_unknown";
 if op=="conditional_action"{truth=evaluate(&cand["condition"],&t["queryResult"]["facts"])?;let apply=cand["intent"]["kind"]=="apply_if_true";reason=if !apply{"record_only"}else if truth=="false"{"condition_false"}else{"condition_unknown"};if truth=="true"&&apply{action_cand=Some(cand["consequence"].clone());}let previous=if let Some(r)=cand.get("priorConditionRef"){Some(&t["conditionMap"][r.as_str().unwrap()])}else{None};let cid=previous.map(|v|v["id"].as_str().unwrap().to_string()).unwrap_or_else(||format!("coord8:condition:{oid}"));let version=previous.map_or(1,|v|v["version"].as_u64().unwrap()+1);let mut rec=json!({"id":cid,"version":version,"kind":"condition_record","schemaVersion":8,"operationId":oid,"rawRef":raw_ref,"content":cand["content"],"condition":cand["condition"],"intent":cand["intent"],"consequence":cand["consequence"],"truth":truth,"status":if truth=="unknown"{"pending"}else{"evaluated"},"basis":cand["condition"]["atoms"].as_array().unwrap().iter().map(|a|{let f=t["queryResult"]["facts"].as_array().unwrap().iter().find(|f|f["ref"]==a["factRef"]).unwrap();json!({"factRef":f["ref"],"sourceRef":f["sourceRef"],"sourceVersion":f["sourceVersion"],"evaluatedAt":at})}).collect::<Vec<_>>(),"evaluatedAt":at,"effect":{"kind":"not_applied","reason":reason}});if let Some(old)=previous{rec["supersedes"]=old["id"].clone();}condition=Some(rec);}
 let mut applied=None;let mut topic_targets=vec![];let mut action_text=String::new();if let Some(ac)=action_cand{contract::action(t,&ac)?;let op=ac["operation"].as_str().unwrap();let old=if op=="create"{None}else{Some(&t["targetMap"][ac["targetRef"].as_str().unwrap()])};if let Some(a)=old{if !Self::action_refs_valid(c,&a["sourceRefs"])?{return Err(error("condition_basis_invalid"))}}let previous=old.map_or(0,|a|a["version"].as_u64().unwrap());let aid=old.map(|a|a["id"].as_str().unwrap().to_string()).unwrap_or_else(||format!("action:{oid}"));let content=if op=="create"||op=="adjust"{ac["content"].clone()}else{old.unwrap()["confirmedContent"].clone()};let mut refs=old.and_then(|a|a["sourceRefs"].as_array().cloned()).unwrap_or_default();if let Some(a)=ac["sourceRefs"].as_array(){for rf in a{let rf=rf.as_str().unwrap();let r=if let Some(r)=t["sourceMap"].get(rf){json!({"id":r["id"],"version":r["version"],"authorizationGeneration":get(c,"sources",r["sourceId"].as_str().unwrap())?.unwrap()["generation"]})}else{let qr=&t["queryResult"];let id=qr["sourceRef"].as_str().unwrap();put(c,"records",id,&json!({"id":id,"kind":"coord8_query_basis","schemaVersion":8,"sourceId":"conversation","version":1,"status":"active","validUntil":qr["validUntil"],"queryId":qr["queryId"]}))?;json!({"id":id,"version":1,"authorizationGeneration":t["conversationGeneration"]})};if !refs.contains(&r){refs.push(r);}}}if !Self::action_refs_valid(c,&json!(refs))?{return Err(error("condition_basis_invalid"))}let a=json!({"id":aid,"version":previous+1,"confirmedContent":content,"status":match op{"complete"=>"completed","cancel"=>"cancelled",_=>"planned"},"createdAt":old.map(|a|a["createdAt"].clone()).unwrap_or(json!(at)),"updatedAt":at,"confirmationRawRef":raw_ref,"sourceRefs":refs});let eid=format!("action-event:{oid}");put(c,"records",&eid,&json!({"id":eid,"kind":"action_event","schemaVersion":8,"operationId":oid,"previousVersion":previous,"operation":op,"rawRef":raw_ref,"at":at,"action":a}))?;put(c,"feedback",&format!("action-feedback:{oid}"),&json!({"kind":"action_feedback","schemaVersion":8,"operationId":oid,"eventId":eid,"rawRef":raw_ref,"actionId":aid,"operation":op,"at":at}))?;let effect=json!({"action":{"id":aid,"version":previous+1},"eventRef":eid,"operation":op});if let Some(rec)=&mut condition{rec["effect"]=json!({"kind":"action_applied","applied":effect});}applied=Some(effect);if a["status"]=="planned"{topic_targets.push(json!(aid));}action_text=format!("本地记录：{}{}。",match op{"adjust"=>"已调整为：","complete"=>"已完成：","cancel"=>"已取消：",_=>"已记下："},content.as_str().unwrap());}
 let (result,reply)=if let Some(rec)=condition{let cref=json!({"id":rec["id"],"version":rec["version"]});put(c,"records",&format!("coord8:condition-event:{oid}"),&json!({"id":format!("coord8:condition-event:{oid}"),"kind":"condition_event","schemaVersion":8,"operationId":oid,"rawRef":raw_ref,"condition":rec,"at":at}))?;if let Some(applied)=applied{(json!({"kind":"condition_and_action","businessChanged":true,"condition":cref,"truth":"true","applied":applied}),format!("条件依据已保存；{action_text}"))}else{(json!({"kind":"condition_only","businessChanged":true,"condition":cref,"truth":truth,"reason":reason}),format!("条件已记录；安排未更改。{}",match reason{"condition_false"=>"当前依据未满足条件，不推导相反安排。","record_only"=>"按你的意图仅记录。",_=>"条件仍待判断。"}))}}else if let Some(applied)=applied{(json!({"kind":"action","businessChanged":true,"applied":applied}),action_text)}else if op=="clarify"{let question=cand["question"].as_str().unwrap();(json!({"kind":"clarify","businessChanged":false,"question":question}),format!("本轮未更改安排。\n{question}"))}else{(json!({"kind":"none","businessChanged":false}),format!("本轮未更改安排。\n{}",response["answerText"].as_str().unwrap()))};
 let reply=reply.chars().take(2000).collect::<String>();
 put(c,"records",&raw_ref,&json!({"id":raw_ref,"kind":"operation_expression","schemaVersion":8,"text":t["question"],"sourceId":"conversation","version":1,"status":"active","observedAt":at,"turnId":t["turnId"],"domain":t["packet"]["domain"]}))?;{let v=t;let raw_id=&raw_ref;let turn=t["turnId"].as_str().unwrap();
  // Retain the pre-existing explicit numerical short-term state capability; never infer long-term memory.
  if op=="none"&&!super::super::operations::caution(v["question"].as_str().unwrap()){
   let raw=v["question"].as_str().unwrap();let domain=v["packet"]["domain"].as_str().unwrap();
   let state=if ["work","health"].contains(&domain)&&has(raw,&["我有","只有","有空","可用","能拿出","可以留出"]){quantity(raw,"分钟").filter(|n|*n>=1.0&&*n<=240.0&&n.fract()==0.0).map(|n|("available_time",n))}else if domain=="health"&&has(raw,&["我","自己"])&&has(raw,&["睡了","睡眠"]){quantity(raw,"小时").filter(|n|*n>=0.0&&*n<=24.0).map(|n|("sleep_hours",n))}else{None};
   if let Some((key,value))=state{for mut old in active_states(c,at)?.into_iter().filter(|s|s["domain"]==domain&&s["stateKey"]==key){old["status"]=json!("superseded");old["validUntil"]=json!(at);put(c,"states",old["id"].as_str().unwrap(),&old)?;Self::invalidate(c,old["rawId"].as_str().unwrap())?;}
    let sid=format!("state:{turn}");put(c,"states",&sid,&json!({"id":sid,"rawId":raw_id,"stateKey":key,"value":value,"domain":domain,"generation":1,"status":"active","observedAt":at,"validUntil":at+86400000,"identity":"user_statement"}))?;
   }
  }
}
 let receipt=json!({"operationId":oid,"turnRequestId":t["turnRequestId"],"turnId":t["turnId"],"state":"committed","committedAt":at,"reply":reply,"result":result});put(c,"derivations",&format!("coord8:answer:{oid}"),&json!({"id":format!("coord8:answer:{oid}"),"kind":"action_answer","schemaVersion":8,"operationId":oid,"turnId":t["turnId"],"rawRef":raw_ref,"text":reply,"createdAt":at,"modelId":t["modelId"]}))?;let mut draft=get(c,"drafts",&format!("draft:{}",t["turnId"].as_str().unwrap()))?.unwrap();draft["status"]=json!("committed");put(c,"drafts",draft["id"].as_str().unwrap(),&draft)?;put(c,"sources","coord8:topic",&json!({"targets":topic_targets,"turns":[t["turnId"]]}))?;let mut done=t.clone();self.v8_end_host(stage,&mut done)?;Self::v8_change(&mut done,"committed");done["receipt"]=receipt.clone();self.v8_put(&done)?;put(c,"packets",&format!("coord8:committed:{}",t["turnId"].as_str().unwrap()),&receipt)?;Ok(Self::v8_status(&done))})
    }
}
