use super::*;use std::sync::{Arc,Mutex,atomic::{AtomicUsize,Ordering}};use crate::model_port::{ModelPort,ModelResponse};
static NEXT:AtomicUsize=AtomicUsize::new(0);
pub(super) fn store()->Store{let mut s=Store::open(&PathBuf::from(ROOT).join(format!("synthetic/controlled-{}-{}.sqlite",std::process::id(),NEXT.fetch_add(1,Ordering::SeqCst)))).unwrap();s.connect_source().unwrap();s.controlled("save_ai_provider_settings","save_credential",json!({"requestId":"key","expectedCredentialRevision":0,"apiKey":"p152-secret-leak-canary"})).unwrap();ready(&s);s}
fn setting_action(s:&Store,op:&str,extra:Value)->R<Value>{let v=s.provider_view()?;let mut p=json!({"requestId":crate::conversation_store::uid("setting"),"expectedCredentialRevision":v["credentialRevision"],"expectedProfileRevision":v["profileRevision"],"expectedCatalogRevision":s.catalog()?["revision"],"expectedSettingsRevision":v["settingsRevision"]});if op!="test_models"{p["testReceiptId"]=v["testReceiptId"].clone();}for(k,v)in extra.as_object().unwrap(){p[k]=v.clone();}s.controlled("save_ai_provider_settings",op,p)}
fn ready(s:&Store){setting_action(s,"test_models",json!({})).unwrap();setting_action(s,"select_model",json!({"modelId":"user-chosen-synthetic"})).unwrap();setting_action(s,"set_enabled",json!({"enabled":true})).unwrap();}
fn preview(s:&Store,t:&str,q:&str)->Value{if s.provider_view().unwrap()["enabled"]!=true{ready(s);}let draft=json!({"requestId":format!("d-{t}"),"turnId":t,"revision":1,"text":q});s.draft(decode(draft.clone()).unwrap(),draft).unwrap();let p=json!({"requestId":format!("p-{t}"),"turnId":t,"expectedDraftRevision":1});let packet=s.prepare(decode(p.clone()).unwrap(),p).unwrap();let refs=packet["snapshot"]["records"].as_array().unwrap().iter().map(|r|json!({"id":r["id"],"version":r["version"],"authorizationGeneration":1})).collect::<Vec<_>>();s.controlled("resolve_request_context","prepare_disclosure",json!({"requestId":format!("v-{t}"),"turnId":t,"packetId":packet["id"],"modelId":"user-chosen-synthetic","inputRefs":refs})).unwrap()}
fn confirmation(v:&Value)->Value{json!({"requestId":format!("send-{}",v["turnId"].as_str().unwrap()),"previewId":v["previewId"],"expectedPreviewRevision":1,"confirmationToken":v["confirmationToken"]})}
fn send(s:&Arc<Mutex<Store>>,v:&Value,port:&mut dyn ModelPort)->R<Value>{crate::host_gateway::dispatch_with_port(s,"send_source_ai_request",json!({"version":5,"operation":"confirm_send","payload":confirmation(v)}).to_string().as_bytes(),port)}
struct Spy{calls:usize,body:String,reply:String}
impl Spy{fn new()->Self{Self{calls:0,body:String::new(),reply:"synthetic reply".into()}}}
impl ModelPort for Spy{fn generate(&mut self,b:&str,_:&[u8])->R<ModelResponse>{self.calls+=1;self.body=b.into();Ok(ModelResponse{text:self.reply.clone(),usage:None})}}
#[test]fn exact_preview_body_is_only_body_sent_and_duplicate_consumes_once(){let s=store();let v=preview(&s,"one","我的睡眠记录");let body:Value=serde_json::from_str(v["exactBody"].as_str().unwrap()).unwrap();assert_eq!(body["model"],v["modelId"]);assert_eq!(body["messages"].as_array().unwrap().len(),2);let user:Value=serde_json::from_str(body["messages"][1]["content"].as_str().unwrap()).unwrap();assert_eq!(user["items"],v["items"]);assert_eq!(user["question"],v["question"]);assert!(!v.to_string().contains("p152-secret-leak-canary"));let s=Arc::new(Mutex::new(s));let mut spy=Spy::new();assert_eq!(send(&s,&v,&mut spy).unwrap()["state"],"succeeded");assert_eq!(spy.body,v["exactBody"].as_str().unwrap());assert_eq!(send(&s,&v,&mut spy).unwrap()["state"],"succeeded");assert_eq!(spy.calls,1);}
#[test]fn stale_model_draft_source_or_credential_never_reaches_adapter(){for mutation in 0..4 {let s=store();let v=preview(&s,"one","我的睡眠记录");match mutation{0=>{setting_action(&s,"test_models",json!({})).unwrap();},1=>{let p=json!({"requestId":"edit","turnId":"one","revision":2,"text":"我的步数记录"});s.draft(decode(p.clone()).unwrap(),p).unwrap();},2=>{let mut src=get(&s.c,"sources","health-demo").unwrap().unwrap();src["authorized"]=json!(false);put(&s.c,"sources","health-demo",&src).unwrap();},_=>{s.controlled("save_ai_provider_settings","delete_credential",json!({"requestId":"delete","expectedCredentialRevision":1})).unwrap();}}let s=Arc::new(Mutex::new(s));let mut spy=Spy::new();assert!(send(&s,&v,&mut spy).is_err());assert_eq!(spy.calls,0);}}
#[test]fn readonly_health_source_bytes_unchanged_and_changes_invalidate_preview(){let s=store();let path=crate::health_source::path(&s.fixture()).unwrap();let before=std::fs::read(&path).unwrap();let v=preview(&s,"one","我的睡眠记录");assert_eq!(std::fs::read(&path).unwrap(),before);let c=Connection::open(&path).unwrap();c.execute("UPDATE states SET body=json_set(body,'$.value',123) WHERE id='sleep'",[]).unwrap();drop(c);let mut spy=Spy::new();assert!(send(&Arc::new(Mutex::new(s)),&v,&mut spy).is_err());assert_eq!(spy.calls,0);}
#[test]fn cancelled_preview_and_forged_body_are_rejected(){let s=store();let v=preview(&s,"one","睡眠记录");s.controlled("resolve_request_context","cancel_preview",json!({"requestId":"cancel","previewId":v["previewId"]})).unwrap();let mut spy=Spy::new();let s=Arc::new(Mutex::new(s));assert!(send(&s,&v,&mut spy).is_err());let mut p=confirmation(&v);p["exactBody"]=json!("forged secret body");assert!(s.lock().unwrap().consume(p).is_err());assert_eq!(spy.calls,0);}
#[test]fn remote_key_echo_is_never_persisted_or_returned(){let s=store();let v=preview(&s,"one","睡眠记录");let path=s.c.path().unwrap().to_string();let s=Arc::new(Mutex::new(s));let mut spy=Spy::new();spy.reply="p152-secret-leak-canary".into();let result=send(&s,&v,&mut spy).unwrap();assert_eq!(result["errorCode"],"provider_response_rejected");assert!(!result.to_string().contains(&spy.reply));let bytes=std::fs::read(path).unwrap();assert!(!bytes.windows(spy.reply.len()).any(|w|w==spy.reply.as_bytes()));}
#[test]fn restart_inflight_stays_unknown_and_never_resends(){let s=store();let v=preview(&s,"one","睡眠记录");assert!(matches!(s.consume(confirmation(&v)).unwrap(),Start::Send(_)));let path=s.c.path().unwrap().to_string();drop(s);let s=Store::open(Path::new(&path)).unwrap();let mut spy=Spy::new();let r=send(&Arc::new(Mutex::new(s)),&v,&mut spy).unwrap();assert_eq!(r["state"],"outcome_unknown");assert_eq!(spy.calls,0);}
#[test]fn cancel_after_handoff_does_not_claim_remote_retraction(){let s=store();let v=preview(&s,"one","睡眠记录");let Start::Send(plan)=s.consume(confirmation(&v)).unwrap() else{panic!()};let r=s.controlled("resolve_request_context","cancel_preview",json!({"requestId":"cancel","previewId":v["previewId"]})).unwrap();assert_eq!(r["state"],"cancel_requested_after_dispatch");let r=s.finish(&plan,Ok(ModelResponse{text:"late response".into(),usage:None})).unwrap();assert_eq!(r["state"],"cancelled_after_dispatch");assert!(get(&s.c,"derivations","answer:one").unwrap().is_none());}
#[test]fn future_or_wrong_metric_has_no_fabricated_health_projection(){let s=store();let v=preview(&s,"one","今天的睡眠记录");assert!(v["items"].as_array().unwrap().iter().all(|i|i["identity"]!="来源观察"));let v=preview(&s,"two","我的步数记录");assert!(v["items"].as_array().unwrap().iter().filter(|i|i["identity"]=="来源观察").all(|i|i["text"].as_str().unwrap().contains("步数")));}
#[test]fn expired_preview_or_client_supplied_body_cannot_be_confirmed(){let s=store();let v=preview(&s,"one","睡眠记录");let mut p=confirmation(&v);p["exactBody"]=json!("forged");assert!(s.consume(p).is_err());let key=v["previewId"].as_str().unwrap();let mut old=get(&s.c,"packets",key).unwrap().unwrap();old["expiresAt"]=json!(now()-1);put(&s.c,"packets",key,&old).unwrap();assert!(s.consume(confirmation(&v)).is_err());}
#[test]fn second_preview_replaces_confirmation_slot(){let s=store();let first=preview(&s,"one","睡眠记录");let second=s.controlled("resolve_request_context","prepare_disclosure",json!({"requestId":"fresh-preview","turnId":"one","packetId":"packet:one","modelId":"user-chosen-synthetic","inputRefs":first["inputRefs"]})).unwrap();assert_ne!(first["previewId"],second["previewId"]);assert!(s.consume(confirmation(&first)).is_err());assert!(matches!(s.consume(confirmation(&second)).unwrap(),Start::Send(_)));}
#[test]fn concurrent_duplicate_while_transport_owns_body_does_not_send_twice(){struct Waiting{started:std::sync::mpsc::Sender<()>,release:std::sync::mpsc::Receiver<()>}impl ModelPort for Waiting{fn generate(&mut self,_:&str,_:&[u8])->R<ModelResponse>{self.started.send(()).unwrap();self.release.recv().unwrap();Ok(ModelResponse{text:"synthetic delayed".into(),usage:None})}}
 let s=store();let v=preview(&s,"one","睡眠记录");let s=Arc::new(Mutex::new(s));let (started,ready)=std::sync::mpsc::channel();let(release,wait)=std::sync::mpsc::channel();let copy=s.clone();let preview=v.clone();let handle=std::thread::spawn(move||send(&copy,&preview,&mut Waiting{started,release:wait}));ready.recv().unwrap();let mut spy=Spy::new();assert_eq!(send(&s,&v,&mut spy).unwrap()["state"],"dispatching");assert_eq!(spy.calls,0);release.send(()).unwrap();assert_eq!(handle.join().unwrap().unwrap()["state"],"succeeded");}
#[test]fn second_store_instance_and_source_sidecar_fail_closed(){let s=store();assert!(Store::open(Path::new(s.c.path().unwrap())).is_err());let path=crate::health_source::path(&s.fixture()).unwrap();std::fs::OpenOptions::new().create_new(true).write(true).mode(0o600).open(PathBuf::from(format!("{}-journal",path.display()))).unwrap();assert!(crate::health_source::read(&s.fixture(),"睡眠记录").is_err());}

#[test]fn forged_confirmation_token_never_dispatches(){let s=store();let v=preview(&s,"token","睡眠记录");let mut forged=confirmation(&v);forged["confirmationToken"]=json!("forged-token");assert!(s.consume(forged).is_err());}
#[test]fn old_projection_invalidated_even_after_large_unrelated_history(){let s=store();preview(&s,"prior","睡眠记录");for i in 0..150{put(&s.c,"records",&format!("history-{i}"),&json!({"id":format!("history-{i}"),"kind":"health_conversation_expression","domain":"work","sourceId":"conversation","text":"synthetic history","status":"active","version":1})).unwrap();}s.refresh_source("今天的睡眠记录").unwrap();assert_eq!(get(&s.c,"records","health-source-sleep").unwrap().unwrap()["status"],"unavailable");}
#[test]fn unknown_estimated_and_multi_source_are_preserved_without_source_writes(){let s=store();let path=crate::health_source::path(&s.fixture()).unwrap();let c=Connection::open(&path).unwrap();c.execute("UPDATE states SET body=json_set(body,'$.value',NULL) WHERE id='sleep'",[]).unwrap();drop(c);let before=std::fs::read(&path).unwrap();let rows=crate::health_source::read(&s.fixture(),"睡眠记录").unwrap();assert!(rows[0]["value"].is_null());assert!(rows[0]["text"].as_str().unwrap().contains("未知，不当作零"));assert!(rows[0]["text"].as_str().unwrap().contains("不合并为总量"));let exercise=crate::health_source::read(&s.fixture(),"运动").unwrap();assert!(exercise.iter().any(|r|r["estimated"]==true&&r["text"].as_str().unwrap().contains("估算")));assert_eq!(std::fs::read(path).unwrap(),before);}

#[test]fn real_initial_state_contains_no_synthetic_personal_rows(){let s=store();for table in TABLES{s.c.execute(&format!("DELETE FROM {table}"),[]).unwrap();}Store::seed_real(&s.c).unwrap();assert!(list(&s.c,"records",10).unwrap().is_empty());assert!(list(&s.c,"memories",10).unwrap().is_empty());assert!(list(&s.c,"states",10).unwrap().is_empty());}
#[test]fn real_local_response_never_uses_client_answer(){let d:Commit=decode(json!({"requestId":"local","turnId":"local","packetId":"packet","modelId":"OfflineA","text":"合成演练 · fake remote answer","inputRefs":[]})).unwrap();assert!(Store::local_reply(&d).is_err());let mut d=d;d.clarification=Some(Clarification{field:"domain".into()});assert!(Store::local_reply(&d).unwrap().starts_with("本地澄清"));assert!(!Store::local_reply(&d).unwrap().contains("fake"));}
pub(super) fn catalog_config(mode:&str,provider:&str,model:&str)->Value{json!({"version":1,"primary":{"mode":mode,"providerId":provider,"modelLabel":model,"endpointUrl":if mode=="cloud"{Some(if provider=="deepseek"{"https://api.deepseek.com".to_string()}else{format!("offline://catalog/cloud/{provider}")})}else{None},"localRuntime":if mode=="local"{Some("synthetic-local-runtime-v1")}else{None}},"routingPolicy":{"preferLocal":true,"allowCloudSupplement":false,"allowAutomaticFailover":false,"preferFastResponse":false},"fallback":{"configured":false,"providerId":null},"advanced":{"expanded":false,"capabilityOverrides":{"text":"auto","vision":"auto","speech_input":"auto","speech_output":"auto","tool_use":"auto","long_context":"auto"},"temperature":70,"maxOutputTokens":2048,"timeoutSeconds":60,"contextWindow":32}})}
fn save_catalog(s:&Store,rev:u64,c:Value)->R<Value>{s.controlled("save_ai_provider_settings","save_local_catalog",json!({"requestId":crate::conversation_store::uid("catalog"),"expectedRevision":rev,"settings":c}))}
#[test]fn catalog_cloud_local_persist_restart_and_cas(){let s=store();save_catalog(&s,0,catalog_config("cloud","openai","cloud-model")).unwrap();assert!(save_catalog(&s,0,catalog_config("local","ollama","local-model")).is_err());let path=s.c.path().unwrap().to_string();drop(s);let s=Store::open(Path::new(&path)).unwrap();assert_eq!(s.catalog().unwrap()["settings"]["primary"]["providerId"],"openai");save_catalog(&s,1,catalog_config("local","ollama","local-model")).unwrap();drop(s);let s=Store::open(Path::new(&path)).unwrap();assert_eq!(s.catalog().unwrap()["settings"]["primary"]["providerId"],"ollama");assert!(s.catalog_send_revision("local-model").is_err());}
#[test]fn catalog_strict_secret_endpoint_and_range_rejected(){let s=store();for kind in 0..3{let mut c=catalog_config("cloud","deepseek","user-chosen-synthetic");match kind{0=>c["primary"]["apiKey"]=json!("secret-canary"),1=>c["primary"]["endpointUrl"]=json!("https://unapproved.invalid"),_=>c["advanced"]["maxOutputTokens"]=json!(65535)}assert!(save_catalog(&s,0,c).is_err());}assert_eq!(s.catalog().unwrap()["revision"],0);}
#[test]fn catalog_change_invalidates_old_confirmation(){let s=store();let v=preview(&s,"catalog-turn","睡眠记录");save_catalog(&s,0,catalog_config("cloud","deepseek","user-chosen-synthetic")).unwrap();assert!(s.consume(confirmation(&v)).is_err());assert_eq!(s.catalog_send_revision("user-chosen-synthetic").unwrap(),1);}
#[test]fn catalog_metadata_and_forged_reserved_sources_never_enter_context(){let s=store();save_catalog(&s,0,catalog_config("cloud","deepseek","catalog-private-canary")).unwrap();let mut metadata=s.catalog().unwrap();assert_eq!(metadata["authorized"],false);metadata["authorized"]=json!(true);put(&s.c,"sources","_settings_catalog",&metadata).unwrap();let d=json!({"requestId":"catalog-draft","turnId":"cat","revision":1,"text":"睡眠记录"});s.draft(decode(d.clone()).unwrap(),d).unwrap();put(&s.c,"records","forged-reserved",&json!({"id":"forged-reserved","kind":"source_projection","domain":"health","sourceId":"_settings_catalog","metric":"sleep","status":"active","version":1,"observedAt":now(),"text":"catalog-private-canary"})).unwrap();let args=json!({"requestId":"cat-prepare","turnId":"cat","expectedDraftRevision":1});let p=s.prepare(decode(args.clone()).unwrap(),args).unwrap();assert!(!p.to_string().contains("catalog-private-canary"));assert!(!p["snapshot"]["sources"].to_string().contains("_settings_catalog"));assert!(!enabled(&s.c,"_settings_catalog").unwrap());save_catalog(&s,1,catalog_config("cloud","deepseek","user-chosen-synthetic")).unwrap();let forged=json!({"requestId":"bad-ref","turnId":"cat","packetId":"packet:cat","modelId":"user-chosen-synthetic","inputRefs":[{"id":"_settings_catalog","version":1,"authorizationGeneration":1}]});assert!(s.controlled("resolve_request_context","prepare_disclosure",forged).is_err());let v=preview(&s,"clean","睡眠记录");assert!(!v["exactBody"].as_str().unwrap().contains("catalog-private-canary"));assert!(get(&s.c,"memories","_settings_catalog").unwrap().is_none());assert!(get(&s.c,"states","_settings_catalog").unwrap().is_none());}
fn c1_pending_state(s:&Store){put(&s.c,"records","c1-state-raw",&json!({"id":"c1-state-raw","kind":"health_conversation_expression","domain":"health","sourceId":"conversation","status":"active","version":1,"text":"我有20分钟","observedAt":now()})).unwrap();put(&s.c,"states","c1-state",&json!({"id":"c1-state","rawId":"c1-state-raw","stateKey":"available_time","value":20,"domain":"health","status":"active","observedAt":now(),"validUntil":now()+1000,"generation":1,"identity":"user_statement"})).unwrap();}
#[test]fn c1_expired_state_blocks_confirm_before_adapter_call(){let _clock=super::tests::c1_clock();let s=store();c1_pending_state(&s);let v=preview(&s,"c1-before-send","健康活动怎么安排");super::tests::c1_advance(2000);let mut spy=Spy::new();assert_eq!(send(&Arc::new(Mutex::new(s)),&v,&mut spy).unwrap_err().code,"context_stale");assert_eq!(spy.calls,0);}
#[test]fn c1_state_expiry_during_adapter_marks_late_response_stale(){let _clock=super::tests::c1_clock();let s=store();c1_pending_state(&s);let v=preview(&s,"c1-after-send","健康活动怎么安排");struct Expiring{calls:usize}impl ModelPort for Expiring{fn generate(&mut self,_:&str,_:&[u8])->R<ModelResponse>{self.calls+=1;super::tests::c1_advance(2000);Ok(ModelResponse{text:"synthetic late answer".into(),usage:None})}}let s=Arc::new(Mutex::new(s));let mut port=Expiring{calls:0};send(&s,&v,&mut port).unwrap();assert_eq!(port.calls,1);assert_eq!(get(&s.lock().unwrap().c,"derivations","answer:c1-after-send").unwrap().unwrap()["status"],"stale");send(&s,&v,&mut port).unwrap();assert_eq!(port.calls,1);}

#[test]fn c154_confirm_keychain_unavailable_is_before_adapter_and_keeps_old_ciphertext(){
 let s=store();let v=preview(&s,"c154-key","睡眠记录");let provider=PathBuf::from(ROOT).join(format!("synthetic/{}-provider.sqlite",s.fixture()));let before=fs::read(&provider).unwrap();let s=Arc::new(Mutex::new(s));
 crate::provider_store::fail_next_synthetic_lookup(crate::secure_credentials::CredentialFailure::KeychainUnavailable);let mut spy=Spy::new();assert_eq!(send(&s,&v,&mut spy).unwrap_err().code,"credential_unavailable");assert_eq!(spy.calls,0);assert_eq!(fs::read(provider).unwrap(),before);let s=s.lock().unwrap();assert!(get(&s.c,"packets",v["previewId"].as_str().unwrap()).unwrap().unwrap().get("deliveryState").is_none());assert!(get(&s.c,"derivations","answer:c154-key").unwrap().is_none());
}
#[test]fn c154_confirm_production_parser_failures_are_consumed_without_resend(){
 struct Wire{calls:usize,body:Vec<u8>}impl ModelPort for Wire{fn generate(&mut self,_:&str,_:&[u8])->R<ModelResponse>{self.calls+=1;crate::provider_transport::decode_chat_response(&self.body)}}
 for (body,code) in [(b"not-json".to_vec(),"provider_protocol"),(br#"{"choices":[{"message":{"content":null}}]}"#.to_vec(),"provider_protocol"),(br#"{"choices":[{"message":{"content":""}}]}"#.to_vec(),"provider_response_empty")]{
 let s=store();let v=preview(&s,"c154-wire","睡眠记录");let path=s.c.path().unwrap().to_owned();let s=Arc::new(Mutex::new(s));let mut wire=Wire{calls:0,body};let result=send(&s,&v,&mut wire).unwrap();assert_eq!(result["errorCode"],code);assert_eq!(result["state"],"failed");assert_eq!(send(&s,&v,&mut wire).unwrap()["state"],"failed");assert_eq!(wire.calls,1);drop(s);let s=Arc::new(Mutex::new(Store::open(Path::new(&path)).unwrap()));assert_eq!(send(&s,&v,&mut wire).unwrap()["state"],"failed");assert_eq!(wire.calls,1);
 }
}
#[test]fn c154_confirm_store_busy_after_response_is_not_network_failure_and_restart_never_resends(){
 struct Busy{calls:usize,path:String,lease:Option<Connection>}impl ModelPort for Busy{fn generate(&mut self,_:&str,_:&[u8])->R<ModelResponse>{self.calls+=1;let c=Connection::open(&self.path).unwrap();c.execute_batch("BEGIN IMMEDIATE").unwrap();self.lease=Some(c);Ok(ModelResponse{text:"Synthetic final response".into(),usage:None})}}
 let s=store();let v=preview(&s,"c154-busy","睡眠记录");let path=s.c.path().unwrap().to_owned();let s=Arc::new(Mutex::new(s));let mut wire=Busy{calls:0,path:path.clone(),lease:None};assert_eq!(send(&s,&v,&mut wire).unwrap_err().code,"response_storage_failed");assert_eq!(wire.calls,1);drop(wire.lease.take());assert!(get(&s.lock().unwrap().c,"derivations","answer:c154-busy").unwrap().is_none());drop(s);let s=Arc::new(Mutex::new(Store::open(Path::new(&path)).unwrap()));assert_eq!(send(&s,&v,&mut wire).unwrap()["state"],"outcome_unknown");assert_eq!(wire.calls,1);
}
#[test]fn c154_confirm_derivation_write_failure_rolls_back_and_preserves_old_rows(){
 let s=store();let v=preview(&s,"c154-write","睡眠记录");s.c.execute_batch("CREATE TRIGGER synthetic_write_failure BEFORE INSERT ON derivations BEGIN SELECT RAISE(ABORT,'synthetic'); END").unwrap();let s=Arc::new(Mutex::new(s));let mut spy=Spy::new();assert_eq!(send(&s,&v,&mut spy).unwrap_err().code,"dispatch_outcome_unknown");assert_eq!(spy.calls,1);assert_eq!(send(&s,&v,&mut spy).unwrap()["state"],"outcome_unknown");assert_eq!(spy.calls,1);let s=s.lock().unwrap();assert!(get(&s.c,"derivations","answer:c154-write").unwrap().is_none());assert_eq!(get(&s.c,"drafts","draft:c154-write").unwrap().unwrap()["status"],"pending");
}

#[test]fn c154_confirm_storage_lock_before_consumption_has_zero_adapter_calls(){let s=store();let v=preview(&s,"c154-locked","睡眠记录");let c=Connection::open(s.c.path().unwrap()).unwrap();c.execute_batch("BEGIN IMMEDIATE").unwrap();let s=Arc::new(Mutex::new(s));let mut spy=Spy::new();assert_eq!(send(&s,&v,&mut spy).unwrap_err().code,"confirmation_storage_failed");assert_eq!(spy.calls,0);drop(c);assert!(get(&s.lock().unwrap().c,"packets",v["previewId"].as_str().unwrap()).unwrap().unwrap().get("deliveryState").is_none());}
