//! SourcePort boundary: fixed synthetic source during this approved phase.
use crate::{repository::Error,health_reader::Reader};use std::{path::PathBuf,os::unix::fs::{OpenOptionsExt,MetadataExt}};use rusqlite::{Connection,params};use serde_json::{Value,json};
type R<T>=Result<T,Error>;
pub(crate) fn path(fixture:&str)->R<PathBuf>{if fixture.is_empty()||!fixture.bytes().all(|b|b.is_ascii_alphanumeric()||b==b'-'){return Err(Error::new("source_target_rejected"));}if crate::runtime_root::is_real(){return Err(Error::new("real_stage_not_authorized"));}Ok(crate::runtime_root::verify()?.join(format!("health-{fixture}.sqlite")))}
pub(crate) fn initialize_fixture(fixture:&str)->R<()>{let p=path(fixture)?;match std::fs::symlink_metadata(&p){Ok(m)=>{if !m.is_file()||m.file_type().is_symlink()||m.nlink()!=1||m.uid()!=unsafe{libc::getuid()}||m.mode()&0o777!=0o600{return Err(Error::new("source_target_rejected"));}return Ok(())},Err(e) if e.kind()==std::io::ErrorKind::NotFound=>(),Err(_)=>return Err(Error::new("source_target_rejected"))}let f=std::fs::OpenOptions::new().create_new(true).write(true).mode(0o600).custom_flags(libc::O_NOFOLLOW).open(&p).map_err(|_|Error::new("source_target_rejected"))?;drop(f);let c=Connection::open_with_flags(&p,rusqlite::OpenFlags::SQLITE_OPEN_READ_WRITE|rusqlite::OpenFlags::SQLITE_OPEN_NOFOLLOW)?;c.execute_batch("CREATE TABLE records(id TEXT PRIMARY KEY,body TEXT);CREATE TABLE sources(id TEXT PRIMARY KEY,body TEXT);CREATE TABLE states(id TEXT PRIMARY KEY,body TEXT);")?;let at=crate::conversation_store::now() as i64;let day=at/86400000-1;
 for (metric,value,estimated) in [("sleep",360.,false),("steps",6200.,false),("exercise",18.,true)]{let b=json!({"protocol":"apple-file-v1","kind":"health_current_state","metric":metric,"dayIndex":day,"offsetMinutes":480,"sources":[{"name":"Synthetic Watch"}],"value":value,"estimated":estimated,"method":"synthetic_projection","observedAt":day*86400000,"receivedAt":at});c.execute("INSERT INTO states VALUES(?1,?2)",params![metric,b.to_string()])?;}
 let unknown=json!({"protocol":"apple-file-v1","kind":"health_current_state","metric":"sleep","dayIndex":day-1,"offsetMinutes":480,"sources":[{"name":"Synthetic Other Source"}],"value":null,"estimated":false,"method":"uncertain","observedAt":(day-1)*86400000,"receivedAt":at});c.execute("INSERT INTO states VALUES('unknown',?1)",[unknown.to_string()])?;let b=json!({"protocol":"apple-file-v1","kind":"health_batch","receivedAt":at});c.execute("INSERT INTO records VALUES('health-apple-batch:fixture',?1)",[b.to_string()])?;Ok(())}
pub(crate) fn read(fixture:&str,question:&str)->R<Vec<Value>>{let p=path(fixture)?;let reader=Reader::open(&p)?;let q=question.to_lowercase();let metrics:Vec<&str>=if q.contains('睡')||q.contains("sleep"){vec!["sleep"]}else if q.contains("步数")||q.contains("steps"){vec!["steps"]}else if q.contains("运动")||q.contains("散步")||q.contains("活动"){vec!["sleep","exercise"]}else{vec!["sleep","steps","exercise"]};let today=crate::conversation_store::now() as i64/86400000;let exact=if q.contains("今天"){Some(today)}else if q.contains("昨天"){Some(today-1)}else{None};let mut out=vec![];
 for metric in metrics{let v=reader.recent(metric,exact)?;let chosen=v["points"].as_array().and_then(|a|a.iter().rev().find(|p|p["present"]==true&&exact.is_none_or(|d|p["day"]==d)));if let Some(point)=chosen{let day=point["day"].as_i64().unwrap();let value=point["value"].as_f64();let unit=if metric=="steps"{"步"}else{"分钟"};let name=match metric{"sleep"=>"睡眠","steps"=>"步数",_=>"Apple运动时间"};let mut text=format!("{name}：{}；来源 {}；来源日期 {}，UTC偏移 {} 分钟。",value.map(|n|format!("{n} {unit}")).unwrap_or("未知，不当作零".into()),v["source"].as_str().unwrap_or(""),calendar_day(day),v["offset"].as_i64().unwrap_or(0));if point["estimated"]==true{text.push_str("此值为区间分配估算。");}if v["groups"].as_array().is_some_and(|a|a.len()>1)||!v["nextGroupPage"].is_null(){text.push_str("存在其他来源组，本次仅引用这一组，不合并为总量。");}out.push(json!({"metric":metric,"text":text,"value":point["value"],"dayIndex":day,"observedAt":day*86400000,"offsetMinutes":v["offset"],"estimated":point["estimated"],"sourceName":v["source"]}));}}
 Ok(out)
}

pub(crate) fn relevant(question:&str,metric:&str)->bool{let q=question.to_lowercase();if q.contains('睡')||q.contains("sleep"){metric=="sleep"}else if q.contains("步数")||q.contains("steps"){metric=="steps"}else if q.contains("运动")||q.contains("散步")||q.contains("活动"){["sleep","exercise"].contains(&metric)}else{["sleep","steps","exercise"].contains(&metric)}}

fn calendar_day(day:i64)->String{let t=(day*86400) as libc::time_t;let mut tm:libc::tm=unsafe{std::mem::zeroed()};unsafe{libc::gmtime_r(&t,&mut tm)};format!("{:04}-{:02}-{:02}",tm.tm_year+1900,tm.tm_mon+1,tm.tm_mday)}
