import assert from 'node:assert/strict';import {ControlledConversation} from '../candidate/ui/controlled_conversation.js';
import {spawn} from 'node:child_process';import {createInterface} from 'node:readline';import {writeFile} from 'node:fs/promises';
const child=spawn('/private/tmp/lifeos-p3-152-health-conversation-v1/real-target/debug/synthetic-driver',[],{stdio:['pipe','pipe','pipe']});let n=0;const pending=new Map();let stderr='';child.stderr.on('data',v=>stderr+=v);createInterface({input:child.stdout}).on('line',l=>{const r=JSON.parse(l),p=pending.get(r.id);pending.delete(r.id);r.ok?p.resolve(r.result):p.reject(r.error)});child.on('exit',()=>{for(const p of pending.values())p.reject(Error('driver exit '+stderr));});
const call=(command,payload)=>new Promise((resolve,reject)=>{const id=++n;pending.set(id,{resolve,reject});child.stdin.write(JSON.stringify({id,command,request:{version:1,payload}})+'\n')});
const invoke=(command,request)=>new Promise((resolve,reject)=>{const id=++n;pending.set(id,{resolve,reject});child.stdin.write(JSON.stringify({id,command,request})+'\n')});
try{await call('connect_source_directory',{requestId:crypto.randomUUID()});for(let i=0;i<80;i++){const s=(await call('get_source_status',{})).connectors[0];if(s.error)throw s.error;if(s.scanComplete&&s.pending===0)break;await new Promise(r=>setTimeout(r,100));}
const a=new ControlledConversation({invoke});await a.saveCredential('complete-only-fictional-secret',0);await a.selectModel('combined-synthetic-model');const d={requestId:crypto.randomUUID(),turnId:crypto.randomUUID(),revision:1,text:'我的项目星舟资料包含什么内容'};const out=await a.prepare(d,()=>true);console.log('preview-kind',out.kind);console.log('items',JSON.stringify(out.preview?.items));assert.equal(out.kind,'preview');assert(out.preview.items.some(i=>i.text.includes('星舟')));console.log('send',await a.confirm(out.preview));console.log('turns',JSON.stringify((await a.read()).turns));
await call('import_apple_health_file',{action:'start',file:'health-demo.xml'});for(let i=0;i<80;i++){const s=await call('import_apple_health_file',{action:'status'});if(s.status!=='running'){assert.equal(s.status,'completed');break;}await new Promise(r=>setTimeout(r,100));}console.log('health',JSON.stringify(await invoke('get_today',{version:2,operation:'health_view',payload:{metric:'steps',days:7}})));
}
catch(e){console.log('ERROR',JSON.stringify(e));process.exitCode=1}finally{child.kill()}
