const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const time=(n:any)=>typeof n==='number'?new Date(n).toLocaleString('zh-CN',{hour12:false}):'暂无';
export function appleImportView(state:any){
 const s=state.status||{status:'idle'},running=s.status==='running';
 const result=['completed','duplicate'].includes(s.status)?`<p role="status">${s.status==='duplicate'?'此文件已导入，未重复写入。':'导入完成。'} 新增观察 ${s.inserted} · 重复内容 ${s.duplicates} · 不支持 ${s.unsupported} · 失败 ${s.failed}</p><p class="tiny">最近成功导入（本机时间）${time(s.importedAt)}${s.originalImport?' · 保留原导入时间':''}</p><p class="tiny">${s.attachments||0} 个附件未处理；不支持数包含其他顶层对象。</p>${Object.keys(s.unsupportedTypes||{}).length?`<details data-keep="apple-unsupported"><summary>查看不支持类型</summary>${Object.entries(s.unsupportedTypes).map(([k,v])=>`<p class="tiny">${esc(k)} · ${esc(v)}</p>`).join('')}</details>`:''}`:s.status==='failed'?`<p role="alert">文件导入失败：${esc(s.code)}。文件失败 1，整批新增 0；无法确认的记录数量不作推测。已有数据保留。</p><button class="button secondary" data-action="apple-retry">重试此文件</button>`:running?`<p role="status">${esc(s.phase||'正在准备导入')} · 已处理 ${Number(s.processed||0)} 条；完成前不发布新观察。</p><progress aria-label="苹果健康文件导入进度"></progress>`:'<p>尚未导入苹果健康文件。</p>';
 return `<section class="config-card health-section" aria-label="苹果健康文件导入"><h2>苹果健康文件</h2><p>文件导入，非自动同步 · 仅本任务合成演练</p><button class="button primary" data-action="apple-open" ${running||state.loading?'disabled':''}>导入苹果健康文件</button>${state.loading?'<p role="status">正在读取可选合成文件…</p>':''}${state.error?`<p role="alert">${esc(state.error)}</p>`:''}${state.picker?`<section class="apple-file-picker" aria-label="选择合成健康文件"><h3>选择 XML 或 ZIP 文件</h3><p class="tiny">仅显示本任务专用目录，不访问个人目录。选中即导入。</p>${state.picker.map((file:string)=>`<p><button class="button secondary" data-action="apple-select" data-id="${esc(file)}">${esc(file)}</button></p>`).join('')||'<p>没有可选文件。</p>'}<button class="button ghost" data-action="apple-close">取消选择</button></section>`:''}${s.file?`<p class="tiny">文件：${esc(s.file)}</p>`:''}${result}<p class="tiny">支持睡眠区间、步数、Apple 运动时长。重复内容不是样本修订证明；覆盖范围未知，不代表健康库全部导入。</p><p class="tiny">观察在“我”，导入批次在 Memory；健康导入不授权 AI 处理。</p></section>`;
}
export class AppleImportController {
 state:any={status:{status:'idle'},picker:null,error:'',loading:false};starting=false;polling=false;
 constructor(private invoke:any,private changed:()=>void,private refresh:()=>Promise<void>){}
 private call(action:string,file?:string){const payload:any={action};if(file!==undefined)payload.file=file;return this.invoke('import_apple_health_file',new TextEncoder().encode(JSON.stringify({version:1,payload})));}
 async restore(){this.state.status=await this.call('status');}
 async open(){if(this.starting||this.state.status.status==='running')return;this.state.loading=true;this.state.error='';this.changed();try{this.state.picker=(await this.call('list')).files;}catch(e:any){this.state.error=`无法列出合成文件（${e?.code||'读取失败'}）。`;}finally{this.state.loading=false;this.changed();}}
 close(){this.state.picker=null;this.changed();}
 async choose(file:string){if(this.starting||this.state.status.status==='running')return;this.starting=true;this.state.picker=null;this.state.error='';this.state.status={status:'running',file,processed:0};this.changed();try{this.state.status=await this.call('start',file);}catch(e:any){this.state.status={status:'failed',file,code:e?.code||'health_start_failed',failed:1};}finally{this.starting=false;this.changed();}}
 async poll(){if(this.starting||this.polling||this.state.status.status!=='running')return;this.polling=true;try{this.state.status=await this.call('status');if(this.state.status.status!=='running')await this.refresh();this.state.error='';this.changed();}catch(e:any){this.state.error=`暂时无法取得进度（${e?.code||'读取失败'}），将继续核对。`;this.changed();}finally{this.polling=false;}}
}
