import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {ConversationFlow} from '../candidate/ui/conversation_flow.js';
function setup(){const calls=[];let seq=0;const app={open:async()=>({}),ask:async()=>{},call:async()=>{},cancel:async p=>calls.push(['cancel',p.previewId]),preview:async(t,x=[])=>{calls.push(['preview',t,[...x]]);return {previewId:'p'+(++seq),state:'ready',revision:1,confirmationToken:'token'+seq,expiresAt:Date.now()+60000,items:['s1','s2','s3'].filter(s=>!x.includes(s)).map(s=>({kind:'source',source:{segmentId:s},text:s}))}},send:async()=>{calls.push(['send']);return{state:'succeeded'}}};const flow=new ConversationFlow(app,()=>{},async()=>{});return{flow,calls,app}}
test('public preview omits turnId: UI remove delegates controlled Flow turn and cumulatively excludes',async()=>{const {flow,calls}=setup();try{await flow.start();flow.edit('question');const turn=flow.draft.turnId;await flow.prepare();assert(!('turnId' in flow.preview));const old=flow.preview.previewId;
 const source=readFileSync(new URL('../candidate/ui/source_ui.js',import.meta.url),'utf8');assert(source.includes('await flow.remove(id)'));assert(!source.includes('flow.preview?.turnId'));
 await flow.remove('s1');assert.notEqual(flow.preview.previewId,old);assert(!flow.preview.items.some(i=>i.source.segmentId==='s1'));await flow.remove('s2');assert.deepEqual(calls.filter(c=>c[0]==='preview').at(-1),['preview',turn,['s1','s2']]);assert.equal(calls.filter(c=>c[0]==='send').length,0);assert(calls.some(c=>c[0]==='cancel'&&c[1]===old));}finally{flow.dispose()}});
test('prepareTurn supplied turn retained without DTO internal fields',async()=>{const {flow,calls}=setup();try{await flow.start();await flow.prepareTurn('saved-turn');await flow.remove('s3');assert.deepEqual(calls.at(-1),['preview','saved-turn',['s3']]);}finally{flow.dispose()}});
test('reassembly failure is visible; old preview cannot be confirmed',async()=>{const {flow,calls,app}=setup();try{await flow.start();await flow.prepareTurn('t');app.preview=async()=>{throw{code:'database_unavailable'}};await flow.remove('s1');assert.equal(flow.preview,null);assert.equal(flow.error.code,'database_unavailable');await flow.confirm();assert(!calls.some(c=>c[0]==='send'));}finally{flow.dispose()}});
test('cancel failure refuses new package and old confirmation',async()=>{const {flow,calls,app}=setup();try{await flow.start();await flow.prepareTurn('t');app.cancel=async()=>{throw{code:'operation_failed'}};await flow.remove('s1');assert.equal(flow.preview,null);assert.equal(flow.error.code,'operation_failed');assert.equal(calls.filter(c=>c[0]==='preview').length,1);await flow.confirm();assert(!calls.some(c=>c[0]==='send'));}finally{flow.dispose()}});
test('unknown segment or missing context fail visibly and cannot preserve ready token',async()=>{const {flow}=setup();try{await flow.start();await flow.prepareTurn('t');await flow.remove('unknown');assert.equal(flow.preview,null);assert.equal(flow.error.code,'preview_stale');await flow.remove('s1');assert.equal(flow.error.code,'preview_stale');}finally{flow.dispose()}});
test('edit during reassembly discards late result, preserving edited draft',async()=>{const {flow,app}=setup();let resolve;try{await flow.start();await flow.prepareTurn('t');const original=app.preview;app.preview=async(t,x)=>{await new Promise(r=>resolve=r);return original(t,x)};const pending=flow.remove('s1');await Promise.resolve();flow.edit('new question');resolve();await pending;assert.equal(flow.preview,null);assert.equal(flow.draft.text,'new question');}finally{flow.dispose()}});
