import assert from 'node:assert/strict';import {spawn,execFileSync} from 'node:child_process';import {createInterface} from 'node:readline';import {once} from 'node:events';
import {chooseContext,interpretation} from '../candidate/ui/health_context.js';import {HealthConversation} from '../candidate/ui/health_conversation.js';
const results=[];async function test(name,f){try{await f();results.push({name,pass:true})}catch(e){results.push({name,pass:false,error:e.stack||JSON.stringify(e)})}}
const at=1900000000000;
function packet(){return {id:'p',turnId:'today',domain:'health',question:'今天健康活动怎么安排',now:at,questions:[{id:'yesterday',field:'available_time',domain:'health',status:'answered',answeredAt:at-86400001}],snapshot:{states:[],memories:[],feedback:[],derivations:[],records:[{id:'exercise',sourceId:'health',domain:'health',kind:'source_projection',metric:'exercise',text:'健康活动：合成运动观察',status:'active',version:1,observedAt:at-1000,validUntil:at+86400000}],sources:[{id:'health',authorized:true,generation:1},{id:'conversation',authorized:true,generation:1},{id:'time',authorized:true,generation:1}]}}}
function state(p,validUntil){p.snapshot.records.push({id:'raw-time',sourceId:'conversation',domain:'health',kind:'health_conversation_expression',text:'我有20分钟',status:'active',version:1,observedAt:at-86400001});p.snapshot.states.push({id:'state-time',rawId:'raw-time',stateKey:'available_time',value:20,domain:'health',status:'active',observedAt:at-86400001,validUntil});}
const decide=p=>interpretation(p,chooseContext(p));
await test('expired answered information opens one new gap; history untouched',()=>{const p=packet();state(p,at-1);const old=structuredClone(p.questions);assert.equal(decide(p).clarification.field,'available_time');assert.deepEqual(p.questions,old);assert.equal(chooseContext(p).states.length,0)});
await test('valid replacement state answers gap; expired or revoked state does not',()=>{for(const mode of ['valid','expired','grant-revoked','raw-revoked']){const p=packet();state(p,mode==='expired'?at-1:at+86400000);if(mode==='grant-revoked')p.snapshot.sources.find(s=>s.id==='conversation').authorized=false;if(mode==='raw-revoked')p.snapshot.records.find(r=>r.id==='raw-time').status='revoked';assert.equal(decide(p).clarification?.field,mode==='valid'?undefined:'available_time')}});
await test('source availability is usable only when current and authorized',()=>{for(const mode of ['valid','expired','revoked','tombstone']){const p=packet();state(p,at-1);p.snapshot.records.push({id:'source-time',sourceId:'time',domain:'health',kind:'source_projection',text:'健康活动安排：我有30分钟',status:mode==='tombstone'?'revoked':'active',version:2,observedAt:at,validUntil:mode==='expired'?at:at+10000});if(mode==='revoked')p.snapshot.sources.find(s=>s.id==='time').authorized=false;assert.equal(decide(p).clarification?.field,mode==='valid'?undefined:'available_time')}});
await test('reject remains durable; deferred and ignored respect their scope',()=>{for(const status of ['rejected','pending','deferred','ignored']){const p=packet();state(p,at-1);p.questions[0]={...p.questions[0],status,resumeAt:at+10000,basisTurn:'today'};assert.equal(decide(p).clarification,undefined);assert.equal(p.questions[0].status,status);}const p=packet();p.questions[0].status='deferred';p.questions[0].resumeAt=at-1;assert.equal(decide(p).clarification.field,'available_time');});
await test('prior answered domain is not an authorization or domain for a new ambiguous request',()=>{const p=packet();p.domain='ambiguous';p.question='工作还是健康怎么安排';p.questions[0]={id:'old-domain',domain:'ambiguous',field:'domain',status:'answered'};assert.equal(chooseContext(p).inputRefs.length,0);assert.equal(decide(p).clarification.field,'domain')});
let calls=0;globalThis.fetch=()=>{calls++;throw Error('network denied')};
function host(fixture){const p=spawn('/private/tmp/lifeos-p3-154-real-continuity-v1/target/debug/synthetic-driver',['--synthetic-fixture',fixture],{stdio:['pipe','pipe','pipe']});let n=0;const pending=new Map();createInterface({input:p.stdout}).on('line',l=>{const v=JSON.parse(l),h=pending.get(v.id);if(!h)return;pending.delete(v.id);clearTimeout(h.timer);v.ok?h.resolve(v.result):h.reject(v.error)});p.on('exit',()=>{for(const h of pending.values()){clearTimeout(h.timer);h.reject(Error('driver exited'))}});return {pid:p.pid,invoke:(command,request)=>new Promise((resolve,reject)=>{const id=++n,timer=setTimeout(()=>{reject(Error('timeout'));p.kill()},10000);pending.set(id,{resolve,reject,timer});p.stdin.write(JSON.stringify({id,command,request})+'\n')}),close:async()=>{const done=once(p,'exit');p.stdin.end();await done}}}
const draft=text=>({requestId:crypto.randomUUID(),turnId:crypto.randomUUID(),revision:1,text});let restart;
await test('expired persisted state after independent restart permits new question and retains old answered row',async()=>{const fixture='p154-c1-'+crypto.randomUUID();let h=host(fixture),a=new HealthConversation(h);const pids=[h.pid];try{await a.answer(draft('健康活动怎么安排'),()=>true);await a.answer(draft('我有20分钟'),()=>true);const q=(await a.read()).questions[0];assert.equal(q.status,'answered');await h.close();
 const db='/private/tmp/lifeos-p3-154-real-continuity-v1/synthetic/'+fixture+'.sqlite';
 // Test setup only: expire the state while the owned fixture process is closed, with no new IPC or runtime clock override.
 execFileSync('python3',['-c',`import sqlite3,sys,time\nc=sqlite3.connect(sys.argv[1]);at=int(time.time()*1000)-1;c.execute("UPDATE states SET body=json_set(body,'$.validUntil',?,'$.observedAt',?)",(at,at-86400000));c.commit();c.close()`,db]);
 h=host(fixture);pids.push(h.pid);a=new HealthConversation(h);assert.equal((await a.read()).states.length,0);assert.equal((await a.read()).questions[0].status,'answered');await a.answer(draft('今天健康活动怎么安排'),()=>true);const s=await a.read();assert.equal(s.questions[0].status,'pending');assert.notEqual(s.questions[0].id,q.id);assert.equal(s.turns.length,3);
 const old=JSON.parse(execFileSync('python3',['-c',`import sqlite3,sys\nc=sqlite3.connect('file:'+sys.argv[1]+'?mode=ro',uri=True);print(c.execute('SELECT body FROM questions WHERE id=?',(sys.argv[2],)).fetchone()[0]);c.close()`,db,q.id],{encoding:'utf8'}));assert.deepEqual(old,q);restart={fixture,pids,oldQuestion:q.id,newQuestion:s.questions[0].id};
 }finally{await h.close()}});
console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,networkCalls:calls,restart,results},null,2));if(results.some(r=>!r.pass))process.exitCode=1;
