(() => {
  "use strict";
  const app = document.getElementById("app");
  const invoke = window.__TAURI__?.core?.invoke;
  const samples = [
    { key: "p3-121-synthetic-one", text: "P3-121 synthetic capture one", label: "记录合成样本一" },
    { key: "p3-121-synthetic-two", text: "P3-121 synthetic capture two", label: "记录合成样本二" },
  ];
  const validTexts = new Set(samples.map((item) => item.text));
  const contexts = {
    launch: ["LifeOS 产品开发", "Project", "Work", "正在进行", "正在把产品体验和可靠 Runtime 放回同一条路径。", "先核对 capture、刷新与关闭重开后的内容身份。"],
    recovery: ["训练恢复", "Period / Program", "Health", "持续关注", "训练节奏稳定；恢复感仍需被保守地观察。", "先记录下一次主观感受，不生成训练调整。"],
    sleep: ["最近睡眠", "Observed Context", "Health", "持续关注", "有较晚结束工作的固定合成痕迹。", "证据不足，不建立因果结论。"],
  };
  const memory = [
    ["original", "用户原文", "user", "P3-121 的合成捕获原文", "task-local SQLite · user_original", "可找回"],
    ["confirmed", "确认事实", "user", "本轮只允许三项既有 IPC", "Frozen ABF · 用户确认边界", "已确认"],
    ["observation", "AI Observation", "observation", "Work 与 Health Context 同时存在", "固定 synthetic fixture", "待核对"],
    ["inference", "AI Inference", "inference", "可靠闭环优先于更多建议", "固定 synthetic derivation", "证据有限"],
    ["decision", "Decision Candidate", "decision", "先验证关闭重开，再扩展能力", "候选，不会执行或写入", "待你决定"],
  ];
  const state = { page: "today", mode: "normal", context: "launch", memory: "original", filter: "all", ai: false, capture: false, health: true, motion: false, runtime: null, today: { records: [], audit: { event_count: 0 } }, notice: "正在核对离线本地 Runtime…", error: false };
  const esc = (value) => String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
  const code = (error) => (error && typeof error === "object" && error.code) || "runtime_contract_rejected";
  const tag = (text, tone = "") => `<span class="identity ${tone}">${esc(text)}</span>`;
  const button = (text, action, kind = "button") => `<button type="button" class="${kind}" data-action="${action}">${text}</button>`;
  const icon = (name) => {
    const paths = {
      today: "M4 12h16M12 4v16M5 5l14 14M19 5L5 19",
      me: "M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM4 20c.8-3.4 3.3-5.2 8-5.2s7.2 1.8 8 5.2",
      contexts: "M4 7.2h5l1.6 2H20v8.6a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z",
      memory: "M6 4.8h9.2A2.8 2.8 0 0 1 18 7.6V19H8.8A2.8 2.8 0 0 0 6 21zM6 4.8V21M18 19h-7.2A2.8 2.8 0 0 0 8 21",
      settings: "M12 8.4a3.6 3.6 0 1 0 0 7.2 3.6 3.6 0 0 0 0-7.2ZM19.1 13.5l1.1.9-1.8 3.1-1.4-.5a7.8 7.8 0 0 1-1.6.9l-.2 1.5h-3.6l-.3-1.5a7.8 7.8 0 0 1-1.6-.9l-1.4.5-1.8-3.1 1.1-.9a7.5 7.5 0 0 1 0-1.8l-1.1-.9 1.8-3.1 1.4.5a7.8 7.8 0 0 1 1.6-.9l.3-1.5h3.6l.2 1.5a7.8 7.8 0 0 1 1.6.9l1.4-.5 1.8 3.1-1.1.9a7.5 7.5 0 0 1 0 1.8Z",
      sparkle: "m12 3 1.7 5.3L19 10l-5.3 1.7L12 17l-1.7-5.3L5 10l5.3-1.7zM19 16l.7 2.3L22 19l-2.3.7L19 22l-.7-2.3L16 19l2.3-.7z",
    };
    return `<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="${paths[name] || paths.sparkle}"/></svg>`;
  };
  const call = async (command, request = {}) => { if (typeof invoke !== "function") throw { code: "tauri_bridge_unavailable" }; return invoke(command, { request }); };
  const context = () => contexts[state.context];
  function verifyStatus(value) {
    const commands = ["capture_record", "get_today", "runtime_status"].join(",");
    const closed = ["filesystem", "raw_database", "generic_path_api", "shell", "process_spawn", "network", "vault", "export", "sync"];
    if (!value || value.status !== "restricted_offline" || !value.offline || value.ai_enabled || value.unknown_ipc !== "deny" || value.ipc_allowlist?.join(",") !== commands || value.renderer_direct_capabilities?.length !== 0 || closed.some((key) => value[key] !== false)) throw { code: "runtime_contract_rejected" };
    return value;
  }
  function verifyToday(value) {
    if (!value || !["empty", "loaded"].includes(value.status) || !Array.isArray(value.records) || value.source !== "local_capture" || value.ai_status !== "disabled") throw { code: "today_contract_rejected" };
    const ids = new Set();
    for (const record of value.records) if (!record || !validTexts.has(record.content) || record.identity !== "user_original" || record.source !== "local_capture" || !record.id || ids.has(record.id)) throw { code: "today_identity_rejected" }; else ids.add(record.id);
    if (value.records.length > 2) throw { code: "today_limit_rejected" };
    return value;
  }
  async function refresh(receipt = true) {
    try { state.today = verifyToday(await call("get_today", {})); if (receipt) state.notice = `Today 已从 get_today 重读：${state.today.records.length} 条固定合成原文。`; state.error = false; }
    catch (error) { state.today = { records: [], audit: { event_count: 0 } }; state.notice = `读取被阻断：${code(error)}。未展示缓存或部分记录。`; state.error = true; throw error; }
    finally { render(); }
  }
  async function capture(sample) {
    state.capture = false; state.notice = "正在等待 capture_record 的权威回执…"; state.error = false; render();
    try {
      const result = await call("capture_record", { text: sample.text, key: sample.key });
      if (!result || !["saved", "idempotent_repeat"].includes(result.status) || result.record?.content !== sample.text || result.record?.identity !== "user_original") throw { code: "capture_contract_rejected" };
      await refresh(false); state.notice = result.status === "saved" ? "已保存：原文先由 SQLite 原子发布，再经 get_today 找回。" : "幂等重复：记录未增加；同一固定原文身份保持不变。"; state.error = false;
    } catch (error) { state.notice = `已阻断：${code(error)}。没有显示成功态；将重新读取权威状态。`; state.error = true; await refresh(false).catch(() => {}); }
    render();
  }
  function chrome() { return `<div class="page-chrome"><span>8月25日 · 周一</span>${button(state.motion ? "低动态已开启" : "低动态", "motion", "chrome-button")}<span class="synthetic-mark">固定合成 · 本地离线</span></div>`; }
  function header(eyebrow, title, subhead) { return `<header class="page-header"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="subhead">${subhead}</p></div>${chrome()}</header>`; }
  function records() { return state.today.records.length ? `<div class="record-list">${state.today.records.map((record, index) => `<article class="record-card"><div>${tag("用户原文", "user")}<small>合成记录 ${index + 1}</small></div><p>${esc(record.content)}</p><small>通过 get_today 从 task-local SQLite 找回 · AI 未参与</small></article>`).join("")}</div>` : `<section class="empty-state"><strong>今天还没有 Runtime 记录。</strong><p>这是合法空状态。你可以在需要时明确记录一条固定合成原文。</p>${button("快速记录", "capture-open", "button primary")}</section>`; }
  function focus() {
    if (state.mode === "empty") return `<section class="empty-state focus-card"><strong>今天没有特别需要处理的事情。</strong><p>这是合法、安静的 Person 状态；不需要为了填充页面强行产生建议。</p>${button("查看 Contexts", "nav:contexts")}</section>`;
    if (state.mode === "insufficient") return `<section class="empty-state focus-card"><strong>现在没有可靠的 Today's Focus。</strong><p>零散变化不足以支持整体优先级判断。LifeOS 不会为了填充页面生成建议。</p><div class="evidence-box"><strong>证据缺口</strong>：缺少已确认的下一步与可比较的近期依据。</div></section>`;
    return `<section class="focus-card"><div class="section-top">${tag("Today's Focus", "decision")}<span aria-hidden="true">•••</span></div><h2>把“以人为主体”的体验与可靠 Runtime 放在同一条路径。</h2><p>先确保 capture、找回与关闭重开后的内容身份一致，再讨论更多能力。</p><div class="focus-reason"><strong>为什么现在值得做</strong><ul><li>用户已确认本轮先完成组合收口</li><li>Runtime 只承接两条明确的合成原文</li><li>没有足够证据时，不把 Work 与 Health 说成因果</li></ul></div><div class="actions">${button("继续", "context:launch", "button primary")}${button("查看依据", "memory:confirmed", "button ghost")}</div></section>`;
  }
  function today() { return `<main id="main-content" class="page today-page" tabindex="-1"><header class="today-hero"><div><p class="eyebrow">Today · Person 的此刻</p><h1>早上好。</h1><p>今天整体比较稳定，有一件事值得优先处理。</p></div><div>${chrome()}<span class="runtime-pill">${state.runtime ? "离线 · 本地 · 仅三项 IPC" : "Runtime 正在核对"}</span></div></header><div class="mode-switch" role="group" aria-label="Today 合成状态">${button("正常", "mode:normal", state.mode === "normal" ? "switch active" : "switch")}${button("合法空状态", "mode:empty", state.mode === "empty" ? "switch active" : "switch")}${button("证据不足", "mode:insufficient", state.mode === "insufficient" ? "switch active" : "switch")}</div><div class="today-grid"><div class="stack">${focus()}<section class="panel"><div class="section-top">${tag("Day Overview", "user")}<strong>轻量的整体状态</strong></div><div class="overview"><span><small>状态</small><b>稳定</b></span><span><small>精力</small><b>中等</b></span><span><small>心情</small><b>平静</b></span></div><p class="tiny">固定合成摘要，不是评分、诊断或建议。</p></section></div><aside class="stack"><section class="panel"><div class="section-top">${tag("LifeOS noticed", "observation")}<strong>有待核对的观察</strong></div><p>最近几天的固定合成记录中，睡眠和下午中断同时出现；暂时没有足够证据判断两者相关。</p><div class="actions">${button("看看为什么", "memory:observation", "button ghost")}${button("先忽略", "demo:ignore", "button ghost")}</div></section><section class="panel"><div class="section-top">${tag("Today", "user")}<strong>已确认安排</strong></div><ol class="schedule"><li><time>10:00</time>产品讨论</li><li><time>15:30</time>训练</li><li><time>17:00</time>提交设计稿</li></ol><p class="tiny">固定合成安排；不是外部日历。</p></section><section class="panel"><div class="section-top">${tag("Recent", "decision")}<small>${state.today.records.length} 条 · ${state.today.audit.event_count || 0} 个审计事件</small></div>${records()}<div class="actions">${button("刷新 Today", "refresh", "button ghost")}${button("快速记录", "capture-open", "button primary")}</div></section></aside></div></main>`; }
  function me() { return `<main id="main-content" class="page" tabindex="-1">${header("Me · Person 的长期视角", "Me", "LifeOS 对你的整体理解与洞察。每一层都可以回到自己的身份和依据。 ")}<section class="panel me-current"><div class="person-orb" aria-hidden="true">✦</div><div><div class="section-top"><div><p class="section-label">现在的我</p><h2>这周的工作推进感稳定，但恢复时间需要被认真对待。</h2></div>${tag("固定 synthetic", "fixture")}</div><p>最近主要精力在 LifeOS 产品开发；训练保持稳定，睡眠变化只被保守记录。这不是画像或诊断。</p><div class="actions">${button("查看理解依据", "memory:inference", "button ghost")}${button("问 Global AI", "ai-open", "button ghost")}</div></div><aside><strong>你可以问</strong>${button("我最近状态怎么样？", "ai-open", "question")}${button("我现在最大的矛盾是什么？", "ai-open", "question")}${button("接下来应把精力放在哪里？", "ai-open", "question")}</aside></section><section class="panel"><div class="section-top"><h2>我正在关注</h2>${button("查看全部", "nav:contexts", "button ghost")}</div><div class="me-grid">${Object.entries(contexts).map(([id, item]) => `<button data-action="context:${id}"><strong>${item[0]}</strong>${tag(`${item[2]} · ${item[1]}`, item[2] === "Health" ? "user" : "decision")}<p>${item[4]}</p><small>${item[3]}</small></button>`).join("")}</div></section><section class="panel"><div class="section-top"><h2>长期视角</h2>${button("查看领域 Gate", "domain-gate", "button ghost")}</div><div class="domain-grid"><article><strong>工作视角</strong>${tag("深度智能已启用", "decision")}<p>重点在明确核心价值和 MVP 路径。</p></article><article><strong>健康视角</strong>${tag("深度智能已启用", "user")}<p>只保守呈现训练与恢复的固定合成状态。</p></article><article><strong>其他人生数据</strong>${tag("尚未启用", "inference")}<p>可以承接，但没有新增深度智能入口。</p></article></div></section></main>`; }
  function contextsPage() { const sections = [["正在进行", ["launch"]], ["持续关注", ["recovery", "sleep"]], ["已结束", []]]; return `<main id="main-content" class="page" tabindex="-1">${header("Contexts · 正在经历的事", "Contexts", "按你和事情的当前关系组织。Project 只是 Context 的一种类型。")}${sections.map(([name, ids]) => `<section class="context-group"><h2>${name}</h2>${ids.length ? ids.map((id) => { const item = contexts[id]; return `<button class="context-row" data-action="context:${id}"><span>${tag(item[1], item[2] === "Health" ? "user" : "decision")}<strong>${item[0]}</strong><small>${item[2]} · ${item[3]} · ${item[4]}</small></span><b>›</b></button>`; }).join("") : `<p class="quiet">没有已结束 Context。空状态不等于需要自动创建一个。</p>`}</section>`).join("")}<section class="panel candidate-panel"><div><p class="section-label">建议创建</p><h2>LifeOS 不能静默创建 Context</h2><p>“近期旅行安排”只是固定合成候选；需要你确认名称、范围与状态。</p></div>${tag("候选", "inference")}${button("查看建议", "demo:view")}</section></main>`; }
  function detail() { const item = context(); return `<main id="main-content" class="page" tabindex="-1">${button("‹ Contexts", "nav:contexts", "back")}${header(`Context Detail · ${item[2]}`, item[0], "从现在、已确认的下一步和最近发生的事恢复上下文；Global AI 会透明继承此 Context。 ")}<div class="two-column"><div class="stack"><section class="panel"><p class="section-label">现在</p><h2>${item[4]}</h2>${tag(`${item[1]} · ${item[2]}`, "decision")}</section><section class="panel"><div class="section-top"><div><p class="section-label">Next</p><h2>${item[5]}</h2></div>${tag("确认事实", "user")}</div><div class="actions">${button("确认继续（演示）", "demo:confirm", "button primary")}${button("调整下一步（演示）", "demo:edit")}</div></section><section class="panel"><p class="section-label">最近发生</p><ol class="timeline"><li>用户原文以固定 synthetic 身份进入 Runtime</li><li>Today 只从 get_today 找回</li><li>AI 输出仍是需要用户决定的候选</li></ol></section></div><aside class="stack"><section class="panel"><p class="section-label">LifeOS understands</p><p>首要任务是可靠地完成当前闭环，而不是生成更多建议。</p>${tag("AI Inference · fixture", "inference")}${button("不准确（演示）", "demo:correct", "button ghost")}</section><section class="panel"><p class="section-label">Related / Evidence</p><p>可以沿着 Derivation 回到原文、确认事实与来源指针。</p>${button("打开 Memory Detail", "memory:original")}</section></aside></div></main>`; }
  function memoryPage() { const rows = state.filter === "all" ? memory : memory.filter((item) => item[2] === state.filter); return `<main id="main-content" class="page" tabindex="-1">${header("Memory · Evidence Browser", "Memory", "关于这个人的认识，必须能回到身份、依据与来源。")}<section class="panel memory-toolbar"><div><span class="section-label">身份筛选</span><h2>安静地浏览，而不是堆成文件夹。</h2></div><div class="filter-row">${[["all", "全部"], ["user", "用户原文／确认"], ["observation", "Observation"], ["inference", "Inference"], ["decision", "Decision"]].map(([id, label]) => button(label, `filter:${id}`, state.filter === id ? "filter active" : "filter")).join("")}</div></section><section class="panel memory-list">${rows.map((item) => `<button class="memory-row" data-action="memory:${item[0]}"><span>${tag(item[1], item[2])}<strong>${item[3]}</strong><small>${item[4]}</small></span><span>${item[5]}</span><b>›</b></button>`).join("") || `<p class="quiet">没有匹配的长期记忆。搜索不会伪造结果。</p>`}</section></main>`; }
  function memoryDetail() { const item = memory.find((entry) => entry[0] === state.memory) || memory[0]; const broken = item[0] === "inference"; return `<main id="main-content" class="page" tabindex="-1">${button("‹ Memory", "nav:memory", "back")}${header("Memory Detail · 可追溯性", item[3], "身份、理解、推导、证据与来源按层分开；不能用一张卡片混成事实。 ")}<div class="two-column"><section class="stack"><article class="panel"><div class="section-top"><div>${tag(item[1], item[2])}<h2>${item[3]}</h2></div>${tag(item[5], item[2])}</div><p>来源：${item[4]}</p><div class="actions">${button("准确（演示）", "demo:confirm", "button primary")}${button("不准确（演示）", "demo:correct")}${button("纠正（演示）", "demo:edit")}</div></article><article class="panel"><p class="section-label">为什么 LifeOS 这样理解</p><ol class="trace"><li><strong>Identity</strong><span>每个对象有独立身份，而不是被 AI 静默改写的原文。</span></li><li><strong>Understanding</strong><span>这是固定合成理解，明确标注为 Observation、Inference 或候选。</span></li><li><strong>Derivation</strong><span>输入范围和用途可见；本轮没有模型或网络调用。</span></li><li><strong>Evidence</strong><span>用户原文、确认事实与 Runtime 回执相互分离。</span></li><li><strong>Source</strong><span>${broken ? "来源指针不可达；不能据此生成可靠建议。" : "仅指向固定 synthetic 来源，不读取真实文件。"}</span></li></ol></article></section><aside class="stack"><section class="panel"><p class="section-label">处理范围</p><p>Work 与 Health 仅是展示用的 Person Context。本次没有真实 Source、模型、工具或权限使用。</p></section><section class="notice ${broken ? "danger" : "mint"}"><strong>${broken ? "断链披露" : "证据可回溯"}</strong><p>${broken ? "来源不足时保持诚实，不把不确定性提升为建议。" : "仍由用户决定是否接受任何候选。"}</p></section></aside></div></main>`; }
  function workspace() { return `<main id="main-content" class="page workspace-page" tabindex="-1">${header("AI Workspace · 深度展开", "AI Workspace", "Global AI 的深度形态：上下文和候选都可检查，但模型保持关闭。")}<div class="workspace-grid"><section class="stack"><article class="panel"><p class="section-label">Conversation + Work</p><h2>今天想和 LifeOS 一起推进什么？</h2><p>本轮不发送问题、不调用模型，也不把候选写进 Runtime。</p><div class="suggestions">${button("总结近况（展示）", "demo:view", "chip")}${button("理清思路（展示）", "demo:view", "chip")}${button("制定计划（展示）", "demo:view", "chip")}</div></article><article class="panel"><div class="section-top"><div><h2>为你推荐</h2><p class="quiet">候选工作以 Observation／Inference 身份出现，仍需要你的确认。</p></div>${tag("固定 synthetic", "fixture")}</div><div class="recommendation"><strong>先验证 capture、刷新和关闭重开</strong><p>候选：这是本轮可靠闭环的最小步骤。</p>${tag("Suggested Action", "inference")}</div><div class="recommendation"><strong>检查今天的整体优先级</strong><p>证据不足时允许保持没有建议。</p>${tag("AI Observation", "observation")}</div></article></section><aside class="stack"><article class="panel"><div class="section-top"><h2>当前上下文</h2>${tag("可检查", "decision")}</div><div class="chip-row">${tag("Person", "fixture")}${tag("Work", "fixture")}${state.health ? tag("Health", "fixture") : `<span class="context-diff">Health 已临时移除，不改持久事实。</span>`}</div>${button(state.health ? "临时移除 Health" : "重新加入 Health", state.health ? "health:remove" : "health:add", "small-button")}<p class="tiny">Selection: ${context()[0]}</p></article><article class="panel"><p class="section-label">Future Agent Task</p><p>诚实占位：没有 Agent、工具、权限或执行记录。</p>${tag("未实现", "inference")}</article></aside></div></main>`; }
  function settings() { return `<main id="main-content" class="page" tabindex="-1">${header("Settings · 辅助入口", "原型边界", "Settings 不是一级工作区；这里仅披露当前受控组合候选的边界。 ")}<section class="settings-grid"><article class="panel"><p class="section-label">Motion</p><h2>低动态预览</h2><p>只影响当前 UI transition，不修改设备或系统设置。</p>${button(state.motion ? "已启用低动态" : "启用低动态", "motion", state.motion ? "button primary" : "button")}</article><article class="panel"><p class="section-label">允许</p><p>全新 task-local SQLite；capture_record、get_today、runtime_status；两条固定合成原文。</p></article><article class="panel"><p class="section-label">关闭</p><p>模型、网络、文件、导入、clear、export、权限、恢复、Vault、同步、多设备和外部用户。</p></article></section></main>`; }
  function overlay() { const panel = state.ai ? `<aside class="ai-panel" role="dialog" aria-label="Global AI" aria-modal="false"><div class="section-top"><div><p class="eyebrow">Global AI</p><h2>问 LifeOS</h2></div>${button("×", "ai-close", "icon-button")}</div><p>全局、上下文可见的入口。模型未启用：这里不会发送、保存或推断任何内容。</p><div class="chip-row">${tag("Person", "fixture")}${tag(`Page: ${state.page}`, "fixture")}${tag(`Selection: ${context()[0]}`, "fixture")}${state.health ? tag("Health", "fixture") : ""}</div><section class="notice"><strong>AI Observation · 固定演示</strong><p>${state.health ? "工作和 Health Context 同时存在，但没有足够证据判断它们的因果关系。" : "本次临时不使用 Health Context；持久事实保持不变。"}</p></section><section class="candidate-card">${tag("Suggested Action", "inference")}<p>候选：先核对首屏叙事和生命周期，再决定是否继续视觉细节。</p><div class="actions">${button("确认（演示）", "demo:confirm")}${button("编辑（演示）", "demo:edit")}${button("拒绝（演示）", "demo:reject")}</div></section>${button("展开 AI Workspace", "workspace", "button primary")}</aside>` : ""; const captureDialog = state.capture ? `<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="Quick Capture"><div class="section-top"><div><p class="eyebrow">Quick Capture</p><h2>先保留原文，再让你决定关联</h2></div>${button("×", "capture-close", "icon-button")}</div><p>没有自由文本、文件或导入入口。只能选择 Frozen ABF 的两条合成原文。</p><div class="capture-options">${samples.map((sample) => `<button data-action="capture:${sample.key}"><strong>${sample.label}</strong><span>${sample.text}</span></button>`).join("")}</div><p class="boundary-note">capture_record 成功后才调用 get_today 重读；失败不会显示成功态。</p></section></div>` : ""; return panel + captureDialog; }
  function page() { return ({ today, me, contexts: contextsPage, "context-detail": detail, memory: memoryPage, "memory-detail": memoryDetail, workspace, settings })[state.page](); }
  function shell() {
    const nav = [["today", "Today", "today"], ["me", "Me", "me"], ["contexts", "Contexts", "contexts"], ["memory", "Memory", "memory"], ["settings", "Settings", "settings"]];
    const selected = (id) => state.page === id || (id === "contexts" && state.page === "context-detail") || (id === "memory" && state.page === "memory-detail");
    const navButton = ([id, label, glyph]) => `<button class="rail-button" data-action="nav:${id}" data-tooltip="${label}" aria-current="${selected(id) ? "page" : "false"}" aria-label="${label}">${icon(glyph)}</button>`;
    return `<div class="app-shell"><nav class="icon-rail" aria-label="LifeOS 主导航"><span class="brand-mark" aria-label="LifeOS">${icon("sparkle")}</span>${nav.slice(0, 4).map(navButton).join("")}<span class="rail-spacer"></span>${nav.slice(4).map(navButton).join("")}</nav><section class="workspace">${page()}</section><footer class="composer"><button class="composer-ai" data-action="ai-open" aria-label="打开 Global AI">${icon("sparkle")}</button><button class="composer-prompt" data-action="ai-open"><span>问 LifeOS…</span><small>Global AI · 模型未启用</small></button><button class="capture-plus" data-action="capture-open" aria-label="打开 Quick Capture">＋</button></footer><p class="runtime-notice ${state.error ? "error" : ""}" role="status">${esc(state.notice)}</p>${overlay()}</div>`;
  }
  function render() { document.body.classList.toggle("reduced-motion", state.motion); app.innerHTML = shell(); }
  const demo = { confirm: "候选已由你确认（演示）；没有新增持久化事实。", edit: "候选已编辑（演示）；原文与证据身份保持分离。", reject: "候选已拒绝（演示）；Runtime 数据没有变化。", ignore: "观察已忽略（演示）；没有新增建议。", correct: "已记录纠正意图（演示）；本轮不实现反馈持久化。", view: "这是固定 synthetic 候选；需要用户决定，不能自动创建对象。" };
  app.addEventListener("click", (event) => { const target = event.target.closest("[data-action]"); if (!target) return; const action = target.dataset.action;
    if (action.startsWith("nav:")) { state.page = action.slice(4); state.ai = false; state.capture = false; render(); return; }
    if (action.startsWith("mode:")) { state.mode = action.slice(5); render(); return; }
    if (action.startsWith("context:")) { state.context = action.slice(8); state.page = "context-detail"; state.ai = false; render(); return; }
    if (action.startsWith("memory:")) { state.memory = action.slice(7); state.page = "memory-detail"; state.ai = false; render(); return; }
    if (action.startsWith("filter:")) { state.filter = action.slice(7); render(); return; }
    if (action.startsWith("capture:")) { const sample = samples.find((item) => item.key === action.slice(8)); if (sample) capture(sample); return; }
    if (action.startsWith("demo:")) { state.notice = demo[action.slice(5)] || "固定 synthetic 演示状态已更新。"; state.error = false; render(); return; }
    if (action === "refresh") { refresh(); return; }
    if (action === "ai-open") { state.ai = true; state.capture = false; render(); return; }
    if (action === "ai-close") { state.ai = false; render(); return; }
    if (action === "capture-open") { state.capture = true; state.ai = false; render(); return; }
    if (action === "capture-close") { state.capture = false; render(); return; }
    if (action === "workspace") { state.page = "workspace"; state.ai = false; render(); return; }
    if (action === "health:remove" || action === "health:add") { state.health = action.endsWith("add"); state.notice = state.health ? "Health 已重新加入本次临时 Context。" : "Health 已从本次临时 Context 移除；没有改写持久事实。"; render(); return; }
    if (action === "motion") { state.motion = !state.motion; state.notice = state.motion ? "低动态预览已开启；没有修改系统设置。" : "低动态预览已关闭；没有修改系统设置。"; render(); return; }
    if (action === "domain-gate") { state.notice = "Finance 等其他领域保持未启用：数据、价值、反馈和安全 Gate 尚未满足。"; render(); }
  });
  document.addEventListener("keydown", (event) => { if (event.key === "Escape" && (state.ai || state.capture)) { state.ai = false; state.capture = false; render(); document.getElementById("main-content")?.focus(); } });
  async function init() { render(); try { state.runtime = verifyStatus(await call("runtime_status", {})); await refresh(false); state.notice = "Runtime 已核对：离线、本地、固定 synthetic 数据与三项 IPC 均处于受控边界。"; state.error = false; } catch (error) { state.notice = `启动被阻断：${code(error)}。未显示成功或缓存状态。`; state.error = true; } render(); }
  init();
})();
