import {ControlledConversation,ControlledFlow} from './controlled_conversation.ts';
import {icon} from './source_icons.ts';
const invoke=(window as any).__TAURI__.core.invoke;
const app=new ControlledConversation({invoke:(c,r)=>invoke(c,new TextEncoder().encode(JSON.stringify(r)))});
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let page='Today',aiOpen=false,notice='';
const flow=new ControlledFlow(app,()=>render());
const button=(action:string,label:string,id='')=>`<button type="button" class="button secondary" data-action="${action}" data-id="${esc(id)}">${label}</button>`;
const title=(name:string,sub:string)=>`<header class="page-head"><div><h1>${name}</h1><p class="subhead">${sub}</p></div></header>`;
const label=(s:any)=>s.stateKey==='available_time'?`可用时间 · ${s.value} 分钟`:`自述睡眠 · ${s.value} 小时`;
const date=(v:number)=>new Date(v).toLocaleDateString('zh-CN');
function body(){const s=flow.snapshot;
 if(page==='Settings')return `<div class="settings-shell"><nav class="settings-nav" aria-label="设置导航"><p>设置</p><button aria-current="page">模型设置</button></nav><div class="settings-content">${title('模型设置','选择这次对话使用的模型。')}<section class="service-card"><div><p class="eyebrow">当前服务</p><h2>DeepSeek</h2><p>${s?.provider?.credentialState==='stored'?'凭据已加密保存':'尚未配置凭据'} · 合成演练</p></div><span class="state-dot">${esc(s?.provider?.modelId||'未选择模型')}</span></section><section class="config-card"><h2>服务配置</h2><label>合成 API Key<input type="password" id="key" autocomplete="off" placeholder="仅输入虚构演练值"></label><div class="form-actions">${button('save-key','保存凭据')}${button('delete-key','删除本任务凭据')}</div><label>模型<input id="model" list="model-options" value="${esc(s?.provider?.modelId||'')}" placeholder="输入模型 ID"><datalist id="model-options">${(s?.provider?.models||[]).map((m:string)=>`<option value="${esc(m)}"></option>`).join('')}</datalist></label>${button('select-model','选择模型')}<p class="tiny">使用已有选项或输入模型 ID；选择本身不会联网测试。</p><details><summary>其他服务目录</summary><h3>云端服务</h3>${['OpenAI','Anthropic','Google Gemini','DeepSeek','Kimi','OpenRouter','其他 OpenAI-compatible 服务','自定义兼容接口'].map(n=>`<p>${n} · ${n==='DeepSeek'?'本任务受控服务':'目录保留，本任务不可发送'}</p>`).join('')}<h3>本地服务</h3>${['Ollama','LM Studio','OpenAI-compatible 本地接口','自定义本地服务'].map(n=>`<p>${n} · 目录保留，本任务不可发送</p>`).join('')}</details></section><p class="usage-help">当前为合成离线演练。每次确认仅验证发送流程；真实网络尚未启用。</p>${button('open-ai','返回对话')}</div></div>`;
 if(page==='Me')return `<div class="page-wrap">${title('我','你的明确表达，形成有时效的当前状态。')}<section class="panel"><h2>当前状态</h2>${s?.states?.length?s.states.map((st:any)=>`<article class="record"><strong>${esc(label(st))}</strong><p class="quiet">${st.domain==='health'?'健康':'工作'} · 用户${st.identity==='user_self_report'?'自述':'明确表达'} · 有效至 ${new Date(st.validUntil).toLocaleString('zh-CN')}</p><p class="verbatim">${esc(st.rawText)}</p></article>`).join(''):'<p class="quiet">还没有当前状态。你可以在对话中说明或纠正。</p>'}<p class="tiny">这些短期状态不会自动成为长期记忆；自述不替代来源中的观察。</p></section></div>`;
 if(page==='Memory')return `<div class="page-wrap">${title('记忆','已确认的长期信息，与临时对话分开保留。')}<section class="panel">${(s?.memories||[]).map((m:any)=>`<article class="record"><small>已确认记忆 · 合成资料</small><p>${esc(m.text)}</p></article>`).join('')}<p class="tiny">普通回答只作为 AI 候选内容保存，不会自动写入这里。</p></section></div>`;
 if(page==='Contexts')return `<div class="page-wrap">${title('上下文','相关资料随问题进入对话。')}<section class="panel"><p>直接提问即可。回答下的“查看依据”会展示本次用到的合成来源和用户表达。</p><p class="quiet">此演练没有独立的上下文编辑功能。</p>${button('open-ai','开始对话')}</section></div>`;
 return `<div class="page-wrap"><section class="today-page"><div class="today-hero"><div><h1>你好。</h1><p class="today-subhead">给今天留一点从容。</p></div><div class="today-chrome"><span>${new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date())}</span>${icon('calendar')}</div></div><span class="synthetic-mark">合成演练 · 未联网</span><div class="today-grid"><section class="panel"><div class="section-head"><h2>从一个问题开始</h2>${icon('spark')}</div><p class="quiet">理清下一步，也给自己的状态留一点空间。</p><p>你可以问“根据我的健康记录，怎么安排活动？”</p><p class="tiny">直接输入问题，相关依据会在回答中按需展开。</p>${button('open-ai','打开对话')}</section></div><p class="usage-help">这里使用合成来源和离线测试模型，验证有限的对话流程。</p></section></div>`;
}
function chat(){const s=flow.snapshot;return `${s?.hasMore?'<p class="tiny">显示最近的有限对话，较早记录仍在本地保留。</p>':''}${!s?.turns?.length?'<p class="quiet">说说你想了解什么。</p>':''}${(s?.turns||[]).map((t:any)=>{const q=s.questions.find((q:any)=>q.id===t.clarificationId&&q.status==='pending');return `<article class="turn"><div class="ai-question"><small>你的原始表达</small><p class="verbatim">${esc(t.text)}</p></div><div class="ai-answer"><small>AI 候选回答${t.status==='stale'?' · 旧依据已失效，保留历史':''}</small><p class="verbatim">${esc(t.answer)}</p>${t.refs.length?`<details data-keep="${esc(t.turnId)}"><summary>查看依据 · ${t.refs.length} 条</summary>${t.refs.map((r:any)=>`<article class="record"><small>${r.identity==='source_projection'?'合成来源':r.identity==='health_conversation_expression'?'用户明确表达':'已确认记忆'}${r.observedAt?` · ${date(r.observedAt)}`:''}${r.estimated?' · 估计值':''}</small><p class="verbatim">${esc(r.text)}</p></article>`).join('')}</details>`:''}${q?`<div class="form-actions">${button('defer','稍后再说',q.id)}${button('ignore','忽略这个问题',q.id)}</div>`:''}</div></article>`}).join('')}`;}
function errorText(e:any){const messages:any={credential_missing:'请先在模型设置中保存凭据并选择模型。',credential_invalid:'凭据格式不正确，请在设置中检查。',credential_authentication_failed:'本地凭据无法解密，请在设置中重新保存。',provider_authentication:'服务拒绝了凭据。草稿已保留，请检查设置。',provider_model:'服务不接受所选模型。请在设置中选择后重新准备。',provider_timeout:'请求超时，是否已发送无法确认。草稿保留；重试需要新的披露确认。',provider_network:'连接中断，是否已发送无法确认。草稿保留；重试需要新的披露确认。',dispatch_outcome_unknown:'结果尚未确认，不会自动重发。草稿已保留。',preview_stale:'内容或设置已变化，请重新准备披露。',context_stale:'来源或上下文已变化，请重新准备。',provider_unavailable:'服务暂不可用。草稿已保留，请手动重试。',context_budget_rejected:'相关内容过长，请收窄问题。',provider_response_rejected:'服务回答未通过本地检查，草稿已保留。'};return messages[e?.code]||'操作未完成，草稿已保留。';}
function disclosure(){const v=flow.preview;if(!v)return '';return `<section class="confirmation" aria-label="本次发送预览"><h3>发送前，请看一下</h3><p>接收方：DeepSeek · ${esc(v.modelId)}</p><small>合成演练，未联网 · 本次只包含下方问题与 ${v.items.length} 条依据</small><h3>你的问题</h3><p class="verbatim">${esc(v.question)}</p>${!v.items.some((i:any)=>i.identity==='来源观察'&&i.domain==='health')?'<p>本次没有健康来源观察，不会声称使用了健康依据。</p>':''}${v.items.map((i:any)=>`<article class="record"><small>${esc(i.citationId)} · ${esc(i.identity)}</small><p class="verbatim">${esc(i.text)}</p></article>`).join('')}<details data-keep="instructions"><summary>固定模型说明与完整请求</summary><p class="verbatim">${esc(v.instructions)}</p><small>${esc(v.recipient)}</small><pre class="source-original">${esc(v.exactBody)}</pre></details><div class="form-actions"><button class="button primary" data-action="confirm" ${flow.busy?'disabled':''}>确认演练发送</button>${button('cancel','取消')}</div></section>`;}
const composer=document.createElement('form');composer.className='question-form';composer.innerHTML=`<button type="button" class="ai-launch" data-action="open-ai" aria-label="Global AI">${icon('spark')}</button><label class="sr-only" for="conversation">自然提问</label><textarea id="conversation" maxlength="2000" rows="1" placeholder="问 LifeOS…"></textarea><button type="submit" class="button primary">发送</button>`;
const editor=composer.querySelector('textarea')!;
composer.addEventListener('submit',e=>{e.preventDefault();aiOpen=true;void flow.prepare().then(scrollEnd);render()});editor.addEventListener('input',()=>flow.edit(editor.value));editor.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();composer.requestSubmit()}});
function scrollEnd(){const el=document.getElementById('chat-scroll');if(el)el.scrollTop=el.scrollHeight;}
function render(){const focus=document.activeElement===editor,start=editor.selectionStart,end=editor.selectionEnd;const scroll=document.getElementById('chat-scroll')?.scrollTop;const kept=[...document.querySelectorAll('details[data-keep][open]')].map((v:any)=>v.dataset.keep);composer.remove();
 document.getElementById('app')!.innerHTML=`<div class="app-shell"><nav class="icon-rail" aria-label="主导航"><span class="brand-mark">${icon('spark')}</span>${['Today','Me','Contexts','Memory'].map(p=>`<button class="rail-button" data-page="${p}" aria-label="${p}" ${page===p?'aria-current="page"':''}>${icon(p.toLowerCase())}</button>`).join('')}<span class="rail-spacer"></span><button class="rail-button settings-button" data-page="Settings" aria-label="Settings">${icon('settings')}</button></nav><main id="main" tabindex="-1" class="workspace">${body()}</main><aside class="ai-panel ${aiOpen?'open':''}" ${aiOpen?'':'hidden'} aria-label="Global AI 对话"><div class="ai-panel-head"><div><h2>Global AI</h2><small>合成演练 · ${esc(flow.snapshot?.provider?.modelId||'未配置模型')}</small></div><button class="close" data-action="close-ai" aria-label="关闭对话">${icon('close')}</button></div><div class="chat-scroll" id="chat-scroll">${chat()}${disclosure()}<div id="chat-status"></div></div><div class="ai-panel-composer" id="panel-composer"></div></aside><div class="composer" id="bottom-composer"></div></div>`;
 document.getElementById(aiOpen?'panel-composer':'bottom-composer')!.append(composer);if(editor.value!==flow.draft.text)editor.value=flow.draft.text;(composer.querySelector('[type=submit]') as HTMLButtonElement).disabled=!flow.opened||flow.busy;
 const status=flow.phase==='restoring'?'正在恢复本地会话…':flow.phase==='preparing'?'正在本地筛选相关内容…':flow.busy?'正在进行合成发送…':flow.phase==='cancelled'?flow.notice:flow.error?errorText(flow.error):notice;
 const html=`<p class="notice" role="status">${esc(status)}</p>${flow.busy?button('cancel','取消'):flow.phase==='failed'?button('retry','重新准备披露'):flow.phase==='open-failed'?button('restore','重试恢复'):''}`;
 if(aiOpen)document.getElementById('chat-status')!.innerHTML=html;else {const n=document.createElement('div');n.className='composer-status';n.innerHTML=html;document.getElementById('bottom-composer')!.prepend(n);}
 document.querySelectorAll('details[data-keep]').forEach((n:any)=>{n.open=kept.includes(n.dataset.keep)});if(scroll!==undefined)document.getElementById('chat-scroll')!.scrollTop=scroll;if(focus){editor.focus();editor.setSelectionRange(start,end);}
}
document.addEventListener('click',async e=>{const b=(e.target as Element).closest('button') as HTMLButtonElement;if(!b)return;const p=b.dataset.page,a=b.dataset.action,id=b.dataset.id||'';try{if(p){page=p;aiOpen=false;}if(a==='open-ai'){aiOpen=true;}if(a==='close-ai')aiOpen=false;if(a==='cancel')await flow.cancel();if(a==='retry')await flow.prepare();if(a==='restore')await flow.start();if(a==='confirm')await flow.confirm();if(a==='select-model')await flow.selectModel((document.getElementById('model') as HTMLInputElement).value);if(a==='save-key'){const key=document.getElementById('key') as HTMLInputElement;const value=key.value;key.value='';await flow.saveCredential(value);}if(a==='delete-key')await flow.deleteCredential();if(a==='ignore'||a==='defer')await flow.decide(id,a);render();if(a==='open-ai'){editor.focus();scrollEnd();}}catch{notice='操作未完成，请重试。';render();}});
render();void flow.start();
