import {test} from 'node:test';import assert from 'node:assert/strict';
import {appleImportView} from '../ui/apple_import.js';
import {SourcesController} from '../ui/sources_view.js';
import {healthView,appleHistory} from '../ui/health_view.js';import {resolve} from '../ui/core.js';
function fixture(handler){const calls=[];const c=new SourcesController(async(name,r)=>{assert.equal(name,'import_apple_health_file');assert.equal(r.version,1);calls.push(r.payload);return handler(r.payload);},()=>{});c.active=true;return {c,calls};}
const complete={status:'completed',file:'demo.xml',inserted:3,duplicates:1,unsupported:2,failed:0,attachments:1,importedAt:1,unsupportedTypes:{Other:2}};
const settle=()=>new Promise(r=>setImmediate(r));
test('current UI file selection uses sole import IPC and refreshes terminal status',async()=>{const x=fixture(p=>p.action==='list'?{files:['demo.xml']}:p.action==='start'?{status:'running',file:p.file}:complete);try{await x.c.action('apple-open');await x.c.action('apple-select','demo.xml');await settle();assert.deepEqual(x.calls,[{action:'list'},{action:'start',file:'demo.xml'},{action:'status'}]);assert.equal(x.c.importState.status.status,'completed');assert.equal(x.c.importState.picker,null);}finally{x.c.dispose()}});
test('failed start preserves the selected file across idle status and explicit retry',async()=>{let tries=0;const x=fixture(p=>p.action==='start'?(++tries===1?Promise.reject({code:'health_file_changed'}):{status:'running',file:p.file}):tries===1?{status:'idle'}:complete);try{await x.c.action('apple-select','demo.xml');await settle();assert(appleImportView(x.c.importState).includes('已有数据保留'));assert.equal(x.c.importState.status.file,'demo.xml');await x.c.action('apple-retry');await settle();assert.equal(tries,2);assert.deepEqual(x.calls.filter(p=>p.action==='start'),[{action:'start',file:'demo.xml'},{action:'start',file:'demo.xml'}]);assert.equal(x.c.importState.status.status,'completed');}finally{x.c.dispose()}});
test('starting and running cannot start another import or reopen picker',async()=>{let release;const wait=new Promise(r=>release=r);const x=fixture(p=>p.action==='start'?wait:{status:'running',file:'first.xml'});try{const pending=x.c.action('apple-select','first.xml');await x.c.action('apple-select','second.xml');assert.equal(x.calls.length,1);release({status:'running',file:'first.xml'});await pending;await settle();await x.c.action('apple-select','third.xml');await x.c.action('apple-open');await x.c.action('apple-retry');assert.equal(x.calls.filter(p=>p.action==='start').length,1);assert(!x.calls.some(p=>p.action==='list'));}finally{x.c.dispose()}});
test('current status restoration keeps original duplicate time without new samples',async()=>{const x=fixture(()=>({...complete,status:'duplicate',inserted:0,originalImport:true}));try{await x.c.start('health');const html=appleImportView(x.c.importState);for(const t of ['未重复写入','保留原导入时间','重复内容','非自动同步','不支持','失败 0'])assert(html.includes(t));}finally{x.c.dispose()}});
test('HTML escaping applies to filename and unsupported types',()=>{const h=appleImportView({status:{...complete,file:'<img>',unsupportedTypes:{'<script>':1}},picker:['"<svg>']});assert(!h.includes('<script>'));assert(!h.includes('<img>'));assert(h.includes('&lt;svg&gt;'));});
test('unknown failed counts are not fabricated totals',()=>{const h=appleImportView({status:{status:'failed',code:'health_document_corrupt',file:'a.zip'}});assert(h.includes('文件失败 1'));assert(h.includes('无法确认的记录数量不作推测'));assert(!h.includes('undefined'));});
const snapshot={records:[{id:'batch',kind:'health_batch',protocol:'apple-file-v1',file:'demo.xml',status:'observed',modelEligible:false,inserted:1,duplicates:0,unsupported:1,receivedAt:1}],states:[{id:'state',kind:'health_current_state',protocol:'apple-file-v1',status:'observed',modelEligible:false,dayIndex:20000,metric:'steps',unit:'count',value:null,offsetMinutes:480,observedAt:1,receivedAt:2,sources:[{name:'Synthetic',value:null}],refs:[]}],sources:[],memories:[],feedback:[],derivations:[]};
test('Apple observation labels do not imply completeness, identity or revision',()=>{const h=healthView(snapshot,true);for(const t of ['查询覆盖未知','非完整日总量','未区分同名设备','暂无法可靠合并','内容去重不是样本修订证明','最新256条'])assert(h.includes(t),t);assert(!h.includes('undefined'));assert(appleHistory(snapshot).includes('demo.xml'));});
test('actual frontend resolver excludes Apple batches and states under all purposes',()=>{for(const purpose of ['person','health','work']){const r=resolve(snapshot,purpose);assert.equal(r.included.length,0);assert.equal(r.states.length,0);assert(!JSON.stringify(r).includes('demo.xml'));}});
test('semantic partial success exposes skipped and unprojected without claiming complete coverage',()=>{const html=appleImportView({status:{...complete,status:'successful_with_skips',skipped:1,unprojected:2}});assert(html.includes('部分记录已跳过'));assert(html.includes('跳过 1'));assert(html.includes('未投影观察 2'));assert(!html.includes('尚未导入苹果健康文件'));});
